// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "/Plugin/FX/Niagara/Private/NiagaraQuaternionUtils.ush"

struct FNiagaraTransform
{
	float3	Translation;
	float4	Rotation;
	float3	Scale;
};

FNiagaraTransform LoadTransform(ByteAddressBuffer Buffer, uint Offset)
{
	FNiagaraTransform R;
	R.Translation	= asfloat(Buffer.Load3(Offset + 0));
	R.Rotation		= asfloat(Buffer.Load4(Offset + 12));
	R.Scale			= asfloat(Buffer.Load3(Offset + 20));
	return R;
}

FNiagaraTransform MakeTransform(float3 Translation, float4 Rotation, float3 Scale)
{
	FNiagaraTransform R;
	R.Translation	= Translation;
	R.Rotation		= Rotation;
	R.Scale			= Scale;
	return R;
}

FNiagaraTransform MultiplyTransform(in FNiagaraTransform A, in FNiagaraTransform B)
{
	FNiagaraTransform R;
	R.Translation	= RotateVectorByQuat(A.Translation * B.Scale, B.Rotation) + B.Translation;
	R.Rotation		= MultiplyQuat(A.Rotation, B.Rotation);
	R.Scale			= A.Scale * B.Scale;
	return R;
}
