[URL]
GameNameShort=LLH

[Plugins]
+ProgramEnabledPlugins="LiveLink"
+ProgramEnabledPlugins="StructUtils"
+ProgramEnabledPlugins="ContentBrowserAssetDataSource"
+ProgramEnabledPlugins="PropertyAccessEditor"
+ProgramEnabledPlugins="PythonScriptPlugin"

+ProgramOptionalPlugins="AppleARKitFaceSupport"
#+ProgramOptionalPlugins="LiveLinkViconDataStream"
+ProgramOptionalPlugins="LiveLinkInputDevice"
+ProgramOptionalPlugins="MocopiLiveLink"
+ProgramOptionalPlugins="OptitrackLiveLink"

[/Script/MacTargetPlatform.XcodeProjectSettings]
TemplateMacPlist=(FilePath="/Engine/Source/Programs/LiveLinkHub/Resources/Mac/Info.plist")


[/Script/UnrealEd.ProjectPackagingSettings]
bShareMaterialShaderCode=false

[ConsoleVariables]
DetailsPanel.Style.EnableCardLayout = true