[URL]
GameNameShort=LLH

[Plugins]
+ProgramEnabledPlugins="LiveLink"
+ProgramEnabledPlugins="LiveLinkHub"
+ProgramEnabledPlugins="StructUtils"
+ProgramEnabledPlugins="ContentBrowserAssetDataSource"
+ProgramEnabledPlugins="PropertyAccessEditor"
+ProgramEnabledPlugins="PythonScriptPlugin"

+ProgramOptionalPlugins="AppleARKitFaceSupport"
#+ProgramOptionalPlugins="LiveLinkViconDataStream"
+ProgramOptionalPlugins="LiveLinkInputDevice"
+ProgramOptionalPlugins="MocopiLiveLink"
+ProgramOptionalPlugins="OptitrackLiveLink"

[/Script/MacTargetPlatform.XcodeProjectSettings]
TemplateMacPlist=(FilePath="/Engine/Source/Programs/LiveLinkHub/Resources/Mac/Info.plist")


[/Script/AppleARKit.AppleARKitSettings]
bEnableLiveLinkForFaceTracking=true


[/Script/UnrealEd.ProjectPackagingSettings]
bShareMaterialShaderCode=false

[ConsoleVariables]
DetailsPanel.Style.EnableCardLayout = true

[LiveLinkHub]
# This is used when distributing UEFN to stage the content, config and plugin manifests of the livelinkhub dependencies
+PluginDependencies="Engine/Plugins/Animation/LiveLink"
+PluginDependencies="Engine/Plugins/Animation/LiveLinkHub"
+PluginDependencies="Engine/Plugins/Runtime/AudioCapture"
+PluginDependencies="Engine/Plugins/Runtime/AppleImageUtils"
+PluginDependencies="Engine/Plugins/Runtime/MsQuic"
+PluginDependencies="Engine/Plugins/Runtime/ProceduralMeshComponent"
+PluginDependencies="Engine/Plugins/MovieScene/LevelSequenceEditor"
+PluginDependencies="Engine/Plugins/MovieScene/SequencerScripting"
+PluginDependencies="Engine/Plugins/Experimental/PythonScriptPlugin"
+PluginDependencies="Engine/Plugins/Editor/ContentBrowser/ContentBrowserFileDataSource"
+PluginDependencies="Engine/Plugins/Messaging/UdpMessaging"
+PluginDependencies="Engine/Plugins/Runtime/Windows/XInputDevice"
+PluginDependencies="Engine/Plugins/Editor/ContentBrowser/ContentBrowserAssetDataSource"
+PluginDependencies="Engine/Plugins/Animation/LiveLink"
+PluginDependencies="Engine/Plugins/VirtualProduction/Takes"
+PluginDependencies="Engine/Plugins/Developer/Concert/ConcertSync/ConcertSyncClient"
+PluginDependencies="Engine/Plugins/Experimental/StructUtils"
+PluginDependencies="Engine/Plugins/Developer/Concert/ConcertSync/ConcertSyncCore"
+PluginDependencies="Engine/Plugins/Developer/Concert/ConcertMain"
+PluginDependencies="Engine/Plugins/Runtime/Database/SQLiteCore"
+PluginDependencies="Engine/Plugins/Runtime/AR/AppleAR/AppleARKitFaceSupport"
+PluginDependencies="Engine/Plugins/Runtime/AR/AppleAR/AppleARKit"
+PluginDependencies="Engine/Plugins/Runtime/AR/ARUtilities"
+PluginDependencies="Engine/Plugins/Runtime/PropertyAccess"

# Disallow staging Python content at the moment since we don't ship with the Python dll
+PluginContentDenyList="Engine/Plugins/Experimental/PythonScriptPlugin"

# This is the content that gets loaded by LiveLinkHub on startup, so it needs to be staged as uncooked assets along with UEFN.
+ContentDependencies="Engine/Content/Animation/DefaultAnimBoneCompressionSettings.uasset"
+ContentDependencies="Engine/Content/Animation/DefaultAnimCurveCompressionSettings.uasset"
+ContentDependencies="Engine/Content/Animation/DefaultRecorderBoneCompression.uasset"
+ContentDependencies="Engine/Content/Animation/DefaultVariableFrameStrippingSettings.uasset"
+ContentDependencies="Engine/Content/ArtTools/RenderToTexture/Meshes/S_1_Unit_Plane.uasset"
+ContentDependencies="Engine/Content/BasicShapes/Cone.uasset"
+ContentDependencies="Engine/Content/BasicShapes/Cube.uasset"
+ContentDependencies="Engine/Content/BasicShapes/Cylinder.uasset"
+ContentDependencies="Engine/Content/BasicShapes/Plane.uasset"
+ContentDependencies="Engine/Content/BasicShapes/Sphere.uasset"
+ContentDependencies="Engine/Content/EditorLandscapeResources/DataLayer.uasset"
+ContentDependencies="Engine/Content/EditorLandscapeResources/DefaultAlphaTexture.uasset"
+ContentDependencies="Engine/Content/EditorLandscapeResources/SplineEditorMesh.uasset"
+ContentDependencies="Engine/Content/EditorLandscapeResources/SplineEditorMeshMat.uasset"
+ContentDependencies="Engine/Content/EditorMaterials/Camera/CineMat.uasset"
+ContentDependencies="Engine/Content/EditorMaterials/Camera/MI_CineMat_Rig.uasset"
+ContentDependencies="Engine/Content/EditorMaterials/ParticleSystems/PSysThumbnail_NoImage.uasset"
+ContentDependencies="Engine/Content/EditorMaterials/ParticleSystems/PSysThumbnail_OOD.uasset"
+ContentDependencies="Engine/Content/EditorMaterials/WorldPartition/WorldPartitionSpatialHashGridPreviewMaterial.uasset"
+ContentDependencies="Engine/Content/EditorMeshes/Camera/SM_CraneRig_Arm.uasset"
+ContentDependencies="Engine/Content/EditorMeshes/Camera/SM_CraneRig_Base.uasset"
+ContentDependencies="Engine/Content/EditorMeshes/Camera/SM_CraneRig_Body.uasset"
+ContentDependencies="Engine/Content/EditorMeshes/Camera/SM_CraneRig_Mount.uasset"
+ContentDependencies="Engine/Content/EditorMeshes/Camera/SM_RailRig_Mount.uasset"
+ContentDependencies="Engine/Content/EditorMeshes/Camera/SM_RailRig_Track.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_Actor.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_BoxReflectionCapture.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_Solver.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_Terrain.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_Trigger.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_TriggerBox.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_TriggerCapsule.uasset"
+ContentDependencies="Engine/Content/EditorResources/S_TriggerSphere.uasset"
+ContentDependencies="Engine/Content/EngineDamageTypes/DmgTypeBP_Environmental.uasset"
+ContentDependencies="Engine/Content/EngineDebugMaterials/DebugMeshMaterial.uasset"
+ContentDependencies="Engine/Content/EngineDebugMaterials/M_SimpleUnlitTranslucent.uasset"
+ContentDependencies="Engine/Content/EngineDebugMaterials/M_VolumeRenderSphereTracePP.uasset"
+ContentDependencies="Engine/Content/EngineDebugMaterials/VolumeToRender.uasset"
+ContentDependencies="Engine/Content/EngineFonts/Faces/DroidSansFallback.uasset"
+ContentDependencies="Engine/Content/EngineFonts/Faces/RobotoBold.uasset"
+ContentDependencies="Engine/Content/EngineFonts/Faces/RobotoBoldItalic.uasset"
+ContentDependencies="Engine/Content/EngineFonts/Faces/RobotoItalic.uasset"
+ContentDependencies="Engine/Content/EngineFonts/Faces/RobotoLight.uasset"
+ContentDependencies="Engine/Content/EngineFonts/Faces/RobotoRegular.uasset"
+ContentDependencies="Engine/Content/EngineFonts/Roboto.uasset"
+ContentDependencies="Engine/Content/EngineFonts/RobotoDistanceField.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenDiffuseMap.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenDiffuseMap_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenEmissiveMap.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenEmissiveMap_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenGrayscaleMap.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenGrayscaleMap_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenLinearColor.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenLinearColor_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenNormalMap.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/BaseFlattenNormalMap_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Black_1x1_EXR_Texture_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultBokeh.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultDeferredDecalMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultDeferredDecalMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultDestructiblePhysicalMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultDiffuse.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultLightFunctionMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultLightFunctionMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultPhysicalMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultPostProcessMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultPostProcessMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultTextMaterialOpaque.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultWhiteGrid.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/DefaultWhiteGrid_Low.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/EmissiveMeshMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/FlattenMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/FlattenMaterial_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/FlattenMaterial_WS_Normal_VT.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/GizmoMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Good64x64TilingNoiseHighFreq.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/InvalidLightmapSettings.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/M_InvalidLightmapSettings.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/MiniFont.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/NaniteHiddenSectionMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/PhAT_JointLimitMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/PreintegratedSkinBRDF.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/RemoveSurfaceMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/T_Default_Material_Grid_M.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/T_Default_Material_Grid_N.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/WeightMapArrayPlaceholderTexture.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/WeightMapPlaceholderTexture.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Widget3DPassThrough.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Widget3DPassThrough_Masked.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Widget3DPassThrough_Masked_OneSided.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Widget3DPassThrough_Opaque.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Widget3DPassThrough_Opaque_OneSided.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Widget3DPassThrough_Translucent.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/Widget3DPassThrough_Translucent_OneSided.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/WorldGridMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMaterials/WorldGridMaterial.uasset"
+ContentDependencies="Engine/Content/EngineMeshes/Sphere.uasset"
+ContentDependencies="Engine/Content/EngineResources/Black.uasset"
+ContentDependencies="Engine/Content/EngineResources/DefaultTexture.uasset"
+ContentDependencies="Engine/Content/EngineResources/DefaultTextureCube.uasset"
+ContentDependencies="Engine/Content/EngineResources/DefaultVolumeTexture.uasset"
+ContentDependencies="Engine/Content/EngineResources/DefaultVolumeTexture2D.uasset"
+ContentDependencies="Engine/Content/EngineResources/GradientTexture0.uasset"
+ContentDependencies="Engine/Content/EngineResources/WhiteSquareTexture.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/CloudGradientTexture.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/CloudWeatherTexture.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/T_NoiseErosion.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/T_NoiseShape64.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/T_VolumeNoiseErosion32.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/T_VolumeNoiseShape64.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/m_SimpleVolumetricCloud.uasset"
+ContentDependencies="Engine/Content/EngineSky/VolumetricClouds/m_SimpleVolumetricCloud_Inst.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Opacity/CameraDepthFade.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/ConvertFromDiffSpec.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/ConvertFromDiffSpec.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/ConvertFromDiffSpec.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/ConvertFromDiffSpec.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/ConvertFromDiffSpec.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/ConvertFromDiffSpec.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/PowerToRoughness.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/PowerToRoughness.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/PowerToRoughness.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/PowerToRoughness.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/PowerToRoughness.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions01/Shading/PowerToRoughness.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/Math/Transform3x3Matrix.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/PivotPainter2/Black_1x1_EXR_Texture.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/SplitComponents.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/Utility/BreakOutFloat2Components.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/Utility/BreakOutFloat3Components.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/Utility/CameraDirectionVector.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/Utility/MakeFloat2.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/Utility/MakeFloat3.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/Utility/MakeFloat4.uasset"
+ContentDependencies="Engine/Content/Functions/Engine_MaterialFunctions02/WorldPositionOffset/CameraOffset.uasset"
+ContentDependencies="Engine/Content/VREditor/LaserPointer/VR_LaserPower_01.uasset"
+ContentDependencies="Engine/Content/VREditor/SnapGrid/SnapGridMaterial.uasset"
+ContentDependencies="Engine/Content/VREditor/SnapGrid/SnapGridPlaneMesh.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Drop_Item_From_ContentBrowser.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Gizmo_Handle_Clicked.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Object_PickUp.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Object_Snaps_To_Another_Actor.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Object_Snaps_To_Grid.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Scaling_Down.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Scaling_Up.uasset"
+ContentDependencies="Engine/Content/VREditor/Sounds/UI/Selection_Changes.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/BoundingBoxCorner.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/BoundingBoxEdge.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/Main.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/PlaneTranslationHandle.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/RotationHandleFull.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/RotationHandleIndicator.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/RotationHandleQuarter.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/SM_Sequencer_Node.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/StartRotationHandleIndicator.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/TransformGizmoFreeRotation.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/TransformGizmoMaterial.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/TransformGizmoMaterial_Inst.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/TranslateArrowHandle.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/TranslucentTransformGizmoMaterial.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/TranslucentTransformGizmoMaterial_Inst.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/UniformScaleHandle.uasset"
+ContentDependencies="Engine/Content/VREditor/TransformGizmo/Xray.uasset"
+ContentDependencies="Engine/Content/VREditor/ViewportInteractionAssetContainerData.uasset"