// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../SHCommon.ush"
#include "../MonteCarlo.ush"
#include "../OctahedralCommon.ush"
#include "LumenCardCommon.ush"
#include "LumenTracingCommon.ush"
#include "LumenSoftwareRayTracing.ush"
#include "LumenRadianceCacheCommon.ush"
#include "LumenRadianceCacheMarkCommon.ush"
#include "LumenTranslucencyVolumeLightingShared.ush"
#include "LumenScreenProbeCommon.ush"
#include "../RayTracing/RayGenUtils.ush"
#include "LumenRadianceCacheTracingCommon.ush"

#ifndef THREADGROUP_SIZE
#define THREADGROUP_SIZE 1
#endif

#ifndef PROBE_SOURCE_MODE
#define PROBE_SOURCE_MODE 0
#endif

#define FROXEL_POS_OFFSET 1

#define FROXEL_PROBE_DEBUG_COLOR 0

/*
 * Froxel Probes TODO
 *  - Single ray tracing dispatch
 *     - Do not trace low res probe indirectly, instead add them to trace ray bucket and write all to the new volume texture
 *     - Rays are added to the bucket in batch by the indirect compute copying the data today.
 *  - separate LFSR code in tool class
 *  - Add back pre exposition of data
 */

void LumenFrontLayerTranslucencyClearGBufferPS(
	  in  float4 SvPosition		: SV_Position
	, out float4 OutColor		: SV_Target0
	, out float  OutDepth		: SV_DEPTH)
{
	const uint2 PixelCoord = uint2(SvPosition.xy);

	OutColor = 0;
	OutDepth = SceneTexturesStruct.SceneDepthTexture.Load(int3(PixelCoord, 0)).r;
}

#ifdef MarkRadianceProbesUsedByTranslucencyVolumeCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, THREADGROUP_SIZE)]
void MarkRadianceProbesUsedByTranslucencyVolumeCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
	uint3 GridCoordinate = DispatchThreadId;

	if (all(GridCoordinate < TranslucencyGIGridSize))
	{
		float3 WorldPosition = ComputeCellWorldPosition(GridCoordinate, FROXEL_POS_OFFSET ? FrameJitterOffset.xyz : 0.0f);
		uint ClipmapIndex = GetRadianceProbeClipmapForMark(WorldPosition);

		if (IsValidRadianceCacheClipmapForMark(ClipmapIndex) && IsFroxelVisible(GridCoordinate))
		{
			MarkPositionUsedInIndirectionTexture(WorldPosition, ClipmapIndex);
		}
	}
}
#endif

RWTexture3D<float3> RWVolumeTraceRadiance;
RWTexture3D<float> RWVolumeTraceHitDistance;
Texture3D<float3> VolumeFroxelProbeRadiance;

// Applying an offset from the depth buffer helps with reducing self intersection with global distance field tracing.
void ApplyDepthconstraintsToOffset(float3 GridCoordinate, inout float3 LocalFrameJitterOffset)
{
	if (GridCenterOffsetFromDepthBuffer >= 0.0)
	{
		float4 GridSampleClip	= mul(float4(ComputeCellTranslatedWorldPosition(GridCoordinate, LocalFrameJitterOffset), 1), View.TranslatedWorldToClip);
		float3 GridSampleScreen	= GridSampleClip.xyz / GridSampleClip.w;
		float3 GridSampleUVz	= float3(GridSampleScreen.xy * View.ScreenPositionScaleBias.xy + View.ScreenPositionScaleBias.wz, GridSampleScreen.z);
		float GridSampleSceneDepth = ConvertFromDeviceZ(SceneTexturesStruct.SceneDepthTexture.SampleLevel(SceneTexturesStruct_SceneDepthTextureSampler, GridSampleUVz.xy, 0).r);

		float DepthGridCoordinateWithZOffset = ComputeZSliceFromDepth(GridSampleSceneDepth) - GridCenterOffsetFromDepthBuffer;

		float3 GridCoordinateOffset = float3(GridCoordinate) + LocalFrameJitterOffset;
		
		const float DepthToSampleGridOffset = DepthGridCoordinateWithZOffset - GridCoordinateOffset.z;	// <0 if samples is in front of the depth buffer
		if (DepthToSampleGridOffset < 0.0																// Move the sample forward only if the depth buffer grid coordinate is closer,
			&& (-DepthToSampleGridOffset < GridCenterOffsetThresholdToAcceptDepthBufferOffset)			// But only if it is less than N slice away (to not bring all the sample behind forward)
			)
		{
			// If the grid sample is further than the grid z for the depth buffer, adjust the offset 
			LocalFrameJitterOffset.z += DepthToSampleGridOffset;
		}
	}
}

#ifdef TranslucencyVolumeTraceVoxelsCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void TranslucencyVolumeTraceVoxelsCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
#define DEINTERLEAVED_VOLUME_TRACING 0
#if DEINTERLEAVED_VOLUME_TRACING
	uint3 GridCoordinate = uint3(DispatchThreadId.xy % TranslucencyGIGridSize.xy, DispatchThreadId.z);
	uint2 TraceTexelCoord = DispatchThreadId.xy / TranslucencyGIGridSize.xy;
#else
	uint3 GridCoordinate = uint3(DispatchThreadId.xy / TranslucencyVolumeTracingOctahedronResolution, DispatchThreadId.z);
	uint2 TraceTexelCoord = DispatchThreadId.xy - GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution;
#endif

	if (all(GridCoordinate < TranslucencyGIGridSize) && all(TraceTexelCoord < TranslucencyVolumeTracingOctahedronResolution))
	{
		float3 TraceRadiance = 0;
		float TraceHitDistance = MaxTraceDistance;

		if (IsFroxelVisible(GridCoordinate))
		{
			float3 LocalFrameJitterOffset = FROXEL_POS_OFFSET ? FrameJitterOffset.xyz : 0.0f;
			ApplyDepthconstraintsToOffset(GridCoordinate, LocalFrameJitterOffset);

			float3 WorldPosition = ComputeCellWorldPosition(GridCoordinate, LocalFrameJitterOffset);
			float3 TranslatedWorldPosition = ComputeCellTranslatedWorldPosition(GridCoordinate, LocalFrameJitterOffset);

			float2 ProbeUV;
			float ConeHalfAngle;
			GetProbeTracingUV(TraceTexelCoord, GetProbeTexelCenter(GridCoordinate.xy), ProbeUV, ConeHalfAngle);

			float3 WorldConeDirection = EquiAreaSphericalMapping(ProbeUV);

			float TraceDistance = MaxTraceDistance;
			FRadianceCacheCoverage Coverage;
			Coverage.bValid = false;

#if PROBE_SOURCE_MODE == PROBE_SOURCE_MODE_RADIANCE_CACHE
			Coverage = GetRadianceCacheCoverage(WorldPosition, WorldConeDirection, .5f);
				
			if (Coverage.bValid)
			{
				TraceDistance = min(TraceDistance, Coverage.MinTraceDistanceBeforeInterpolation);
			}
#endif
			float VoxelTraceStartDistance = CalculateVoxelTraceStartDistance(0, MaxTraceDistance, MaxMeshSDFTraceDistance, false) * VoxelTraceStartDistanceScale;

			FConeTraceInput TraceInput;
			TraceInput.Setup(WorldPosition, TranslatedWorldPosition, WorldConeDirection, ConeHalfAngle, 0, 0, TraceDistance, StepFactor);
			TraceInput.VoxelTraceStartDistance = VoxelTraceStartDistance;
			TraceInput.SDFStepFactor = 1;

			FConeTraceResult TraceResult = (FConeTraceResult)0;
			TraceResult.Transparency = 1;

#if TRACE_FROM_VOLUME
			RayTraceGlobalDistanceField(TraceInput, TraceResult);
#endif

			if (TraceResult.Transparency <= .5f)
			{
				TraceHitDistance = TraceResult.OpaqueHitDistance;
			}

#if PROBE_SOURCE_MODE == PROBE_SOURCE_MODE_FROXEL
			if (true) // Froxel probes are always valid for the translucency volume froxels.
			{
				const float3 FroxelProbeRadiance = GetFroxelProbeLighting(VolumeFroxelProbeRadiance, GridCoordinate, ProbeUV);// *View.OneOverPreExposure;
			
				// Lerp according to tracing coverage=1-transparency
				TraceResult.Lighting += FroxelProbeRadiance * TraceResult.Transparency;
			
				TraceResult.Transparency = 0.0;
			}
			else
#elif PROBE_SOURCE_MODE == PROBE_SOURCE_MODE_RADIANCE_CACHE
			if (Coverage.bValid)
			{
				SampleRadianceCacheAndApply(Coverage, WorldPosition, WorldConeDirection, ConeHalfAngle, TraceResult.Lighting, TraceResult.Transparency);
			}
			else
#endif
			{
				ApplySkylightToTraceResult(WorldConeDirection, TraceResult);
			}

			TraceRadiance = TraceResult.Lighting;

			TraceRadiance *= View.PreExposure;

			float MaxLighting = max3(TraceRadiance.x, TraceRadiance.y, TraceRadiance.z);

			if (MaxLighting > MaxRayIntensity)
			{
				TraceRadiance *= MaxRayIntensity / MaxLighting;
			}
		}

		uint3 WriteCoord = uint3(GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution + TraceTexelCoord, GridCoordinate.z);
		RWVolumeTraceRadiance[WriteCoord] = TraceRadiance;
		RWVolumeTraceHitDistance[WriteCoord] = min(TraceHitDistance, MaxHalfFloat);
	}
}
#endif

Texture3D<float3> VolumeTraceRadiance;
Texture3D<float> VolumeTraceHitDistance;

float3 PreviousFrameJitterOffset;
float4x4 UnjitteredPrevWorldToClip;

int SpatialFilterSampleCount;
int3 SpatialFilterDirection;
float3 SpatialFilterGaussParams;

float GaussianWeight1d(float Distance)
{
	const float StandardDev					= SpatialFilterGaussParams.x;	// s
	const float InvStandardDevSquaredTimes2	= SpatialFilterGaussParams.y;	// 1 / (2 * s * s)
	const float InvStandardDevTimesSqrt2	= SpatialFilterGaussParams.z;	// 1 / (s * sqrt(2PI))
	return InvStandardDevTimesSqrt2 * exp(-Distance * Distance * InvStandardDevSquaredTimes2);
}

#ifdef TranslucencyVolumeSpatialSeparableFilterCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void TranslucencyVolumeSpatialSeparableFilterCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
	uint3 GridCoordinate = uint3(DispatchThreadId.xy / TranslucencyVolumeTracingOctahedronResolution, DispatchThreadId.z);
	uint2 TraceTexelCoord = DispatchThreadId.xy - GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution;

	if (all(GridCoordinate < TranslucencyGIGridSize) && all(TraceTexelCoord < TranslucencyVolumeTracingOctahedronResolution))
	{
		float3 FilteredRadiance = 0;
		float TotalWeight = 0;

		LOOP
		for (int Offset = -SpatialFilterSampleCount; Offset <= SpatialFilterSampleCount; Offset++)
		{
			int3 NeighborGridCoordinate = GridCoordinate + SpatialFilterDirection * Offset;

			if (all(and(NeighborGridCoordinate >= 0, NeighborGridCoordinate < TranslucencyGIGridSize)))
			{
				float3 NeighborRadiance = VolumeTraceRadiance[uint3(NeighborGridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution + TraceTexelCoord, NeighborGridCoordinate.z)];
				float Weight = GaussianWeight1d(float(Offset));
				FilteredRadiance += NeighborRadiance * Weight;
				TotalWeight += Weight;
			}
		}
		
		RWVolumeTraceRadiance[DispatchThreadId] = FilteredRadiance / max(TotalWeight, .00001f);
	}
}
#endif

RWTexture3D<float4> RWTranslucencyGI0;
RWTexture3D<float4> RWTranslucencyGI1;
RWTexture3D<float4> RWTranslucencyGINewHistory0;
RWTexture3D<float4> RWTranslucencyGINewHistory1;

Texture3D TranslucencyGIHistory0;
Texture3D TranslucencyGIHistory1;
SamplerState TranslucencyGIHistorySampler;

float HistoryWeight; 

#ifdef TranslucencyVolumeIntegrateCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, THREADGROUP_SIZE)]
void TranslucencyVolumeIntegrateCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
	uint3 GridCoordinate = DispatchThreadId;

	if (all(GridCoordinate < TranslucencyGIGridSize))
	{
		float3 WorldPosition = ComputeCellWorldPosition(GridCoordinate, FROXEL_POS_OFFSET ? FrameJitterOffset.xyz : 0.0f);

		FTwoBandSHVectorRGB Lighting = (FTwoBandSHVectorRGB)0;
		bool bNewLightingValid = false;
		float InvTracingOctahedronResolution = 1.0f / (float)TranslucencyVolumeTracingOctahedronResolution;

		if (IsFroxelVisible(GridCoordinate))
		{
			for (uint Y = 0; Y < TranslucencyVolumeTracingOctahedronResolution; Y++)
			{
				for (uint X = 0; X < TranslucencyVolumeTracingOctahedronResolution; X++)
				{
					float3 TraceRadiance = VolumeTraceRadiance[uint3(GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution + uint2(X, Y), GridCoordinate.z)] * View.OneOverPreExposure;

					float2 ProbeTexelCenter = float2(0.5, 0.5);
					float2 ProbeUV = (float2(X, Y) + ProbeTexelCenter) * InvTracingOctahedronResolution;
					float3 WorldConeDirection = EquiAreaSphericalMapping(ProbeUV);

					Lighting = AddSH(Lighting, MulSH(SHBasisFunction(WorldConeDirection), TraceRadiance));
				}
			}

			float NormalizeFactor = PI / TranslucencyVolumeTracingOctahedronResolution / TranslucencyVolumeTracingOctahedronResolution;
			Lighting.R.V *= NormalizeFactor;
			Lighting.G.V *= NormalizeFactor;
			Lighting.B.V *= NormalizeFactor;
			bNewLightingValid = true;
		}

		// Output for Volumetric Fog which has its own temporal filter
		{
			float3 AmbientLightingVector = float3(Lighting.R.V.x, Lighting.G.V.x, Lighting.B.V.x);
			RWTranslucencyGI0[GridCoordinate] = float4(AmbientLightingVector, 0);

			float3 LuminanceWeights = AmbientLightingVector.rgb / (dot(AmbientLightingVector, 1) + 0.00001f);
			float3 Coefficient0 = float3(Lighting.R.V.y, Lighting.G.V.y, Lighting.B.V.y);
			float3 Coefficient1 = float3(Lighting.R.V.z, Lighting.G.V.z, Lighting.B.V.z);
			float3 Coefficient2 = float3(Lighting.R.V.w, Lighting.G.V.w, Lighting.B.V.w);
			RWTranslucencyGI1[GridCoordinate] = float4(dot(Coefficient0, LuminanceWeights), dot(Coefficient1, LuminanceWeights), dot(Coefficient2, LuminanceWeights), 0);
		}

		float TranslucencyVolumeIntensityScale = 4;
		Lighting.R.V *= TranslucencyVolumeIntensityScale;
		Lighting.G.V *= TranslucencyVolumeIntensityScale;
		Lighting.B.V *= TranslucencyVolumeIntensityScale;

		FTwoBandSHVectorRGB NewHistoryLighting = Lighting;

	#if USE_TEMPORAL_REPROJECTION
		float3 HistoryUV = ComputeTranslucencyGIVolumeUV(ComputeCellWorldPosition(GridCoordinate, .5f), UnjitteredPrevWorldToClip);
		float HistoryAlpha = bNewLightingValid ? HistoryWeight : 1.0f;

		if (any(HistoryUV < 0) || any(HistoryUV >= 1))
		{
			HistoryAlpha = 0;
		}

		if (HistoryAlpha > 0)
		{
			float3 AmbientLightingVector = Texture3DSampleLevel(TranslucencyGIHistory0, TranslucencyGIHistorySampler, HistoryUV, 0).xyz;
			float3 DirectionalLightingVector = Texture3DSampleLevel(TranslucencyGIHistory1, TranslucencyGIHistorySampler, HistoryUV, 0).xyz;

			FTwoBandSHVectorRGB HistoryLighting;
			HistoryLighting.R.V.x = AmbientLightingVector.r;
			HistoryLighting.G.V.x = AmbientLightingVector.g;
			HistoryLighting.B.V.x = AmbientLightingVector.b;
			float3 NormalizedAmbientColor = AmbientLightingVector.rgb / ( Luminance( AmbientLightingVector.rgb ) + 0.00001f );

			HistoryLighting.R.V.yzw = DirectionalLightingVector.rgb * NormalizedAmbientColor.r;
			HistoryLighting.G.V.yzw = DirectionalLightingVector.rgb * NormalizedAmbientColor.g;
			HistoryLighting.B.V.yzw = DirectionalLightingVector.rgb * NormalizedAmbientColor.b;

			NewHistoryLighting.R.V = lerp(Lighting.R.V, HistoryLighting.R.V, HistoryAlpha);
			NewHistoryLighting.G.V = lerp(Lighting.G.V, HistoryLighting.G.V, HistoryAlpha);
			NewHistoryLighting.B.V = lerp(Lighting.B.V, HistoryLighting.B.V, HistoryAlpha);
		}
	#endif

		{
			RWTranslucencyGINewHistory0[GridCoordinate] = float4(NewHistoryLighting.R.V.x, NewHistoryLighting.G.V.x, NewHistoryLighting.B.V.x, 0);

			float3 LuminanceWeights = LuminanceFactors();
			float3 Coefficient0 = float3(NewHistoryLighting.R.V.y, NewHistoryLighting.G.V.y, NewHistoryLighting.B.V.y);
			float3 Coefficient1 = float3(NewHistoryLighting.R.V.z, NewHistoryLighting.G.V.z, NewHistoryLighting.B.V.z);
			float3 Coefficient2 = float3(NewHistoryLighting.R.V.w, NewHistoryLighting.G.V.w, NewHistoryLighting.B.V.w);
			RWTranslucencyGINewHistory1[GridCoordinate] = float4(dot(Coefficient0, LuminanceWeights), dot(Coefficient1, LuminanceWeights), dot(Coefficient2, LuminanceWeights), 0);
		}
	}
}
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////
// Froxel probe tracing.


#if defined(FroxelProbesUpdateSchedulerMainCS)

uint CameraCut;

// TODO use waveops when proven
groupshared uint s_FroxelClearCount;
groupshared uint s_FroxelClearGlobalGroupOffset;
groupshared uint s_FroxelLowResInitCount;
groupshared uint s_FroxelLowResInitGlobalGroupOffset;
groupshared uint s_FroxelReprojUpdateCount;
groupshared uint s_FroxelReprojUpdateGlobalGroupOffset;

RWBuffer<uint>  FroxelClearCountBufferUAV;
RWBuffer<uint4> FroxelClearListBufferUAV;			// 16 bit uint4
RWBuffer<uint>  FroxelLowResInitCountBufferUAV;
RWBuffer<uint4> FroxelLowResInitListBufferUAV;		// 16 bit uint4
RWBuffer<uint>  FroxelReprojUpdateCountBufferUAV;
RWBuffer<uint4> FroxelReprojUpdateListBufferUAV;	// 16 bit uint4
RWBuffer<uint>  FroxelRefineTraceRayCountBufferUAV;
RWBuffer<uint4> FroxelRefineTraceRayListBufferUAV;	// 16 bit uint4

uint4 ProbeSamplesToTrace[8];						// must match MAX_FRUSTUM_PROBES_REFINE_TRACEPERFRAME

[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void FroxelProbesUpdateSchedulerMainCS(
	uint3 DispatchThreadId	: SV_DispatchThreadID,
	uint3 GroupThreadId		: SV_GroupThreadID)
{
	uint3 FroxelProbeGridCoordinate = DispatchThreadId.xyz;

	const bool bGroupFirstThread = all(GroupThreadId==0);
	if(bGroupFirstThread)
	{
		s_FroxelClearCount  = 0;
		s_FroxelLowResInitCount  = 0;
		s_FroxelReprojUpdateCount = 0;
	}
	GroupMemoryBarrierWithGroupSync();

	// A probe is valid to trace if it is within the texture resolution, and the froxel can be scene on screen using conservtive HZB test.
	const bool bFroxelProbeVisible = IsFroxelProbeVisible(FroxelProbeGridCoordinate); 
	const bool bValidProbeCoord = all(FroxelProbeGridCoordinate < TranslucencyVolumeTracingFroxelProbesGridSize);

	bool bFroxelWasNotVisibleLastFrame = false;
	if(bValidProbeCoord)
	{ 
		uint3 FroxelGridCoordinate = FroxelProbeGridCoordinate * TranslucencyVolumeTracingFroxelProbesFroxelSize;
		float3 HistoryUV = ComputeTranslucencyGIVolumeUV(ComputeCellWorldPosition(FroxelGridCoordinate, .5f), UnjitteredPrevWorldToClip);
		bFroxelWasNotVisibleLastFrame = any(HistoryUV < 0) || any(HistoryUV >= 1);
	}

	const bool bNewFroxelThisFrame = bValidProbeCoord && (CameraCut || bFroxelWasNotVisibleLastFrame);

	// Each thread update the count of froxel that requires rough update for this group.
	uint FroxelUpdateLocalGroupOffset = 0;
	if (bValidProbeCoord)
	{
		if (!bFroxelProbeVisible)
		{
			InterlockedAdd(s_FroxelClearCount, 1, FroxelUpdateLocalGroupOffset);
		}
		else if (bNewFroxelThisFrame)
		{
			InterlockedAdd(s_FroxelLowResInitCount, 1, FroxelUpdateLocalGroupOffset);
		}
		else
		{
			InterlockedAdd(s_FroxelReprojUpdateCount, 1, FroxelUpdateLocalGroupOffset);
		}
	}
	GroupMemoryBarrierWithGroupSync();

	// Now update the global count and recover the global write offset.
	if(bGroupFirstThread && bValidProbeCoord)
	{
		InterlockedAdd(FroxelClearCountBufferUAV[0], s_FroxelClearCount, s_FroxelClearGlobalGroupOffset);
		InterlockedAdd(FroxelLowResInitCountBufferUAV[0], s_FroxelLowResInitCount, s_FroxelLowResInitGlobalGroupOffset);
		InterlockedAdd(FroxelReprojUpdateCountBufferUAV[0], s_FroxelReprojUpdateCount, s_FroxelReprojUpdateGlobalGroupOffset);
	}
	GroupMemoryBarrierWithGroupSync();
	
	// Write out the data of the froxel requiring a rough or reprojection update.
	if (bValidProbeCoord)
	{
		if (!bFroxelProbeVisible)
		{
			FroxelClearListBufferUAV[s_FroxelClearGlobalGroupOffset + FroxelUpdateLocalGroupOffset] = uint4(FroxelProbeGridCoordinate, 0);
		}
		else if (bNewFroxelThisFrame)
		{
			FroxelLowResInitListBufferUAV[s_FroxelLowResInitGlobalGroupOffset + FroxelUpdateLocalGroupOffset] = uint4(FroxelProbeGridCoordinate, 0);
		}
		else
		{
			const uint TracesPerProbePerFrame = TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;
			uint TraceRayDataStartIndex = 0;
			InterlockedAdd(FroxelRefineTraceRayCountBufferUAV[0], TracesPerProbePerFrame, TraceRayDataStartIndex);

			uint StateFrameIndex = View.StateFrameIndex * TracesPerProbePerFrame;
			for (int i = 0; i < TracesPerProbePerFrame; ++i)
			{
#if 0
				// Mark froxel probes octahedron coord to trace
				uint ProbeUpdateIndex = (StateFrameIndex + i) % (TranslucencyVolumeTracingFroxelProbesOctahedronResolution * TranslucencyVolumeTracingFroxelProbesOctahedronResolution);
				uint ProbeCoordY = ProbeUpdateIndex / TranslucencyVolumeTracingFroxelProbesOctahedronResolution;
				uint ProbeCoordX = ProbeUpdateIndex - ProbeCoordY * TranslucencyVolumeTracingFroxelProbesOctahedronResolution;
				uint2 SampleCoord = uint2(ProbeCoordX, ProbeCoordY);
#else
				uint2 SampleCoord = ProbeSamplesToTrace[i].xy;
#endif

				uint PackedProbeTexelCoord = (SampleCoord.x & 0xFF) | ((SampleCoord.y & 0xFF) << 8u); // This allows for probe resolution up to 256

				FroxelRefineTraceRayListBufferUAV[TraceRayDataStartIndex + i] = uint4(FroxelProbeGridCoordinate, PackedProbeTexelCoord);
			}

			FroxelReprojUpdateListBufferUAV[s_FroxelReprojUpdateGlobalGroupOffset + FroxelUpdateLocalGroupOffset] = uint4(FroxelProbeGridCoordinate, 0);
		}

	}
}
	
#endif // FroxelProbesUpdateSchedulerCS


// low res probes are likely 4x4 so to waste less threads in a wave we organise tracing as group of 4x4x4, probe pixels on XY and different probes on Z.
#define LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X	4
#define LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y	4
#define LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z	4

#define UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X	4
#define UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y	4
#define UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z	4

#define REFINE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X	64

#if defined(FroxelProbesUpdateIndirectArgsSetupMainCS)

#if PERMUTATION_DEBUG_PRINT
#include "../ShaderPrint.ush"
#endif

Buffer<uint>	FroxelClearCountBuffer;
RWBuffer<uint>	FroxelClearDispatchIndirectBufferUAV;
Buffer<uint>	FroxelLowResInitCountBuffer;
RWBuffer<uint>	FroxelLowResTraceDispatchIndirectBufferUAV;
RWBuffer<uint>	FroxelLowResTraceDispatchIndirectBufferRTUAV;
RWBuffer<uint>	FroxelLowResCopyDispatchIndirectBufferUAV;
Buffer<uint>	FroxelReprojUpdateCountBuffer;
RWBuffer<uint>	FroxelReprojUpdateDispatchIndirectBufferUAV;
Buffer<uint>	FroxelRefineTraceRayCountBuffer;
RWBuffer<uint>	FroxelRefineTraceRayDispatchIndirectBufferUAV;
RWBuffer<uint>	FroxelRefineTraceRayDispatchIndirectBufferRTUAV;
// Due to shader print, we are now maxing out the 8 UAV slot on dx11. Next time we will have to merge indirect dispatch buffers into a single one.

uint2			RayTracingThreadGroupSize;

[numthreads(THREADGROUP_SIZE, 1, 1)]
void FroxelProbesUpdateIndirectArgsSetupMainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	// Assuming we never go above 65k froxel update for now

	if (DispatchThreadId.x == 0)
	{
		// Indirect disaptch to trace low res probes when reseting froxel probes due to impossible temporal reprojection
		FroxelLowResTraceDispatchIndirectBufferUAV[0] = DivideAndRoundUp( TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution,	LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelLowResTraceDispatchIndirectBufferUAV[1] = DivideAndRoundUp( TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution,	LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y);
		FroxelLowResTraceDispatchIndirectBufferUAV[2] = DivideAndRoundUp( FroxelLowResInitCountBuffer[0],									LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z);
	}
	else if (DispatchThreadId.x == 1)
	{
		// Same as above but for ray tracing
		const uint NumRays  = FroxelLowResInitCountBuffer[0] * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution;

		uint NumGroups = (NumRays + RayTracingThreadGroupSize.x - 1) / RayTracingThreadGroupSize.x; // Roundup
		int3 IndirectArgs = GetRayTracingThreadCountWrapped(NumGroups, RADIANCE_CACHE_TRACE_TILE_SIZE_1D);
		WriteDispatchIndirectArgs(FroxelLowResTraceDispatchIndirectBufferRTUAV, 0, IndirectArgs);
	}
	else if (DispatchThreadId.x == 2)
	{
		// Indirect dispatch when copying the low res traced data onto the froxel probes
		FroxelLowResCopyDispatchIndirectBufferUAV[0] = DivideAndRoundUp( TranslucencyVolumeTracingFroxelProbesOctahedronResolution,			UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelLowResCopyDispatchIndirectBufferUAV[1] = DivideAndRoundUp( TranslucencyVolumeTracingFroxelProbesOctahedronResolution,			UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y);
		FroxelLowResCopyDispatchIndirectBufferUAV[2] = DivideAndRoundUp( FroxelLowResInitCountBuffer[0],									UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z);
	}
	else if (DispatchThreadId.x == 3)
	{
		// Indirect dispatch when reprojecting previous frame data into froxel probes
		FroxelReprojUpdateDispatchIndirectBufferUAV[0] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,		UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelReprojUpdateDispatchIndirectBufferUAV[1] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,		UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y);
		FroxelReprojUpdateDispatchIndirectBufferUAV[2] = DivideAndRoundUp(FroxelReprojUpdateCountBuffer[0],									UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z);
	}
	else if (DispatchThreadId.x == 4)
	{
		// Indirect dispatch when refining a probe with N ray trace per frame
		FroxelRefineTraceRayDispatchIndirectBufferUAV[0] = DivideAndRoundUp(FroxelRefineTraceRayCountBuffer[0], REFINE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelRefineTraceRayDispatchIndirectBufferUAV[1] = 1;
		FroxelRefineTraceRayDispatchIndirectBufferUAV[2] = 1;
	}
	else if (DispatchThreadId.x == 5)
	{
		// Same as above but for ray tracing
		const uint NumRays = FroxelRefineTraceRayCountBuffer[0];

		uint NumGroups = (NumRays + RayTracingThreadGroupSize.x - 1) / RayTracingThreadGroupSize.x; // Roundup
		int3 IndirectArgs = GetRayTracingThreadCountWrapped(NumGroups, RADIANCE_CACHE_TRACE_TILE_SIZE_1D);
		WriteDispatchIndirectArgs(FroxelRefineTraceRayDispatchIndirectBufferRTUAV, 0, IndirectArgs);
	}
	else if (DispatchThreadId.x == 6)
	{
		// Indirect dispatch when clearing non visible probes to black
		FroxelClearDispatchIndirectBufferUAV[0] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution, UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelClearDispatchIndirectBufferUAV[1] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution, UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y);
		FroxelClearDispatchIndirectBufferUAV[2] = DivideAndRoundUp(FroxelClearCountBuffer[0], UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z);
	}
	// Only 8 threads are dispatched.

#if PERMUTATION_DEBUG_PRINT
	if (DispatchThreadId.x == 0)
	{
		FShaderPrintContext Context = InitShaderPrintContext(true, uint2(500, 500));

		const uint LowResTraceCount = FroxelLowResInitCountBuffer[0] * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution;
		const uint RefineTraceCount = FroxelRefineTraceRayCountBuffer[0];
		const uint TotalTraceCount = LowResTraceCount + RefineTraceCount;

		Print(Context, TEXT("** Froxel Probes Scheduled Work **"));
		Newline(Context);
		Newline(Context);
		Print(Context, TEXT(" - LowRes reset probe count   = "));
		Print(Context, FroxelLowResInitCountBuffer[0]);
		Newline(Context);
		Print(Context, TEXT(" - Reprojected  probe count   = "));
		Print(Context, FroxelReprojUpdateCountBuffer[0]);
		Newline(Context);
		Print(Context, TEXT(" - Cleared  probe count       = "));
		Print(Context, FroxelClearCountBuffer[0]);
		Newline(Context);
		Newline(Context);
		Print(Context, TEXT(" - LowRes  probe trace count  = "));
		Print(Context, LowResTraceCount);
		Print(Context, TEXT("  (LowRes probe resolution = "));
		Print(Context, TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution, GetDefaultFontColor(), 2);
		Print(Context, TEXT(")"));
		Newline(Context);
		Print(Context, TEXT(" - Refined probe trace count  = "));
		Print(Context, RefineTraceCount);
		Print(Context, TEXT("  (Ray traced per probe per frame = "));
		Print(Context, TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame, GetDefaultFontColor(), 2);
		Print(Context, TEXT(")"));
		Newline(Context);
		Print(Context, TEXT(" - Total ray traced count     = "));
		Print(Context, TotalTraceCount);
	}
#endif
}
	
#endif // FroxelProbesUpdateIndirectArgsSetupMainCS




#if defined(UpdateFroxelProbesMainCS)

#if PERMUTATION_PROBE_FILL_MODE == 0	// Reproject last frame
Texture3D<float3>   VolumeFroxelProbeRadianceHistory;
Texture3D<float>    VolumeFroxelProbeHitDistanceHistory;
#elif PERMUTATION_PROBE_FILL_MODE == 1	// Copy low res probe data
Texture3D<float3>   VolumeFroxelLowResProbeRadiance;
Texture3D<float>    VolumeFroxelLowResProbeHitDistance;
#elif PERMUTATION_PROBE_FILL_MODE == 2	// Fill to black
#endif

RWTexture3D<float3> RWVolumeFroxelProbeRadiance;
RWTexture3D<float>  RWVolumeFroxelProbeHitDistance;

Buffer<uint>  FroxelUpdateCountBuffer;
Buffer<uint4> FroxelUpdateListBuffer;

float2 ViewFroxelProbesHistoryPreExposureAndInv;

[numthreads(UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X, UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y, UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z)]
void UpdateFroxelProbesMainCS(
	uint3 DispatchThreadIdIn : SV_DispatchThreadID)
{
	uint FroxelLowResInitCount = FroxelUpdateCountBuffer[0];
	if (DispatchThreadIdIn.z >= FroxelLowResInitCount)
	{
		return; // Not a froxel to regenerate
	}

	uint3 FroxelProbeGridCoordinate = FroxelUpdateListBuffer[DispatchThreadIdIn.z].xyz;
	uint2 FroxelProbeTraceTexelCoord = DispatchThreadIdIn.xy;

	// on the Z axis
	uint  FroxelProbesOctahedronResolution = TranslucencyVolumeTracingFroxelProbesOctahedronResolution;
//	uint3 DispatchThreadId = uint3(DispatchThreadIdIn.xy, 0) + FroxelProbeGridCoordinate * uint3(FroxelProbesOctahedronResolution.xx, 1);

//	uint3 FroxelProbeGridCoordinate = uint3(DispatchThreadId.xy / FroxelProbesOctahedronResolution, DispatchThreadId.z);
//	uint2 FroxelProbeTraceTexelCoord = DispatchThreadId.xy - FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution;

	float3 TraceRadiance = 0;
	float TraceHitDistance = MaxHalfFloat;

	if (all(FroxelProbeGridCoordinate < TranslucencyVolumeTracingFroxelProbesGridSize) && all(FroxelProbeTraceTexelCoord < FroxelProbesOctahedronResolution))
	{

#if PERMUTATION_PROBE_FILL_MODE == 0	// Reproject last frame

		const float3 FroxelProbeOffset = 0.0; // must be 0, not 0.5, in order to not perpetually shit data in UV space. TODO: review all alignement. => put probes at vertices of the froxels?
		float3 HistoryUV = ComputeTranslucencyGIVolumeUV(ComputeCellWorldPosition(FroxelProbeGridCoordinate * TranslucencyVolumeTracingFroxelProbesFroxelSize, FroxelProbeOffset), UnjitteredPrevWorldToClip);

		// This correction is required because the rounded up froxel probes space can be larger than the froxel count
		HistoryUV *= float3(TranslucencyGIGridSize) / float3(TranslucencyVolumeTracingFroxelProbesGridSize * TranslucencyVolumeTracingFroxelProbesFroxelSize);

		float2 ProbeUV;
		float ConeHalfAngle;
		const float2 ProbeTexelCenter = 0.5; // No jittering so not using GetProbeTexelCenter for stability
		GetFroxelProbeTracingUV(FroxelProbeTraceTexelCoord, ProbeTexelCenter, FroxelProbesOctahedronResolution, ProbeUV, ConeHalfAngle);

		// the coord of the probe to reproject
		float3 FroxelProbeGridTexelCoordFloat = clamp(HistoryUV * float3(TranslucencyVolumeTracingFroxelProbesGridSize), 0.0.xxx, float3(TranslucencyVolumeTracingFroxelProbesGridSize-1));
		uint3 FroxelProbeGridTexelCoord = FroxelProbeGridTexelCoordFloat;

	#if 0
		TraceRadiance = VolumeFroxelProbeRadianceHistory[uint3(FroxelProbeGridTexelCoord.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord.z)];
		TraceHitDistance = RWVolumeFroxelProbeHitDistance[uint3(FroxelProbeGridTexelCoord.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord.z)];
	#else
		float3 LerpUVs = saturate(FroxelProbeGridTexelCoordFloat - float3(FroxelProbeGridTexelCoord));

		uint3 FroxelProbeGridTexelCoord0 = FroxelProbeGridTexelCoord;
		uint3 FroxelProbeGridTexelCoord1 = min(FroxelProbeGridTexelCoord0 + 1, TranslucencyVolumeTracingFroxelProbesGridSize - 1);

		float3 Lighting000 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float3 Lighting001 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float3 Lighting010 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float3 Lighting011 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float3 Lighting100 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float3 Lighting101 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float3 Lighting110 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float3 Lighting111 = VolumeFroxelProbeRadianceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];

		float3 LightingX0 = lerp(lerp(Lighting000, Lighting001, LerpUVs.zzz), lerp(Lighting010, Lighting011, LerpUVs.zzz), LerpUVs.yyy);
		float3 LightingX1 = lerp(lerp(Lighting100, Lighting101, LerpUVs.zzz), lerp(Lighting110, Lighting111, LerpUVs.zzz), LerpUVs.yyy);
		TraceRadiance = lerp(LightingX0, LightingX1, LerpUVs.xxx);

		float HitDist000 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float HitDist001 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float HitDist010 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float HitDist011 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float HitDist100 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float HitDist101 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float HitDist110 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float HitDist111 = VolumeFroxelProbeHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];

		float3 HitDistX0 = lerp(lerp(HitDist000, HitDist001, LerpUVs.zzz), lerp(HitDist010, HitDist011, LerpUVs.zzz), LerpUVs.yyy);
		float3 HitDistX1 = lerp(lerp(HitDist100, HitDist101, LerpUVs.zzz), lerp(HitDist110, HitDist111, LerpUVs.zzz), LerpUVs.yyy);
		TraceHitDistance = lerp(HitDistX0, HitDistX1, LerpUVs.xxx);
	#endif

		// Adapt to current exposure
//		TraceRadiance *= ViewFroxelProbesHistoryPreExposureAndInv.y * View.PreExposure;

	#if FROXEL_PROBE_DEBUG_COLOR
		TraceRadiance *= float3(1, 1, 0);
	#endif

		uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
		RWVolumeFroxelProbeRadiance[WriteCoord] = TraceRadiance;
		RWVolumeFroxelProbeHitDistance[WriteCoord] = min(TraceHitDistance, MaxHalfFloat);

#elif PERMUTATION_PROBE_FILL_MODE == 1	// Copy low res probe data

		uint3 SourceCoord = uint3(FroxelProbeGridCoordinate.xy * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution, FroxelProbeGridCoordinate.z);
		SourceCoord.xy += float2(FroxelProbeTraceTexelCoord) * float(TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution) / float(TranslucencyVolumeTracingFroxelProbesOctahedronResolution);

		TraceRadiance = VolumeFroxelLowResProbeRadiance[SourceCoord];
		TraceHitDistance = VolumeFroxelLowResProbeHitDistance[SourceCoord];

	#if FROXEL_PROBE_DEBUG_COLOR
		TraceRadiance *= float3(1, 0, 0);
	#endif

		uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
		RWVolumeFroxelProbeRadiance[WriteCoord] = TraceRadiance;
		RWVolumeFroxelProbeHitDistance[WriteCoord] = TraceHitDistance;
		
#elif PERMUTATION_PROBE_FILL_MODE == 2	// Clear froxel probe

		TraceRadiance = 0.0.xxx;
		TraceHitDistance = MaxHalfFloat;

	#if FROXEL_PROBE_DEBUG_COLOR
		TraceRadiance = float3(0, 0, 1);
	#endif

		uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
		RWVolumeFroxelProbeRadiance[WriteCoord] = TraceRadiance;
		RWVolumeFroxelProbeHitDistance[WriteCoord] = TraceHitDistance;

#endif
	}
}

#endif






#if LUMEN_HARDWARE_RAYTRACING

#include "/Engine/Shared/RayTracingTypes.h"
#include "LumenHardwareRayTracingCommon.ush"

#ifndef DIM_LIGHTING_MODE
#define DIM_LIGHTING_MODE LIGHTING_FROM_SURFACE_CACHE
#endif

// From FLumenHardwareRayTracingShaderBase::SharedParameters
RaytracingAccelerationStructure TLAS;
uint MaxTraversalIterations;
uint MeshSectionVisibilityTest;

#endif // LUMEN_HARDWARE_RAYTRACING

#if LUMEN_HARDWARE_INLINE_RAYTRACING

// From FLumenHardwareRayTracingShaderBase::SharedParameters
StructuredBuffer<FHitGroupRootConstants> HitGroupData;
StructuredBuffer<FRayTracingSceneMetadataRecord> RayTracingSceneMetadata;

FLumenTraceRayInlineCallback InitLumenTraceRayInlineCallback()
{
	FLumenTraceRayInlineCallback Callback;
	Callback.HitGroupData = HitGroupData;
	Callback.bShadowRay = false;
	return Callback;
}

#endif // LUMEN_HARDWARE_INLINE_RAYTRACING

#if defined(TranslucencyVolumeFroxelProbesCS) || defined(TranslucencyVolumeFroxelLowResProbesRayTracingRGS) || defined(TranslucencyVolumeFroxelLowResProbesRayTracingCS) || \
	defined(FroxelProbesRefineTraceRayCS) || defined(FroxelProbesRefineHWRayTracingRGS) || defined(FroxelProbesRefineHWRayTracingCS)

struct FTranslucencyVolumeTraceRayResult
{
	float3 Radiance;
	float  HitDistance;
};

FTranslucencyVolumeTraceRayResult TranslucencyVolumeTraceRayCommon(uint3 FroxelProbeGridCoordinate, float3 WorldPosition, float3 TranslatedWorldPosition, float3 WorldConeDirection, float ConeHalfAngle)
{
	float TraceHitDistance = MaxTraceDistance;

#if LUMEN_HARDWARE_RAYTRACING

	FRayDesc Ray;
	Ray.Origin = WorldPosition + DFHackToFloat(PrimaryView.PreViewTranslation); // LUMEN_LWC_TODO
	Ray.Direction = WorldConeDirection;
	Ray.TMin = 0;
	Ray.TMax = MaxTraceDistance;

	FRayCone RayCone = (FRayCone)0;
	RayCone = PropagateRayCone(RayCone, ConeHalfAngle, 0.0);

	const uint LinearCoord = FroxelProbeGridCoordinate.y * TranslucencyVolumeTracingFroxelProbesGridSize.x + FroxelProbeGridCoordinate.x;
	FRayTracedLightingContext Context = CreateRayTracedLightingContext(
		RayCone,
		FroxelProbeGridCoordinate.xy,
		LinearCoord,
		/*CullingMode*/ RAY_FLAG_NONE, // Disable culling in order to minimize leaking when rays start inside walls
		MaxTraversalIterations,
		MeshSectionVisibilityTest != 0);

	FRayTracedLightingResult TraceLightingResult;
	TraceLightingResult.Radiance = 0;
	TraceLightingResult.TraceHitDistance = MaxTraceDistance;
#if DIM_LIGHTING_MODE == LIGHTING_FROM_SURFACE_CACHE
#if LUMEN_HARDWARE_INLINE_RAYTRACING
	Context.HitGroupData = HitGroupData;
	Context.RayTracingSceneMetadata = RayTracingSceneMetadata;
#endif
	TraceLightingResult = TraceAndCalculateRayTracedLightingFromSurfaceCache(TLAS, Ray, Context);
#else
	TraceLightingResult = TraceAndCalculateRayTracedLighting(TLAS, Ray, Context, DIM_LIGHTING_MODE, false);
#endif

	FConeTraceResult TraceResult = (FConeTraceResult)0;
	TraceResult.OpaqueHitDistance = TraceLightingResult.TraceHitDistance;
	TraceResult.Lighting = TraceLightingResult.Radiance;
	if (TraceLightingResult.bIsHit)
	{
		TraceHitDistance = TraceResult.OpaqueHitDistance;
		TraceResult.Transparency = 0.0;
	}
	else
	{
		TraceResult.Transparency = 1.0;
		ApplySkylightToTraceResult(WorldConeDirection, TraceResult);
	}


#else // LUMEN_HARDWARE_RAYTRACING

	float VoxelTraceStartDistance = CalculateVoxelTraceStartDistance(0, MaxTraceDistance, MaxMeshSDFTraceDistance, false) * VoxelTraceStartDistanceScale;

	FConeTraceInput TraceInput;
	TraceInput.Setup(WorldPosition, TranslatedWorldPosition, WorldConeDirection, ConeHalfAngle, 0, 0, MaxTraceDistance, StepFactor);
	TraceInput.VoxelTraceStartDistance = VoxelTraceStartDistance;
	TraceInput.SDFStepFactor = 1;

	FConeTraceResult TraceResult = (FConeTraceResult)0;
	TraceResult.Transparency = 1;

	RayTraceGlobalDistanceField(TraceInput, TraceResult);

	if (TraceResult.Transparency <= .5f)
	{
		TraceHitDistance = TraceResult.OpaqueHitDistance;
	}

	ApplySkylightToTraceResult(WorldConeDirection, TraceResult);

#endif // LUMEN_HARDWARE_RAYTRACING

	FTranslucencyVolumeTraceRayResult Result;
	Result.Radiance		= TraceResult.Lighting;
	Result.HitDistance	= TraceHitDistance;
	return Result;
}

void TranslucencyVolumeFroxelProbesTracingCommon(
	uint3 DispatchThreadId,
	uint  FroxelProbesOctahedronResolution)
{
	uint3 FroxelProbeGridCoordinate = uint3(DispatchThreadId.xy / FroxelProbesOctahedronResolution, DispatchThreadId.z);
	uint2 FroxelProbeTraceTexelCoord = DispatchThreadId.xy - FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution;
	
	uint3 FroxelGridCoordinate = FroxelProbeGridCoordinate * TranslucencyVolumeTracingFroxelProbesFroxelSize;

	if (all(FroxelProbeGridCoordinate < TranslucencyVolumeTracingFroxelProbesGridSize) && all(FroxelProbeTraceTexelCoord < FroxelProbesOctahedronResolution))
	{
		FTranslucencyVolumeTraceRayResult TraceResult;
		TraceResult.Radiance = 0;
		TraceResult.HitDistance = MaxTraceDistance;

		if (IsFroxelProbeVisible(FroxelProbeGridCoordinate)) 
		{
			float3 LocalFrameJitterOffset = 0.5f; // Do not Jitter for now
			ApplyDepthconstraintsToOffset(FroxelGridCoordinate + TranslucencyVolumeTracingFroxelProbesFroxelSize/2, LocalFrameJitterOffset);

			float3 WorldPosition = ComputeCellWorldPosition(FroxelGridCoordinate, LocalFrameJitterOffset);
			float3 TranslatedWorldPosition = ComputeCellTranslatedWorldPosition(FroxelGridCoordinate, LocalFrameJitterOffset);

			float2 ProbeUV;
			float ConeHalfAngle;
			const float2 ProbeTexelCenter = 0.5; // No jittering so not using GetProbeTexelCenter for stability
			GetFroxelProbeTracingUV(FroxelProbeTraceTexelCoord, ProbeTexelCenter, FroxelProbesOctahedronResolution,  ProbeUV, ConeHalfAngle);

			float3 WorldConeDirection = EquiAreaSphericalMapping(ProbeUV);
			
			TraceResult = TranslucencyVolumeTraceRayCommon(FroxelProbeGridCoordinate, WorldPosition, TranslatedWorldPosition, WorldConeDirection, ConeHalfAngle);

		//	TraceResult.Radiance *= View.PreExposure;
			float MaxLighting = max3(TraceResult.Radiance.x, TraceResult.Radiance.y, TraceResult.Radiance.z);
			if (MaxLighting > MaxRayIntensity)
			{
				TraceResult.Radiance *= MaxRayIntensity / MaxLighting;
			}
		}

		uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
		RWVolumeTraceRadiance[WriteCoord] = TraceResult.Radiance;
		RWVolumeTraceHitDistance[WriteCoord] = min(TraceResult.HitDistance, MaxHalfFloat);
	}
}



#if defined(TranslucencyVolumeFroxelProbesCS)

#if	PERMUTATION_LOWRES_FROXEL_INDIRECT

Buffer<uint>  FroxelLowResInitCountBuffer;
Buffer<uint4> FroxelLowResInitListBuffer;

[numthreads(LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X, LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y, LOWRES_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z)]
void TranslucencyVolumeFroxelProbesCS(
	uint3 DispatchThreadIdIn : SV_DispatchThreadID)
{
	uint FroxelLowResInitCount = FroxelLowResInitCountBuffer[0];
	if (DispatchThreadIdIn.z >= FroxelLowResInitCount)
	{
		return; // Not a froxel to regenerate
	}
	uint3 FroxelGridCoord = FroxelLowResInitListBuffer[DispatchThreadIdIn.z].xyz;
	// on the Z axis
	uint3 DispatchThreadId = uint3(DispatchThreadIdIn.xy, 0) + FroxelGridCoord * uint3(TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution.xx, 1);
	uint  FroxelProbesOctahedronResolution = TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution; // Select the resoltion of low res probes

	TranslucencyVolumeFroxelProbesTracingCommon(DispatchThreadId, FroxelProbesOctahedronResolution);
}

#else // PERMUTATION_LOWRES_FROXEL_INDIRECT

[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void TranslucencyVolumeFroxelProbesCS(
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint  FroxelProbesOctahedronResolution = TranslucencyVolumeTracingFroxelProbesOctahedronResolution;

	TranslucencyVolumeFroxelProbesTracingCommon(DispatchThreadId, FroxelProbesOctahedronResolution);
}
#endif // PERMUTATION_LOWRES_FROXEL_INDIRECT

#endif // TranslucencyVolumeFroxelProbesCS

// Ray tracing version of TranslucencyVolumeFroxelProbesCS + PERMUTATION_LOWRES_FROXEL_INDIRECT=1
#if defined(TranslucencyVolumeFroxelLowResProbesRayTracingRGS) || defined(TranslucencyVolumeFroxelLowResProbesRayTracingCS)

Buffer<uint>  FroxelLowResInitCountBuffer;
Buffer<uint4> FroxelLowResInitListBuffer;

//LUMEN_HARDWARE_RAY_TRACING_ENTRY(TranslucencyVolumeFroxelLowResProbesRayTracing)
//{
//	uint ThreadIndex = GetUnWrappedRayTracingDispatchThreadId(DispatchRaysIndex(), RADIANCE_CACHE_TRACE_TILE_SIZE_1D);

#if LUMEN_HARDWARE_INLINE_RAYTRACING

[numthreads(INLINE_RAY_TRACING_THREAD_GROUP_SIZE_X, INLINE_RAY_TRACING_THREAD_GROUP_SIZE_Y, 1)]
void TranslucencyVolumeFroxelLowResProbesRayTracingCS(
	uint3 GroupId : SV_GroupID,
	uint GroupIndex : SV_GroupIndex)
{
	uint GroupLinearIndex = GetUnWrappedRayTracingDispatchThreadId(GroupId, RADIANCE_CACHE_TRACE_TILE_SIZE_1D);
	uint ThreadIndex = GroupLinearIndex * INLINE_RAY_TRACING_THREAD_GROUP_SIZE_X + GroupIndex;

#else // LUMEN_HARDWARE_INLINE_RAYTRACING}

RAY_TRACING_ENTRY_RAYGEN(TranslucencyVolumeFroxelLowResProbesRayTracingRGS)
{
	uint ThreadIndex = GetUnWrappedRayTracingDispatchThreadId(DispatchRaysIndex(), RADIANCE_CACHE_TRACE_TILE_SIZE_1D);

#endif // LUMEN_HARDWARE_INLINE_RAYTRACING

	uint ProbeIndex = ThreadIndex / (TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);
	uint ProbePixelLinearIndex = ThreadIndex - ProbeIndex * (TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);
	uint2 ProbePixelCoord;
	ProbePixelCoord.y = ProbePixelLinearIndex / TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution;
	ProbePixelCoord.x = ProbePixelLinearIndex - ProbePixelCoord.y * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution;

	uint FroxelLowResInitCount = FroxelLowResInitCountBuffer[0];
	if (ProbeIndex >= FroxelLowResInitCount)
	{
		return; // Not a froxel to regenerate
	}

	uint3 FroxelGridCoord = FroxelLowResInitListBuffer[ProbeIndex].xyz;
	// on the Z axis
	uint3 DispatchThreadId = uint3(ProbePixelCoord, 0) + FroxelGridCoord * uint3(TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution.xx, 1);
	uint  FroxelProbesOctahedronResolution = TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution; // Select the resoltion of low res probes

	TranslucencyVolumeFroxelProbesTracingCommon(DispatchThreadId, FroxelProbesOctahedronResolution);
}

#endif // TranslucencyVolumeFroxelProbesCS



#if defined(FroxelProbesRefineTraceRayCS) || defined(FroxelProbesRefineHWRayTracingRGS) || defined(FroxelProbesRefineHWRayTracingCS)

Buffer<uint>	FroxelRefineTraceRayCountBuffer;
Buffer<uint4>	FroxelRefineTraceRayListBuffer;

RWTexture3D<float3> RWVolumeFroxelProbeRadiance;
RWTexture3D<float>  RWVolumeFroxelProbeHitDistance;

void TranslucencyVolumeFroxelProbesRefineTraceRay(uint RayTraceLinearIndex)
{
	uint FroxelRefineTraceRayCount = FroxelRefineTraceRayCountBuffer[0];
	if (RayTraceLinearIndex >= FroxelRefineTraceRayCount)
	{
		return; // Not a froxel to regenerate
	}

	uint  FroxelProbesOctahedronResolution = TranslucencyVolumeTracingFroxelProbesOctahedronResolution;

	uint4 RayTracedData = FroxelRefineTraceRayListBuffer[RayTraceLinearIndex];
	uint3 FroxelGridCoord = RayTracedData.xyz;
	uint PackedProbeTexelCoord = RayTracedData.w;
	uint ProbeCoordX = PackedProbeTexelCoord & 0xFF;
	uint ProbeCoordY = (PackedProbeTexelCoord >> 8) & 0xFF;

	uint3 FroxelProbeGridCoordinate = FroxelGridCoord;
	uint2 FroxelProbeTraceTexelCoord = uint2(ProbeCoordX, ProbeCoordY);
	uint3 FroxelGridCoordinate = FroxelProbeGridCoordinate * TranslucencyVolumeTracingFroxelProbesFroxelSize;

	float3 LocalFrameJitterOffset = 0.5f; // Do not Jitter for now
	ApplyDepthconstraintsToOffset(FroxelGridCoordinate + TranslucencyVolumeTracingFroxelProbesFroxelSize / 2, LocalFrameJitterOffset);

	float3 WorldPosition = ComputeCellWorldPosition(FroxelGridCoordinate, LocalFrameJitterOffset);
	float3 TranslatedWorldPosition = ComputeCellTranslatedWorldPosition(FroxelGridCoordinate, LocalFrameJitterOffset);

	float2 ProbeUV;
	float ConeHalfAngle;
	const float2 ProbeTexelCenter = 0.5; // Do not Jitter for now
	GetFroxelProbeTracingUV(FroxelProbeTraceTexelCoord, ProbeTexelCenter, FroxelProbesOctahedronResolution, ProbeUV, ConeHalfAngle);
	float3 WorldConeDirection = EquiAreaSphericalMapping(ProbeUV);

	FTranslucencyVolumeTraceRayResult TraceResult = TranslucencyVolumeTraceRayCommon(FroxelProbeGridCoordinate, WorldPosition, TranslatedWorldPosition, WorldConeDirection, ConeHalfAngle);

//	TraceResult.Radiance *= View.PreExposure;
	float MaxLighting = max3(TraceResult.Radiance.x, TraceResult.Radiance.y, TraceResult.Radiance.z);
	if (MaxLighting > MaxRayIntensity)
	{
		TraceResult.Radiance *= MaxRayIntensity / MaxLighting;
	}

#if FROXEL_PROBE_DEBUG_COLOR
	TraceResult.Radiance *= float3(0, 1, 1);
#endif

	uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
	RWVolumeFroxelProbeRadiance[WriteCoord] = TraceResult.Radiance;
	//	RWVolumeFroxelProbeRadiance[WriteCoord] = FroxelGridCoord / 25.0;
	RWVolumeFroxelProbeHitDistance[WriteCoord] = min(TraceResult.HitDistance, MaxHalfFloat);
}

#endif // defined(FroxelProbesRefineTraceRayCS) || defined(FroxelProbesRefineHWRayTracingRGS) || defined(FroxelProbesRefineHWRayTracingCS)





#if defined(FroxelProbesRefineTraceRayCS)

[numthreads(REFINE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X, 1, 1)]
void FroxelProbesRefineTraceRayCS(
	uint3 DispatchThreadIdIn : SV_DispatchThreadID)
{
	TranslucencyVolumeFroxelProbesRefineTraceRay(DispatchThreadIdIn.x);
}

#endif


// Ray tracing version of FroxelProbesRefineTraceRayCS
#if defined(FroxelProbesRefineHWRayTracingRGS) || defined(FroxelProbesRefineHWRayTracingCS)

#if LUMEN_HARDWARE_INLINE_RAYTRACING

[numthreads(INLINE_RAY_TRACING_THREAD_GROUP_SIZE_X, INLINE_RAY_TRACING_THREAD_GROUP_SIZE_Y, 1)]
void FroxelProbesRefineHWRayTracingCS(
	uint3 GroupId : SV_GroupID,
	uint GroupIndex : SV_GroupIndex)
{
	uint GroupLinearIndex = GetUnWrappedRayTracingDispatchThreadId(GroupId, RADIANCE_CACHE_TRACE_TILE_SIZE_1D);
	uint RayTraceLinearIndex = GroupLinearIndex * INLINE_RAY_TRACING_THREAD_GROUP_SIZE_X + GroupIndex;

	TranslucencyVolumeFroxelProbesRefineTraceRay(RayTraceLinearIndex);
}

#else // LUMEN_HARDWARE_INLINE_RAYTRACING}

RAY_TRACING_ENTRY_RAYGEN(FroxelProbesRefineHWRayTracingRGS)
{
	uint RayTraceLinearIndex = GetUnWrappedRayTracingDispatchThreadId(DispatchRaysIndex(), RADIANCE_CACHE_TRACE_TILE_SIZE_1D);

	TranslucencyVolumeFroxelProbesRefineTraceRay(RayTraceLinearIndex);
}

#endif // LUMEN_HARDWARE_INLINE_RAYTRACING

#endif



#endif // All probe tracing shaders