// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../SHCommon.ush"
#include "../MonteCarlo.ush"
#include "../OctahedralCommon.ush"
#include "LumenCardCommon.ush"
#include "LumenTracingCommon.ush"
#include "LumenSoftwareRayTracing.ush"
#include "LumenRadianceCacheCommon.ush"
#include "LumenRadianceCacheMarkCommon.ush"
#include "LumenTranslucencyVolumeLightingShared.ush"
#include "LumenScreenProbeCommon.ush"
#include "../RayTracing/RayGenUtils.ush"
#include "LumenRadianceCacheTracingCommon.ush"

#ifndef THREADGROUP_SIZE
#define THREADGROUP_SIZE 1
#endif

#ifndef PROBE_SOURCE_MODE
#define PROBE_SOURCE_MODE 0
#endif

#define FROXEL_POS_OFFSET 1

#define FROXEL_PROBE_DEBUG_COLOR 0

/*
 * Froxel Probes TODO
 *  - Add back pre exposition of data
 */

void LumenFrontLayerTranslucencyClearGBufferPS(
	  in  float4 SvPosition		: SV_Position
	, out float4 OutColor		: SV_Target0
	, out float  OutDepth		: SV_DEPTH)
{
	const uint2 PixelCoord = uint2(SvPosition.xy);

	OutColor = 0;
	OutDepth = SceneTexturesStruct.SceneDepthTexture.Load(int3(PixelCoord, 0)).r;
}

#ifdef MarkRadianceProbesUsedByTranslucencyVolumeCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, THREADGROUP_SIZE)]
void MarkRadianceProbesUsedByTranslucencyVolumeCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
	uint3 GridCoordinate = DispatchThreadId;

	if (all(GridCoordinate < TranslucencyGIGridSize))
	{
		float3 WorldPosition = ComputeCellWorldPosition(GridCoordinate, FROXEL_POS_OFFSET ? FrameJitterOffset.xyz : 0.0f);
		uint ClipmapIndex = GetRadianceProbeClipmapForMark(WorldPosition);

		if (IsValidRadianceCacheClipmapForMark(ClipmapIndex) && IsFroxelVisible(GridCoordinate))
		{
			MarkPositionUsedInIndirectionTexture(WorldPosition, ClipmapIndex);
		}
	}
}
#endif

RWTexture3D<float3> RWVolumeTraceRadiance;
RWTexture3D<float> RWVolumeTraceHitDistance;
Texture3D<float3> VolumeFroxelProbeRadianceHitDistance;	// Only float3, filtering out the unused distance for now.

// Applying an offset from the depth buffer helps with reducing self intersection with global distance field tracing.
void ApplyDepthconstraintsToOffset(float3 GridCoordinate, inout float3 LocalFrameJitterOffset)
{
	if (GridCenterOffsetFromDepthBuffer >= 0.0)
	{
		float4 GridSampleClip	= mul(float4(ComputeCellTranslatedWorldPosition(GridCoordinate, LocalFrameJitterOffset), 1), View.TranslatedWorldToClip);
		float3 GridSampleScreen	= GridSampleClip.xyz / GridSampleClip.w;
		float3 GridSampleUVz	= float3(GridSampleScreen.xy * View.ScreenPositionScaleBias.xy + View.ScreenPositionScaleBias.wz, GridSampleScreen.z);
		float GridSampleSceneDepth = ConvertFromDeviceZ(SceneTexturesStruct.SceneDepthTexture.SampleLevel(SceneTexturesStruct_SceneDepthTextureSampler, GridSampleUVz.xy, 0).r);

		float DepthGridCoordinateWithZOffset = ComputeZSliceFromDepth(GridSampleSceneDepth) - GridCenterOffsetFromDepthBuffer;

		float3 GridCoordinateOffset = float3(GridCoordinate) + LocalFrameJitterOffset;
		
		const float DepthToSampleGridOffset = DepthGridCoordinateWithZOffset - GridCoordinateOffset.z;	// <0 if samples is in front of the depth buffer
		if (DepthToSampleGridOffset < 0.0																// Move the sample forward only if the depth buffer grid coordinate is closer,
			&& (-DepthToSampleGridOffset < GridCenterOffsetThresholdToAcceptDepthBufferOffset)			// But only if it is less than N slice away (to not bring all the sample behind forward)
			)
		{
			// If the grid sample is further than the grid z for the depth buffer, adjust the offset 
			LocalFrameJitterOffset.z += DepthToSampleGridOffset;
		}
	}
}

#ifdef TranslucencyVolumeTraceVoxelsCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void TranslucencyVolumeTraceVoxelsCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
#define DEINTERLEAVED_VOLUME_TRACING 0
#if DEINTERLEAVED_VOLUME_TRACING
	uint3 GridCoordinate = uint3(DispatchThreadId.xy % TranslucencyGIGridSize.xy, DispatchThreadId.z);
	uint2 TraceTexelCoord = DispatchThreadId.xy / TranslucencyGIGridSize.xy;
#else
	uint3 GridCoordinate = uint3(DispatchThreadId.xy / TranslucencyVolumeTracingOctahedronResolution, DispatchThreadId.z);
	uint2 TraceTexelCoord = DispatchThreadId.xy - GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution;
#endif

	if (all(GridCoordinate < TranslucencyGIGridSize) && all(TraceTexelCoord < TranslucencyVolumeTracingOctahedronResolution))
	{
		float3 TraceRadiance = 0;
		float TraceHitDistance = MaxTraceDistance;

		if (IsFroxelVisible(GridCoordinate))
		{
			float3 LocalFrameJitterOffset = FROXEL_POS_OFFSET ? FrameJitterOffset.xyz : 0.0f;
			ApplyDepthconstraintsToOffset(GridCoordinate, LocalFrameJitterOffset);

			float3 WorldPosition = ComputeCellWorldPosition(GridCoordinate, LocalFrameJitterOffset);
			float3 TranslatedWorldPosition = ComputeCellTranslatedWorldPosition(GridCoordinate, LocalFrameJitterOffset);

			float2 ProbeUV;
			float ConeHalfAngle;
			GetProbeTracingUV(TraceTexelCoord, GetProbeTexelCenter(GridCoordinate.xy), ProbeUV, ConeHalfAngle);

			float3 WorldConeDirection = EquiAreaSphericalMapping(ProbeUV);

			float TraceDistance = MaxTraceDistance;
			FRadianceCacheCoverage Coverage;
			Coverage.bValid = false;

#if PROBE_SOURCE_MODE == PROBE_SOURCE_MODE_RADIANCE_CACHE
			Coverage = GetRadianceCacheCoverage(WorldPosition, WorldConeDirection, .5f);
				
			if (Coverage.bValid)
			{
				TraceDistance = min(TraceDistance, Coverage.MinTraceDistanceBeforeInterpolation);
			}
#endif
			float VoxelTraceStartDistance = CalculateVoxelTraceStartDistance(0, MaxTraceDistance, MaxMeshSDFTraceDistance, false) * VoxelTraceStartDistanceScale;

			FConeTraceInput TraceInput;
			TraceInput.Setup(WorldPosition, TranslatedWorldPosition, WorldConeDirection, ConeHalfAngle, 0, 0, TraceDistance, StepFactor);
			TraceInput.VoxelTraceStartDistance = VoxelTraceStartDistance;
			TraceInput.SDFStepFactor = 1;

			FConeTraceResult TraceResult = (FConeTraceResult)0;
			TraceResult.Transparency = 1;

#if TRACE_FROM_VOLUME
			RayTraceGlobalDistanceField(TraceInput, TraceResult);
#endif

			if (TraceResult.Transparency <= .5f)
			{
				TraceHitDistance = TraceResult.OpaqueHitDistance;
			}

#if PROBE_SOURCE_MODE == PROBE_SOURCE_MODE_FROXEL
			if (true) // Froxel probes are always valid for the translucency volume froxels.
			{
				const float3 FroxelProbeRadiance = GetFroxelProbeLighting(VolumeFroxelProbeRadianceHitDistance, GridCoordinate, ProbeUV).rgb;// *View.OneOverPreExposure;
			
				// Lerp according to tracing coverage=1-transparency
				TraceResult.Lighting += FroxelProbeRadiance * TraceResult.Transparency;
			
				TraceResult.Transparency = 0.0;
			}
			else
#elif PROBE_SOURCE_MODE == PROBE_SOURCE_MODE_RADIANCE_CACHE
			if (Coverage.bValid)
			{
				SampleRadianceCacheAndApply(Coverage, WorldPosition, WorldConeDirection, ConeHalfAngle, TraceResult.Lighting, TraceResult.Transparency);
			}
			else
#endif
			{
				ApplySkylightToTraceResult(WorldConeDirection, TraceResult);
			}

			TraceRadiance = TraceResult.Lighting;

			TraceRadiance *= View.PreExposure;

			float MaxLighting = max3(TraceRadiance.x, TraceRadiance.y, TraceRadiance.z);

			if (MaxLighting > MaxRayIntensity)
			{
				TraceRadiance *= MaxRayIntensity / MaxLighting;
			}
		}

		uint3 WriteCoord = uint3(GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution + TraceTexelCoord, GridCoordinate.z);
		RWVolumeTraceRadiance[WriteCoord] = TraceRadiance;
		RWVolumeTraceHitDistance[WriteCoord] = min(TraceHitDistance, MaxHalfFloat);
	}
}
#endif

Texture3D<float3> VolumeTraceRadiance;
Texture3D<float> VolumeTraceHitDistance;

float3 PreviousFrameJitterOffset;
float4x4 UnjitteredPrevWorldToClip;

int SpatialFilterSampleCount;
int3 SpatialFilterDirection;
float3 SpatialFilterGaussParams;

float GaussianWeight1d(float Distance)
{
	const float StandardDev					= SpatialFilterGaussParams.x;	// s
	const float InvStandardDevSquaredTimes2	= SpatialFilterGaussParams.y;	// 1 / (2 * s * s)
	const float InvStandardDevTimesSqrt2	= SpatialFilterGaussParams.z;	// 1 / (s * sqrt(2PI))
	return InvStandardDevTimesSqrt2 * exp(-Distance * Distance * InvStandardDevSquaredTimes2);
}

#ifdef TranslucencyVolumeSpatialSeparableFilterCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void TranslucencyVolumeSpatialSeparableFilterCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
	uint3 GridCoordinate = uint3(DispatchThreadId.xy / TranslucencyVolumeTracingOctahedronResolution, DispatchThreadId.z);
	uint2 TraceTexelCoord = DispatchThreadId.xy - GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution;

	if (all(GridCoordinate < TranslucencyGIGridSize) && all(TraceTexelCoord < TranslucencyVolumeTracingOctahedronResolution))
	{
		float3 FilteredRadiance = 0;
		float TotalWeight = 0;

		LOOP
		for (int Offset = -SpatialFilterSampleCount; Offset <= SpatialFilterSampleCount; Offset++)
		{
			int3 NeighborGridCoordinate = GridCoordinate + SpatialFilterDirection * Offset;

			if (all(and(NeighborGridCoordinate >= 0, NeighborGridCoordinate < TranslucencyGIGridSize)))
			{
				float3 NeighborRadiance = VolumeTraceRadiance[uint3(NeighborGridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution + TraceTexelCoord, NeighborGridCoordinate.z)];
				float Weight = GaussianWeight1d(float(Offset));
				FilteredRadiance += NeighborRadiance * Weight;
				TotalWeight += Weight;
			}
		}
		
		RWVolumeTraceRadiance[DispatchThreadId] = FilteredRadiance / max(TotalWeight, .00001f);
	}
}
#endif

RWTexture3D<float4> RWTranslucencyGI0;
RWTexture3D<float4> RWTranslucencyGI1;
RWTexture3D<float4> RWTranslucencyGINewHistory0;
RWTexture3D<float4> RWTranslucencyGINewHistory1;

Texture3D TranslucencyGIHistory0;
Texture3D TranslucencyGIHistory1;
SamplerState TranslucencyGIHistorySampler;

float HistoryWeight; 

#ifdef TranslucencyVolumeIntegrateCS
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, THREADGROUP_SIZE)]
void TranslucencyVolumeIntegrateCS(
	uint3 GroupId : SV_GroupID,
	uint3 DispatchThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID)
{
	uint3 GridCoordinate = DispatchThreadId;

	if (all(GridCoordinate < TranslucencyGIGridSize))
	{
		float3 WorldPosition = ComputeCellWorldPosition(GridCoordinate, FROXEL_POS_OFFSET ? FrameJitterOffset.xyz : 0.0f);

		FTwoBandSHVectorRGB Lighting = (FTwoBandSHVectorRGB)0;
		bool bNewLightingValid = false;
		float InvTracingOctahedronResolution = 1.0f / (float)TranslucencyVolumeTracingOctahedronResolution;

		if (IsFroxelVisible(GridCoordinate))
		{
			for (uint Y = 0; Y < TranslucencyVolumeTracingOctahedronResolution; Y++)
			{
				for (uint X = 0; X < TranslucencyVolumeTracingOctahedronResolution; X++)
				{
					float3 TraceRadiance = VolumeTraceRadiance[uint3(GridCoordinate.xy * TranslucencyVolumeTracingOctahedronResolution + uint2(X, Y), GridCoordinate.z)] * View.OneOverPreExposure;

					float2 ProbeTexelCenter = float2(0.5, 0.5);
					float2 ProbeUV = (float2(X, Y) + ProbeTexelCenter) * InvTracingOctahedronResolution;
					float3 WorldConeDirection = EquiAreaSphericalMapping(ProbeUV);

					Lighting = AddSH(Lighting, MulSH(SHBasisFunction(WorldConeDirection), TraceRadiance));
				}
			}

			float NormalizeFactor = PI / TranslucencyVolumeTracingOctahedronResolution / TranslucencyVolumeTracingOctahedronResolution;
			Lighting.R.V *= NormalizeFactor;
			Lighting.G.V *= NormalizeFactor;
			Lighting.B.V *= NormalizeFactor;
			bNewLightingValid = true;
		}

		// Output for Volumetric Fog which has its own temporal filter
		{
			float3 AmbientLightingVector = float3(Lighting.R.V.x, Lighting.G.V.x, Lighting.B.V.x);
			RWTranslucencyGI0[GridCoordinate] = float4(AmbientLightingVector, 0);

			float3 LuminanceWeights = AmbientLightingVector.rgb / (dot(AmbientLightingVector, 1) + 0.00001f);
			float3 Coefficient0 = float3(Lighting.R.V.y, Lighting.G.V.y, Lighting.B.V.y);
			float3 Coefficient1 = float3(Lighting.R.V.z, Lighting.G.V.z, Lighting.B.V.z);
			float3 Coefficient2 = float3(Lighting.R.V.w, Lighting.G.V.w, Lighting.B.V.w);
			RWTranslucencyGI1[GridCoordinate] = float4(dot(Coefficient0, LuminanceWeights), dot(Coefficient1, LuminanceWeights), dot(Coefficient2, LuminanceWeights), 0);
		}

		float TranslucencyVolumeIntensityScale = 4;
		Lighting.R.V *= TranslucencyVolumeIntensityScale;
		Lighting.G.V *= TranslucencyVolumeIntensityScale;
		Lighting.B.V *= TranslucencyVolumeIntensityScale;

		FTwoBandSHVectorRGB NewHistoryLighting = Lighting;

	#if USE_TEMPORAL_REPROJECTION
		float3 HistoryUV = ComputeTranslucencyGIVolumeUV(ComputeCellWorldPosition(GridCoordinate, .5f), UnjitteredPrevWorldToClip);
		float HistoryAlpha = bNewLightingValid ? HistoryWeight : 1.0f;

		if (any(HistoryUV < 0) || any(HistoryUV >= 1))
		{
			HistoryAlpha = 0;
		}

		if (HistoryAlpha > 0)
		{
			float3 AmbientLightingVector = Texture3DSampleLevel(TranslucencyGIHistory0, TranslucencyGIHistorySampler, HistoryUV, 0).xyz;
			float3 DirectionalLightingVector = Texture3DSampleLevel(TranslucencyGIHistory1, TranslucencyGIHistorySampler, HistoryUV, 0).xyz;

			FTwoBandSHVectorRGB HistoryLighting;
			HistoryLighting.R.V.x = AmbientLightingVector.r;
			HistoryLighting.G.V.x = AmbientLightingVector.g;
			HistoryLighting.B.V.x = AmbientLightingVector.b;
			float3 NormalizedAmbientColor = AmbientLightingVector.rgb / ( Luminance( AmbientLightingVector.rgb ) + 0.00001f );

			HistoryLighting.R.V.yzw = DirectionalLightingVector.rgb * NormalizedAmbientColor.r;
			HistoryLighting.G.V.yzw = DirectionalLightingVector.rgb * NormalizedAmbientColor.g;
			HistoryLighting.B.V.yzw = DirectionalLightingVector.rgb * NormalizedAmbientColor.b;

			NewHistoryLighting.R.V = lerp(Lighting.R.V, HistoryLighting.R.V, HistoryAlpha);
			NewHistoryLighting.G.V = lerp(Lighting.G.V, HistoryLighting.G.V, HistoryAlpha);
			NewHistoryLighting.B.V = lerp(Lighting.B.V, HistoryLighting.B.V, HistoryAlpha);
		}
	#endif

		{
			RWTranslucencyGINewHistory0[GridCoordinate] = float4(NewHistoryLighting.R.V.x, NewHistoryLighting.G.V.x, NewHistoryLighting.B.V.x, 0);

			float3 LuminanceWeights = LuminanceFactors();
			float3 Coefficient0 = float3(NewHistoryLighting.R.V.y, NewHistoryLighting.G.V.y, NewHistoryLighting.B.V.y);
			float3 Coefficient1 = float3(NewHistoryLighting.R.V.z, NewHistoryLighting.G.V.z, NewHistoryLighting.B.V.z);
			float3 Coefficient2 = float3(NewHistoryLighting.R.V.w, NewHistoryLighting.G.V.w, NewHistoryLighting.B.V.w);
			RWTranslucencyGINewHistory1[GridCoordinate] = float4(dot(Coefficient0, LuminanceWeights), dot(Coefficient1, LuminanceWeights), dot(Coefficient2, LuminanceWeights), 0);
		}
	}
}
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////
// Froxel probe tracing.


#if defined(FroxelProbesUpdateSchedulerMainCS)

uint CameraCut;

// TODO use waveops when proven
groupshared uint s_FroxelClearCount;
groupshared uint s_FroxelClearGlobalGroupOffset;
groupshared uint s_FroxelLowResInitCount;
groupshared uint s_FroxelLowResInitGlobalGroupOffset;
groupshared uint s_FroxelReprojRefineCount;
groupshared uint s_FroxelReprojRefineGlobalGroupOffset;

RWByteAddressBuffer		FroxelClearCountBufferUAV;
RWBuffer<uint4>			FroxelClearListBufferUAV;
RWByteAddressBuffer		FroxelInitAndRefineCountBufferUAV;
RWBuffer<uint4>			FroxelLowResInitListBufferUAV;
RWBuffer<uint4>			FroxelRefineListBufferUAV;

uint4 ProbeSamplesToTrace[8];						// must match MAX_FRUSTUM_PROBES_REFINE_TRACEPERFRAME

[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void FroxelProbesUpdateSchedulerMainCS(
	uint3 DispatchThreadId	: SV_DispatchThreadID,
	uint3 GroupThreadId		: SV_GroupThreadID)
{
	uint3 FroxelProbeGridCoordinate = DispatchThreadId.xyz;

	const bool bGroupFirstThread = all(GroupThreadId==0);
	if(bGroupFirstThread)
	{
		s_FroxelClearCount  = 0;
		s_FroxelClearGlobalGroupOffset = 0;
		s_FroxelLowResInitCount  = 0;
		s_FroxelLowResInitGlobalGroupOffset = 0;
		s_FroxelReprojRefineCount = 0;
		s_FroxelReprojRefineGlobalGroupOffset = 0;
	}
	GroupMemoryBarrierWithGroupSync();

	// A probe is valid to trace if it is within the texture resolution, and the froxel can be scene on screen using conservtive HZB test.
	const bool bFroxelProbeVisible = IsFroxelProbeVisible(FroxelProbeGridCoordinate); 
	const bool bValidProbeCoord = all(FroxelProbeGridCoordinate < TranslucencyVolumeTracingFroxelProbesGridSize);

	bool bFroxelWasNotVisibleLastFrame = false;
	if(bValidProbeCoord)
	{ 
		uint3 FroxelGridCoordinate = FroxelProbeGridCoordinate * TranslucencyVolumeTracingFroxelProbesFroxelSize;
		float3 HistoryUV = ComputeTranslucencyGIVolumeUV(ComputeCellWorldPosition(FroxelGridCoordinate, .5f), UnjitteredPrevWorldToClip);
		bFroxelWasNotVisibleLastFrame = any(HistoryUV < 0) || any(HistoryUV >= 1);
	}

	const bool bNewFroxelThisFrame = bValidProbeCoord && (CameraCut || bFroxelWasNotVisibleLastFrame);

	// Each thread update the count of froxel that requires rough update for this group.
	uint FroxelUpdateLocalGroupOffset = 0;
	if (bValidProbeCoord)
	{
		if (!bFroxelProbeVisible)
		{
			InterlockedAdd(s_FroxelClearCount, 1, FroxelUpdateLocalGroupOffset);
		}
		else if (bNewFroxelThisFrame)
		{
			InterlockedAdd(s_FroxelLowResInitCount, 1, FroxelUpdateLocalGroupOffset);
		}
		else
		{
			InterlockedAdd(s_FroxelReprojRefineCount, 1, FroxelUpdateLocalGroupOffset);
		}
	}
	GroupMemoryBarrierWithGroupSync();

	// Now update the global count and recover the global write offset.
	if(bGroupFirstThread && bValidProbeCoord)
	{
		if (s_FroxelClearCount > 0)
		{
			FroxelClearCountBufferUAV.InterlockedAdd(0, s_FroxelClearCount, s_FroxelClearGlobalGroupOffset);
		}
		if (s_FroxelLowResInitCount > 0)
		{
			FroxelInitAndRefineCountBufferUAV.InterlockedAdd(0, s_FroxelLowResInitCount, s_FroxelLowResInitGlobalGroupOffset);
		}
		if (s_FroxelReprojRefineCount > 0)
		{
			FroxelInitAndRefineCountBufferUAV.InterlockedAdd(4, s_FroxelReprojRefineCount, s_FroxelReprojRefineGlobalGroupOffset);
		}
	}
	GroupMemoryBarrierWithGroupSync();
	
	// Write out the data of the froxel requiring a rough or reprojection update.
	if (bValidProbeCoord)
	{
		if (!bFroxelProbeVisible)
		{
			FroxelClearListBufferUAV[s_FroxelClearGlobalGroupOffset + FroxelUpdateLocalGroupOffset] = uint4(FroxelProbeGridCoordinate, 0);
		}
		else if (bNewFroxelThisFrame)
		{
			FroxelLowResInitListBufferUAV[s_FroxelLowResInitGlobalGroupOffset + FroxelUpdateLocalGroupOffset] = uint4(FroxelProbeGridCoordinate, 0);
		}
		else
		{
			const uint TraceCountPerProbePerFrame = TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;
			uint StateFrameIndex = View.StateFrameIndex * TraceCountPerProbePerFrame;
			for (int i = 0; i < TraceCountPerProbePerFrame; ++i)
			{
#if 0
				// Mark froxel probes octahedron coord to trace
				uint ProbeUpdateIndex = (StateFrameIndex + i) % (TranslucencyVolumeTracingFroxelProbesOctahedronResolution * TranslucencyVolumeTracingFroxelProbesOctahedronResolution);
				uint ProbeCoordY = ProbeUpdateIndex / TranslucencyVolumeTracingFroxelProbesOctahedronResolution;
				uint ProbeCoordX = ProbeUpdateIndex - ProbeCoordY * TranslucencyVolumeTracingFroxelProbesOctahedronResolution;
				uint2 SampleCoord = uint2(ProbeCoordX, ProbeCoordY);
#else
				uint2 SampleCoord = ProbeSamplesToTrace[i].xy;
#endif

				uint PackedProbeTexelCoord = (SampleCoord.x & 0xFF) | ((SampleCoord.y & 0xFF) << 8u); // This allows for probe resolution up to 256

				FroxelRefineListBufferUAV[(s_FroxelReprojRefineGlobalGroupOffset + FroxelUpdateLocalGroupOffset) * TraceCountPerProbePerFrame + i] = uint4(FroxelProbeGridCoordinate, PackedProbeTexelCoord);
			}
		}

	}
}
	
#endif // FroxelProbesUpdateSchedulerCS


// low res probes are likely 4x4 so to waste less threads in a wave we organise tracing as group of 4x4x4, probe pixels on XY and different probes on Z.
#define SOFTWARE_TRACE_INDIRECT_DISPATCH_THREADGROUP_X	64

#define UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X	4
#define UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y	4
#define UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z	4

#define REFINE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X	64

#if defined(FroxelProbesUpdateIndirectArgsSetupMainCS)

#if PERMUTATION_DEBUG_PRINT
#include "../ShaderPrint.ush"
#endif

ByteAddressBuffer		FroxelClearCountBuffer;
RWBuffer<uint>			FroxelClearDispatchIndirectBufferUAV;
ByteAddressBuffer		FroxelInitAndRefineCountBuffer;
RWBuffer<uint>			FroxelInitAndRefineTraceDispatchIndirectBufferUAV;
RWBuffer<uint>			FroxelLowResCopyDispatchIndirectBufferUAV;
RWBuffer<uint>			FroxelReprojRefineDispatchIndirectBufferUAV;

uint					bUsingRayTracing;
uint2					RayTracingThreadGroupSize;

[numthreads(THREADGROUP_SIZE, 1, 1)]
void FroxelProbesUpdateIndirectArgsSetupMainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	// Assuming we never go above 65k froxel update for now

	const uint FroxelClearCount = FroxelClearCountBuffer.Load(0);
	const uint2 FroxelInitAndRefineCount = FroxelInitAndRefineCountBuffer.Load2(0);
	const uint FroxelInitCount = FroxelInitAndRefineCount.x;
	const uint FroxelReprojectRefineCount = FroxelInitAndRefineCount.y;

	if (DispatchThreadId.x == 0)
	{
		// Indirect dispatch when clearing non visible probes to black
		FroxelClearDispatchIndirectBufferUAV[0] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,	UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelClearDispatchIndirectBufferUAV[1] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,	UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y);
		FroxelClearDispatchIndirectBufferUAV[2] = DivideAndRoundUp(FroxelClearCount,											UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z);
	}
	else if (DispatchThreadId.x == 1)
	{
		// Indirect dispatch when copying the low res traced data onto the froxel probes
		FroxelLowResCopyDispatchIndirectBufferUAV[0] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,	UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelLowResCopyDispatchIndirectBufferUAV[1] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,	UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y);
		FroxelLowResCopyDispatchIndirectBufferUAV[2] = DivideAndRoundUp(FroxelInitCount,											UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z);
	}
	else if (DispatchThreadId.x == 2)
	{
		// Indirect dispatch when reprojecting previous frame data into froxel probes
		FroxelReprojRefineDispatchIndirectBufferUAV[0] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,	UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X);
		FroxelReprojRefineDispatchIndirectBufferUAV[1] = DivideAndRoundUp(TranslucencyVolumeTracingFroxelProbesOctahedronResolution,	UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y);
		FroxelReprojRefineDispatchIndirectBufferUAV[2] = DivideAndRoundUp(FroxelReprojectRefineCount,									UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z);
	}
	else if (DispatchThreadId.x == 3)
	{
		const uint NumRays = FroxelInitCount * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution
			+ FroxelReprojectRefineCount * TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;

		uint NumGroups = DivideAndRoundUp(NumRays, SOFTWARE_TRACE_INDIRECT_DISPATCH_THREADGROUP_X);
		if (bUsingRayTracing > 0)
		{
			NumGroups = (NumRays + RayTracingThreadGroupSize.x - 1) / RayTracingThreadGroupSize.x; // DivideAndRoundUp
		}

		int3 IndirectArgs = GetRayTracingThreadCountWrapped(NumGroups, RADIANCE_CACHE_TRACE_TILE_SIZE_1D);
		WriteDispatchIndirectArgs(FroxelInitAndRefineTraceDispatchIndirectBufferUAV, 0, IndirectArgs);
	}

#if PERMUTATION_DEBUG_PRINT
	if (DispatchThreadId.x == 0)
	{
		FShaderPrintContext Context = InitShaderPrintContext(true, uint2(500, 500));

		const uint LowResTraceCount = FroxelInitCount * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution;
		const uint RefineTraceCount = FroxelReprojectRefineCount;
		const uint TotalTraceCount = LowResTraceCount + RefineTraceCount;

		Print(Context, TEXT("** Froxel Probes Scheduled Work **"));
		Newline(Context);
		Newline(Context);
		Print(Context, TEXT(" - LowRes reset probe count   = "));
		Print(Context, FroxelInitCount);
		Newline(Context);
		Print(Context, TEXT(" - Reprojected  probe count   = "));
		Print(Context, FroxelReprojectRefineCount);
		Newline(Context);
		Print(Context, TEXT(" - Cleared  probe count       = "));
		Print(Context, FroxelClearCount);
		Newline(Context);
		Newline(Context);
		Print(Context, TEXT(" - LowRes  probe trace count  = "));
		Print(Context, LowResTraceCount);
		Print(Context, TEXT("  (LowRes probe resolution = "));
		Print(Context, TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution, GetDefaultFontColor(), 2);
		Print(Context, TEXT(")"));
		Newline(Context);
		Print(Context, TEXT(" - Refined probe trace count  = "));
		Print(Context, RefineTraceCount);
	}
#endif
}
	
#endif // FroxelProbesUpdateIndirectArgsSetupMainCS




#if defined(UpdateFroxelProbesMainCS)
 
#if PERMUTATION_PROBE_FILL_MODE == 0	// Reproject last frame 
Texture3D<float4>   VolumeFroxelProbeRadianceHitDistanceHistory;
Texture3D<float3>   VolumeFroxelLowResProbeRadiance;
Texture3D<float>    VolumeFroxelLowResProbeHitDistance;
#elif PERMUTATION_PROBE_FILL_MODE == 1	// Copy low res probe data 
Texture3D<float3>   VolumeFroxelLowResProbeRadiance;
Texture3D<float>    VolumeFroxelLowResProbeHitDistance;
#elif PERMUTATION_PROBE_FILL_MODE == 2	// Fill to black 
#endif

RWTexture3D<float4> RWVolumeFroxelProbeRadianceHitDistance;

ByteAddressBuffer	FroxelClearCountBuffer;
ByteAddressBuffer	FroxelInitAndRefineCountBuffer;
Buffer<uint4>		FroxelUpdateListBuffer;

uint4 ProbeSamplesToTrace[8];						// must match MAX_FRUSTUM_PROBES_REFINE_TRACEPERFRAME

float2 ViewFroxelProbesHistoryPreExposureAndInv;

[numthreads(UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_X, UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Y, UPDATE_FROXEL_INDIRECT_DISPATCH_THREADGROUP_Z)]
void UpdateFroxelProbesMainCS(
	uint3 DispatchThreadIdIn : SV_DispatchThreadID)
{
	uint FroxelUpdateListIndex = DispatchThreadIdIn.z;

#if PERMUTATION_PROBE_FILL_MODE==2
	uint FroxelToProcessCount = FroxelClearCountBuffer.Load(0);
#else
	const uint2 FroxelInitAndRefineCount = FroxelInitAndRefineCountBuffer.Load2(0);
	const uint FroxelInitCount = FroxelInitAndRefineCount.x;
	const uint FroxelTexelReprojectRefineCount = FroxelInitAndRefineCount.y;
	uint FroxelToProcessCount = FroxelInitCount;
	if (PERMUTATION_PROBE_FILL_MODE == 0)
	{
		FroxelUpdateListIndex = FroxelUpdateListIndex * TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;
		FroxelToProcessCount = FroxelTexelReprojectRefineCount;
	}
#endif

	if (DispatchThreadIdIn.z >= FroxelToProcessCount)
	{
		return; // Not a froxel to regenerate
	}

	uint3 FroxelProbeGridCoordinate = FroxelUpdateListBuffer[FroxelUpdateListIndex].xyz;
	uint2 FroxelProbeTraceTexelCoord = DispatchThreadIdIn.xy;

	// on the Z axis
	uint  FroxelProbesOctahedronResolution = TranslucencyVolumeTracingFroxelProbesOctahedronResolution;
//	uint3 DispatchThreadId = uint3(DispatchThreadIdIn.xy, 0) + FroxelProbeGridCoordinate * uint3(FroxelProbesOctahedronResolution.xx, 1);

//	uint3 FroxelProbeGridCoordinate = uint3(DispatchThreadId.xy / FroxelProbesOctahedronResolution, DispatchThreadId.z);
//	uint2 FroxelProbeTraceTexelCoord = DispatchThreadId.xy - FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution;

	float3 TraceRadiance = 0;
	float TraceHitDistance = MaxHalfFloat;

	if (all(FroxelProbeGridCoordinate < TranslucencyVolumeTracingFroxelProbesGridSize) && all(FroxelProbeTraceTexelCoord < FroxelProbesOctahedronResolution))
	{

#if PERMUTATION_PROBE_FILL_MODE == 0	// Reproject last frame

		const float3 FroxelProbeOffset = 0.0; // must be 0, not 0.5, in order to not perpetually shit data in UV space. TODO: review all alignement. => put probes at vertices of the froxels?
		float3 HistoryUV = ComputeTranslucencyGIVolumeUV(ComputeCellWorldPosition(FroxelProbeGridCoordinate * TranslucencyVolumeTracingFroxelProbesFroxelSize, FroxelProbeOffset), UnjitteredPrevWorldToClip);

		// This correction is required because the rounded up froxel probes space can be larger than the froxel count
		HistoryUV *= float3(TranslucencyGIGridSize) / float3(TranslucencyVolumeTracingFroxelProbesGridSize * TranslucencyVolumeTracingFroxelProbesFroxelSize);

		float2 ProbeUV;
		float ConeHalfAngle;
		const float2 ProbeTexelCenter = 0.5; // No jittering so not using GetProbeTexelCenter for stability
		GetFroxelProbeTracingUV(FroxelProbeTraceTexelCoord, ProbeTexelCenter, FroxelProbesOctahedronResolution, ProbeUV, ConeHalfAngle);

		// the coord of the probe to reproject
		float3 FroxelProbeGridTexelCoordFloat = clamp(HistoryUV * float3(TranslucencyVolumeTracingFroxelProbesGridSize), 0.0.xxx, float3(TranslucencyVolumeTracingFroxelProbesGridSize-1));
		uint3 FroxelProbeGridTexelCoord = FroxelProbeGridTexelCoordFloat;

	#if 0
		float4 ProbeRadianceHitDistance = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(FroxelProbeGridTexelCoord.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord.z)];
		TraceRadiance = ProbeRadianceHitDistance.rgb;
		TraceHitDistance = ProbeRadianceHitDistance.a;
	#else
		float3 LerpUVs = saturate(FroxelProbeGridTexelCoordFloat - float3(FroxelProbeGridTexelCoord));

		uint3 FroxelProbeGridTexelCoord0 = FroxelProbeGridTexelCoord;
		uint3 FroxelProbeGridTexelCoord1 = min(FroxelProbeGridTexelCoord0 + 1, TranslucencyVolumeTracingFroxelProbesGridSize - 1);

		float4 LightHitDist000 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float4 LightHitDist001 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float4 LightHitDist010 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float4 LightHitDist011 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord0.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float4 LightHitDist100 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float4 LightHitDist101 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord0.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];
		float4 LightHitDist110 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord0.z)];
		float4 LightHitDist111 = VolumeFroxelProbeRadianceHitDistanceHistory[uint3(uint2(FroxelProbeGridTexelCoord1.x, FroxelProbeGridTexelCoord1.y) * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridTexelCoord1.z)];

		float4 LightHitDistX0 = lerp(lerp(LightHitDist000, LightHitDist001, LerpUVs.zzzz), lerp(LightHitDist010, LightHitDist011, LerpUVs.zzzz), LerpUVs.yyyy);
		float4 LightHitDistX1 = lerp(lerp(LightHitDist100, LightHitDist101, LerpUVs.zzzz), lerp(LightHitDist110, LightHitDist111, LerpUVs.zzzz), LerpUVs.yyyy);
		float4 ProbeRadianceHitDistance = lerp(LightHitDistX0, LightHitDistX1, LerpUVs.xxxx);

		TraceRadiance = ProbeRadianceHitDistance.rgb;
		TraceHitDistance = ProbeRadianceHitDistance.a;
	#endif

		// Now override pixels that should be refined this frame.
		// This is done as a gather operation to not have to dispatch another compute shader to scatter the data after.
		for (int i = 0; i < TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame; ++i)
		{
			if (all(ProbeSamplesToTrace[i].xy == FroxelProbeTraceTexelCoord))
			{
				uint3 SourceCoord = uint3(FroxelProbeGridCoordinate.xy * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution + uint2(i, 0), FroxelProbeGridCoordinate.z);
				TraceRadiance		= VolumeFroxelLowResProbeRadiance[SourceCoord];
				TraceHitDistance	= VolumeFroxelLowResProbeHitDistance[SourceCoord];
			}
		}

		// Adapt to current exposure
//		TraceRadiance *= ViewFroxelProbesHistoryPreExposureAndInv.y * View.PreExposure;

	#if FROXEL_PROBE_DEBUG_COLOR
		TraceRadiance *= float3(0.96, 0.996, 0.0);
	#endif

		uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
		RWVolumeFroxelProbeRadianceHitDistance[WriteCoord] = float4(TraceRadiance, min(TraceHitDistance, MaxHalfFloat));

#elif PERMUTATION_PROBE_FILL_MODE == 1	// Copy low res probe data

		uint3 SourceCoord = uint3(FroxelProbeGridCoordinate.xy * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution, FroxelProbeGridCoordinate.z);
		SourceCoord.xy += float2(FroxelProbeTraceTexelCoord) * float(TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution) / float(TranslucencyVolumeTracingFroxelProbesOctahedronResolution);

		TraceRadiance = VolumeFroxelLowResProbeRadiance[SourceCoord];
		TraceHitDistance = VolumeFroxelLowResProbeHitDistance[SourceCoord];

	#if FROXEL_PROBE_DEBUG_COLOR
		TraceRadiance *= float3(1, 1, 0.0);
	#endif

		uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
		RWVolumeFroxelProbeRadianceHitDistance[WriteCoord] = float4(TraceRadiance, TraceHitDistance);
		
#elif PERMUTATION_PROBE_FILL_MODE == 2	// Clear froxel probe

		TraceRadiance = 0.0.xxx;
		TraceHitDistance = MaxHalfFloat;

	#if FROXEL_PROBE_DEBUG_COLOR
		TraceRadiance = float3(0, 0, 1);
	#endif

		uint3 WriteCoord = uint3(FroxelProbeGridCoordinate.xy * FroxelProbesOctahedronResolution + FroxelProbeTraceTexelCoord, FroxelProbeGridCoordinate.z);
		RWVolumeFroxelProbeRadianceHitDistance[WriteCoord] = float4(TraceRadiance, TraceHitDistance);

#endif
	}
}

#endif






#if LUMEN_HARDWARE_RAYTRACING

#include "/Engine/Shared/RayTracingTypes.h"
#include "LumenHardwareRayTracingCommon.ush"

#ifndef DIM_LIGHTING_MODE
#define DIM_LIGHTING_MODE LIGHTING_FROM_SURFACE_CACHE
#endif

// From FLumenHardwareRayTracingShaderBase::SharedParameters
RaytracingAccelerationStructure TLAS;
uint MaxTraversalIterations;
uint MeshSectionVisibilityTest;

#endif // LUMEN_HARDWARE_RAYTRACING

#if LUMEN_HARDWARE_INLINE_RAYTRACING

// From FLumenHardwareRayTracingShaderBase::SharedParameters
StructuredBuffer<FHitGroupRootConstants> HitGroupData;
StructuredBuffer<FRayTracingSceneMetadataRecord> RayTracingSceneMetadata;

FLumenTraceRayInlineCallback InitLumenTraceRayInlineCallback()
{
	FLumenTraceRayInlineCallback Callback;
	Callback.HitGroupData = HitGroupData;
	Callback.bShadowRay = false;
	return Callback;
}

#endif // LUMEN_HARDWARE_INLINE_RAYTRACING

#if defined(TranslucencyVolumeFroxelProbesSoftwareRayTracingCS) || defined(TranslucencyVolumeFroxelProbesHardwareRayTracingRGS) || defined(TranslucencyVolumeFroxelProbesHardwareRayTracingCS)

struct FTranslucencyVolumeTraceRayResult
{
	float3 Radiance;
	float  HitDistance;
};

FTranslucencyVolumeTraceRayResult TranslucencyVolumeTraceRayCommon(uint3 FroxelProbeGridCoordinate, float3 WorldPosition, float3 TranslatedWorldPosition, float3 WorldConeDirection, float ConeHalfAngle)
{
	float TraceHitDistance = MaxTraceDistance;

#if LUMEN_HARDWARE_RAYTRACING

	FRayDesc Ray;
	Ray.Origin = WorldPosition + DFHackToFloat(PrimaryView.PreViewTranslation); // LUMEN_LWC_TODO
	Ray.Direction = WorldConeDirection;
	Ray.TMin = 0;
	Ray.TMax = MaxTraceDistance;

	FRayCone RayCone = (FRayCone)0;
	RayCone = PropagateRayCone(RayCone, ConeHalfAngle, 0.0);

	const uint LinearCoord = FroxelProbeGridCoordinate.y * TranslucencyVolumeTracingFroxelProbesGridSize.x + FroxelProbeGridCoordinate.x;
	FRayTracedLightingContext Context = CreateRayTracedLightingContext(
		RayCone,
		FroxelProbeGridCoordinate.xy,
		LinearCoord,
		/*CullingMode*/ RAY_FLAG_NONE, // Disable culling in order to minimize leaking when rays start inside walls
		MaxTraversalIterations,
		MeshSectionVisibilityTest != 0);

	FRayTracedLightingResult TraceLightingResult;
	TraceLightingResult.Radiance = 0;
	TraceLightingResult.TraceHitDistance = MaxTraceDistance;
#if DIM_LIGHTING_MODE == LIGHTING_FROM_SURFACE_CACHE
#if LUMEN_HARDWARE_INLINE_RAYTRACING
	Context.HitGroupData = HitGroupData;
	Context.RayTracingSceneMetadata = RayTracingSceneMetadata;
#endif
	TraceLightingResult = TraceAndCalculateRayTracedLightingFromSurfaceCache(TLAS, Ray, Context);
#else
	TraceLightingResult = TraceAndCalculateRayTracedLighting(TLAS, Ray, Context, DIM_LIGHTING_MODE, false);
#endif

	FConeTraceResult TraceResult = (FConeTraceResult)0;
	TraceResult.OpaqueHitDistance = TraceLightingResult.TraceHitDistance;
	TraceResult.Lighting = TraceLightingResult.Radiance;
	if (TraceLightingResult.bIsHit)
	{
		TraceHitDistance = TraceResult.OpaqueHitDistance;
		TraceResult.Transparency = 0.0;
	}
	else
	{
		TraceResult.Transparency = 1.0;
		ApplySkylightToTraceResult(WorldConeDirection, TraceResult);
	}


#else // LUMEN_HARDWARE_RAYTRACING

	float VoxelTraceStartDistance = CalculateVoxelTraceStartDistance(0, MaxTraceDistance, MaxMeshSDFTraceDistance, false) * VoxelTraceStartDistanceScale;

	FConeTraceInput TraceInput;
	TraceInput.Setup(WorldPosition, TranslatedWorldPosition, WorldConeDirection, ConeHalfAngle, 0, 0, MaxTraceDistance, StepFactor);
	TraceInput.VoxelTraceStartDistance = VoxelTraceStartDistance;
	TraceInput.SDFStepFactor = 1;

	FConeTraceResult TraceResult = (FConeTraceResult)0;
	TraceResult.Transparency = 1;

	RayTraceGlobalDistanceField(TraceInput, TraceResult);

	if (TraceResult.Transparency <= .5f)
	{
		TraceHitDistance = TraceResult.OpaqueHitDistance;
	}

	ApplySkylightToTraceResult(WorldConeDirection, TraceResult);

#endif // LUMEN_HARDWARE_RAYTRACING

	FTranslucencyVolumeTraceRayResult Result;
	Result.Radiance		= TraceResult.Lighting;
	Result.HitDistance	= TraceHitDistance;
	return Result;
}



float4 TranslucencyVolumeFroxelProbesTracingCommon(
	uint3 ProbeGridCoordinate,
	uint2 ProbeTraceTexelCoord,
	uint  ProbesOctahedronResolution)
{
	uint3 FroxelGridCoordinate = ProbeGridCoordinate * TranslucencyVolumeTracingFroxelProbesFroxelSize;

	if (all(ProbeGridCoordinate < TranslucencyVolumeTracingFroxelProbesGridSize) && all(ProbeTraceTexelCoord < ProbesOctahedronResolution))
	{
		FTranslucencyVolumeTraceRayResult TraceResult;
		TraceResult.Radiance = 0;
		TraceResult.HitDistance = MaxTraceDistance;

		if (IsFroxelProbeVisible(ProbeGridCoordinate))
		{
			float3 LocalFrameJitterOffset = 0.5f; // Do not Jitter for now
			ApplyDepthconstraintsToOffset(FroxelGridCoordinate + TranslucencyVolumeTracingFroxelProbesFroxelSize / 2, LocalFrameJitterOffset);

			float3 WorldPosition = ComputeCellWorldPosition(FroxelGridCoordinate, LocalFrameJitterOffset);
			float3 TranslatedWorldPosition = ComputeCellTranslatedWorldPosition(FroxelGridCoordinate, LocalFrameJitterOffset);

			float2 ProbeUV;
			float ConeHalfAngle;
			const float2 ProbeTexelCenter = 0.5; // No jittering so not using GetProbeTexelCenter for stability
			GetFroxelProbeTracingUV(ProbeTraceTexelCoord, ProbeTexelCenter, ProbesOctahedronResolution, ProbeUV, ConeHalfAngle);

			float3 WorldConeDirection = EquiAreaSphericalMapping(ProbeUV);

			TraceResult = TranslucencyVolumeTraceRayCommon(ProbeGridCoordinate, WorldPosition, TranslatedWorldPosition, WorldConeDirection, ConeHalfAngle);

			//	TraceResult.Radiance *= View.PreExposure;
			float MaxLighting = max3(TraceResult.Radiance.x, TraceResult.Radiance.y, TraceResult.Radiance.z);
			if (MaxLighting > MaxRayIntensity)
			{
				TraceResult.Radiance *= MaxRayIntensity / MaxLighting;
			}
		}

		return float4(TraceResult.Radiance, min(TraceResult.HitDistance, MaxHalfFloat));
	}
	return float4(0, 0, 0, MaxHalfFloat);
}



#if defined(TranslucencyVolumeFroxelProbesSoftwareRayTracingCS)

ByteAddressBuffer		FroxelInitAndRefineCountBuffer;
Buffer<uint4>			FroxelLowResInitListBuffer;
Buffer<uint4>			FroxelRefineListBufferSRV;

HLSL_STATIC_ASSERT(SOFTWARE_TRACE_INDIRECT_DISPATCH_THREADGROUP_X == THREADGROUP_SIZE, "");
[numthreads(THREADGROUP_SIZE, 1, 1)]
void TranslucencyVolumeFroxelProbesSoftwareRayTracingCS(
	uint3 GroupId : SV_GroupID,
	uint GroupIndex : SV_GroupIndex,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	const uint GroupLinearIndex = GetUnWrappedRayTracingDispatchThreadId(GroupId, RADIANCE_CACHE_TRACE_TILE_SIZE_1D);
	const uint ThreadIndex = GroupLinearIndex * THREADGROUP_SIZE + GroupIndex;

	const uint2 FroxelInitAndRefineCount = FroxelInitAndRefineCountBuffer.Load2(0);
	const uint FroxelInitCount = FroxelInitAndRefineCount.x;
	const uint FroxelTexelReprojectRefineCount = FroxelInitAndRefineCount.y;

	if (ThreadIndex < FroxelInitCount * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution)
	{
		uint ProbeIndex = ThreadIndex / (TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);
		uint ProbeLocalThreadIndex = ThreadIndex % (TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);
		uint2 ProbeTraceTexelCoord = uint2(ProbeLocalThreadIndex % TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution, ProbeLocalThreadIndex / TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);

		float3 ProbeGridCoordinate = FroxelLowResInitListBuffer[ProbeIndex].xyz;

		float4 RadHitDist = TranslucencyVolumeFroxelProbesTracingCommon(
			ProbeGridCoordinate,
			ProbeTraceTexelCoord,
			TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);

		uint3 WriteCoord = uint3(ProbeGridCoordinate.xy * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution + ProbeTraceTexelCoord, ProbeGridCoordinate.z);
		RWVolumeTraceRadiance[WriteCoord] = RadHitDist.rgb;
		RWVolumeTraceHitDistance[WriteCoord] = RadHitDist.a;
	}
	else
	{
		// Remove all the rays for probe tracing
		const uint LocalThreadIndex = ThreadIndex - FroxelInitCount * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution;

		if (LocalThreadIndex < FroxelTexelReprojectRefineCount * TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame)
		{
			//uint ProbeIndex = LocalThreadIndex / TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;
			uint ProbeThreadIndex = LocalThreadIndex % TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;

			uint4 RayTracedData = FroxelRefineListBufferSRV[LocalThreadIndex];
			uint3 ProbeGridCoordinate = RayTracedData.xyz;
			uint PackedProbeTexelCoord = RayTracedData.w;
			uint ProbeCoordX = PackedProbeTexelCoord & 0xFF;
			uint ProbeCoordY = (PackedProbeTexelCoord >> 8) & 0xFF;
			uint2 ProbeTraceTexelCoord = uint2(ProbeCoordX, ProbeCoordY);


			// Trace for refining high resolution probe
			float4 RadHitDist = TranslucencyVolumeFroxelProbesTracingCommon(
				ProbeGridCoordinate,
				ProbeTraceTexelCoord,
				TranslucencyVolumeTracingFroxelProbesOctahedronResolution);


			// Store in first row of low resolution probe
			uint3 WriteCoord = uint3(ProbeGridCoordinate.xy * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution + uint2(ProbeThreadIndex, 0), ProbeGridCoordinate.z);
			RWVolumeTraceRadiance[WriteCoord] = RadHitDist.rgb;
			RWVolumeTraceHitDistance[WriteCoord] = RadHitDist.a;
		}

	}
}

#endif


#if defined(TranslucencyVolumeFroxelProbesHardwareRayTracingRGS) || defined(TranslucencyVolumeFroxelProbesHardwareRayTracingCS)

ByteAddressBuffer		FroxelInitAndRefineCountBuffer;
Buffer<uint4>			FroxelLowResInitListBuffer;
Buffer<uint4>			FroxelRefineListBufferSRV;

#if LUMEN_HARDWARE_INLINE_RAYTRACING

[numthreads(INLINE_RAY_TRACING_THREAD_GROUP_SIZE_X, INLINE_RAY_TRACING_THREAD_GROUP_SIZE_Y, 1)]
void TranslucencyVolumeFroxelProbesHardwareRayTracingCS(
	uint3 GroupId : SV_GroupID,
	uint GroupIndex : SV_GroupIndex)
{
	uint GroupLinearIndex = GetUnWrappedRayTracingDispatchThreadId(GroupId, RADIANCE_CACHE_TRACE_TILE_SIZE_1D);
	uint ThreadIndex = GroupLinearIndex * INLINE_RAY_TRACING_THREAD_GROUP_SIZE_X + GroupIndex;

#else // LUMEN_HARDWARE_INLINE_RAYTRACING}

RAY_TRACING_ENTRY_RAYGEN(TranslucencyVolumeFroxelProbesHardwareRayTracingRGS)
{
	uint ThreadIndex = GetUnWrappedRayTracingDispatchThreadId(DispatchRaysIndex(), RADIANCE_CACHE_TRACE_TILE_SIZE_1D);

#endif // LUMEN_HARDWARE_INLINE_RAYTRACING

	const uint2 FroxelInitAndRefineCount = FroxelInitAndRefineCountBuffer.Load2(0);
	const uint FroxelInitCount = FroxelInitAndRefineCount.x;
	const uint FroxelTexelReprojectRefineCount = FroxelInitAndRefineCount.y; 

	if (ThreadIndex < FroxelInitCount * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution)
	{
		uint ProbeIndex = ThreadIndex / (TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);
		uint ProbeLocalThreadIndex = ThreadIndex % (TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);
		uint2 ProbeTraceTexelCoord = uint2(ProbeLocalThreadIndex % TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution, ProbeLocalThreadIndex / TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);

		float3 ProbeGridCoordinate = FroxelLowResInitListBuffer[ProbeIndex].xyz;

		float4 RadHitDist = TranslucencyVolumeFroxelProbesTracingCommon(
			ProbeGridCoordinate,
			ProbeTraceTexelCoord,
			TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution);

		uint3 WriteCoord = uint3(ProbeGridCoordinate.xy * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution + ProbeTraceTexelCoord, ProbeGridCoordinate.z);
		RWVolumeTraceRadiance[WriteCoord] = RadHitDist.rgb;
		RWVolumeTraceHitDistance[WriteCoord] = RadHitDist.a;
	}
	else
	{
		// Remove all the rays for probe tracing
		const uint LocalThreadIndex = ThreadIndex - FroxelInitCount * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution;

		if (LocalThreadIndex < FroxelTexelReprojectRefineCount * TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame)
		{
			//uint ProbeIndex = LocalThreadIndex / TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;
			uint ProbeThreadIndex = LocalThreadIndex % TranslucencyVolumeTracingFroxelProbeRefineTraceCountPerFrame;

			uint4 RayTracedData = FroxelRefineListBufferSRV[LocalThreadIndex];
			uint3 ProbeGridCoordinate = RayTracedData.xyz;
			uint PackedProbeTexelCoord = RayTracedData.w;
			uint ProbeCoordX = PackedProbeTexelCoord & 0xFF;
			uint ProbeCoordY = (PackedProbeTexelCoord >> 8) & 0xFF;
			uint2 ProbeTraceTexelCoord = uint2(ProbeCoordX, ProbeCoordY);


			// Trace for refining high resolution probe
			float4 RadHitDist = TranslucencyVolumeFroxelProbesTracingCommon(
				ProbeGridCoordinate,
				ProbeTraceTexelCoord,
				TranslucencyVolumeTracingFroxelProbesOctahedronResolution);


			// Store in first row of low resolution probe
			uint3 WriteCoord = uint3(ProbeGridCoordinate.xy * TranslucencyVolumeTracingFroxelLowResProbesOctahedronResolution + uint2(ProbeThreadIndex, 0), ProbeGridCoordinate.z);
			RWVolumeTraceRadiance[WriteCoord] = RadHitDist.rgb;
			RWVolumeTraceHitDistance[WriteCoord] = RadHitDist.a;
		}

	}
}

#endif // TranslucencyVolumeFroxelProbesHardwareRayTracingRGS TranslucencyVolumeFroxelProbesHardwareRayTracingCS


#endif // All probe tracing shaders