// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "../RayTracing/RayTracingCommon.ush"
#include "../SceneTexturesCommon.ush"
#include "ManyLights.ush"
#include "ManyLightsRayTracing.ush"
#include "../Lumen/LumenHardwareRayTracingPayloadCommon.ush"
#if HAIR_VOXEL_TRACES
	#include "../HairStrands/HairStrandsRaytracing.ush"
#endif

float RayTracingBias;
float RayTracingNormalBias;
uint2 SampleViewSize;
uint DebugMode;
uint MaxTraversalIterations;
RaytracingAccelerationStructure TLAS;

#if LUMEN_HARDWARE_INLINE_RAYTRACING
	struct FHitGroupRootConstants
	{
		uint BaseInstanceIndex;
		uint UserData;
	};

	StructuredBuffer<FHitGroupRootConstants> HitGroupData;
	StructuredBuffer<FRayTracingSceneMetadataRecord> RayTracingSceneMetadata;
#endif

RWTexture2D<uint> RWLightSamples;

Texture2D<float> LightSampleRayDistance;
StructuredBuffer<uint> CompactedTraceTexelData;
StructuredBuffer<uint> CompactedTraceTexelAllocator;
Texture2D<float> DownsampledSceneDepth;
Texture2D<UNORM float3> DownsampledSceneWorldNormal;

RAY_TRACING_ENTRY_RAYGEN_OR_INLINE(HardwareRayTraceLightSamples)
{
	uint ThreadIndex = DispatchThreadIndex.x;
	uint GroupIndex = DispatchThreadIndex.y;
	uint TraceTexelIndex = GroupIndex * 64 + ThreadIndex;

	if (TraceTexelIndex < CompactedTraceTexelAllocator[0])
	{
		uint2 SampleCoord = UnpackTraceTexel(CompactedTraceTexelData[TraceTexelIndex]);
		uint2 ScreenCoord = SampleCoordToScreenCoord(SampleCoord);
		uint2 DownsampledScreenCoord = SampleCoordToDownsampledScreenCoord(SampleCoord);

#if DEBUG_MODE
		FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.55, 0.45));
		int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
		bool bDebug = all(DebugScreenCoord / DOWNSAMPLE_FACTOR == DownsampledScreenCoord);
#endif

		float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
		float SceneDepth = DownsampledSceneDepth[DownsampledScreenCoord];
		float3 SceneWorldNormal = normalize(DecodeNormal(DownsampledSceneWorldNormal[DownsampledScreenCoord]));
		float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, SceneDepth);

		FLightSample LightSample = UnpackLightSample(RWLightSamples[SampleCoord]);
		FLightSampleTrace LightSampleTrace = GetLightSampleTrace(TranslatedWorldPosition, LightSample.LocalLightIndex, SampleCoord);
		const float LightSampleRayMinT = LightSampleRayDistance[SampleCoord];

		FRayDesc Ray = (FRayDesc)0;
		Ray.Origin = TranslatedWorldPosition;
		Ray.Direction = LightSampleTrace.Direction;
		Ray.TMin = max(LightSampleRayMinT, RayTracingBias);
		Ray.TMax = LightSampleTrace.Distance;

		ApplyPositionBias(Ray.Origin, Ray.Direction, SceneWorldNormal, RayTracingNormalBias);

		uint RayFlags = RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH;
		uint RayMask = RAY_TRACING_MASK_OPAQUE;

		FLumenMinimalPayload Payload = (FLumenMinimalPayload)0;

		// #ml_todo: Share it with LumenHardwareRayTracingCommon.ush
		#if LUMEN_HARDWARE_INLINE_RAYTRACING
		{
			FTraceRayInlineContext TraceRayInlineContext = CreateTraceRayInlineContext();
			TraceRayInlineContext.MaxIterations = MaxTraversalIterations;

			FTraceRayInlineResult TraceResult = TraceRayInline(TLAS, RayFlags, RayMask, Ray.GetNativeDesc(), TraceRayInlineContext);

			if (TraceResult.IsHit())
			{
				Payload.HitT = TraceResult.HitT;

				// Our SBTs always have 2 slots per material. Therefore InstanceContributionToHitGroupIndex has a RAY_TRACING_NUM_SHADER_SLOTS multiplier.
				// But because we only encode 1 material into LumenHardwareRayTracingHitDataBuffer we want to get actual material index.
				uint InstanceContributionIndex = TraceResult.InstanceContributionToHitGroupIndex / RAY_TRACING_NUM_SHADER_SLOTS;
				uint HitGroupIndex = TraceResult.GeometryIndex + InstanceContributionIndex;

				FHitGroupRootConstants HitData = HitGroupData[HitGroupIndex];

				const int Primitive = TraceResult.InstanceID;
				const int PrimitiveInstanceIndex = TraceResult.InstanceIndex - HitData.BaseInstanceIndex;
				const uint GPUSceneInstanceIndex = GetGPUSceneInstanceIndex(Primitive, PrimitiveInstanceIndex);
				Payload.SetGPUSceneInstanceIndex(GPUSceneInstanceIndex);

				uint MaterialShaderIndex = HitData.UserData & 0x3FFFFFFF;
				Payload.SetMaterialShaderIndex(MaterialShaderIndex);

				uint bIsTranslucent = (HitData.UserData >> 31) & 0x1;
				Payload.SetIsTranslucent(bIsTranslucent);

				uint bIsTwoSided = (HitData.UserData >> 30) & 0x1;
				Payload.SetIsTwoSided(bIsTwoSided);
			}
			else
			{
				Payload.SetMiss();
			}
		}
		#else
		{
			TraceRay(TLAS, RayFlags, RayMask, /*ShaderSlotIndex*/ 0, RAY_TRACING_NUM_SHADER_SLOTS, 0, Ray.GetNativeDesc(), Payload);
		}
		#endif

		#if HAIR_VOXEL_TRACES
		{
			// #ml_todo: replace with spatiotemporal blue noise
			RandomSequence RandSequence;
			RandomSequence_Initialize(RandSequence, SampleCoord, 0, ManyLightsStateFrameIndex, 1);
			Payload.HitT = TraverseHair(ScreenCoord, RandSequence, Ray.Origin, Ray.Direction, Payload.HitT, VirtualVoxel.Raytracing_ShadowOcclusionThreshold);
		}
		#endif

		#if DEBUG_MODE
		if (bDebug && DebugMode == DEBUG_MODE_VISUALIZE_TRACING)
		{
			const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LightSample.LocalLightIndex);
			const FLightSceneData LightSceneData = GetLightSceneData(LocalLightData.LightSceneId);
			const FDeferredLightData LightData = ConvertToDeferredLight(LightSceneData);

			float3 RayStart = Ray.Origin + Ray.Direction * Ray.TMin;
			float3 RayEnd = Ray.Origin + Ray.Direction * (Payload.IsHit() ? Payload.HitT : Ray.TMax);
			float4 RayColor = float4(LightData.Color.xyz / Luminance(LightData.Color.xyz), 1.0f);

			AddLineTWS(Context, RayStart, RayEnd, RayColor);	
		}
		#endif

		if (Payload.IsHit())
		{
			LightSample.bCompleted = true;
			LightSample.bVisible = false;
			RWLightSamples[SampleCoord] = PackLightSample(LightSample);
		}
	}
}