// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Replication/Editor/View/IReplicationStreamEditor.h"
#include "Replication/Editor/View/PredefinedReplicationColumns.h"
#include "Replication/ReplicationWidgetDelegates.h"

#include "Widgets/DeclarativeSyntaxSupport.h"

class SHorizontalBox;
struct FConcertPropertyChain;

namespace UE::ConcertClientSharedSlate
{
	class IEditableObjectToPropertiesModel;
	class IObjectSelectionSourceModel;
	class IPropertySelectionSourceModel;
	class IReplicationSubobjectView;
	class SBaseReplicationStreamEditor;

	/**
	 * The default replication stream editor adds a checkbox in front of every property row.
	 * 
	 * The checkbox allows adding / removing the properties to / from the selected objects.
	 * The properties are sorted based on the check state: checked come before unchecked.
	 */
	class SDefaultReplicationStreamEditor : public IReplicationStreamEditor
    {
    public:
		
		SLATE_BEGIN_ARGS(SDefaultReplicationStreamEditor)
		{}
			/** Additional columns to add to the object view */
			SLATE_ARGUMENT(TArray<ReplicationObjectColumns::FReplicationObjectColumn>, AdditionalObjectColumns)
			/** Additional columns to add to the property view */
			SLATE_ARGUMENT(TArray<ReplicationPropertyColumns::FReplicationPropertyColumn>, AdditionalPropertyColumns)
			
			/** Optional. Placed between root object outliner and property editor. */
			SLATE_ARGUMENT(TSharedPtr<IReplicationSubobjectView>, SubobjectView)

			/** Called to generate the context menu for objects. This extends the options already generated by this widget. */
			SLATE_EVENT(FExtendMenu, OnExtendObjectsContextMenu)

			/** Optional. Used for determining the order in which properties are displayed. */
			SLATE_EVENT(FSortPropertyPredicate, SortPropertyRowPredicate)

			/** Optional widget to add to the left of the object list search bar. */
			SLATE_NAMED_SLOT(FArguments, LeftOfObjectSearchBar)
			/** Optional widget to add to the left of the property list search bar. */
			SLATE_NAMED_SLOT(FArguments, LeftOfPropertySearchBar)
		SLATE_END_ARGS()

		void Construct(
			const FArguments& InArgs,
			TSharedRef<IEditableObjectToPropertiesModel> InPropertiesModel,
			TSharedRef<IObjectSelectionSourceModel> InObjectSelectionSource,
			TSharedRef<IPropertySelectionSourceModel> InPropertySelectionSource
			);

		//~ Begin IReplicationStreamEditor Interface
		virtual void Refresh() override;
		virtual TArray<FSoftObjectPath> GetSelectedTopLevelObjects() const override;
		virtual TArray<FSoftObjectPath> GetObjectsBeingPropertyEdited() const override;
		//~ End IReplicationStreamEditor Interface

	private:

		/** Core editor implementing generic editing UI & workflows. */
		TSharedPtr<SBaseReplicationStreamEditor> WrappedEditor;
		
		/** Model needed for sorting properties based on selection. */
		TSharedPtr<IEditableObjectToPropertiesModel> PropertiesModel;
		
		bool SortPropertiesPredicate(const FReplicatedPropertyData& Left, const FReplicatedPropertyData& Right) const;
    };
}

