// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../SceneData.ush"
#include "VirtualShadowMapProjectionCommon.ush"
#include "VirtualShadowMapPageOverlap.ush"
#include "VirtualShadowMapPageCacheCommon.ush"
#include "VirtualShadowMapCacheInvalidation.ush"
#include "../ScreenSpaceDenoise/SSDDefinitions.ush"		// For LIGHT_TYPE's
#include "../Nanite/NaniteHZBCull.ush"
#include "../WaveOpUtil.ush"

StructuredBuffer<uint> InstanceInvalidationList;
uint MaxInstanceInvalidations;

[numthreads(VSM_DEFAULT_CS_GROUP_X, 1, 1)]
void InvalidateInstancePagesListCS(
	uint3 GroupId : SV_GroupID,
	uint GroupThreadIndex : SV_GroupIndex,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint ListCount = min(MaxInstanceInvalidations, InstanceInvalidationList[0]);
	if (DispatchThreadId.x >= ListCount)	// List size
	{
		return;
	}
	const uint InstanceId = InstanceInvalidationList[DispatchThreadId.x + 1];	// Skip counter	
	const uint ShadowMapIndex = DispatchThreadId.y;

	checkSlow(ShadowMapIndex < VirtualShadowMap.NumFullShadowMaps);
	const int VirtualShadowMapId = VSM_MAX_SINGLE_PAGE_SHADOW_MAPS + ShadowMapIndex;

	// TODO: Try and clean this up...
	// Currently we only take this path if we just swapped the cache as static flag, so invalidate both
	const bool bForceInvalidateStaticPage = true;
	
	// Invalid instances should not be in this list/path
	InvalidateInstancePages(VirtualShadowMapId, InstanceId, bForceInvalidateStaticPage);
}

StructuredBuffer<uint> VirtualShadowMapInvalidatedInstances;
RWStructuredBuffer<uint> OutInstanceInvalidationList;
RWStructuredBuffer<uint> OutCacheInstanceAsStatic;
uint FramesStaticThreshold;

// TODO: make this shader operate on waves of instances and pack the output
// into a bitfield for static/dynamic reading.
[numthreads(VSM_DEFAULT_CS_GROUP_X, 1, 1)]
void UpdateCacheInstanceAsStaticCS(
	uint DispatchIndex : SV_DispatchThreadID)
{
	// Read/modify write of OutCacheInstanceAsStatic is fine since we are one thread/instance
	const uint InstanceId = DispatchIndex;	
	if (InstanceId >= Scene.GPUScene.NumInstances)
	{
		return;
	}

	const uint SceneFrameNumber = GetGPUSceneFrameNumber();

	if (!IsValidInstanceAndCastShadows(InstanceId))
	{
		// Clear out flags for any future instances that reuse this slot
		// TODO: Initialize this instead when we add instances, once we have a post-scene-update pass.
		// That way we can use the primitive mobility as a hint to the initial cache mode
		OutCacheInstanceAsStatic[InstanceId] = VSM_CACHE_AS_DYNAMIC;
		// NOTE: Initializing the last invalidated frame to 0xFFFFFFFF so we can immediately transitioning
		// static things after they are spawned.
		OutVirtualShadowMapLastInstanceInvalidatedFrame[InstanceId] = 0xFFFFFFFF;
		return;
	}

	const bool bPrevStatic = OutCacheInstanceAsStatic[InstanceId] == VSM_CACHE_AS_STATIC;

	const uint LastInvalidationFrame = OutVirtualShadowMapLastInstanceInvalidatedFrame[InstanceId];
	// Note: cleared to MAX_uint32; treated as "unknown/no invalidations"
	const uint InvalidationAge = 
		SceneFrameNumber >= LastInvalidationFrame ?
		(SceneFrameNumber - LastInvalidationFrame) :
		uint(0xFFFFFFFF);

	const bool bWantStatic = InvalidationAge > FramesStaticThreshold;
	if (bPrevStatic != bWantStatic)
	{
		// Add instance invalidation and swap cache mode
		uint InvalidationListIndex;
		WaveInterlockedAddScalar_(OutInstanceInvalidationList[0], 1U, InvalidationListIndex);

		// Limit this path to some number per frame to keep the list size reasonable
		if (InvalidationListIndex < MaxInstanceInvalidations)
		{
			OutInstanceInvalidationList[InvalidationListIndex + 1] = InstanceId;
			OutCacheInstanceAsStatic[InstanceId] = bWantStatic ? VSM_CACHE_AS_STATIC : VSM_CACHE_AS_DYNAMIC;
		}
	}
}

RWBuffer<uint> OutIndirectArgsBuffer;
uint InvalidateInstancePagesCSGroupSize;

[numthreads(1, 1, 1)]
void SetInstanceInvalidationListIndirectArgs(
	uint DispatchIndex : SV_DispatchThreadID)
{
	uint NumThreads = min(MaxInstanceInvalidations, InstanceInvalidationList[0]);
	uint ThreadGroupSize = InvalidateInstancePagesCSGroupSize;

	WriteDispatchIndirectArgs(OutIndirectArgsBuffer, 0,
		(NumThreads + ThreadGroupSize - 1) / ThreadGroupSize,
		VirtualShadowMap.NumFullShadowMaps,
		1);
}
