; These rules are applied in order, the first rule that applies per file is taken and no others are evaluated

[ExcludeEngineContent]
bExcludeFromPaks=true
bOverrideChunkManifest=true
+Files=".../Engine/Content/EngineFonts/Faces/DroidSansFallback.ufont"
+Files=".../Engine/Content/Slate/Fonts/DroidSansFallback.ttf"
+Files=".../Engine/Content/Slate/Fonts/DroidSansMono.ttf"
+Files=".../Engine/Content/Slate/Fonts/NotoNaskhArabicUI-Regular.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-Black.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-BlackItalic.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-Bold.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-BoldCondensed.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-BoldCondensedItalic.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-BoldItalic.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-Italic.ttf"
+Files=".../Engine/Content/Slate/Fonts/Roboto-Light.ttf"
+Files=".../Engine/Content/SlateDebug/Fonts/LastResort.ttf"
+Files=".../Engine/Content/EngineMaterials/DefaultBloomKernel.*"
+Files=".../Engine/Content/EngineMaterials/BlueNoise.uexp"
;+Files=".../Engine/Content/EngineMaterials/DefaultVirtualTextureMaterial.uexp"
;+Files=".../Engine/Content/EngineMaterials/DefaultDeferredDecalMaterial.uexp"
;+Files=".../Engine/Content/EngineMaterials/HairDefaultMaterial.uexp"
+Files=".../Engine/Content/EngineMaterials/WorldGridMaterial.uexp"
