[/Script/Engine.RendererSettings]
r.screenpercentage=100
r.Mobile.DisableVertexFog=True
r.Shadow.CSM.MaxMobileCascades=1
r.Mobile.UseLegacyShadingModel=False
r.Mobile.AllowDitheredLODTransition=False
r.Mobile.AllowSoftwareOcclusion=False
r.Mobile.VirtualTextures=False
r.DiscardUnusedQuality=False
r.AllowOcclusionQueries=False
r.MinScreenRadiusForLights=0.030000
r.MinScreenRadiusForDepthPrepass=0.030000
r.MinScreenRadiusForCSMDepth=0.010000
r.PrecomputedVisibilityWarning=False
r.TextureStreaming=True
Compat.UseDXT5NormalMaps=False
r.VirtualTextures=False
r.VirtualTexturedLightmaps=False
r.VT.TileSize=128
r.VT.TileBorderSize=4
r.vt.FeedbackFactor=16
r.VT.EnableCompressZlib=True
r.VT.EnableCompressCrunch=False
r.ClearCoatNormal=False
r.AnisotropicBRDF=False
r.ReflectionEnvironmentLightmapMixBasedOnRoughness=False
r.ForwardShading=False
r.VertexFoggingForOpaque=True
r.AllowStaticLighting=True
r.NormalMapsForStaticLighting=False
r.GenerateMeshDistanceFields=False
r.DistanceFieldBuild.EightBit=False
r.GenerateLandscapeGIData=False
r.DistanceFieldBuild.Compress=False
r.TessellationAdaptivePixelsPerTriangle=48.000000
r.SeparateTranslucency=False
r.TranslucentSortPolicy=0
TranslucentSortAxis=(X=0.000000,Y=-1.000000,Z=0.000000)
r.CustomDepth=3
r.CustomDepthTemporalAAJitter=True
r.PostProcessing.PropagateAlpha=0
r.DefaultFeature.Bloom=True
r.DefaultFeature.AmbientOcclusion=False
r.DefaultFeature.AmbientOcclusionStaticFraction=False
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.AutoExposure.Method=0
r.DefaultFeature.AutoExposure.Bias=1.000000
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=False
r.UsePreExposure=True
r.EyeAdaptation.EditorOnly=False
r.EyeAdaptationQuality=0
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.LensFlare=False
r.TemporalAA.Upsampling=False
r.SSGI.Enable=False
r.DefaultFeature.AntiAliasing=2
r.DefaultFeature.LightUnits=1
r.DefaultBackBufferPixelFormat=4
r.Shadow.UnbuiltPreviewInGame=True
r.StencilForLODDither=False
r.EarlyZPass=3
r.EarlyZPassOnlyMaterialMasking=False
r.DBuffer=False
r.ClearSceneMethod=1
r.BasePassOutputsVelocity=False
r.VertexDeformationOutputsVelocity=False
r.SelectiveBasePassOutputs=False
bDefaultParticleCutouts=False
fx.GPUSimulationTextureSizeX=1024
fx.GPUSimulationTextureSizeY=1024
r.AllowGlobalClipPlane=False
r.GBufferFormat=1
r.MorphTarget.Mode=True
r.GPUCrashDebugging=False
vr.InstancedStereo=False
r.MobileHDR=True
vr.MobileMultiView=False
r.Mobile.UseHWsRGBEncoding=False
vr.RoundRobinOcclusion=False
vr.ODSCapture=False
r.MeshStreaming=False
r.WireframeCullThreshold=5.000000
r.RayTracing=False
r.RayTracing.UseTextureLod=False
r.SupportStationarySkylight=True
r.SupportLowQualityLightmaps=True
r.SupportPointLightWholeSceneShadows=False
r.SupportAtmosphericFog=False
r.SupportSkyAtmosphere=False
r.SupportSkyAtmosphereAffectsHeightFog=False
r.SkinCache.CompileShaders=False
r.SkinCache.DefaultBehavior=1
r.SkinCache.SceneMemoryLimitInMB=128.000000
r.SkinCache.ForceRecomputeTangents=False
r.Mobile.EnableStaticAndCSMShadowReceivers=False
r.Mobile.EnableMovableLightCSMShaderCulling=False
r.Mobile.AllowDistanceFieldShadows=False
r.Mobile.AllowMovableDirectionalLights=False
r.MobileNumDynamicPointLights=1
r.MobileDynamicPointLightsUseStaticBranch=True
r.Mobile.EnableMovableSpotlights=False
r.GPUSkin.Support16BitBoneIndex=False
r.GPUSkin.Limit2BoneInfluences=False
r.SupportDepthOnlyIndexBuffers=True
r.SupportReversedIndexBuffers=True
r.SupportMaterialLayers=False
r.LightPropagationVolume=False
r.Mobile.PropagateAlpha=1
r.ReflectionCaptureResolution=512
r.MobileContentScaleFactor=0
r.MobileMSAA=1
r.OpenGL.MaxShaderLibProcessingTime=1000

[DevOptions.Shaders]
NeedsShaderStableKeys=true

[PBCUseWithoutShaderPipelineCache]
;Needed by the automated PSO caching system
PBC_GUID=(X=1, Y=2, Z=3, W=4);

[ConsoleVariables]
;Needed by the automated PSO caching system
r.ProgramBinaryCache.UseWithoutShaderPipelineCache=1
;HMI Optimizations
s.nosound=1
s.disableai=1
s.disablestartupmovie=1

[/Script/Engine.GarbageCollectionSettings]
gc.MaxObjectsInGame=35000

[/Script/Slate.SlateSettings]
bExplicitCanvasChildZOrder=True

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Mobile
AppliedTargetedHardwareClass=Mobile
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Default.Default
LocalMapOptions=
TransitionMap=None
bUseSplitscreen=False
TwoPlayerSplitscreenLayout=Horizontal
ThreePlayerSplitscreenLayout=FavorTop
GameInstanceClass=/Script/Engine.GameInstance
ServerDefaultMap=/Engine/Maps/Entry.Entry
GlobalDefaultGameMode=/Script/Engine.GameModeBase
GlobalDefaultServerGameMode=None

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
MinSDKVersion=29
bSupportsVulkan=True
bDetectVulkanByDefault=True
bSupportsVulkanSM5=True
TargetSDKVersion=31
bAllowIMU=False
bShouldHideUI=True
bVerifyOBBOnStartUp=False
bBuildForArmV7=False
bBuildForX8664=False
bBuildForArm64=True
bBuildForES31=True
bPackageDataInsideApk=True
bAllowLargeOBBFiles=True
PackageName=com.epicgames.[PROJECT]

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
SpatializationPlugin=
ReverbPlugin=
OcclusionPlugin=
SoundCueCookQualityIndex=-1
-TargetedRHIs=SF_VULKAN_SM5
-TargetedRHIs=GLSL_150_ES31
+TargetedRHIs=SF_VULKAN_ES31
+TargetedRHIs=GLSL_ES3_1_ANDROID

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
Compiler=Default
-TargetedRHIs=PCD3D_SM5
-TargetedRHIs=PCD3D_ES31
-TargetedRHIs=GLSL_150_ES31
+TargetedRHIs=PCD3D_SM5
+TargetedRHIs=PCD3D_ES31
+TargetedRHIs=GLSL_150_ES31
DefaultGraphicsRHI=DefaultGraphicsRHI_Default
MinimumOSVersion=MSOS_Vista
bTarget32Bit=False
AudioSampleRate=48000
AudioCallbackBufferFrameSize=1024
AudioNumBuffersToEnqueue=1
AudioMaxChannels=0
AudioNumSourceWorkers=4
SpatializationPlugin=
ReverbPlugin=
OcclusionPlugin=
CompressionOverrides=(bOverrideCompressionTimes=False,DurationThreshold=5.000000,MaxNumRandomBranches=0,SoundCueQualityIndex=0)
bUseAudioStreamCaching=False
CacheSizeKB=0
bResampleForDevice=False
MaxSampleRate=0.000000
HighSampleRate=0.000000
MedSampleRate=0.000000
LowSampleRate=0.000000
MinSampleRate=0.000000
CompressionQualityModifier=0.000000
AutoStreamingThreshold=0.000000
SoundCueCookQualityIndex=-1

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_HMI_Blank",NewGameName="/Script/TP_HMI_Blank")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_HMI_Blank",NewGameName="/Script/TP_HMI_Blank")
