; ------------------------------------------------------------------------------
; Android: Rules for matching devices
; ------------------------------------------------------------------------------

[Android DeviceProfile]
DeviceType=Android
BaseProfileName=
+CVars=r.MobileContentScaleFactor=0
+CVars=r.BloomQuality=2
+CVars=r.DepthOfFieldQuality=0
+CVars=r.LightShaftQuality=0
+CVars=r.RefractionQuality=0
+CVars=r.ShadowQuality=0
+CVars=slate.AbsoluteIndices=1
+CVars=r.Vulkan.DelayAcquireBackBuffer=0
+CVars=r.Vulkan.RobustBufferAccess=1
+CVars=r.Vulkan.DescriptorSetLayoutMode=2
+CVars=r.Android.DisableVulkanSupport=1
+CVars=r.ProgramBinaryCache.RestartAndroidAfterPrecompile=0
+CVars=r.DefaultFeature.AntiAliasing=2
+CVars=r.MobileMSAA=1

;Binary Shader cache
+CVars=r.OpenGL.EnableProgramLRUCache=0
+CVars=r.OpenGL.ProgramLRUCount=10000
+CVars=r.OpenGL.ProgramLRUBinarySize=1000000000
+CVars=r.OpenGL.EvictOnBSSDestruct=1
+CVars=r.OpenGL.EvictOnBSSDestruct.Latency=200
+CVars=r.OpenGL.ProgramLRUKeepBinaryResident=1
+CVars=r.OpenGL.StoreCompressedProgramBinaries=0

; ------------------------------------------------------------------------------
; QNX: Rules for matching devices
; ------------------------------------------------------------------------------

[QNX DeviceProfile]
DeviceType=QNX
BaseProfileName=QNX
+CVars=r.MobileContentScaleFactor=0
+CVars=r.BloomQuality=2
+CVars=r.DepthOfFieldQuality=0
+CVars=r.LightShaftQuality=0
+CVars=r.RefractionQuality=0
+CVars=r.ShadowQuality=0
+CVars=r.DefaultFeature.AntiAliasing=2
+CVars=r.MobileMSAA=1

