// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Graph/Nodes/MovieGraphFileOutputNode.h"
#include "Sound/SampleBufferIO.h"

#include "MovieGraphAudioOutputNode.generated.h"

/**
 * A node which outputs .wav audio after all renders have completed.
 */
UCLASS()
class UMovieGraphAudioOutputNode : public UMovieGraphFileOutputNode
{
	GENERATED_BODY()
	
public:
	UMovieGraphAudioOutputNode() = default;

	// UMovieGraphSettingNode Interface
	virtual void BuildNewProcessCommandLineArgsImpl(TArray<FString>& InOutUnrealURLParams, TArray<FString>& InOutCommandLineArgs, TArray<FString>& InOutDeviceProfileCvars, TArray<FString>& InOutExecCmds) const override;
	// ~UMovieGraphSettingNode Interface

	// UMovieGraphNode Interface
	virtual EMovieGraphBranchRestriction GetBranchRestriction() const override;

#if WITH_EDITOR
	virtual FText GetNodeTitle(const bool bGetDescriptive) const override;
	virtual FText GetKeywords() const override;
	virtual FLinearColor GetNodeTitleColor() const override;
	virtual FSlateIcon GetIconAndTint(FLinearColor& OutColor) const override;
#endif
	// ~UMovieGraphNode Interface

	/**
	 * Although this node does not represent a proper "renderer", it will sometimes be identified in data structures
	 * as a renderer. If that's the case, this is the name of the audio "renderer".
	 */
	inline static const FString RendererName = TEXT("Audio");

	/** The extension of the audio files generated by this node. */
	inline static const FString OutputExtension = TEXT("wav");

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = Overrides, meta = (InlineEditConditionToggle))
	uint8 bOverride_FileNameFormatOverride : 1;
	
	/* File name format string override. If specified it will override the FileNameFormat from the Output Setting node. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "File Output", meta=(EditCondition="bOverride_FileNameFormatOverride"))
	FString FileNameFormatOverride;

protected:
	// UMovieGraphFileOutputNode Interface
	virtual void OnReceiveImageDataImpl(UMovieGraphPipeline* InPipeline, UE::MovieGraph::FMovieGraphOutputMergerFrame* InRawFrameData, const TSet<FMovieGraphRenderDataIdentifier>& InMask) override;
	virtual void OnAllFramesSubmittedImpl() override;
	virtual bool IsFinishedWritingToDiskImpl() const override;
	// ~UMovieGraphFileOutputNode Interface

private:
	/** Represents an audio file, with its associated audio data. */
	struct FFinalAudioData
	{
		FString FilePath;
		Audio::TSampleBuffer<int16> SampleBuffer;
		int32 ShotIndex;
		FMovieGraphRenderDataIdentifier RenderIdentifier;
	};

	/** Generate the final output path for the audio file. */
	FString GenerateOutputPath(const FMovieGraphRenderDataIdentifier& InRenderIdentifier, const TObjectPtr<UMoviePipelineExecutorShot>& InShot) const;

	/** Generates final audio data from all of the audio segments that were collected during render time. */
	void GenerateFinalAudioData(TArray<FFinalAudioData>& OutFinalAudioData);

private:
	/** Kept alive during finalization because the writer writes async to disk but doesn't expect to fall out of scope. */
	TArray<TUniquePtr<Audio::FSoundWavePCMWriter>> ActiveWriters;

	/** Keep track of segments that have already been written to disk to avoid re-writing them (and generating new output futures). */
	TSet<FGuid> AlreadyWrittenSegments;

	/** The pipeline that is running this node. */
	TWeakObjectPtr<UMovieGraphPipeline> CachedPipeline;
};
