// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if HAIR_CARD_MESH_FACTORY

#include "/Engine/Private/HairStrands/HairStrandsVertexFactoryCommon.ush"

///////////////////////////////////////////////////////////////////////////////////////////////////

// Vertex factory Flags
#define EHairCardsVFlags_InvertedUV        0x1
#define EHairCardsVFlags_TextureRootUV     0x2
#define EHairCardsVFlags_TextureGroupIndex 0x4
#define EHairCardsVFlags_TextureColor      0x8
#define EHairCardsVFlags_TextureRoughness  0x10
#define EHairCardsVFlags_TextureAttribute  0x20
#define EHairCardsVFlags_TextureCoverage   0x40
#define EHairCardsVFlags_TextureDepth      0x80
#define EHairCardsVFlags_TextureTangent    0x100
#define EHairCardsVFlags_TextureAuxilary   0x200

// Attribute index
#define EHairCardsVFAttribute_Depth        0
#define EHairCardsVFAttribute_Seed         1
#define EHairCardsVFAttribute_CoordU       2
#define EHairCardsVFAttribute_GroupIndex   3
#define EHairCardsVFAttribute_Roughness    4
#define EHairCardsVFAttribute_RootUV       5
#define EHairCardsVFAttribute_Color        6
#define EHairCardsVFAttribute_Tangent      7
#define EHairCardsVFAttribute_Coverage     8
#define EHairCardsVFAttribute_Auxilary     9

///////////////////////////////////////////////////////////////////////////////////////////////////
// Helper functions for fetching attributes

#define HAIRCARDSVF_USE_LEGACY_LAYOUT 1
#if HAIRCARDSVF_USE_LEGACY_LAYOUT
uint GetHairCardTextureIndex(uint In) 
{ 
	switch (In)
	{
		case EHairCardsVFAttribute_Depth      : return 0;
		case EHairCardsVFAttribute_Seed       : return 3;
		case EHairCardsVFAttribute_CoordU     : return 3;
		case EHairCardsVFAttribute_GroupIndex : return 4; // Only used for mesh, not for cards
		case EHairCardsVFAttribute_Roughness  : return 4;
		case EHairCardsVFAttribute_RootUV     : return 3;
		case EHairCardsVFAttribute_Color      : return 4;
		case EHairCardsVFAttribute_Tangent    : return 1;
		case EHairCardsVFAttribute_Coverage   : return 2;
		case EHairCardsVFAttribute_Auxilary   : return 5; 
	}
	return 0;
}

uint GetHairCardChannelIndex(uint In) 
{ 
	switch (In)
	{
		case EHairCardsVFAttribute_Depth      : return 0;
		case EHairCardsVFAttribute_Seed       : return 3;
		case EHairCardsVFAttribute_CoordU     : return 2;
		case EHairCardsVFAttribute_GroupIndex : return 3;
		case EHairCardsVFAttribute_Roughness  : return 3;
		case EHairCardsVFAttribute_RootUV     : return 0;
		case EHairCardsVFAttribute_Color      : return 0;
		case EHairCardsVFAttribute_Tangent    : return 0;
		case EHairCardsVFAttribute_Coverage   : return 0;
		case EHairCardsVFAttribute_Auxilary   : return 0; 
	}
	return 0;
}
#else
uint GetHairCardTextureIndex(uint In)	{ return ((HairCards.AttributeTextureIndex) >> (In*3u) & 0x7u); }
uint GetHairCardChannelIndex(uint In)	{ return ((HairCards.AttributeChannelIndex) >> (In*2u) & 0x3u); }
#endif
float2 GetAtlasUV(float2 In) 			{ return float2(In.x, (HairCardsVF.Flags & EHairCardsVFlags_InvertedUV) ? 1 - In.y : In.y); }

// Generic attribute texture fetches
float4 FetchAttributeTexture(uint InTextureIndex, float2 InAtlasUV, float InBias)
{
	float4 Out = 0;
	     if (InTextureIndex == 0) { Out = Texture2DSampleBias(HairCardsVF.Texture0Texture, HairCardsVF.Texture0Sampler, InAtlasUV, InBias); }
	else if (InTextureIndex == 1) { Out = Texture2DSampleBias(HairCardsVF.Texture1Texture, HairCardsVF.Texture1Sampler, InAtlasUV, InBias); }
	else if (InTextureIndex == 2) { Out = Texture2DSampleBias(HairCardsVF.Texture2Texture, HairCardsVF.Texture2Sampler, InAtlasUV, InBias); }
	else if (InTextureIndex == 3) { Out = Texture2DSampleBias(HairCardsVF.Texture3Texture, HairCardsVF.Texture3Sampler, InAtlasUV, InBias); }
	else if (InTextureIndex == 4) { Out = Texture2DSampleBias(HairCardsVF.Texture4Texture, HairCardsVF.Texture4Sampler, InAtlasUV, InBias); }
	else if (InTextureIndex == 5) { Out = Texture2DSampleBias(HairCardsVF.Texture5Texture, HairCardsVF.Texture5Sampler, InAtlasUV, InBias); }
	return Out;
}

float4 FetchAttributeTexture(uint InTextureIndex, float2 InAtlasUV)
{
	float4 Out = 0;
		 if (InTextureIndex == 0) { Out = Texture2DSample(HairCardsVF.Texture0Texture, HairCardsVF.Texture0Sampler, InAtlasUV); }
	else if (InTextureIndex == 1) { Out = Texture2DSample(HairCardsVF.Texture1Texture, HairCardsVF.Texture1Sampler, InAtlasUV); }
	else if (InTextureIndex == 2) { Out = Texture2DSample(HairCardsVF.Texture2Texture, HairCardsVF.Texture2Sampler, InAtlasUV); }
	else if (InTextureIndex == 3) { Out = Texture2DSample(HairCardsVF.Texture3Texture, HairCardsVF.Texture3Sampler, InAtlasUV); }
	else if (InTextureIndex == 4) { Out = Texture2DSample(HairCardsVF.Texture4Texture, HairCardsVF.Texture4Sampler, InAtlasUV); }
	else if (InTextureIndex == 5) { Out = Texture2DSample(HairCardsVF.Texture5Texture, HairCardsVF.Texture5Sampler, InAtlasUV); }
	return Out;
}

// Generic attribute fetch functions
float  FetchAttribute1(uint In, float2 InAtlasUV, float InBias) { const float4 Value = FetchAttributeTexture(GetHairCardTextureIndex(In), InAtlasUV, InBias); return Value[GetHairCardChannelIndex(In)];                     }
float  FetchAttribute1(uint In, float2 InAtlasUV)               { const float4 Value = FetchAttributeTexture(GetHairCardTextureIndex(In), InAtlasUV);         return Value[GetHairCardChannelIndex(In)];                     }
float2 FetchAttribute2(uint In, float2 InAtlasUV)               { const float4 Value = FetchAttributeTexture(GetHairCardTextureIndex(In), InAtlasUV);         return GetHairCardChannelIndex(In) == 0 ? Value.xy : Value.zw; } // float2 alignemnt is forced onto .xy or .zw
float3 FetchAttribute3(uint In, float2 InAtlasUV)               { const float4 Value = FetchAttributeTexture(GetHairCardTextureIndex(In), InAtlasUV);         return Value.xyz;                                              } // float3 alignemnt forced onto .xyz
float4 FetchAttribute4(uint In, float2 InAtlasUV)               { const float4 Value = FetchAttributeTexture(GetHairCardTextureIndex(In), InAtlasUV);         return Value;                                                  }

// Special attribute fetch functions
float  GetDepthOffset (float2 InAtlasUV)                        { float  Out = 0;         if (HairCardsVF.Flags & EHairCardsVFlags_TextureDepth)     { Out = FetchAttribute1(EHairCardsVFAttribute_Depth,     InAtlasUV);                          } return Out; }
float  GetSeed        (float2 InAtlasUV)                        { float  Out = 0;         if (HairCardsVF.Flags & EHairCardsVFlags_TextureDepth)     { Out = FetchAttribute1(EHairCardsVFAttribute_Seed,      InAtlasUV);                          } return Out; }
float  GetCoordU      (float2 InAtlasUV)                        { float  Out = 0;         if (HairCardsVF.Flags & EHairCardsVFlags_TextureDepth)     { Out = FetchAttribute1(EHairCardsVFAttribute_CoordU,    InAtlasUV);                          } return Out; }
float  GetGroupIndex  (float2 InAtlasUV, float  InDefault)      { float  Out = InDefault; if (HairCardsVF.Flags & EHairCardsVFlags_TextureGroupIndex){ Out = FetchAttribute1(EHairCardsVFAttribute_GroupIndex,InAtlasUV); Out *= 255.f;            } return Out; }
float  GetRoughness   (float2 InAtlasUV, float  InDefault)      { float  Out = InDefault; if (HairCardsVF.Flags & EHairCardsVFlags_TextureRoughness) { Out = FetchAttribute1(EHairCardsVFAttribute_Roughness, InAtlasUV);                          } return Out; }
float  GetCoverage    (float2 InAtlasUV, float  InDefault)      { float  Out = InDefault; if (HairCardsVF.Flags & EHairCardsVFlags_TextureCoverage)  { Out = FetchAttribute1(EHairCardsVFAttribute_Coverage,  InAtlasUV, HairCardsVF.CoverageBias);} return Out; }
float2 GetRootUV      (float2 InAtlasUV, float2 InDefault)      { float2 Out = InDefault; if (HairCardsVF.Flags & EHairCardsVFlags_TextureRootUV)    { Out = FetchAttribute2(EHairCardsVFAttribute_RootUV,    InAtlasUV);                          } return Out; }
float3 GetColor       (float2 InAtlasUV, float3 InDefault)      { float3 Out = InDefault; if (HairCardsVF.Flags & EHairCardsVFlags_TextureColor)     { Out = FetchAttribute3(EHairCardsVFAttribute_Color,     InAtlasUV); Out = Pow2(Out);         } return Out; } // Cheap sRGB -> Linear encoding
float3 GetTangent     (float2 InAtlasUV, float3 InDefault)      { float3 Out = InDefault; if (HairCardsVF.Flags & EHairCardsVFlags_TextureTangent)   { Out = FetchAttribute3(EHairCardsVFAttribute_Tangent,   InAtlasUV); Out = Out*2-1.f;         } return Out; }
float4 GetAuxilary    (float2 InAtlasUV, float4 InDefault)      { float4 Out = InDefault; if (HairCardsVF.Flags & EHairCardsVFlags_TextureAuxilary)  { Out = FetchAttribute4(EHairCardsVFAttribute_Auxilary,  InAtlasUV);                          } return Out; }

///////////////////////////////////////////////////////////////////////////////////////////////////
// MaterialTemplate interface

float GetHairStrandsDepth(float2 InAtlasUV, float InDeviceZ)
{
	const float SceneDepthOffset = GetDepthOffset(InAtlasUV);
	const float SceneDepth = ConvertFromDeviceZ(InDeviceZ);
	return ConvertToDeviceZ(SceneDepth + SceneDepthOffset);
}

float3 GetHairStrandsTangent(float2 InAtlasUV, half3x3 TangentToWorld, bool bUseTangentSpace)
{
	const float3 LocalTangent = GetTangent(InAtlasUV, float3(0, 1, 0));
	const float3 WorldTangent = mul(LocalTangent, TangentToWorld);
	return bUseTangentSpace ? LocalTangent : WorldTangent;
}

float GetHairStrandsCoverage(float2 InAtlasUV)
{
	return GetCoverage(InAtlasUV, 1.f);
}

float4 GetHairStrandsAuxilaryData(float2 InAtlasUV)
{
	return GetAuxilary(InAtlasUV, 0.f);
}

float2 GetHairStrandsUV(float2 InAtlasUV)
{
	return float2(GetCoordU(InAtlasUV), 0.5f);
}

float2 GetHairStrandsDimensions(float2 InAtlasUV, float HairPrimitiveLength)
{
	return float2(HairPrimitiveLength, 0.01f/*WorldRadius*/);
}

float2 GetHairStrandsRootUV(float2 InAtlasUV, float2 InRootUV)
{
	// Invert V to compensate image origin flip
	// Similar to DecodeHairAttribute in HairStrandVertexFactoryCommon.ush
	return GetRootUV(InAtlasUV, float2(InRootUV.x, 1.0 - InRootUV.y));
}

float GetHairStrandsSeed(float2 InAtlasUV)
{
	return GetSeed(InAtlasUV);
}

uint3 GetHairStrandsClumpID(float2 InAtlasUV)
{
	return 0;
}

float3 GetHairStrandsColor(float2 InAtlasUV, float3 InColor)
{
	return GetColor(InAtlasUV, InColor);
}

float GetHairStrandsRoughness(float2 InAtlasUV, float InCardRoughness)
{
	//return GetRoughness(InAtlasUV, InCardRoughness);
	return (HairCardsVF.Flags & EHairCardsVFlags_TextureRoughness) ? 0 : InCardRoughness;
}

float GetHairStrandsAO(float2 InAtlasUV, float InAO)
{
	return 1.0f;
}

float GetHairStrandsGroupIndex(float2 InAtlasUV, float InCardGroupIndex)
{
	// * For hair cards,  group index is stored onto vertices
	// * For hair meshes, group index is stored within a texture
	return GetGroupIndex(InAtlasUV, InCardGroupIndex);
}
////////////////////////////////////////////////////////////////////////////////

#endif // HAIR_CARD_MESH_FACTORY