<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Development</Configurations>
    <BaseOutputPath>bin\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutomationTool\Gauntlet\Gauntlet.Automation.csproj" />
  </ItemGroup>

</Project>
