// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "MuCOE/Nodes/CustomizableObjectNode.h"

#include "CustomizableObjectNodeModifierBase.generated.h"

enum class EMutableMultipleTagPolicy:uint8;


USTRUCT()
struct FLegacyTag
{
	GENERATED_BODY()

	UPROPERTY()
	TSoftObjectPtr<UCustomizableObject> ParentObject;

	UPROPERTY()
	FGuid ParentNode;

	UPROPERTY()
	FString Tag;

	bool operator==(const FLegacyTag&) const = default;
};


UCLASS(abstract)
class CUSTOMIZABLEOBJECTEDITOR_API UCustomizableObjectNodeModifierBase : public UCustomizableObjectNode
{

	GENERATED_BODY()

public:

	// EdGraphNode interface
	virtual FLinearColor GetNodeTitleColor() const override;

	// UCustomizableObjectNode interface
	virtual void BackwardsCompatibleFixup(int32 CustomizableObjectCustomVersion) override;
	virtual void PostBackwardsCompatibleFixup() override;

	// Own interface
	virtual UEdGraphPin* OutputPin() const;
	virtual const TArray<FString>* GetRequiredTags() const PURE_VIRTUAL(UCustomizableObjectNodeModifierBase::GetRequiredTags, return nullptr; );

	virtual EMutableMultipleTagPolicy GetMultipleTagsPolicy() const PURE_VIRTUAL(UCustomizableObjectNodeModifierBase::GetMultipleTagsPolicy, return {}; );

	/** Return true if the tags and policy in this node would make this node modify the given parameter node. */
	bool IsApplicableTo(UCustomizableObjectNode* Candidate) const;

	/** Get the list of all nodes of this object that may be affected by this modifier. This is an approximate
	* query: it includes all nodes that may be affected by this modifier but it may include nodes that will not 
	* be modified by this modifier because of other conditions.
	*/
	void GetPossiblyModifiedNodes(TArray<UCustomizableObjectNode*>&) const;

	/** Generate a tag that is unique and stable for the given node. */
	static FString MakeNodeAutoTag(UEdGraphNode*);

protected:

	/** This is a list of tags autogenerated due to backwards compatibility upgrade. 
	* It must be removed when we remove the related backwards compatibility code.
	*/
	UPROPERTY()
	TArray<FLegacyTag> LegacyBackportsRequiredTags;
};

