// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "PCGDataAsset.h"

#include "PCGLevelToAsset.generated.h"

class UPackage;

UCLASS(BlueprintType, Blueprintable, meta = (ShowWorldContextPin))
class PCGEDITOR_API UPCGLevelToAsset : public UObject
{
	GENERATED_BODY()

public:
	/** Creates/Updates on PCG Asset per given world. Allows exporter subclassing by passing in a Subclass. */
	static void CreateOrUpdatePCGAssets(const TArray<FAssetData>& WorldAssets, TSubclassOf<UPCGLevelToAsset> Subclass = {});

	/** Creates/Updates on PCG Asset for a specific world. Allows exporter subclassing by passing in a Subclass. Will return null if it fails, or the package that was modified otherwise. */
	static UPackage* CreateOrUpdatePCGAsset(TSoftObjectPtr<UWorld> World, TSubclassOf<UPCGLevelToAsset> Subclass = {});

	/** Creates/Updates a PCG Asset for a specific world, allowing exporter subclassing (and settings creation by extension). Will return null if it fails, or the package that was modified otherwise. */
	static UPackage* CreateOrUpdatePCGAsset(UWorld* World, TSubclassOf<UPCGLevelToAsset> Subclass = {});

	/** Parses the level and fills in the provided data asset. Implement this in BP to drive the generation in a custom manner. */
	UFUNCTION(BlueprintNativeEvent, meta = (DisplayName = "Export Level", ForceAsFunction))
	bool BP_ExportLevel(UWorld* Level, const FString& PackageName, UPCGDataAsset* Asset);

	/** Returns the subtype of PCG data asset generated by the Level To Asset process. Override this in the instances where you would not use the default base class. */
	UFUNCTION(BlueprintNativeEvent, meta = (DisplayName = "Get Asset Type", ForceAsFunction))
	TSubclassOf<UPCGDataAsset> BP_GetAssetType() const;

protected:
	/** Drives the asset creation for the data parsed from the level, will return UPCGDataAsset by default. */
	virtual TSubclassOf<UPCGDataAsset> GetAssetType() const;

	/** Parses the level and pushes data to the asset. */
	virtual bool ExportLevel(UWorld* Level, const FString& PackageName, UPCGDataAsset* Asset);
};