// Copyright Epic Games, Inc. All Rights Reserved.
#include "../Common.ush"

#include "LocalFogVolumeCommon.ush"


RWTexture2DArray<uint> LocalFogVolumeTileDataTextureUAV;

#ifndef THREADGROUP_SIZE
#error THREADGROUP_SIZE must be defined
#endif

[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void LocalFogVolumeTiledCullingCS(uint3 ThreadId : SV_DispatchThreadID)
{
	uint2 TilePos = uint2(ThreadId.xy);

	if (any(TilePos >= LFVTileDataResolution))
	{
		return; // Skip out of bound texture tile data 
	}

	LocalFogVolumeTileDataTextureUAV[uint3(TilePos, 0)] = TilePos.x + TilePos.y; // DEBUG
}


