// Copyright Epic Games, Inc. All Rights Reserved.
#include "../Common.ush"

#if SHADING_PATH_MOBILE
#define MobileSceneTextures MobileBasePass.SceneTextures 
#endif

#include "../SceneTexturesCommon.ush"



#ifndef LFV_SPLAT_VS
#define LFV_SPLAT_VS 0
#endif
#ifndef LFV_SPLAT_PS
#define LFV_SPLAT_PS 0
#endif
#ifndef LFV_TILED_VS
#define LFV_TILED_VS 0
#endif
#ifndef LFV_TILED_PS
#define LFV_TILED_PS 0
#endif



#if LFV_SPLAT_PS
#define LFV_CAN_CLIP 1
#else
#define LFV_CAN_CLIP 0
#endif
#include "LocalFogVolumeCommon.ush"



struct FLocalFogVolumeVertexOutput
{
#if LFV_SPLAT_VS || LFV_SPLAT_PS
	nointerpolation uint InstanceId : TEXCOORD0;
#endif

#if LFV_TILED_VS || LFV_TILED_PS
	nointerpolation uint TileData : TEXCOORD0;
#endif
};

#if LFV_SPLAT_VS
void LocalFogVolumeSplatVS(
	in float4 InPosition : ATTRIBUTE0,
	uint InstanceIndex : SV_InstanceID,
	out float4 OutPosition : SV_POSITION,
	out FLocalFogVolumeVertexOutput OtherVertexOutput
)
{
	ResolvedView = ResolveView();

	float4 LocalPosition = InPosition;

	FLocalFogVolumeGPUInstanceData FogInstance = GetLocalFogVolumeGPUInstanceData(InstanceIndex);

	float4x4 FogTransform = FogInstance.Transform;

	float4 WorldPosition = mul(float4(LocalPosition.xyz, 1.0f), FogTransform);

	float4 TranslatedWorldPosition = float4(WorldPosition.xyz + LWCHackToFloat(PrimaryView.PreViewTranslation), 1);

	OutPosition = mul(TranslatedWorldPosition, PrimaryView.TranslatedWorldToClip);
	OtherVertexOutput.InstanceId = InstanceIndex;
}
#endif // LFV_SPLAT_VS


#if LFV_SPLAT_PS
void LocalFogVolumeSplatPS(
	in float4 SVPos : SV_POSITION,
	in FLocalFogVolumeVertexOutput OtherVertexOutput,
	out float4 OutColor : SV_Target0)
{
	ResolvedView = ResolveView();
	uint InstanceIndex = OtherVertexOutput.InstanceId;

	float3 CamRayTranslatedWorldOrigin	= PrimaryView.TranslatedWorldCameraOrigin;
	float3 CamRayTranslatedWorldDir = normalize(SvPositionToTranslatedWorld(float4(SVPos.xy, 0.5, 1.0)));
	float3 CamRayWorldDir = CamRayTranslatedWorldDir;
	float3 CamRayWorldOrigin = CamRayTranslatedWorldOrigin - LWCHackToFloat(PrimaryView.PreViewTranslation);

#if SHADING_PATH_MOBILE
	// LookupDeviceZ with uint2 SVPos.xy as input does not work on mobile.
	float2 UV = SVPos * View.BufferSizeAndInvSize.zw;
	const float DeviceZ = LookupDeviceZ(UV);
#else
	const float DeviceZ = LookupDeviceZ(uint2(SVPos.xy));
#endif

	float3 DepthBufferTranslatedWorldPos = SvPositionToTranslatedWorld(float4(SVPos.xy, DeviceZ, 1.0));

	float4 LuminanceColorTransmittance = GetLFVInstanceContribution(
		InstanceIndex,
		CamRayWorldOrigin,
		CamRayWorldDir,
		CamRayTranslatedWorldOrigin,
		CamRayTranslatedWorldDir,
		DepthBufferTranslatedWorldPos);

	OutColor = float4(
		LuminanceColorTransmittance.rgb * PrimaryView.PreExposure,
		LuminanceColorTransmittance.a);
}
#endif // LFV_SPLAT_PS





#if LFV_TILED_VS
void LocalFogVolumeTiledVS(
	in uint VertexIndex : SV_VertexID,
	in uint InstanceIndex : SV_InstanceID,
	out float4 OutPosition : SV_POSITION,
	out FLocalFogVolumeVertexOutput OtherVertexOutput
)
{
	ResolvedView = ResolveView();

	uint2 TileCoord;
	TileCoord.y = InstanceIndex / LFVTileDataResolution.x;
	TileCoord.x = InstanceIndex - TileCoord.y * LFVTileDataResolution.x;

	uint2 TileVertex = TileCoord * LFVTilePixelSize;
	TileVertex.x += VertexIndex == 1 || VertexIndex == 2 || VertexIndex == 4 ? LFVTilePixelSize : 0;
	TileVertex.y += VertexIndex == 2 || VertexIndex == 4 || VertexIndex == 5 ? LFVTilePixelSize : 0;

	OutPosition = float4(float2(TileVertex) * ResolvedView.ViewSizeAndInvSize.zw * float2(2.0f, -2.0f) + float2(-1.0, 1.0f), 0.5f, 1.0f);

	OtherVertexOutput.TileData = (TileCoord.x << 16) | TileCoord.y;
}
#endif // LFV_TILED_VS


#if LFV_TILED_PS
void LocalFogVolumeTiledPS(
	in float4 SVPos : SV_POSITION,
	in FLocalFogVolumeVertexOutput OtherVertexOutput,
	out float4 OutColor : SV_Target0)
{
	ResolvedView = ResolveView();

	uint2 TilePos = uint2(OtherVertexOutput.TileData >> 16, OtherVertexOutput.TileData & 0xFFFF);

	uint LFVCount = LFVTileDataTex[uint3(TilePos,0)];

//	OutColor = float4(float(TilePos.x) * 0.1, float(TilePos.y) * 0.1, 0.0, 0.5);
	OutColor = float4(float(LFVCount) * 0.1, 0.0, 0.0, 0.5);
}
#endif // LFV_TILED_PS

