// Copyright Epic Games, Inc. All Rights Reserved.
#include "../Common.ush"

#include "../SHCommon.ush"
#include "../ParticipatingMediaCommon.ush"
#include "../ReflectionEnvironmentShared.ush"



///////////////////////////////////////////////////////////////////////////////
// Local Fog Volume Data

struct FLocalFogVolumeGPUInstanceData
{
	float4x4 Transform;
	float4x4 InvTransform;

	float Density;
	float HeightFalloff;
	float HeightOffset;
	float UniformScale;

	float3 Albedo;
	float  PhaseG;
	float3 Emissive;
	float  FogMode;
};


// Structured buffers cannot be sampled from the vertex shader on some mobile platforms. 
// That is why simple Buffers are used for LocalFogVolumeInstances, because this tech needs to run on mobile platforms.

#if defined(LFVStruct)

#define LFVInsts						LFVStruct.LFV.LocalFogVolumeInstances
#define LFVTileDataTex					LFVStruct.LFV.LocalFogVolumeTileDataTexture

#define LFVTileDataResolution			LFVStruct.LFV.LocalFogVolumeTileDataTextureResolution
#define LFVInstcount					LFVStruct.LFV.LocalFogVolumeInstanceCount
#define LFVTilePixelSize				LFVStruct.LFV.LocalFogVolumeTilePixelSize
#define LFVMaxDensityIntoVolumetricFog	LFVStruct.LFV.LocalFogVolumeMaxDensityIntoVolumetricFog
#define LFVRenderInVolumetricFog		LFVStruct.LFV.ShouldRenderLocalFogVolumeInVolumetricFog

#define LFVDirectionalLightColor		LFVStruct.LFV.DirectionalLightColor
#define LFVDirectionalLightDirection	LFVStruct.LFV.DirectionalLightDirection

#else

uint2									LFV_LocalFogVolumeTileDataTextureResolution;
uint									LFV_LocalFogVolumeInstanceCount;
uint									LFV_LocalFogVolumeTilePixelSize;
float									LFV_LocalFogVolumeMaxDensityIntoVolumetricFog;
uint									LFV_ShouldRenderLocalFogVolumeInVolumetricFog;

float3									LFV_DirectionalLightColor;
float3									LFV_DirectionalLightDirection;

Buffer<float4>							LFV_LocalFogVolumeInstances;
Texture2DArray<uint>					LFV_LocalFogVolumeTileDataTexture;

#define LFVInsts						LFV_LocalFogVolumeInstances
#define LFVTileDataTex					LFV_LocalFogVolumeTileDataTexture

#define LFVTileDataResolution			LFV_LocalFogVolumeTileDataTextureResolution
#define LFVInstcount					LFV_LocalFogVolumeInstanceCount
#define LFVTilePixelSize				LFV_LocalFogVolumeTilePixelSize
#define LFVMaxDensityIntoVolumetricFog	LFV_LocalFogVolumeMaxDensityIntoVolumetricFog
#define LFVRenderInVolumetricFog		LFV_ShouldRenderLocalFogVolumeInVolumetricFog

#define LFVDirectionalLightColor		LFV_DirectionalLightColor
#define LFVDirectionalLightDirection	LFV_DirectionalLightDirection

#endif


FLocalFogVolumeGPUInstanceData GetLocalFogVolumeGPUInstanceData(uint Index)
{
	FLocalFogVolumeGPUInstanceData Data;
	uint Offset = Index * 11;

	Data.Transform			= float4x4(LFVInsts[Offset + 0 ], LFVInsts[Offset + 1 ], LFVInsts[Offset + 2 ], LFVInsts[Offset + 3 ]);
	Data.InvTransform		= float4x4(LFVInsts[Offset + 4 ], LFVInsts[Offset + 5 ], LFVInsts[Offset + 6 ], LFVInsts[Offset + 7 ]);

	float4 Temp0 = LFVInsts[Offset + 8];
	Data.Density = Temp0.x;
	Data.HeightFalloff = Temp0.y;
	Data.HeightOffset = Temp0.z;
	Data.UniformScale = Temp0.w;

	float4 Temp1 = LFVInsts[Offset + 9];
	Data.Albedo = Temp1.xyz;
	Data.PhaseG = Temp1.w;

	float4 Temp2 = LFVInsts[Offset + 10];
	Data.Emissive = Temp2.xyz;
	Data.FogMode = Temp2.w;

	return Data;
}



///////////////////////////////////////////////////////////////////////////////
// Local Fog Volume Tile Data

uint2 LFVUnpackTile(uint In)
{
	return uint2(In & 0xFFFF, In >> 16);
}

uint LFVPackTile(uint2 TileCoord)
{
#if COMPILER_SUPPORTS_PACK_INTRINSICS
	return PackUInt2ToUInt(TileCoord.x, TileCoord.y);
#else
	return TileCoord.x | (TileCoord.y << 16); // assumes 16bit is enough to represent a tiled resolution up to 65,535 :)
#endif
}



///////////////////////////////////////////////////////////////////////////////
// Local Fog Volume Integrals

// CameraPos can be behind of RayStart if the camera is out of the volume
struct FFogData
{
	float IntegratedLuminanceFactor;
	float Coverage;
};

// Height fog is evaluated according to spatially varying density defined as "Density * Exp[-HeightFalloff * z]"
FFogData LocalFogVolumeEvaluateHeightIntegral(FLocalFogVolumeGPUInstanceData FogInstance, float3 CameraPos, float3 RayStart, float3 RayDir, float RayLength)
{
	FFogData FogData;

	float3 RayOriU = mul(float4(RayStart, 1.0f), FogInstance.InvTransform).xyz;
	float3 RayIntU = mul(float4(RayStart + RayDir * RayLength, 1.0f), FogInstance.InvTransform).xyz;
	float3 RayDirU = mul(float4(RayDir, 0.0f), FogInstance.InvTransform).xyz;
	RayDirU = normalize(RayDirU);

	float RayLengthU = length(RayIntU - RayOriU);

	float StartHeight = RayOriU.z - FogInstance.HeightOffset; // accoutn for the fog offset.

	float OpticalDepth = 0.0f;
#if 0
	// Original integral, less artefact
	OpticalDepth = (FogInstance.Density / FogInstance.HeightFalloff) * exp(-StartHeight * FogInstance.HeightFalloff) * (1.0 - exp(-RayDirU.z * RayLengthU * FogInstance.HeightFalloff)) / RayDirU.z;
#elif 1
	// Reworked to avoid large value as input to exp
	//OpticalDepth = (FogInstance.Density / FogInstance.HeightFalloff) * (exp(-StartHeight * FogInstance.HeightFalloff) - exp(-StartHeight * FogInstance.HeightFalloff - RayDir.z * RayLength * FogInstance.HeightFalloff)) / RayDir.z;

	// But we use an updated formulation to avoid large input to exp leading to inf and nan.
	float Factor0 = StartHeight * FogInstance.HeightFalloff;
	float Factor1 = RayDirU.z * RayLengthU * FogInstance.HeightFalloff;
	Factor0 = max(-80.0f, Factor0); // Simply clamp Factor0 to a valid range in order to not have exp explode.

	OpticalDepth = (FogInstance.Density / (FogInstance.HeightFalloff * RayDirU.z)) * (exp(-Factor0) - exp(-(Factor0 + Factor1)));
#endif

	// Transmittance is the 
	float Transmittance = exp(-OpticalDepth);
	// Assuming extinction is grey scale, we can compute a single coverage value from transmittance
	FogData.Coverage = (1.0 - Transmittance);
	// Assuming extinction==scattering, i.e. albedo=1, we can compute the integrale for each point on a ray while accouting for transmittance back to the view.
	// It turns out that, under these conditions, the luminance and emissive factor is simply coverage. => see Mathematica details at the bottom of this page.
	FogData.IntegratedLuminanceFactor = FogData.Coverage;

	return FogData;
}


FFogData LocalFogVolumeEvaluateRadialIntegral(FLocalFogVolumeGPUInstanceData FogInstance, float3 CameraPos, float3 RayStart, float3 RayDir, float RayLength)
{
	FFogData FogData = (FFogData)0;

	float3 RayOriU = mul(float4(RayStart, 1.0f), FogInstance.InvTransform).xyz;
	float3 RayIntU = mul(float4(RayStart + RayDir * RayLength, 1.0f), FogInstance.InvTransform).xyz;
	float3 RayDirU = mul(float4(RayDir, 0.0f), FogInstance.InvTransform).xyz;
	RayDirU = normalize(RayDirU);

	float RayLengthU = length(RayIntU - RayOriU);

	float3 SphereCenter = 0.0f;
	float3 VolumeCenterToRayO = (RayOriU - SphereCenter);

	float b = dot(RayDirU, VolumeCenterToRayO);
	float c = dot(VolumeCenterToRayO, VolumeCenterToRayO) - 1.0f;
	float h = b * b - c;

	float OpticalDepth = 0.0f;
	if (h >= 0.0)
	{
		h = sqrt(h);
		float Length0 = -b - h;
		float Length1 = -b + h;

		Length0 = max(Length0, 0.0);
		Length1 = max(Length1, 0.0);
		Length1 = min(Length1, RayLengthU);

		// Integral of a density that descreases accordingf to square distance from the center of the volume.
		float Integral0 = -(c * Length0 + b * Length0 * Length0 + Length0 * Length0 * Length0 / 3.0f);
		float Integral1 = -(c * Length1 + b * Length1 * Length1 + Length1 * Length1 * Length1 / 3.0f);
		OpticalDepth = max(0.0, FogInstance.Density * (Integral1 - Integral0) * (3.0f / 4.0f));
	}

	// Transmittance is the 
	float Transmittance = exp(-OpticalDepth);
	// Assuming extinction is grey scale, we can compute a single coverage value from transmittance
	FogData.Coverage = (1.0 - Transmittance);
	// Assuming extinction==scattering, i.e. albedo=1, we can compute the integrale for each point on a ray while accouting for transmittance back to the view.
	// It turns out that, under these conditions, the luminance and emissive factor is simply coverage. => see Mathematica details at the bottom of this page.
	FogData.IntegratedLuminanceFactor = FogData.Coverage;

	return FogData;
}



///////////////////////////////////////////////////////////////////////////////
// Local Fog Volume Evaluation

struct LocalFogVolumeCommonLightingInput
{
	float3 DistantSkyLight;
};

LocalFogVolumeCommonLightingInput LocalFogVolumeEvaluateCommonLightingInput()
{
	LocalFogVolumeCommonLightingInput CommonLightingInput = (LocalFogVolumeCommonLightingInput)0;
#if PROJECT_SUPPORT_SKY_ATMOSPHERE_AFFECTS_HEIGHFOG
	CommonLightingInput.DistantSkyLight = Texture2DSampleLevel(View.DistantSkyLightLutTexture, View.DistantSkyLightLutTextureSampler, float2(0.5f, 0.5f), 0.0f).rgb;
#endif
	return CommonLightingInput;
}

float3 LocalFogVolumeEvaluateInScattering(in FLocalFogVolumeGPUInstanceData FogInstance, in FFogData FogData, in LocalFogVolumeCommonLightingInput CommonLightingInput, in float3 RayDirWorld)
{
	half3 InScattering = 0.0f;

	// Lighting equation here matches the volumetric fog.

	// Main forward directional light intensity
	InScattering += LFVDirectionalLightColor * HenyeyGreensteinPhase(-FogInstance.PhaseG, dot(RayDirWorld, LFVDirectionalLightDirection));

	// Sky light
	if (View.SkyLightVolumetricScatteringIntensity > 0)
	{
		float3 SkyLighting = View.SkyLightColor.rgb * GetSkySHDiffuseSimple(RayDirWorld * -FogInstance.PhaseG);

		float SkyVisibility = 1.0f; // Not possible to reach with analytical integration
		InScattering += (SkyVisibility * View.SkyLightVolumetricScatteringIntensity) * SkyLighting;
	}
	
	// Apply the medium uniform single scattering albedo
	InScattering *= FogInstance.Albedo;

	// Now account for emissive luminance after albedo and heighfog contribution has been accounted for.
	// This do mean that the emissive color follows the medium density variation.
	InScattering += FogInstance.Emissive;

	// Then scale the contribution according to the normalised pre intergrated scattering.
	return InScattering * FogData.IntegratedLuminanceFactor;
}



///////////////////////////////////////////////////////////////////////////////
// Local Fog Volume Instance Evaluation

#ifndef LFV_CAN_CLIP
#define LFV_CAN_CLIP 0
#endif

// Returns color transmittance
float4 GetLFVInstanceContribution(
	uint InstanceIndex,
	float3 CamRayWorldOrigin,
	float3 CamRayWorldDir,
	float3 CamRayTranslatedWorldOrigin,
	float3 CamRayTranslatedWorldDir,
	float3 DepthBufferTranslatedWorldPos)
{
	FLocalFogVolumeGPUInstanceData FogInstance = GetLocalFogVolumeGPUInstanceData(InstanceIndex);

	float3 LuminanceColor = float3(0.0f, 0.0f, 0.0f);
	float Transmittance = 1.0f;

	// The "U" prefix is for all compuation done in the Unit Sphere space.
	float3 RayPosU = mul(float4(CamRayWorldOrigin, 1.0f), FogInstance.InvTransform).xyz;
	float3 RayDirU = mul(float4(CamRayWorldDir,    0.0f), FogInstance.InvTransform).xyz; // Try to use InverseTranspose to correctly handle direction transform with scaling.
	RayDirU.xyz = normalize(RayDirU);

	float2 TsU = RayIntersectSphere(RayPosU, RayDirU, float4(0.0, 0.0, 0.0, 1.0));
	if (any(TsU > 0.0))
	{
		float LengthD = length(DepthBufferTranslatedWorldPos - CamRayTranslatedWorldOrigin);

		float3 P0U = RayPosU + max(0.0, TsU.x) * RayDirU;
		float3 P1U = RayPosU + max(0.0, TsU.y) * RayDirU;
		// Computations are all done with Space = world space
		float3 P0Space = mul(float4(P0U, 1.0), FogInstance.Transform).xyz;
		float3 P1Space = mul(float4(P1U, 1.0), FogInstance.Transform).xyz;
		float3 CamRayOriginSpace = CamRayWorldOrigin;
		float3 CamRayDirSpace = CamRayWorldDir;

		float Length0 = length(P0Space - CamRayOriginSpace);
		float Length1 = length(P1Space - CamRayOriginSpace);

		if (LFVRenderInVolumetricFog)
		{
			// Volumetric fog covers up to MaxDistance along ViewZ, exclude analytical fog from this range
			float CosAngle = dot(CamRayWorldDir, View.ViewForward);
			float InvCosAngle = (CosAngle > 0.0001) ? rcp(CosAngle) : 0;
			float ExcludeDistance = View.VolumetricFogMaxDistance * InvCosAngle;
			Length0 = max(Length0, ExcludeDistance);
			Length1 = max(Length1, ExcludeDistance);
		}

		// Clamp the traced distance to depth and compute world length.
		Length0 = min(LengthD, Length0);
		Length1 = min(LengthD, Length1);
		float RayTracedLength = max(0.0, abs(Length1 - Length0));

		if (RayTracedLength > 0.0)
		{
			FFogData FogData = (FFogData)0;

			LocalFogVolumeCommonLightingInput CommonLightingInput = LocalFogVolumeEvaluateCommonLightingInput();

			if (FogInstance.FogMode == 0)
			{
				FogData = LocalFogVolumeEvaluateHeightIntegral(FogInstance, CamRayWorldOrigin, CamRayWorldOrigin + CamRayWorldDir * Length0, CamRayWorldDir, RayTracedLength);
			}
			else // (FogInstance.FogMode == 1)
			{
				// TODO
				// TODO LocalFogVolumeEvaluateRadialIntegral needs to be optimised because it is redoing lots of computations. Maybe move HeightFogIntegral to also be in a local normalised space.
				// TODO It is like that for now while iterating with artists.
				// TODO
				FogData = LocalFogVolumeEvaluateRadialIntegral(FogInstance, CamRayWorldOrigin, CamRayWorldOrigin + CamRayWorldDir * Length0, CamRayWorldDir, RayTracedLength);
			}

			LuminanceColor = LocalFogVolumeEvaluateInScattering(FogInstance, FogData, CommonLightingInput, CamRayWorldDir);
			Transmittance = 1.0 - FogData.Coverage;
		}
		else
		{
#if LFV_CAN_CLIP
			clip(-1.0);
#endif
		}
	}
	else
	{
#if LFV_CAN_CLIP
		clip(-1.0);
#endif
	}

	return float4(LuminanceColor, Transmittance);
}



// Evaluate the local fog volume contribution for a world position.
// Returns a float4 with Luminance Color in RGB and Transmittance in A.
float4 GetLFVContribution(
	in ViewState ResolvedView,
	in uint2 TilePos,
	in float3 TranslatedWorldPosition,
	inout uint LFVCount)
{
	float3 CamRayTranslatedWorldOrigin = ResolvedView.TranslatedWorldCameraOrigin;
	float3 PreViewTranslation = LWCHackToFloat(ResolvedView.PreViewTranslation);

	LFVCount = LFVTileDataTex[uint3(TilePos, 0)];
	const float4 DefaultColorTransmittance = float4(0.0, 0.0, 0.0, 1.0);
	float4 LFVContribution = DefaultColorTransmittance;
	for (int LFVIndex = 0; LFVIndex < LFVCount; ++LFVIndex)
	{
		uint InstanceIndex = LFVTileDataTex[uint3(TilePos, 1 + LFVIndex)];

		float3 CamRayWorldOrigin = CamRayTranslatedWorldOrigin - PreViewTranslation;
		float3 CamRayTranslatedWorldDir = normalize(TranslatedWorldPosition - CamRayTranslatedWorldOrigin);
		float3 CamRayWorldDir = CamRayTranslatedWorldDir;

		float3 DepthBufferTranslatedWorldPos = TranslatedWorldPosition.xyz;

		float4 LFVLuminanceColorTransmittance = GetLFVInstanceContribution(
			InstanceIndex,
			CamRayWorldOrigin,
			CamRayWorldDir,
			CamRayTranslatedWorldOrigin,
			CamRayTranslatedWorldDir,
			DepthBufferTranslatedWorldPos);

		LFVContribution = float4(LFVContribution.rgb * LFVLuminanceColorTransmittance.a + LFVLuminanceColorTransmittance.rgb, LFVContribution.a * LFVLuminanceColorTransmittance.a);
	}
	return LFVContribution;
}

float4 GetLFVContribution(
	in ViewState ResolvedView,
	in uint2 TilePos,
	in float3 TranslatedWorldPosition)
{
	uint LFVCount = 0;
	return GetLFVContribution(ResolvedView, TilePos, TranslatedWorldPosition, LFVCount);
}


