// Copyright Epic Games, Inc. All Rights Reserved.
#include "../Common.ush"

#if SHADING_PATH_MOBILE
#define MobileSceneTextures MobileBasePass.SceneTextures 
#endif

#include "../SceneTexturesCommon.ush"

#define LFV_CAN_CLIP 1
#include "LocalFogVolumeCommon.ush"


struct FLocalFogVolumeVertexOutput
{
	nointerpolation uint InstanceId : TEXCOORD0;
};


void LocalFogVolumeSplatVS(
	in float4 InPosition : ATTRIBUTE0,
	uint InstanceIndex : SV_InstanceID,
	out float4 OutPosition : SV_POSITION,
	out FLocalFogVolumeVertexOutput OtherVertexOutput
)
{
	ResolvedView = ResolveView();

	float4 LocalPosition = InPosition;

	FLocalFogVolumeGPUInstanceData FogInstance = GetLocalFogVolumeGPUInstanceData(InstanceIndex);

	float4x4 FogTransform = FogInstance.Transform;

	float4 WorldPosition = mul(float4(LocalPosition.xyz, 1.0f), FogTransform);

	float4 TranslatedWorldPosition = float4(WorldPosition.xyz + LWCHackToFloat(PrimaryView.PreViewTranslation), 1);

	OutPosition = mul(TranslatedWorldPosition, PrimaryView.TranslatedWorldToClip);
	OtherVertexOutput.InstanceId = InstanceIndex;
}


void LocalFogVolumeSplatPS(
	in float4 SVPos : SV_POSITION,
	in FLocalFogVolumeVertexOutput OtherVertexOutput,
	out float4 OutColor : SV_Target0)
{
	ResolvedView = ResolveView();
	uint InstanceIndex = OtherVertexOutput.InstanceId;

	float3 CamRayTranslatedWorldOrigin	= PrimaryView.TranslatedWorldCameraOrigin;
	float3 CamRayTranslatedWorldDir = normalize(SvPositionToTranslatedWorld(float4(SVPos.xy, 0.5, 1.0)));
	float3 CamRayWorldDir = CamRayTranslatedWorldDir;
	float3 CamRayWorldOrigin = CamRayTranslatedWorldOrigin - LWCHackToFloat(PrimaryView.PreViewTranslation);

#if SHADING_PATH_MOBILE
	// LookupDeviceZ with uint2 SVPos.xy as input does not work on mobile.
	float2 UV = SVPos * View.BufferSizeAndInvSize.zw;
	const float DeviceZ = LookupDeviceZ(UV);
#else
	const float DeviceZ = LookupDeviceZ(uint2(SVPos.xy));
#endif

	float3 DepthBufferTranslatedWorldPos = SvPositionToTranslatedWorld(float4(SVPos.xy, DeviceZ, 1.0));

	float4 LuminanceColorTransmittance = GetLFVInstanceContribution(
		InstanceIndex,
		CamRayWorldOrigin,
		CamRayWorldDir,
		CamRayTranslatedWorldOrigin,
		CamRayTranslatedWorldDir,
		DepthBufferTranslatedWorldPos);

	OutColor = float4(
		LuminanceColorTransmittance.rgb * PrimaryView.PreExposure,
		LuminanceColorTransmittance.a);
}


/*

Proof of the height fog integral equations using Mathematica

(*Density of matter according to height Y*)
Density [y_] := A * Exp[-B * y]
 
(*Ray position*)
Ray[t_] := Oz + t * Rz

(*Integrate Optical Depth for a distance T*)
Fog[T_] := Integrate[Density[Ray[t]], {t, 0, T}]

(*Optical Depth integration equation*)
Fog[T]

(*Transmittance from Optical Depth*)
Exp[-Integrate[Density[Ray[t]], {t, 0, T}]]

(*Transmittance from a position to the origin of tracing*)
Trans[T_] := Exp[-Integrate[Density[Ray[t]], {t, 0, T}]]

(*Integrate emissive and scattering from height fog, assuming density \
is extinction and extinction=scattering, thus albedo=1*)
Integrate[Density[Ray[t]]*EmSc *Trans[t], {t, 0, T}]

=> this leads to EmSc - Transmittance * EmSc
				 EmSc * (1 - Transmittance)
				 EmSc * Coverage

*/