// Copyright Epic Games, Inc. All Rights Reserved.

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

#if BUFFER_TYPE_INDEX == 4 // Float16
	#define BUFFER_TYPE half
	#define READ(X) float(X)
	#define WRITE(X) half(X)
#else
	// BUFFER_TYPE_INDEX == 3 // Float32
	#define BUFFER_TYPE float
	#define READ(X) X
	#define WRITE(X) X
#endif

int Width;
int Height;

int4 OutputChannel_InputChannel_Unused_Unused[MAX_NUM_MAPPED_CHANNELS];

#if INPUT_TYPE == 0 // Texture
Texture2D InputTexture;
#else // INPUT_TYPE == 1 // Buffer
RWBuffer<BUFFER_TYPE> InputBuffer;
#endif

#if OUTPUT_TYPE == 0 // Texture
RWTexture2D<float4> OutputTexture;
#else // OUTPUT_TYPE == 1 // Buffer
RWBuffer<BUFFER_TYPE> OutputBuffer;
#endif

[numthreads(THREAD_GROUP_SIZE, THREAD_GROUP_SIZE, 1)]
void MappedCopy(in const uint3 DispatchThreadID : SV_DispatchThreadID)
{
	if (DispatchThreadID.x >= Width || DispatchThreadID.y >= Height)
	{
		return;
	}

#if INPUT_TYPE == 1 || OUTPUT_TYPE == 1
	const int Idx = DispatchThreadID.y * Width + DispatchThreadID.x;
	const int Offset = Width * Height;
#endif

#if INPUT_TYPE == 0
	const float4 InputColor = InputTexture.Load(int3(DispatchThreadID.x, DispatchThreadID.y, 0));
#endif

	for (int I = 0; I < NUM_MAPPED_CHANNELS; I++)
	{
		const int4 Info = OutputChannel_InputChannel_Unused_Unused[I];
		const int OutputChannel = Info.x;
		const int InputChannel = Info.y;

#if INPUT_TYPE == 0
		const float InputValue = InputColor[InputChannel];
#else
		const float InputValue = InputBuffer[Idx + InputChannel * Offset];
#endif

#if OUTPUT_TYPE == 0
		OutputTexture[DispatchThreadID.xy][OutputChannel] = READ(InputValue);
#else
		OutputBuffer[Idx + OutputChannel * Offset] = WRITE(InputValue);
#endif
	}
}