// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../Hash.ush"

#include "RayTracingCommon.ush"
#include "RayTracingDebugUtils.ush"
#include "RayTracingHitGroupCommon.ush"
#include "/Engine/Shared/RayTracingDebugTypes.h"

RAY_TRACING_ENTRY_ANY_HIT(RayTracingDebugHitStatsAHS,
	FRayTracingDebugPayload, Payload,
	FRayTracingIntersectionAttributes, Attributes)
{
	uint Index = GetInstanceUserData();
	uint OldValue;
	RayTracingDebugHitStatsUniformBuffer.HitStatsOutput[Index].x = Index;
	InterlockedAdd(RayTracingDebugHitStatsUniformBuffer.HitStatsOutput[Index].y, 1, OldValue);
}

RAY_TRACING_ENTRY_CLOSEST_HIT(RayTracingDebugHitStatsCHS,
	FRayTracingDebugPayload, Payload,
	FRayTracingIntersectionAttributes, Attributes)
{
}