// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "BaseCharacterFXEditorMode.h"
#include "DataflowEditorMode.generated.h"

class UDataflowComponent;
class FDataflowPreviewScene;
class SDataflowGraphEditor;

/**
 * The dataflow editor mode is the mode used in the cloth asset editor. It holds most of the inter-tool state.
 * We put things in a mode instead of directly into the asset editor in case we want to someday use the mode
 * in multiple asset editors.
 */
UCLASS(Transient)
class DATAFLOWEDITOR_API UDataflowEditorMode final : public UBaseCharacterFXEditorMode
{
	GENERATED_BODY()

public:

	const static FEditorModeID EM_DataflowEditorModeId;

	UDataflowEditorMode();
	
	/**
	* Gets the tool target requirements for the mode.
	*/
	static const FToolTargetTypeRequirements& GetToolTargetRequirements();

	/**
	* Gets the scene bounding box
	*/
	virtual FBox SceneBoundingBox() const override;

	/** Set the data flow preview scene to store the dynamic meshes generated by the tools */
	void SetDataflowPreviewScene(FDataflowPreviewScene* DataflowPreviewScene) { PreviewScene = DataflowPreviewScene;}

	/** Set the data flow graph editor to create nodes once the tools have ended*/
	void SetDataflowGraphEditor(const TSharedPtr<SDataflowGraphEditor>& DataflowGraphEditor) { GraphEditor = DataflowGraphEditor;}

private:
	// UEdMode
	virtual void CreateToolkit() override;
	virtual void BindCommands() override;
	virtual void Exit() override;
	virtual void Enter() override;
	virtual void ModeTick(float DeltaTime) override;

	// UBaseCharacterFXEditorMode
	virtual void AddToolTargetFactories() override;
	virtual void RegisterTools() override;
	virtual void CreateToolTargets(const TArray<TObjectPtr<UObject>>& AssetsIn) override;
	virtual void InitializeTargets(const TArray<TObjectPtr<UObject>>& AssetsIn) override;

	/** Dataflow preview scene from the toolkit */
	FDataflowPreviewScene* PreviewScene = nullptr;

	/** Correspondence between node types and commands to launch tools */
	TMap<FName, TSharedPtr<const FUICommandInfo>> NodeToolMap;

	/** Graph editor is required to add nodes once some tools are complete */
	TWeakPtr<SDataflowGraphEditor> GraphEditor;
};

