// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "AdvancedPreviewScene.h"

class UDataflowEditorContent;
class USkeletalMeshComponent;
class UDynamicMeshComponent;
class UDataflowComponent;
class UAnimationAsset;
class UAnimSingleNodeInstance;
class UMaterialInterface;
class FAssetEditorModeManager;
class ADataflowActor;
class UMeshElementsVisualizer;
class UInteractiveToolPropertySet;

namespace UE
{
	namespace Geometry
	{
		class FDynamicMesh3;
	}
}

/**
 * Dataflow preview scene
 * @brief the scene is holding all the objects that will be
 * visible and potentially editable within the viewport
 */
class DATAFLOWEDITOR_API FDataflowPreviewScene : public FAdvancedPreviewScene
{
public:

	FDataflowPreviewScene(FPreviewScene::ConstructionValues ConstructionValues, TObjectPtr<UDataflowEditorContent> InEditorContent);
	virtual ~FDataflowPreviewScene();


	//
	// Functional API
	//
public:
	/** Update the state of the scene.*/
	void Update();

	/** Tick */
	// @todo(brice) : depricate
	virtual void Tick(float DeltaTime) override;

	/** Cleam up the scene on exit. */
	void Exit();


	//
	// SkeletalMesh Rendering
	//
public:
	/** Update Skeletal Mesh Component */
	void UpdateSkeletalMeshComponent();

	/** Modify/Get the skeletal mesh component */
	USkeletalMeshComponent* GetSkeletalMeshComponent() { return SkeletalMeshComponent; }
	const USkeletalMeshComponent* GetSkeletalMeshComponent() const { return SkeletalMeshComponent; }




	//
	// ManagedArrayCollectionRendering
	//
public:
	void UpdateDynamicMeshComponents();

	/** Modify/Get the skeletal mesh component */
	TArray<TObjectPtr<UDynamicMeshComponent>> GetDynamicMeshComponents() { return DynamicMeshComponents; }
	const TArray<TObjectPtr<UDynamicMeshComponent>> GetDynamicMeshComponents() const { return DynamicMeshComponents; }

	/** Trigger a Update when the render geometry has changed.*/
	//@todo(brice) : deprecate
	void ReinitializeDynamicMeshComponents();

private:
	/** Reset all the dynamic mesh components */
	void ResetDynamicMeshComponents();
	
	/** Add a dynamic mesh component to the scene */
	TObjectPtr<UDynamicMeshComponent>& AddDynamicMeshComponent(UE::Geometry::FDynamicMesh3&& DynamicMesh, const TArray<UMaterialInterface*>& MaterialSet);




	//
	// Wireframe
	//
public:
	void UpdateWireframeMeshElementsVisualizer();

private:
	void ResetWireframeMeshElementsVisualizer();

	void AddWireframeMeshElementsVisualizer();





	//
	// Visibility
	//
public:
	/** Is there ANYTHING to render */
	bool HasRenderableGeometry();

	/** Build the scene bounding box */
	FBox GetBoundingBox() const;

	/** Build the selected objects bounding box */
	FBox SelectedComponentBounds() const;


	//
	// General Access
	//
public:

	/** Modify/Get the data flow datas */
	TObjectPtr<UDataflowEditorContent> GetDataflowEditorContent() { return EditorContent; }
	const TObjectPtr<UDataflowEditorContent> GetDataflowEditorContent() const { return EditorContent; }

	/** Modify/Get the data flow mode manager */
	TSharedPtr<FAssetEditorModeManager>& GetDataflowModeManager() { return DataflowModeManager; }
	const TSharedPtr<FAssetEditorModeManager>& GetDataflowModeManager() const { return DataflowModeManager; }

	/** Modify/Get the preview anim instance */
	UAnimSingleNodeInstance* GetPreviewAnimInstance() { return PreviewAnimInstance; }
	const UAnimSingleNodeInstance* const GetPreviewAnimInstance() const { return PreviewAnimInstance; }

	/** FGCObject interface */
	virtual void AddReferencedObjects(FReferenceCollector& Collector) override;


private:
	
	/** Check if a primitive component is selected */
	bool IsComponentSelected(const UPrimitiveComponent* InComponent) const;

	/** Data flows assets datas used to build the scene components */
	TObjectPtr<UDataflowEditorContent> EditorContent = nullptr;
	
	/** Dynamic mesh actor */
	TObjectPtr<AActor> DynamicMeshActor = nullptr;

	/** Dynamic mesh components generated by the tools for edit/manipulation*/
	TArray<TObjectPtr<UDynamicMeshComponent>> DynamicMeshComponents;

	/** Skeletal mesh actor */
	TObjectPtr<AActor> SkeletalMeshActor = nullptr;

	/** Skeletal mesh component used for potential binding */
	TObjectPtr<USkeletalMeshComponent> SkeletalMeshComponent = nullptr;

	/** Preview anim instance for the skeletal mesh */
	TObjectPtr<UAnimSingleNodeInstance> PreviewAnimInstance = nullptr;

	/** Mode Manager for selection */
	TSharedPtr<FAssetEditorModeManager> DataflowModeManager;

	// Property objects (visible or not) that get ticked. [ticked]
	TArray<TObjectPtr<UInteractiveToolPropertySet>> PropertyObjectsToTick;

	// Rest space wireframe. They have to get ticked to be able to respond to setting changes. [ticked]
	TObjectPtr<UMeshElementsVisualizer> WireframeDraw = nullptr;

	// Show the wireframe on render. 
	bool bConstructionViewWireframe = true;

	
};

