// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "AdvancedPreviewScene.h"

class UDataflowEditorContent;
class USkeletalMeshComponent;
class UDynamicMeshComponent;
class UDataflowComponent;
class UAnimationAsset;
class UAnimSingleNodeInstance;
class UMaterialInterface;
class FAssetEditorModeManager;
class ADataflowActor;

namespace UE
{
	namespace Geometry
	{
		class FDynamicMesh3;
	}
}

/**
 * Dataflow preview scene
 * @brief the scene is holding all the objects that will be
 * visible and potentially editable within the viewport
 */
class DATAFLOWEDITOR_API FDataflowPreviewScene : public FAdvancedPreviewScene
{
public:

	FDataflowPreviewScene(FPreviewScene::ConstructionValues ConstructionValues, TObjectPtr<UDataflowEditorContent> InEditorContent);
	virtual ~FDataflowPreviewScene();


	void Update();

	/** Update Skeletal Mesh Component */
	void UpdateSkeletalMeshComponent();

	/** FGCObject interface */
	virtual void AddReferencedObjects(FReferenceCollector& Collector) override;

	/** Modify/Get the data flow datas */
	TObjectPtr<UDataflowEditorContent> GetDataflowEditorContent() { return EditorContent; }
	const TObjectPtr<UDataflowEditorContent> GetDataflowEditorContent() const { return EditorContent; }

	/** Modify/Get the data flow mode manager */
	TSharedPtr<FAssetEditorModeManager>& GetDataflowModeManager() { return DataflowModeManager; }
	const TSharedPtr<FAssetEditorModeManager>& GetDataflowModeManager() const { return DataflowModeManager; }
	
	/** Modify/Get the preview anim instance */
	UAnimSingleNodeInstance* GetPreviewAnimInstance() { return PreviewAnimInstance; }
	const UAnimSingleNodeInstance* const GetPreviewAnimInstance() const { return PreviewAnimInstance; }

	/** Modify/Get the skeletal mesh component */
	USkeletalMeshComponent* GetSkeletalMeshComponent() { return SkeletalMeshComponent; }
	const USkeletalMeshComponent* GetSkeletalMeshComponent() const { return SkeletalMeshComponent; }

	/** Reset all the dynamic mesh components */
	void ResetDynamicMeshComponents();
	
	/** Add a dynamic mesh component to the scene */
	TObjectPtr<UDynamicMeshComponent>& AddDynamicMeshComponent(UE::Geometry::FDynamicMesh3&& DynamicMesh, const TArray<UMaterialInterface*>& MaterialSet);

	TArray<TObjectPtr<UDynamicMeshComponent>> GetDynamicMeshComponents() {return DynamicMeshComponents;}

	/** Build the scene bounding box */
	FBox GetBoundingBox() const;
	
private:
	
	/** Check if a primitive component is selected */
	bool IsComponentSelected(const UPrimitiveComponent* InComponent) const;

	/** Data flows assets datas used to build the scene components */
	TObjectPtr<UDataflowEditorContent> EditorContent = nullptr;
	
	/** Dynamic mesh actor */
	TObjectPtr<AActor> DynamicMeshActor = nullptr;

	/** Dynamic mesh components generated by the tools for edit/manipulation*/
	TArray<TObjectPtr<UDynamicMeshComponent>> DynamicMeshComponents;

	/** Skeletal mesh actor */
	TObjectPtr<AActor> SkeletalMeshActor = nullptr;

	/** Skeletal mesh component used for potential binding */
	TObjectPtr<USkeletalMeshComponent> SkeletalMeshComponent = nullptr;

	/** Preview anim instance for the skeletal mesh */
	TObjectPtr<UAnimSingleNodeInstance> PreviewAnimInstance = nullptr;

	/** Mode Manager for selection */
	TSharedPtr<FAssetEditorModeManager> DataflowModeManager;
};

