// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "ISequencerOutlinerColumn.h"
#include "MVVM/ViewModelPtr.h"
#include "Widgets/SCompoundWidget.h"

namespace UE::Sequencer
{

class FEditorViewModel;
class IOutlinerExtension;

/**
* The widget for the inner, darker border of a column widget that handles coloring / sizing
*/
class SOutlinerColumnInnerBorder
	: public SCompoundWidget
{

public:

	SLATE_BEGIN_ARGS(SOutlinerColumnInnerBorder) {}
		SLATE_DEFAULT_SLOT(FArguments, Content)
	SLATE_END_ARGS()

	void Construct(
		const FArguments& InArgs,
		const FCreateOutlinerColumnParams& InParams
	);

private:

	/** Determine whether or not the mouse is directly over this widget for background color */
	void OnMouseEnter(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) override;
	void OnMouseLeave(const FPointerEvent& MouseEvent) override;

	/** Used to determine color if outliner item is directly selected */
	TWeakViewModelPtr<IOutlinerExtension> WeakOutlinerExtension;

	/** Used to determine color if outliner item is being hovered */
	TWeakPtr<FEditorViewModel> WeakEditor;

	/** Is the mouse directly over this widget */
	bool bIsMouseOverInnerBorder = false;
};

/**
* A border widget with appropriate colors to match outliner items in the Sequencer outliner view.
*/
class SOutlinerColumnBorder
	: public SCompoundWidget
{

public:

	SLATE_BEGIN_ARGS(SOutlinerColumnBorder) {}
		SLATE_DEFAULT_SLOT(FArguments, Content)
	SLATE_END_ARGS()

	/**
	* Construct this widget
	*
	* @param	InArgs			The declaration data for this widget
	* @param	InParams		Ouliner Column params for reference to which item is hovered or selected
	* @param	bHasInnerBorder	Should this widget be contained by a 12x12 dark inner border
	*/
	void Construct(
		const FArguments& InArgs, 
		const FCreateOutlinerColumnParams& InParams,
		const bool bHasInnerBorder
	);

private:

	/** Notifies the outliner item that the mouse is within the row for hovered state */
	void OnMouseEnter(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) override;
	void OnMouseLeave(const FPointerEvent& MouseEvent) override;

	/** Handle mouse down events in border so that outliner item events are not generated by the track gutter. */
	virtual FReply OnMouseButtonDown(const FGeometry& MyGeometry, const FPointerEvent& MouseEvent) override;

	/** Used to determine color if outliner item is directly selected */
	TWeakViewModelPtr<IOutlinerExtension> WeakOutlinerExtension;

	/** Used to determine color if outliner item is being hovered */
	TWeakPtr<FEditorViewModel> WeakEditor;
};

} // namespace UE::Sequencer

