// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if !WITH_VERSE_VM
#error In order to use VerseVM, WITH_VERSE_VM must be set
#endif

// IWYU pragma: begin_keep
#include "Containers/Array.h"
#include "Containers/StringConv.h"
#include "VVMBytecode.h"
#include "VVMContext.h"
#include "VVMShape.h"
#include "VVMUTF8String.h"
#include "VVMValue.h"
#include "VVMWriteBarrier.h"
// IWYU pragma: end_keep

// Include autogenerated file.
#include "VVMBytecodesAndCaptures.gen.h"
