// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#if !(WITH_VERSE_VM || defined(__INTELLISENSE__))
#error In order to use VerseVM, WITH_VERSE_VM must be set
#endif

// IWYU pragma: begin_keep
#include "VVMBytecodesAndCaptures.h"
#include "VVMSuspension.h"
// IWYU pragma: end_keep

// Include autogenerated file.
#include "VVMCaptureSwitch.gen.h"
