// Copyright Epic Games, Inc. All Rights Reserved.

#include "NaniteShadeCommon.ush"

#ifdef OVERRIDE_RTWRITEMASKPROCESSING_USH
#include "/Platform/Private/RTWriteMaskLookup.ush"
#endif

#ifndef OPTIMIZE_WRITE_MASK
#define OPTIMIZE_WRITE_MASK 0
#endif

#include "../MortonCode.ush"

uint4 ViewRect;
#if OPTIMIZE_WRITE_MASK
uint ValidWriteMask;
#endif
uint2 DispatchOffsetTL;
uint  ShadingBinCount;
uint  DummyZero;

#define SHADING_BIN_COUNT		(SHADING_BIN_PASS == NANITE_SHADING_BIN_COUNT)
#define SHADING_BIN_RESERVE		(SHADING_BIN_PASS == NANITE_SHADING_BIN_RESERVE)
#define SHADING_BIN_SCATTER		(SHADING_BIN_PASS == NANITE_SHADING_BIN_SCATTER)
#define SHADING_BIN_VALIDATE	(SHADING_BIN_PASS == NANITE_SHADING_BIN_VALIDATE)

#define GATHER4_OPTIMIZATION 0

#if VARIABLE_SHADING_RATE
uint ShadingRateTileSizeBits;
Texture2D<uint> ShadingRateImage;
#endif

#if SHADING_BIN_COUNT || SHADING_BIN_SCATTER
Texture2D<uint> ShadingMask;
SamplerState ShadingMaskSampler;
#endif

// Headers stored at the beginning, followed by bin data starting at ShadingBinDataByteOffset
RWByteAddressBuffer OutShadingBinData;
uint ShadingBinDataByteOffset;

FNaniteShadingBinMeta GetShadingBinMeta(uint ShadingBin)
{
	return OutShadingBinData.Load<FNaniteShadingBinMeta>(ShadingBin * NANITE_SHADING_BIN_META_BYTES);
}

FNaniteMaterialFlags GetShadingBinMaterialFlags(uint ShadingBin)
{
	return UnpackNaniteMaterialFlags(GetShadingBinMeta(ShadingBin).MaterialFlags);
}

#if SHADING_BIN_RESERVE
RWStructuredBuffer<uint> OutShadingBinAllocator;
RWByteAddressBuffer OutShadingBinArgs;
StructuredBuffer<FNaniteShadingBinMeta> ShadingBinMeta;
#endif

#if GATHER_STATS
RWStructuredBuffer<FNaniteShadingBinStats> OutShadingBinStats;
#endif

#if SHADING_BIN_RESERVE || SHADING_BIN_SCATTER
RWStructuredBuffer<FNaniteShadingBinScatterMeta> OutShadingBinScatterMeta;
#endif

#if SHADING_BIN_COUNT || SHADING_BIN_SCATTER

groupshared uint GroupVotedBinAndThread;

groupshared uint GroupFullTileCount_LooseCount;		// 16:16
groupshared uint GroupFullTileOffset;
groupshared uint GroupLooseOffset;

uint CalculateBinCoverage(uint4 ShadingBins, uint ActiveMask, uint BinIndex)
{
	uint MatchMask = 0;
	UNROLL
	for (uint PixelIndex = 0u; PixelIndex < 4u; ++PixelIndex)
	{
		MatchMask |= (ShadingBins[PixelIndex] == BinIndex) ? (1u << PixelIndex) : 0u;
	}
	return ActiveMask & MatchMask;
}

#if OPTIMIZE_WRITE_MASK

#ifndef NUM_EXPORTS
#define NUM_EXPORTS 1
#endif

RWByteAddressBuffer OutCMaskBuffer_0;

#if NUM_EXPORTS > 1
RWByteAddressBuffer OutCMaskBuffer_1;
#endif

#if NUM_EXPORTS > 2
RWByteAddressBuffer OutCMaskBuffer_2;
#endif

#if NUM_EXPORTS > 3
RWByteAddressBuffer OutCMaskBuffer_3;
#endif

#if NUM_EXPORTS > 4
RWByteAddressBuffer OutCMaskBuffer_4;
#endif

#if NUM_EXPORTS > 5
RWByteAddressBuffer OutCMaskBuffer_5;
#endif

#if NUM_EXPORTS > 6
RWByteAddressBuffer OutCMaskBuffer_6;
#endif

#if NUM_EXPORTS > 7
RWByteAddressBuffer OutCMaskBuffer_7;
#endif

#endif

uint PackShadingPixel(uint2 TopLeft, uint2 VRSShift, uint WriteMask)
{
	return (WriteMask << 28) | (VRSShift.y << 27) | (VRSShift.x << 26) | (TopLeft.y << 13) | TopLeft.x;
}

uint2 PackShadingQuad(uint2 TopLeft, uint2 VRSShift, uint WriteMask)
{
	uint2 Packed;
	Packed.x = (VRSShift.y << 29) | (VRSShift.x << 28) | (TopLeft.y << 14) | TopLeft.x;
	Packed.y = WriteMask;
	return Packed;
}

uint SampleCountQuadVRS(uint ShadingRate, uint BinCoverage)
{
	// TODO: Optimize by folding the mask and always doing countbits instead?
	if (ShadingRate == D3D12_SHADING_RATE_2X2)
	{
		return (BinCoverage != 0);
	}
	else if (ShadingRate == D3D12_SHADING_RATE_2X1)
	{
		return ((BinCoverage & 0x3) != 0) + ((BinCoverage & 0xC) != 0);
	}
	else if (ShadingRate == D3D12_SHADING_RATE_1X2)
	{
		return ((BinCoverage & 0x5) != 0) + ((BinCoverage & 0xA) != 0);
	}
	else
	{
		return countbits(BinCoverage);
	}
}

uint ConvertQuadCoverageMaskToWriteMask(uint Coverage)
{
	uint WriteMask = Coverage;					// 0000 0000 0000 WZYX
	WriteMask = WriteMask | (WriteMask << 3);	// 0000 0000 0WZY ?ZYX
	WriteMask = WriteMask | (WriteMask << 6);	// 000W ZY?Z Y?ZY ?ZYX
	return WriteMask & 0x1111u;					// 000W 000Z 000Y 000X
}

void BinShadingQuad(uint2 Coord, uint ThreadIndex)
{
	const uint2 QuadTLCoord = uint2(Coord << 1u) + DispatchOffsetTL;

#if GATHER4_OPTIMIZATION
	uint4 QuadShadingMask = ShadingMask.GatherRed(ShadingMaskSampler, float2(QuadTLCoord + 0.5f) / float2(ViewRect.z, ViewRect.w)).wzxy;
#else
	uint4 QuadShadingMask;
	QuadShadingMask.x = ShadingMask[QuadTLCoord + uint2(0, 0)];
	QuadShadingMask.y = ShadingMask[QuadTLCoord + uint2(1, 0)];
	QuadShadingMask.z = ShadingMask[QuadTLCoord + uint2(0, 1)];
	QuadShadingMask.w = ShadingMask[QuadTLCoord + uint2(1, 1)];
#endif

	FShadingMask ShadingMaskTL = UnpackShadingMask(QuadShadingMask.x);
	FShadingMask ShadingMaskTR = UnpackShadingMask(QuadShadingMask.y);
	FShadingMask ShadingMaskBL = UnpackShadingMask(QuadShadingMask.z);
	FShadingMask ShadingMaskBR = UnpackShadingMask(QuadShadingMask.w);

	const bool4 ValidMask = bool4(
		QuadTLCoord.x		>= ViewRect.x && QuadTLCoord.x		< ViewRect.z,
		QuadTLCoord.y		>= ViewRect.y && QuadTLCoord.y		< ViewRect.w,
		QuadTLCoord.x + 1u	>= ViewRect.x && QuadTLCoord.x + 1u < ViewRect.z,
		QuadTLCoord.y + 1u	>= ViewRect.y && QuadTLCoord.y + 1u < ViewRect.w
	);

	bool4 ValidPixels = bool4(
		all(ValidMask.xy) && ShadingMaskTL.bIsNanitePixel,
		all(ValidMask.zy) && ShadingMaskTR.bIsNanitePixel,
		all(ValidMask.xw) && ShadingMaskBL.bIsNanitePixel,
		all(ValidMask.zw) && ShadingMaskBR.bIsNanitePixel
	);

	uint ActiveMask = PackQuadMask(ValidPixels);

	if (!WaveActiveAnyTrue((ActiveMask | DummyZero) != 0))
	{
		// Quad is entirely non-Nanite or out of bounds.
		return;
	}

	uint4 ShadingBins = uint4(
		ShadingMaskTL.ShadingBin,
		ShadingMaskTR.ShadingBin,
		ShadingMaskBL.ShadingBin,
		ShadingMaskBR.ShadingBin
	);

	const uint WaveLaneIndex = WaveGetLaneIndex();
	const uint BlockThreadIndex = ThreadIndex & 3u;
	const uint BlockFirstThread = ThreadIndex & 28u;

#if VARIABLE_SHADING_RATE
	const uint ShadingRate = ShadingRateImage[QuadTLCoord.xy >> ShadingRateTileSizeBits] & 0xFu;


#if 0
	// Sketch for <= 4x4 VRS tile size support
	// Vote across 2x2 quad blocks (4x4 pixels) to pick a shared mode that is at least as high resolution in both x and y.
	// TODO: This shouldn't affect pixel binning, so separate ShadingRate into two PixelShadingRate and QuadShadingRate first.
	const uint2 FullResXBallot = WaveBallot(ShadingRate == D3D12_SHADING_RATE_1X1 || ShadingRate == D3D12_SHADING_RATE_1X2);
	const uint2 FullResYBallot = WaveBallot(ShadingRate == D3D12_SHADING_RATE_1X1 || ShadingRate == D3D12_SHADING_RATE_2X1);
	const uint BlockFullResXMask = BitFieldExtractU32(WaveLaneIndex >= 32 ? FullResXBallot.y : FullResXBallot.x, 4, BlockFirstThread);
	const uint BlockFullResYMask = BitFieldExtractU32(WaveLaneIndex >= 32 ? FullResYBallot.y : FullResYBallot.x, 4, BlockFirstThread);
	ShadingRate = BlockFullResXMask ?	(BlockFullResYMask ? D3D12_SHADING_RATE_1X1 : D3D12_SHADING_RATE_1X2) :
										(BlockFullResYMask ? D3D12_SHADING_RATE_2X1 : D3D12_SHADING_RATE_2X2);
#endif

	const bool bWaveVRS = WaveActiveAnyTrue(ShadingRate != D3D12_SHADING_RATE_1X1);
#else
	const uint ShadingRate = D3D12_SHADING_RATE_1X1;
	const bool bWaveVRS = false;
#endif

	const uint2 VRSShift = uint2(	ShadingRate == D3D12_SHADING_RATE_2X1 || ShadingRate == D3D12_SHADING_RATE_2X2,
									ShadingRate == D3D12_SHADING_RATE_1X2 || ShadingRate == D3D12_SHADING_RATE_2X2);

#if SHADING_BIN_COUNT
	while (WaveActiveAnyTrue(ActiveMask != 0u))
	{
		if (ActiveMask != 0u)
		{
			// Determine current shading bin for all quad lanes to classify.
			const uint VotedBin = WaveReadLaneFirst(ShadingBins[firstbitlow(ActiveMask)]);

			const uint BinCoverage = CalculateBinCoverage(ShadingBins, ActiveMask, VotedBin);
			ActiveMask &= ~BinCoverage;
			
			if (BinCoverage != 0u)
			{
				const FNaniteMaterialFlags MaterialFlags = GetShadingBinMaterialFlags(VotedBin);

				BRANCH
				if (MaterialFlags.bNoDerivativeOps)
				{
					const uint PixelCount = WaveActiveSum(SampleCountQuadVRS(ShadingRate, BinCoverage));
					if (WaveIsFirstLane())
					{
						OutShadingBinData.InterlockedAdd((VotedBin * NANITE_SHADING_BIN_META_BYTES) + NANITE_SHADING_BIN_META_ELEMENT_COUNT_OFFSET, PixelCount);
					}
				}
				else
				{
					bool bWriteQuad = (BinCoverage != 0u);

					BRANCH
					if (bWaveVRS)
					{
						const uint2 Ballot = WaveBallot(true);
						const uint Mask2x2 = BitFieldExtractU32(WaveLaneIndex >= 32 ? Ballot.y : Ballot.x, 4, BlockFirstThread);

						const uint TestMask =	(ShadingRate == D3D12_SHADING_RATE_2X2) ? 0xF :
												(ShadingRate == D3D12_SHADING_RATE_2X1) ? ((BlockThreadIndex & 2) ? 0xC : 0x3) :
												(ShadingRate == D3D12_SHADING_RATE_1X2) ? ((BlockThreadIndex & 1) ? 0xA : 0x5) :
												(1u << BlockThreadIndex);

						bWriteQuad = (firstbitlow(Mask2x2 & TestMask) == BlockThreadIndex);
					}
					
					if (bWriteQuad)
					{
						const uint AddCount = WaveActiveCountBits(true);
						if (WaveIsFirstLane())
						{
							OutShadingBinData.InterlockedAdd((VotedBin * NANITE_SHADING_BIN_META_BYTES) + NANITE_SHADING_BIN_META_ELEMENT_COUNT_OFFSET, AddCount);
						}
					}
				}
			}
		}
	}
#elif SHADING_BIN_SCATTER

#if GATHER_STATS
	WaveInterlockedAdd(OutShadingBinStats[0].TotalNanitePixels, countbits(ActiveMask));
#endif

	const bool bHalfX = (VRSShift.x > 0);
	const bool bHalfY = (VRSShift.y > 0);
	const bool bHalfXY = (ShadingRate == D3D12_SHADING_RATE_2X2);

	uint QuadWriteMasks;			// 4:4:4:4 write mask. A 4-bits mask per pixel of the current quad. Each mask indicating where in the quad to write that pixel.
	uint CoarsePixelWriteMasks;		// Same as above, but masks are relative to the top-left of the coarse pixel, instead of the quad.
	BRANCH
	if(bWaveVRS)
	{
		// Mask invalid shading bins with distinct invalid values, so invalid bins don't compare equal to each other.
		ShadingBins = uint4(
			ValidPixels.x ? ShadingBins.x : 0xFFFFFFFFu,
			ValidPixels.y ? ShadingBins.y : 0xFFFFFFFEu,
			ValidPixels.z ? ShadingBins.z : 0xFFFFFFFDu,
			ValidPixels.w ? ShadingBins.w : 0xFFFFFFFCu
		);

		// Mark own pixel in write mask
		QuadWriteMasks = (ActiveMask * 0x1111u) & 0x8421;	// WZYX -> W000 0Z00 00Y0 000X

		// Mask out any pixel that doesn't need to be evaluated at the current shading rate
		// and add it to the write mask of the pixel that should scatter write it instead.
		if (bHalfX	&& ShadingBins.x == ShadingBins.y) { ShadingBins.y = 0xFFFFFFFEu; ActiveMask &= ~2u; QuadWriteMasks |= 0x0002; }
		if (bHalfY	&& ShadingBins.x == ShadingBins.z) { ShadingBins.z = 0xFFFFFFFDu; ActiveMask &= ~4u; QuadWriteMasks |= 0x0004; }
		if (bHalfXY && ShadingBins.x == ShadingBins.w) { ShadingBins.w = 0xFFFFFFFCu; ActiveMask &= ~8u; QuadWriteMasks |= 0x0008; }

		if (bHalfXY	&& ShadingBins.y == ShadingBins.z) { ShadingBins.z = 0xFFFFFFFDu; ActiveMask &= ~4u; QuadWriteMasks |= 0x0040; }
		if (bHalfY	&& ShadingBins.y == ShadingBins.w) { ShadingBins.w = 0xFFFFFFFCu; ActiveMask &= ~8u; QuadWriteMasks |= 0x0080; }

		if (bHalfX	&& ShadingBins.z == ShadingBins.w) { ShadingBins.w = 0xFFFFFFFCu; ActiveMask &= ~8u; QuadWriteMasks |= 0x0800; }
		
		// Adjust write masks to be local to the coarse pixel instead of being relative to top-left of the quad
		CoarsePixelWriteMasks = QuadWriteMasks;
		CoarsePixelWriteMasks = !bHalfX ? BitFieldInsertU32(0xF0F0, CoarsePixelWriteMasks >> 1, CoarsePixelWriteMasks) : CoarsePixelWriteMasks;
		CoarsePixelWriteMasks = !bHalfY ? BitFieldInsertU32(0xFF00, CoarsePixelWriteMasks >> 2, CoarsePixelWriteMasks) : CoarsePixelWriteMasks;
	}
	else
	{
		QuadWriteMasks = CoarsePixelWriteMasks = ConvertQuadCoverageMaskToWriteMask(ActiveMask);
	}

	const uint ThreadsPerShadingTile = COMPUTE_MATERIAL_GROUP_SIZE / 4;
	const uint ShadingTileFirstThread = WaveLaneIndex & ~(ThreadsPerShadingTile - 1u) & 31u;

	while (WaveActiveAnyTrue(ActiveMask != 0u))
	{
		uint VotedBin = ActiveMask ? ShadingBins[firstbitlow(ActiveMask)] : 0xFFFFFFFF;

		if (WaveIsFirstLane())
		{
			GroupVotedBinAndThread = 0xFFFFFFFFu;
			GroupFullTileCount_LooseCount = 0u;
		}
		GroupMemoryBarrierWithGroupSync();
		const uint VotedBinAndThread = (VotedBin << 10) | ThreadIndex; // But a live thread that votes for the bin in the low bits
		WaveInterlockedMin(GroupVotedBinAndThread, VotedBinAndThread);
		GroupMemoryBarrierWithGroupSync();
		VotedBin = GroupVotedBinAndThread >> 10;
		const uint GroupUpdateThread = GroupVotedBinAndThread & 1023; // The thread from the low bits gets to do the group update

		const uint BinCoverage = CalculateBinCoverage(ShadingBins, ActiveMask, VotedBin);
		ActiveMask &= ~BinCoverage;

		const uint PixelCount = countbits(BinCoverage);
		bool bFullTile = false;
		
		BRANCH
		if(WaveGetLaneCount() >= ThreadsPerShadingTile)
		{
			const uint2 Ballot = WaveBallot(PixelCount == 4);
			const uint ShadingTileMask = BitFieldExtractU32(WaveLaneIndex >= 32 ? Ballot.y : Ballot.x, ThreadsPerShadingTile, ShadingTileFirstThread);
			bFullTile = (countbits(ShadingTileMask) == ThreadsPerShadingTile);
		}

		const FNaniteMaterialFlags MaterialFlags = GetShadingBinMaterialFlags(VotedBin);
		
		BRANCH
		if (MaterialFlags.bNoDerivativeOps)
		{
			const bool bWriteFullTile	= ( bFullTile && (PixelCount != 0u));
			const bool bWriteLoose		= (!bFullTile && (PixelCount != 0u));

			const uint QuadFullTileCount	= bWriteFullTile ? 4u : 0u;
			const uint QuadLooseCount		= bWriteLoose ? PixelCount : 0u;

			const uint QuadFullTileCount_LooseCount = (QuadLooseCount << 16) | QuadFullTileCount;
			const uint WaveFullTileCount_LooseCount = WaveActiveSum(QuadFullTileCount_LooseCount);

			uint WaveFullTileOffset_LooseOffset = 0;

			BRANCH
			if (WaveIsFirstLane())
			{
				InterlockedAdd(GroupFullTileCount_LooseCount, WaveFullTileCount_LooseCount,	WaveFullTileOffset_LooseOffset);
			}
			GroupMemoryBarrierWithGroupSync();

			BRANCH
			if (ThreadIndex == GroupUpdateThread)
			{
				const uint TotalFullTileCount = GroupFullTileCount_LooseCount & 0xFFFF;
				const uint TotalLooseCount = GroupFullTileCount_LooseCount >> 16;
				OutShadingBinData.InterlockedAdd((VotedBin * NANITE_SHADING_BIN_META_BYTES) + NANITE_SHADING_BIN_META_WRITTEN_COUNT_OFFSET, TotalFullTileCount + TotalLooseCount);
				InterlockedAdd(OutShadingBinScatterMeta[VotedBin].FullTileElementCount, TotalFullTileCount,	GroupFullTileOffset);
				InterlockedAdd(OutShadingBinScatterMeta[VotedBin].LooseElementCount,	TotalLooseCount,	GroupLooseOffset);
			}
			GroupMemoryBarrierWithGroupSync();

			const uint WavePrefixFullTileCount_LooseCount = WavePrefixSum(QuadFullTileCount_LooseCount);
			const uint FullTileDataOffset	= GroupFullTileOffset	+ (WaveReadLaneFirst(WaveFullTileOffset_LooseOffset) & 0xFFFFu)	+ (WavePrefixFullTileCount_LooseCount & 0xFFFFu);
			const uint LooseDataOffset		= GroupLooseOffset		+ (WaveReadLaneFirst(WaveFullTileOffset_LooseOffset) >> 16)		+ (WavePrefixFullTileCount_LooseCount >> 16);

			uint DataWriteOffset;
			if (bFullTile)
			{ 
				DataWriteOffset = ShadingBinDataByteOffset + (GetShadingBinMeta(VotedBin).RangeStart + FullTileDataOffset) * 4u;
			}
			else
			{
				DataWriteOffset = ShadingBinDataByteOffset + (OutShadingBinScatterMeta[VotedBin].RangeEnd - LooseDataOffset - countbits(BinCoverage)) * 4u;
			}
			
			GroupMemoryBarrierWithGroupSync();

			uint TempMask = BinCoverage;
			UNROLL
			for (uint i = 0; i < 4; i++)
			{
				if (TempMask == 0)
					break;

				const uint PixelIndex = firstbitlow(TempMask);
				TempMask &= TempMask - 1u;

				const uint2 PixelCoord = QuadTLCoord + uint2(PixelIndex & 1u, PixelIndex >> 1);
				const uint2 CoarsePixelTL = (PixelCoord >> VRSShift) << VRSShift;

				const uint WriteMask = BitFieldExtractU32(CoarsePixelWriteMasks, 4, PixelIndex * 4);
				OutShadingBinData.Store(DataWriteOffset, PackShadingPixel(CoarsePixelTL, VRSShift, WriteMask));
				DataWriteOffset += 4;
			}
		}
		else
		{
			uint OutputWriteMask = ConvertQuadCoverageMaskToWriteMask(BinCoverage);

			BRANCH
			if(bWaveVRS && ShadingRate != D3D12_SHADING_RATE_1X1)
			{
				// Combine the individual active write masks into a single quad mask for the current bin
				uint QuadMask = QuadWriteMasks & (OutputWriteMask * 0xFu);

				// Merge down to single 4-bit mask
				QuadMask |= QuadMask >> 8;
				QuadMask |= QuadMask >> 4;
				QuadMask &= 0xF;

				// Assemble Quad masks into a 2x2 quad (4x4 pixel) mask
				const uint BlockShift = (BlockThreadIndex * 4);
				uint BlockMask = QuadMask << BlockShift;
				BlockMask |= QuadReadAcrossX(BlockMask);
				BlockMask |= QuadReadAcrossY(BlockMask);

				const uint ShiftedBlockMask = BlockMask >> BlockShift;
				
				// Calculate write masks for the individual lanes from the block mask
				if (ShadingRate == D3D12_SHADING_RATE_2X2)
				{
					OutputWriteMask = BlockThreadIndex ? 0 : BlockMask;
				}
				else if (ShadingRate == D3D12_SHADING_RATE_2X1)
				{
					OutputWriteMask = (BlockThreadIndex & 1) ? 0u : ShiftedBlockMask;
					OutputWriteMask = (OutputWriteMask & 0x0033u) | ((OutputWriteMask << 6) & 0x3300u);
				}
				else if (ShadingRate == D3D12_SHADING_RATE_1X2)
				{
					OutputWriteMask = (BlockThreadIndex & 2) ? 0u : ShiftedBlockMask;
					OutputWriteMask = (OutputWriteMask & 0x0505u) | ((OutputWriteMask << 3) & 0x5050u);
				}
			}

			const bool bWriteQuad		= (OutputWriteMask != 0u);
			const bool bWriteFullTile	= (bFullTile && bWriteQuad);
			const bool bWriteLoose		= (!bFullTile && bWriteQuad);

			const uint WaveFullTileCount_LooseCount = WaveActiveCountBits(bWriteFullTile) | (WaveActiveCountBits(bWriteLoose) << 16);

			uint WaveFullTileOffset_LooseOffset = 0;

			BRANCH
			if (WaveIsFirstLane())
			{
				InterlockedAdd(GroupFullTileCount_LooseCount, WaveFullTileCount_LooseCount, WaveFullTileOffset_LooseOffset);
			}
			GroupMemoryBarrierWithGroupSync();

			BRANCH
			if (ThreadIndex == GroupUpdateThread)
			{
				const uint TotalFullTileCount = GroupFullTileCount_LooseCount & 0xFFFF;
				const uint TotalLooseCount = GroupFullTileCount_LooseCount >> 16;

				OutShadingBinData.InterlockedAdd((VotedBin * NANITE_SHADING_BIN_META_BYTES) + NANITE_SHADING_BIN_META_WRITTEN_COUNT_OFFSET, TotalFullTileCount + TotalLooseCount);
				InterlockedAdd(OutShadingBinScatterMeta[VotedBin].FullTileElementCount, TotalFullTileCount,	GroupFullTileOffset);
				InterlockedAdd(OutShadingBinScatterMeta[VotedBin].LooseElementCount,	TotalLooseCount,	GroupLooseOffset);
			}
			GroupMemoryBarrierWithGroupSync();

			const uint FullTileDataOffset	= GroupFullTileOffset	+ (WaveReadLaneFirst(WaveFullTileOffset_LooseOffset) & 0xFFFFu) + WavePrefixCountBits(bWriteFullTile);
			const uint LooseDataOffset		= GroupLooseOffset		+ (WaveReadLaneFirst(WaveFullTileOffset_LooseOffset) >> 16)		+ WavePrefixCountBits(bWriteLoose);
			GroupMemoryBarrierWithGroupSync();

			if (bWriteQuad)
			{
				const uint RangeStart = GetShadingBinMeta(VotedBin).RangeStart;

				const uint2 PackedShadingQuad = PackShadingQuad(QuadTLCoord, VRSShift, OutputWriteMask);
				BRANCH
				if (bWriteFullTile)
				{
					OutShadingBinData.Store2(ShadingBinDataByteOffset + (RangeStart * 4 + FullTileDataOffset * 8), PackedShadingQuad);
				}
				else
				{
					const uint BaseAddress = OutShadingBinScatterMeta[VotedBin].RangeEnd;
					OutShadingBinData.Store2(ShadingBinDataByteOffset + (BaseAddress * 4u - LooseDataOffset * 8u - 8u), PackedShadingQuad);
				}

#if GATHER_STATS
				const uint NumHelpers = 4	- ((OutputWriteMask & 0x000Fu) != 0u)
											- ((OutputWriteMask & 0x00F0u) != 0u)
											- ((OutputWriteMask & 0x0F00u) != 0u)
											- ((OutputWriteMask & 0xF000u) != 0u);
				WaveInterlockedAdd(OutShadingBinStats[0].TotalHelperCount, NumHelpers);
#endif
			}
		}
	}
#endif
#if OPTIMIZE_WRITE_MASK
	RWByteAddressBuffer CMaskExports[] = 
	{
		OutCMaskBuffer_0,
	#if NUM_EXPORTS > 1
		OutCMaskBuffer_1,
	#endif
	#if NUM_EXPORTS > 2
		OutCMaskBuffer_2,
	#endif
	#if NUM_EXPORTS > 3
		OutCMaskBuffer_3,
	#endif
	#if NUM_EXPORTS > 4
		OutCMaskBuffer_4,
	#endif
	#if NUM_EXPORTS > 5
		OutCMaskBuffer_5,
	#endif
	#if NUM_EXPORTS > 6
		OutCMaskBuffer_6,
	#endif
	#if NUM_EXPORTS > 7
		OutCMaskBuffer_7
	#endif
	};

	// Fetch per pixel shading write masks and remove mask bits if they are not valid writes (i.e. no cmask for that export)
	const uint WriteMaskTL = select(ValidPixels.x, BitFieldExtractU32(GetShadingBinMeta(ShadingMaskTL.ShadingBin).MaterialFlags, 8u, 24u), 0x0u);
	const uint WriteMaskTR = select(ValidPixels.y, BitFieldExtractU32(GetShadingBinMeta(ShadingMaskTR.ShadingBin).MaterialFlags, 8u, 24u), 0x0u);
	const uint WriteMaskBL = select(ValidPixels.z, BitFieldExtractU32(GetShadingBinMeta(ShadingMaskBL.ShadingBin).MaterialFlags, 8u, 24u), 0x0u);
	const uint WriteMaskBR = select(ValidPixels.w, BitFieldExtractU32(GetShadingBinMeta(ShadingMaskBR.ShadingBin).MaterialFlags, 8u, 24u), 0x0u);

	// NOTE: It should be only necessary to test the TL pixel's cmask index/shift, since a quad shouldn't be able to span multiple nibbles.
	uint CMaskIndex;
	uint CMaskShift;
	ComputeCMaskIndexAndShift(QuadTLCoord / 8u, CMaskIndex, CMaskShift);

	const uint CMaskTileBitIndex = (ThreadIndex >> 2) & 3u;		// 4 threads cover 4x4 CMask tile. Assumes CMask tile order is the same as Morton order: TL, TR, BL, BR
	const uint CMaskBitIndex = (CMaskIndex & 0x3) * 8u + CMaskShift + CMaskTileBitIndex;
	const uint CMaskValue4x4 = 1u << CMaskBitIndex;

	// Calculate 4x4 pixel write masks. Set bit means all 4x4 pixels are written
	const uint WriteMaskQuad = WriteMaskTL & WriteMaskTR & WriteMaskBL & WriteMaskBR;
	uint WriteMask4x4 = WriteMaskQuad;
	WriteMask4x4 &= QuadReadAcrossX(WriteMask4x4);
	WriteMask4x4 &= QuadReadAcrossY(WriteMask4x4);

	uint Mask = ValidWriteMask;

	UNROLL
	for (uint Export = 0; Export < NUM_EXPORTS; ++Export)
	{
		// Remaps from compacted (valid) targets to sparse write mask indices
		// i.e. Export0 can be MRT1 which is represented as bit index 1 in ValidWriteMask
		//   - 0 is MRT0/SceneColor which isn't valid to export
		uint MaskIndex = firstbitlow(Mask);
		Mask &= Mask - 1u;

		const bool bWriteCMask4x4 = BitFieldExtractU32(WriteMask4x4, 1, MaskIndex) != 0;

		uint CMaskValue = bWriteCMask4x4 ? CMaskValue4x4 : 0u;
#if COMPILER_SUPPORTS_WAVE_SWIZZLE_GCN
		// Combine CMask bits to form full 8x8 CMask tile to minimize number of atomics
		CMaskValue |= WaveLaneSwizzleGCN(CMaskValue, 0x1F, 0x00, 0x04);
		CMaskValue |= WaveLaneSwizzleGCN(CMaskValue, 0x1F, 0x00, 0x08);
		if (CMaskValue != 0 && (ThreadIndex & 15) == 0)
#else
		if (CMaskValue != 0 && (ThreadIndex & 3) == 0)
#endif
		{
			CMaskExports[Export].InterlockedOr(CMaskIndex, CMaskValue);
		}
	}
#endif // OPTIMIZE_WRITE_MASK
}

uint2 LinearToSwizzled(uint LinearIndex)
{
	// Just like pixel shaders, compute 2x2 CS quads from thread index so we can leverage the 4 lane cross bar.
	// [0 1][2 3] -> [0 1][4 5]
	// [4 5][6 7] -> [2 3][6 7]
	const uint SwizzleX = BitFieldInsertU32(BitFieldMaskU32(1u, 0u), LinearIndex, BitFieldExtractU32(LinearIndex, 3u, 2u));
	const uint SwizzleY = BitFieldInsertU32(BitFieldMaskU32(2u, 0u), BitFieldExtractU32(LinearIndex, 2u, 1u), BitFieldExtractU32(LinearIndex, 3u, 3u));
	return uint2(SwizzleX, SwizzleY);
}

#if BINNING_TECHNIQUE == 1

// Binning at 32x32 macro tile granularity
[numthreads(32, 32, 1)]
void ShadingBinBuildCS(uint ThreadIndex : SV_GroupIndex, uint2 GroupId : SV_GroupID)
{
	const uint2 MacroTileDim = uint2(32u, 32u);

	// Compute the starting 2x2 quad location of the 32x32 macro tile
	const uint2 MacroTileStart = GroupId * MacroTileDim;

#if 1
	uint2 Coord = MacroTileStart + MortonDecode(ThreadIndex);
#else
	const uint2 MicroTileDim = uint2( 8u,  8u);

	// Compute linear index of 8x8 micro tile
	// 0...1023 -> 0...15
	const uint MicroTileIndex = ThreadIndex >> 6u;

	// Compute index within 8x8 micro tile
	const uint TileQuad = ThreadIndex - (MicroTileIndex * MicroTileDim.x * MicroTileDim.y);

	const uint2 MicroTileStart = LinearToSwizzled(MicroTileIndex) * MicroTileDim;
	uint2 Coord = MacroTileStart + MicroTileStart + LinearToSwizzled(TileQuad);
#endif
	BinShadingQuad(Coord, ThreadIndex);
}

#else

[numthreads(8, 8, 1)]
void ShadingBinBuildCS(uint ThreadIndex : SV_GroupIndex, uint2 GroupId : SV_GroupID)
{
	uint2 Coord = GroupId.xy * 8u;

#if 1
	Coord += LinearToSwizzled(ThreadIndex);
#else
	Coord += Unflatten2D(ThreadIndex, uint2(8u, 8u));
#endif

	BinShadingQuad(Coord, ThreadIndex);
}

#endif // BINNING_TECHNIQUE

#elif SHADING_BIN_RESERVE

[numthreads(64, 1, 1)]
void ShadingBinReserveCS(uint ShadingBin : SV_DispatchThreadID)
{
	if (ShadingBin >= ShadingBinCount)
		return;

	const FNaniteMaterialFlags MaterialFlags = GetShadingBinMaterialFlags(ShadingBin);

	uint BinPixelCount;
	if (MaterialFlags.bNoDerivativeOps)
	{
		BinPixelCount = GetShadingBinMeta(ShadingBin).ElementCount;

		if (BinPixelCount > 0)
		{
			uint RangeStart;
			InterlockedAdd(OutShadingBinAllocator[0], BinPixelCount, RangeStart);
			OutShadingBinData.Store((ShadingBin * NANITE_SHADING_BIN_META_BYTES) + NANITE_SHADING_BIN_META_RANGE_START_OFFSET, RangeStart);

			OutShadingBinScatterMeta[ShadingBin].RangeEnd = RangeStart + BinPixelCount;
			OutShadingBinScatterMeta[ShadingBin].LooseElementCount = 0;
			OutShadingBinScatterMeta[ShadingBin].FullTileElementCount = 0;
		}

#if GATHER_STATS
		const uint WaveBinPixelCount = WaveActiveSum(BinPixelCount);
		if (WaveIsFirstLane())
		{
			InterlockedAdd(OutShadingBinStats[0].TotalShadedPixels, WaveBinPixelCount);
		}
#endif
	}
	else
	{
		const uint BinQuadCount = GetShadingBinMeta(ShadingBin).ElementCount;

		if (BinQuadCount > 0)
		{
			uint RangeStart;
			InterlockedAdd(OutShadingBinAllocator[0], BinQuadCount * 2, RangeStart);
			OutShadingBinData.Store((ShadingBin * NANITE_SHADING_BIN_META_BYTES) + NANITE_SHADING_BIN_META_RANGE_START_OFFSET, RangeStart);

			OutShadingBinScatterMeta[ShadingBin].RangeEnd = RangeStart + BinQuadCount * 2;
			OutShadingBinScatterMeta[ShadingBin].LooseElementCount = 0;
			OutShadingBinScatterMeta[ShadingBin].FullTileElementCount = 0;
		}

		const uint ArgsOffset = ShadingBin * 4u;

		// Includes helper lanes
		BinPixelCount = BinQuadCount * 4u;

#if GATHER_STATS
		const uint WaveBinQuadCount = WaveActiveSum(BinQuadCount);
		if (WaveIsFirstLane())
		{
			InterlockedAdd(OutShadingBinStats[0].TotalShadedQuads, WaveBinQuadCount);
		}
#endif
	}
	
	uint4 ShadingBinArgs;
	ShadingBinArgs.x = DivideAndRoundUp(BinPixelCount, COMPUTE_MATERIAL_GROUP_SIZE);	// ThreadGroupCountX
	ShadingBinArgs.y = 1u;										// ThreadGroupCountY
	ShadingBinArgs.z = 1u;										// ThreadGroupCountZ
	ShadingBinArgs.w = 0u;										// Reserved / Unused
	OutShadingBinArgs.Store4(ShadingBin * 16u, ShadingBinArgs);
}
#elif SHADING_BIN_VALIDATE

[numthreads(64, 1, 1)]
void ShadingBinValidateCS(uint ShadingBin : SV_DispatchThreadID)
{
	if (ShadingBin >= ShadingBinCount)
		return;

	const FNaniteShadingBinMeta ShadingBinMeta = GetShadingBinMeta(ShadingBin);
	if (ShadingBinMeta.ElementCount != ShadingBinMeta.WrittenCount)
	{
		PLATFORM_BREAK();
	}
}

#endif
