// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#ifndef WITH_WORLDMETRICS_DEBUG
#define WITH_WORLDMETRICS_DEBUG (!UE_BUILD_SHIPPING && ALLOW_CONSOLE)
#endif	// WITH_WORLDMETRICS_DEBUG

#if WITH_WORLDMETRICS_DEBUG
#define WORLDMETRICS_DEBUG_ONLY(...) __VA_ARGS__
#else
#define WORLDMETRICS_DEBUG_ONLY(...)
#endif	// WITH_WORLDMETRICS_DEBUG
