[Audio]
AudioDeviceModuleName=XAudio2
; Defines a platform-specific volume headroom (in dB) for audio to provide better platform consistency with respect to volume levels.
PlatformHeadroomDB=0

[TextureStreaming]
; PoolSizeVRAMPercentage is how much percentage of GPU Dedicated VRAM should be used as a TexturePool cache for streaming textures (0 - unlimited streaming)
PoolSizeVRAMPercentage=70

[Engine.DeviceConfiguration]
ConfigClass=/Engine/DeviceProfiles/SetDeviceProfileWindows.SetDeviceProfileWindows_C

[SystemSettings]
r.setres=1280x720

[AppxManifest]
?xml.version=1.0
?xml.encoding=utf-8
Package.xmlns=http://schemas.microsoft.com/appx/manifest/foundation/windows10
Package.xmlns:mp=http://schemas.microsoft.com/appx/2014/phone/manifest
Package.xmlns:uap=http://schemas.microsoft.com/appx/manifest/uap/windows10
Package.Identity.Name=%AlphaNumericDot:/Script/EngineSettings.GeneralProjectSettings:ProjectName%
Package.Identity.Publisher=%DefaultValue:/Script/EngineSettings.GeneralProjectSettings:CompanyDistinguishedName:String:CN=No Publisher, O=No Publisher%
Package.Identity.Version=%DefaultValue:/Script/EngineSettings.GeneralProjectSettings:ProjectVersion:String:1.0.0.0%
Package.Identity.ProcessorArchitecture=%ExeFlavor%
Package.Dependencies.TargetDeviceFamily[0].Name=Windows.Universal
Package.Dependencies.TargetDeviceFamily[0].MinVersion=%DefaultValue:/Script/UWPTargetPlatform.UWPTargetSettings:MinimumPlatformVersion:String:10.0.10240.0%
Package.Dependencies.TargetDeviceFamily[0].MaxVersionTested=%DefaultValue:/Script/UWPTargetPlatform.UWPTargetSettings:MinimumPlatformVersion:String:10.0.10586.0%
Package.Dependencies.PackageDependency[0].Name=Microsoft.VCLibs.140.00
Package.Dependencies.PackageDependency[0].MinVersion=14.0.0.0
Package.Dependencies.PackageDependency[0].Publisher=CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Package.Properties.DisplayName=$/Script/EngineSettings.GeneralProjectSettings:ProjectName$
Package.Properties.PublisherDisplayName=%DefaultValue:/Script/EngineSettings.GeneralProjectSettings:CompanyName:String:No Publisher%
Package.Properties.Description=%DefaultValue:/Script/EngineSettings.GeneralProjectSettings:Description:String:No Package Description Set%
Package.Properties.Logo=%ResourceBinary:/Script/UWPTargetPlatform.UWPTargetSettings:StoreLogo%
Package.Resources.Resource[n].Language=%Array:/Script/UnrealEd.ProjectPackagingSettings:CulturesToStage%
Package.Applications.Application[0].Id=App%AlphaNumericDot:/Script/EngineSettings.GeneralProjectSettings:ProjectName%
Package.Applications.Application[0].Executable=%RelativeExePath%
Package.Applications.Application[0].EntryPoint=App%AlphaNumericDot:/Script/EngineSettings.GeneralProjectSettings:ProjectName%.App
Package.Applications.Application[0].uap:VisualElements.DisplayName=%ResourceString:/Script/EngineSettings.GeneralProjectSettings:ProjectName%
Package.Applications.Application[0].uap:VisualElements.Square150x150Logo=%ResourceBinary:/Script/UWPTargetPlatform.UWPTargetSettings:Logo%
Package.Applications.Application[0].uap:VisualElements.Square44x44Logo=%ResourceBinary:/Script/UWPTargetPlatform.UWPTargetSettings:SmallLogo%
Package.Applications.Application[0].uap:VisualElements.Description=%ResourceString:/Script/EngineSettings.GeneralProjectSettings:Description%
Package.Applications.Application[0].uap:VisualElements.BackgroundColor=%DefaultValue:/Script/UWPTargetPlatform.UWPTargetSettings:TileBackgroundColorHex:String:#000040%
Package.Applications.Application[0].uap:VisualElements.uap:SplashScreen.Image=%ResourceBinary:/Script/UWPTargetPlatform.UWPTargetSettings:SplashScreen%
Package.Applications.Application[0].uap:VisualElements.uap:SplashScreen.BackgroundColor=%DefaultValue:/Script/UWPTargetPlatform.UWPTargetSettings:SplashScreenBackgroundColorHex:String:#000040%
Package.Capabilities.Capability[0].Name=internetClientServer
Package.Capabilities.Capability[1].Name=privateNetworkClientServer