// Copyright Epic Games, Inc. All Rights Reserved.

//------------------------------------------------------- CONFIG WAVE SIZE

// needed if CONFIG_OPTIMIZED_LDS_ACCESS == 0 for ConvertWaveBroadcastToLDS()
//#if DIM_WAVE_SIZE == 0 // fallback to LDS
//	#define WAVE_BROADCAST_GROUPSIZE (16 * 16)
//#endif

//------------------------------------------------------- INCLUDES

#include "TSRCommon.ush"


//------------------------------------------------------- CONFIG

#define DEBUG_ARRAY_SIZE 8

#define DEBUG_DISABLE_PADDING 0

#define DEBUG_DIGESTABLE 0

/** Whether to detect flickering. */
#define CONFIG_MOIRE_DETECTION (DIM_FLICKERING_DETECTION)

#define CONFIG_HISTORY_RESURRECTION (DIM_HISTORY_RESURRECTION)


//------------------------------------------------------- DERIVED
	
#if DIM_WAVE_SIZE == 0 || DEBUG_DIGESTABLE
	/** Load an entire 32x32 with 1x1 worth of data by lane, only using LDS. */
	#define GROUP_TILE_SIZE 32

	#define WAVE_COUNT_X GROUP_TILE_SIZE
	#define WAVE_COUNT_Y GROUP_TILE_SIZE

	#define LANE_COUNT_X 1
	#define LANE_COUNT_Y 1

	#define LANE_STRIDE_X 1
	#define LANE_STRIDE_Y 1

	#define LDS_SIZE (GROUP_TILE_SIZE * GROUP_TILE_SIZE)

	#define TENSOR_REGISTER_LAYOUT FRegisters_S_OneVector

#elif DIM_WAVE_SIZE == 64 || DIM_WAVE_SIZE == 32 || DIM_WAVE_SIZE == 16
	/** Layouts wave in row major 32x32 tile so an entire row of pixels fits within a single wave, and waveops horizontally, but LDS vertically.
	 * Each lane worth of a 1x4 of data per lane to minimise to trade VGPR pressure for both number of wave ops and LDS.
	 */
	#define GROUP_TILE_SIZE 32

	#if DIM_WAVE_SIZE == 16
		// We need a LANE_STRIDE_X of at least 2 to have the entire row of pixels fits within a single wave.
		#define LANE_STRIDE_X 2

		// Only process 2 pixels per lane to reduce register pressure on Intel Arc Alchemist GPUs
		#define LANE_STRIDE_Y 1
	#else
		#define LANE_STRIDE_X 1
		#if CONFIG_COMPILE_FP16
			#define LANE_STRIDE_Y 4
		#else
			#define LANE_STRIDE_Y 2
		#endif
	#endif

	#define WAVE_COUNT_X 1
	#define WAVE_COUNT_Y (GROUP_TILE_SIZE / LANE_STRIDE_Y)

	#define LANE_COUNT_X (GROUP_TILE_SIZE / LANE_STRIDE_X)
	#define LANE_COUNT_Y 1

	#if LANE_STRIDE_Y > 1
		// Each wave needs to output top and bottom rows of pixels into LDS;
		#define LDS_SIZE ((2 * LANE_STRIDE_X) * LANE_COUNT_X * WAVE_COUNT_Y)
	#else
		#define LDS_SIZE (GROUP_TILE_SIZE * GROUP_TILE_SIZE)
	#endif

	#ifdef PLATFORM_SPECIFIC_TENSOR_REGISTER_LAYOUT
		#define TENSOR_REGISTER_LAYOUT PLATFORM_SPECIFIC_TENSOR_REGISTER_LAYOUT
	#endif
	
	/** Manually despill to LDS to save more register pressure. */
	#if CONFIG_COMPILE_FP16 && !CONFIG_SCENE_COLOR_ALPHA
		#define CONFIG_LDS_DESPILL 1
		#define CONFIG_CACHE_REFETCH 1
	#endif

#else
	#error Unknown wave size
#endif

#if CONFIG_COMPILE_FP16
	#define LDS_DWORD_COMPONENT_COUNT 2
#else
	#define LDS_DWORD_COMPONENT_COUNT 4
#endif

#ifndef CONFIG_LDS_DESPILL
	#define CONFIG_LDS_DESPILL 0
#endif

/** Whether should minimise register pressure by reloading some data from cache using memory fetches. */
#ifndef CONFIG_CACHE_REFETCH
	#define CONFIG_CACHE_REFETCH 0
#endif

/** Manually despill to LDS on RDNA platforms to save more register pressure. */
#if CONFIG_LDS_DESPILL
	#define LDS_DESPILL_THREAD_COUNT (WAVE_COUNT_X * WAVE_COUNT_Y) * (LANE_COUNT_X * LANE_COUNT_Y)
	#define LDS_DESPILL_OFFSET       (LANE_STRIDE_X * LANE_STRIDE_Y) * GetVectorDwordSize(tsr_half, 4)

	#define LDS_DESPILL_OFFSET_COUNT 2
	
	#define LDS_DESPILL_DWORD_COUNT  LDS_DESPILL_THREAD_COUNT * LDS_DESPILL_OFFSET * LDS_DESPILL_OFFSET_COUNT
#endif

/** Size of the SIMD per lane that also number of input pixel loaded into each individual lanes. */
#define SIMD_SIZE (LANE_STRIDE_X * LANE_STRIDE_Y)

//------------------------------------------------------- INCLUDE CONVOLUTION NETWORK

#include "TSRConvolutionNetwork.ush"


//------------------------------------------------------- TYPEDEFS

#define tsr_simd_float  TLaneVector2D<float, 1, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_float2 TLaneVector2D<float, 2, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_half  TLaneVector2D<tsr_half, 1, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_half2 TLaneVector2D<tsr_half, 2, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_half3 TLaneVector2D<tsr_half, 3, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_half4 TLaneVector2D<tsr_half, 4, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_halfC TLaneVector2D<tsr_half, CONFIG_CHANNEL_COUNT, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_ushort  TLaneVector2D<tsr_ushort, 1, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_short2  TLaneVector2D<tsr_ushort, 2, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_bool    TLaneVector2D<bool, 1, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_bool4   TLaneVector2D<bool, 4, LANE_STRIDE_X, LANE_STRIDE_Y>
#define tsr_simd_boolC   TLaneVector2D<bool, CONFIG_CHANNEL_COUNT, LANE_STRIDE_X, LANE_STRIDE_Y>

#ifndef PLATFORM_SPECIFIC_ISOLATE
	#define PLATFORM_SPECIFIC_ISOLATE ISOLATE
#endif


//------------------------------------------------------- CONSTANTS

static const float kHistoryGuidePreceptionAdd = 1.0;

static const tsr_half FilteringWeight = rcp(tsr_half(1.0 + 4 * 0.5 + 4 * 0.25));

#if CONFIG_LDS_DESPILL
	static const uint kDespillInput = LDS_DESPILL_THREAD_COUNT * LDS_DESPILL_OFFSET * 0;
	static const uint kDespillHistory = LDS_DESPILL_THREAD_COUNT * LDS_DESPILL_OFFSET * 1;
#endif


//------------------------------------------------------- PARAMETERS

FScreenTransform InputPixelPosToTranslucencyTextureUV;
float4x4 ClipToResurrectionClip;
float2 TranslucencyTextureUVMin;
float2 TranslucencyTextureUVMax;
float3 HistoryGuideQuantizationError;
float FlickeringFramePeriod;
float TheoricBlendFactor;
uint TileOverscan;
float PerceptionAdd;


Texture2D<tsr_halfC> InputTexture;
Texture2D<tsr_half>  InputMoireLumaTexture;
Texture2D<tsr_half4> InputSceneTranslucencyTexture;
Texture2D<tsr_half4> ReprojectedHistoryGuideTexture;
Texture2D<tsr_half>  ReprojectedHistoryGuideMetadataTexture;
Texture2D<tsr_half4> ReprojectedHistoryMoireTexture;
#if CONFIG_HISTORY_RESURRECTION
	Texture2D<tsr_half4> ResurrectedHistoryGuideTexture;
	Texture2D<tsr_half>  ResurrectedHistoryGuideMetadataTexture;
#endif
Texture2D<tsr_half2> DecimateMaskTexture;
Texture2D<tsr_ushort> IsMovingMaskTexture;
Texture2D<float2> ClosestDepthTexture;

RWTexture2DArray<tsr_half4> HistoryGuideOutput;
RWTexture2DArray<tsr_half4> HistoryMoireOutput;
RWTexture2D<tsr_half4>  HistoryRejectionOutput;
RWTexture2D<float2>     DilatedVelocityOutput;
RWTexture2D<tsr_halfC>  InputSceneColorOutput;
RWTexture2D<tsr_half>   InputSceneColorLdrLumaOutput;
RWTexture2D<tsr_ushort> AntiAliasMaskOutput;


//------------------------------------------------------- GLOBALS

static uint2 GGroupId = 0;

static tsr_simd_halfC Debug[DEBUG_ARRAY_SIZE];


//------------------------------------------------------- INPUT FETCHES

tsr_short2 ComputeElementPixelPos(const uint ElementIndex)
{
	tsr_short2 ClampedFetchPixelPos = ComputeElementInputPixelPos(
		/* LaneStride = */ uint2(LANE_STRIDE_X, LANE_STRIDE_Y),
		TileOverscan,
		InputInfo_ViewportMin,
		InputInfo_ViewportMax,
		GGroupId,
		GGroupThreadIndex,
		ElementIndex);

	return ClampedFetchPixelPos;
}

tsr_simd_short2 ComputePixelPos()
{
	tsr_simd_short2 PixelPos;

	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	{
		PixelPos.SetElement(ElementIndex, ComputeElementPixelPos(ElementIndex));
	}

	return PixelPos;
}

tsr_short2 ComputeElementOutputPixelPos(const uint ElementIndex)
{
	return ComputeElementOutputPixelPos(
		/* LaneStride = */ uint2(LANE_STRIDE_X, LANE_STRIDE_Y),
		TileOverscan,
		InputInfo_ViewportMin,
		InputInfo_ViewportMax,
		GGroupId,
		GGroupThreadIndex,
		ElementIndex);
}

void FetchDecimateMask(
	tsr_simd_short2 PixelPos,
	out tsr_simd_half VelocityEdge,
	out tsr_simd_bool bIsDisoccluded)
{
	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	{
		tsr_short2 ClampedFetchPixelPos = PixelPos.GetElement(ElementIndex);
		
		tsr_half2 DecimateMask = DecimateMaskTexture[ClampedFetchPixelPos];

		VelocityEdge.SetElement(ElementIndex, DecimateMask.g);
		bIsDisoccluded.SetElement(ElementIndex, !(DecimateMask.r > tsr_half(PARALLAX_REJECTION_MASK_THRESHOLD)));
	}
} // FetchDecimateMask()

void FetchSceneColorAndTranslucency(
	tsr_simd_short2 PixelPos,
	out tsr_simd_halfC OriginalOpaqueInput,
	out tsr_simd_half4 OriginalTranslucencyInput)
{
	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	{
		tsr_short2 ClampedFetchPixelPos = PixelPos.GetElement(ElementIndex);
		
		float2 TranslucencyTextureUV = ApplyScreenTransform(float2(ClampedFetchPixelPos), InputPixelPosToTranslucencyTextureUV);
		TranslucencyTextureUV = fastClamp(TranslucencyTextureUV, TranslucencyTextureUVMin, TranslucencyTextureUVMax);
		
		OriginalOpaqueInput.SetElement(ElementIndex, InputTexture[ClampedFetchPixelPos]);
		OriginalTranslucencyInput.SetElement(ElementIndex, InputSceneTranslucencyTexture.SampleLevel(GlobalBilinearClampedSampler, TranslucencyTextureUV, 0));
	}
} // FetchSceneColorAndTranslucency()

void FetchHistoryGuide(
	Texture2D<tsr_half4> HistoryGuideTexture,
	Texture2D<tsr_half>  HistoryGuideMetadataTexture,
	tsr_simd_short2 PixelPos,
	out tsr_simd_halfC History,
	out tsr_simd_half  HistoryUncertainty)
{
	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	#if CONFIG_SCENE_COLOR_ALPHA
	{
		tsr_short2 ClampedFetchPixelPos = PixelPos.GetElement(ElementIndex);

		History.SetElement(ElementIndex, HistoryGuideTexture[ClampedFetchPixelPos]);
		HistoryUncertainty.SetElement(ElementIndex, HistoryGuideMetadataTexture[ClampedFetchPixelPos]);
	}
	#else
	{
		tsr_short2 ClampedFetchPixelPos = PixelPos.GetElement(ElementIndex);

		tsr_half4 ReprojectedGuide = HistoryGuideTexture[ClampedFetchPixelPos];
		History.SetElement(ElementIndex, ReprojectedGuide.rgb);
		HistoryUncertainty.SetElement(ElementIndex, ReprojectedGuide.a);
	}
	#endif
} // FetchHistoryGuide()

#if CONFIG_MOIRE_DETECTION

void FetchMoireInput(
	tsr_simd_short2 PixelPos,
	out tsr_simd_half MoireInput,
	out tsr_simd_half4 PrevMoireHistory,
	out tsr_simd_half bIsStatic)
{
	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	{
		tsr_short2 ClampedFetchPixelPos = PixelPos.GetElement(ElementIndex);
		
		MoireInput.SetElement(ElementIndex, InputMoireLumaTexture[ClampedFetchPixelPos]);
		PrevMoireHistory.SetElement(ElementIndex, ReprojectedHistoryMoireTexture[ClampedFetchPixelPos]);
		bIsStatic.SetElement(ElementIndex, tsr_half(1.0) - tsr_half(IsMovingMaskTexture[ClampedFetchPixelPos]) * rcp(tsr_half(255.0)));
	}
} // FetchMoireInput()

#endif // CONFIG_MOIRE_DETECTION


//------------------------------------------------------- COMPOSE SEPARATE TRANSLUCENCY

/** Compose translucency in linear color space. */
CALL_SITE_DEBUGLOC
tsr_simd_halfC ComposeTranslucency(tsr_simd_halfC Color, tsr_simd_half4 Translucency)
{
	tsr_simd_halfC ComposedColor;
	ComposedColor = Color * tsr_simd_halfC::Vectorize(Translucency[3]) + ResizeChannels<CONFIG_CHANNEL_COUNT>(Translucency);
	#if CONFIG_SCENE_COLOR_ALPHA
		ComposedColor.SetComponent(3, Color[3] * Translucency[3]);
	#endif
	#if CONFIG_SCENE_COLOR_ALPHA
		ComposedColor = min(ComposedColor, tsr_simd_halfC::Const(LargestSceneColorRGBA));
	#else
		ComposedColor = min(ComposedColor, tsr_simd_halfC::Const(LargestSceneColorRGB));
	#endif
	return ComposedColor;
}


//------------------------------------------------------- CHANGE LDR EXPOSURE

CALL_SITE_DEBUGLOC
tsr_simd_halfC RemovePerceptionAdd(tsr_simd_halfC SrcColor, const float SourcePerceptionAdd)
{
	tsr_simd_halfC Minus = tsr_simd_halfC::Const(tsr_half(1.0)) - SrcColor;
	tsr_simd_halfC LDRToLinear = min(tsr_simd_halfC::Const(tsr_half(SourcePerceptionAdd)) * rcp(Minus), tsr_simd_halfC::Const(tsr_half(MaxHalfFloat)));

	return SrcColor * LDRToLinear;
}

CALL_SITE_DEBUGLOC
tsr_simd_halfC AddPerceptionAdd(tsr_simd_halfC SrcColor, const float DestPerceptionAdd)
{
	SrcColor = SrcColor * rcp(SrcColor + tsr_simd_halfC::Const(tsr_half(DestPerceptionAdd)));
	return SrcColor;
}

CALL_SITE_DEBUGLOC
tsr_simd_halfC ChangePerceptionAdd(tsr_simd_halfC SrcColor, const float SourcePerceptionAdd, const float DestPerceptionAdd)
{
	SrcColor = RemovePerceptionAdd(SrcColor, SourcePerceptionAdd);
	SrcColor = AddPerceptionAdd(SrcColor, DestPerceptionAdd);
	return SrcColor;
}


//------------------------------------------------------- SPATIAL ANTI-ALIASER

// Compute the LDR luminance the spatial anti-aliaser should anti-alias.
CALL_SITE_DEBUGLOC
tsr_simd_half ComputeSpatialAntiAliaserLumaLDR(tsr_simd_halfC SceneColor)
{
	const tsr_half SpatialAAExposure = tsr_half(0.5);
		
	tsr_simd_half AALumaLDR;

	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	{
		tsr_half PixelLuma = dot(SceneColor.GetElement(ElementIndex).rgb, tsr_half3(0.299f, 0.587f, 0.114f));
		AALumaLDR.SetElement(ElementIndex, PixelLuma / (SpatialAAExposure + PixelLuma));
	}

	return AALumaLDR;
}

// Returns whether the aliasing is visible at all, to avoid paying spatial-antialiaser on low contrasts areas.
CALL_SITE_DEBUGLOC
tsr_simd_bool IsAliasingVisible(tsr_simd_halfC ExposedInputBoxSize)
{
	#if CONFIG_SCENE_COLOR_ALPHA
		tsr_simd_half ExposedInputLuminanceBox = dot(ExposedInputBoxSize, tsr_simd_halfC::Const(tsr_halfC(0.299f, 0.587f, 0.114f, 0.0)));
	#else
		tsr_simd_half ExposedInputLuminanceBox = dot(ExposedInputBoxSize, tsr_simd_halfC::Const(tsr_halfC(0.299f, 0.587f, 0.114f)));
	#endif

	tsr_simd_bool bAliasingIsVisible = ExposedInputLuminanceBox > tsr_simd_half::Const(SPATIAL_ANTI_ALIASER_MIN_LUMIMANCE);

	return bAliasingIsVisible;
}

// Whether to run spatial anti-aliaser on the frame. Must match SpatialAntiAliasingLerp.
CALL_SITE_DEBUGLOC
tsr_simd_bool ShouldSpatialAntiAlias(tsr_simd_bool bIsDisoccluded, tsr_simd_bool bResurrectHistory, tsr_simd_bool bAliasingIsVisible, tsr_simd_half RejectionBlendFinal)
{
	tsr_simd_bool bSpatialAntiAlias = and(bAliasingIsVisible, or(RejectionBlendFinal < tsr_simd_half::Const(tsr_half(0.25)), and(bIsDisoccluded, not(bResurrectHistory))));
	
	return bSpatialAntiAlias;
}


//------------------------------------------------------- FLICKERING TEMPORAL ANALYSIS

void ComputeMoireError(
	tsr_simd_bool  bIsDisoccluded,
	tsr_simd_half  bIsStatic,
	tsr_simd_half  MoireInput,
	tsr_simd_halfC OriginalOpaqueInput,
	tsr_simd_half4 PrevMoireHistory,
	out tsr_simd_half4 OutMoireHistory,
	out tsr_simd_half  OutMoireError)
{
	const tsr_half MinBlendFinal = tsr_half(0.05);
	const tsr_half MoireEncodingError = tsr_half(rcp(127.0));
	const tsr_half MaxPrevTotalVariationCount = tsr_half(20.0);

	// Compute the threshold at which the variation count should quick in
	const tsr_half TotalVariationCountThreshold = tsr_half(1.0 / (1.0 - pow(1.0 - MinBlendFinal, tsr_half(FlickeringFramePeriod))));

	// Input luminance to monitor flickering from.
	tsr_simd_half InputLuma = MoireInput;

	// How much input luminance from the TSRComputeMoireLuma.usf measurement has been modified since for instance with fog, water.
	tsr_simd_half InputLumaModification;
	{
		const tsr_half InputLumaEncodingError = tsr_half(0.5 / 255.0);
			
		OriginalOpaqueInput = OriginalOpaqueInput * rcp(OriginalOpaqueInput + tsr_simd_halfC::Const(tsr_half(PerceptionAdd)));


		tsr_simd_half SceneColorLuma;
		UNROLL_N(SIMD_SIZE)
		for (uint SimdIndex = 0; SimdIndex < SIMD_SIZE; SimdIndex++)
		{
			SceneColorLuma.SetElement(SimdIndex, dot(OriginalOpaqueInput.GetElement(SimdIndex).rgb, kMoireLumaWeights));
		}

		InputLumaModification = max(abs(InputLuma - SceneColorLuma) - tsr_simd_half::Const(InputLumaEncodingError), tsr_simd_half::Const(0.0));
	}

	// Unpack history
	tsr_simd_half PrevFlickeringHistory = PrevMoireHistory[0];
	tsr_simd_half PrevGradient = PrevMoireHistory[1] * tsr_half(255.0 / 127.0) - tsr_half(1.0);
	//tsr_simd_half PrevTotalVariation = PrevMoireHistory[2] * tsr_simd_half::Const(1.0 - MinBlendFinal);
	tsr_simd_half PrevTotalVariation = PrevMoireHistory[2] * tsr_simd_half::Const(tsr_half(1.0) - MinBlendFinal);
	tsr_simd_half PrevTotalVariationCount = PrevMoireHistory[3] * MaxPrevTotalVariationCount * tsr_simd_half::Const(tsr_half(1.0) - MinBlendFinal);
	
	// Discard history on moving objects.
	PrevTotalVariation = PrevTotalVariation * bIsStatic;
	PrevTotalVariationCount = PrevTotalVariationCount * bIsStatic;

	// Run the exact same heuristic as MeasureRejection on a single channel.
	tsr_simd_half FilteredInputLumaModification;
	tsr_simd_half OutRejectionBlendFinal;
	tsr_simd_half OutRejectionClampBlend;
	{
		tsr_simd_half BackbufferQuantizationErrorVector = tsr_simd_half::Const(MoireEncodingError);
		
		tsr_simd_half InputC0 = InputLuma;

		// Anhilate history
		tsr_simd_half InputC2 = InputC0;
		tsr_simd_half HistoryC2 = PrevFlickeringHistory;
		AnnihilateMutuallySingleChannel3x3(InputLuma, PrevFlickeringHistory, /* out */ InputC2, /* out */ HistoryC2);

		// Convolve the input luma to have the exact same moire pattern as FilteredInput below.
		tsr_simd_half FilteredInput;
		tsr_simd_half FilteredHistory;
		Deconcatenate(Blur3x3(Concatenate(InputC2, InputLumaModification, HistoryC2)), /* out */ FilteredInput, /* out */ FilteredInputLumaModification, /* out */ FilteredHistory);
		
		// Compute clamping box of the limance.
		tsr_simd_half FilteredBoxMin;
		tsr_simd_half FilteredBoxMax;
		tsr_simd_half BoxSize;
		{
			tsr_simd_half2 Min;
			tsr_simd_half2 Max;
			MinMax3x3(Concatenate(FilteredInput, InputC2), /* out */ Min, /* out */ Max);
			FilteredBoxMin = Min[0] - BackbufferQuantizationErrorVector;
			FilteredBoxMax = Max[0] + BackbufferQuantizationErrorVector;
		
			BoxSize = (
				(Max[1] - Min[1]) * tsr_simd_half::Const(FilteringWeight) +
				(BackbufferQuantizationErrorVector * tsr_half(2 * FilteringWeight)));
		}

		tsr_simd_half ClampedFilteredHistory = fastClamp(FilteredHistory, FilteredBoxMin, FilteredBoxMax);

		tsr_simd_half Delta = max(abs(FilteredInput - FilteredHistory), BoxSize);
	
		tsr_simd_half ClampError = BackbufferQuantizationErrorVector;
		ClampError = max(ClampError, BoxSize * tsr_half(0.25)); // original
		
		tsr_simd_half RawClampedEnergy = abs(ClampedFilteredHistory - FilteredHistory);
		tsr_simd_half RawRejection     = saturate(tsr_simd_half::Const(1.0) - max(RawClampedEnergy - ClampError, tsr_simd_half::Const(0.0)) * rcp(Delta));

		tsr_simd_half FilteredClampedEnergy;
		Deconcatenate(MaxRMinG3x3(Median3x3(Concatenate(RawClampedEnergy, RawRejection))), /* out */ FilteredClampedEnergy, /* out */ OutRejectionClampBlend);

		OutRejectionBlendFinal = saturate(tsr_simd_half::Const(1.0) - max(FilteredClampedEnergy - ClampError, tsr_simd_half::Const(0.0)) * rcp(Delta));
	}
	
	// Simulate what happens in TSRUpdateHistory.usf
	tsr_simd_half FinalFlickeringHistory;
	tsr_simd_half CurrentGradient;
	{
		tsr_simd_half ClampedPrevFlickeringHistory = ClampPlus3x3(PrevFlickeringHistory, InputLuma);
		tsr_simd_half FinalPrevFlickeringHistory = lerp(ClampedPrevFlickeringHistory, PrevFlickeringHistory, OutRejectionClampBlend);

		tsr_simd_half FinalBlendFinal = max(tsr_simd_half::Const(1.0) - OutRejectionBlendFinal, tsr_simd_half::Const(MinBlendFinal));
		
		FinalFlickeringHistory = InputLuma * FinalBlendFinal - FinalPrevFlickeringHistory * (FinalBlendFinal - tsr_simd_half::Const(1.0));
		
		tsr_simd_half GhostingHistory = InputLuma * tsr_simd_half::Const(MinBlendFinal) - PrevFlickeringHistory * tsr_simd_half::Const(MinBlendFinal - (1.0));

		CurrentGradient = FinalFlickeringHistory - GhostingHistory;
	}

	// Remove how much luma has changed from luma measurement to final scene color from the gradient.
	for (uint SimdIndex = 0; SimdIndex < SIMD_SIZE; SimdIndex++)
	{
		tsr_half LocalCurrentGradient = CurrentGradient.GetElement(SimdIndex);
		tsr_half LocalInputLumaModification = FilteredInputLumaModification.GetElement(SimdIndex);
			
		CurrentGradient.SetElement(SimdIndex, clamp(LocalCurrentGradient * tsr_half(POSITIVE_INFINITY), tsr_half(-1.0), tsr_half(1.0)) * max(abs(LocalCurrentGradient) - LocalInputLumaModification, tsr_half(0.0)));
	}

	#if 0
		tsr_simd_half InputBoxSize = InputLumaMax - InputLumaMin;
		CurrentGradient = sign(CurrentGradient) * max(abs(CurrentGradient) - tsr_simd_half::Const(0.5) * InputBoxSize, tsr_simd_half::Const(0.0));
	#endif

	tsr_simd_half IsFlicker;
	UNROLL_N(SIMD_SIZE)
	for (uint SimdIndex = 0; SimdIndex < SIMD_SIZE; SimdIndex++)
	{
		tsr_half LocalCurrentGradient = CurrentGradient.GetElement(SimdIndex);
		tsr_half LocalPrevGradient = PrevGradient.GetElement(SimdIndex);

		bool bGradientsAreSameSign = LocalCurrentGradient * LocalPrevGradient > tsr_half(0.0);
		bool bGradientsAreWithinError = abs(LocalCurrentGradient) < MoireEncodingError || abs(LocalPrevGradient) < MoireEncodingError;
		//bool bCurrentGradientSubstentialEnough = abs(LocalCurrentGradient) > View.GeneralPurposeTweak * abs(LocalPrevGradient); // - 2.0 * MoireEncodingError;

		tsr_half LocalIsFlicker = select((
			bGradientsAreSameSign ||
			bGradientsAreWithinError ||
			//!bCurrentGradientSubstentialEnough ||
			bCameraCut), tsr_half(0.0), tsr_half(1.0));

		IsFlicker.SetElement(SimdIndex, LocalIsFlicker);
	}

	// Compute the total variation of the gradient over time.
	tsr_simd_half GradientVariation = min(abs(PrevGradient), abs(CurrentGradient)) * IsFlicker;

	// Dilates the total variation and contribution to keep stability despite inacuracies in the history reprojection
	// of these need a nearest filter which isn't precise at all.
	tsr_simd_half TotalVariationContribution;
	tsr_simd_half TotalVariationCountContribution;
	Deconcatenate(Max3x3(Concatenate(GradientVariation, IsFlicker)), /* out */ TotalVariationContribution, /* out */ TotalVariationCountContribution);

	UNROLL_N(SIMD_SIZE)
	for (uint SimdIndex = 0; SimdIndex < SIMD_SIZE; SimdIndex++)
	{
		tsr_half LocalCurrentGradient = CurrentGradient.GetElement(SimdIndex);

		tsr_half LocalPrevGradient = PrevGradient.GetElement(SimdIndex);
		tsr_half LocalPrevTotalVariation = PrevTotalVariation.GetElement(SimdIndex);
		tsr_half LocalPrevTotalVariationCount = PrevTotalVariationCount.GetElement(SimdIndex);
		bool LocalIsDisoccluded = bIsDisoccluded.GetElement(SimdIndex);

		tsr_half LocalIsFlicker = IsFlicker.GetElement(SimdIndex);

		tsr_half LocalTotalVariationContribution = TotalVariationContribution.GetElement(SimdIndex);
		tsr_half LocalTotalVariationCountContribution = TotalVariationCountContribution.GetElement(SimdIndex);
			
		// Blend out previous gradient
		tsr_half LocalPrevBlendedGradient = LocalPrevGradient * (tsr_half(1.0) - MinBlendFinal) * (tsr_half(1.0) - LocalIsFlicker);

		// Compute new gradient.
		#if 1
			tsr_half LocalNewGradient = LocalPrevBlendedGradient + LocalCurrentGradient;
		#else
			tsr_half LocalNewGradient = abs(LocalPrevBlendedGradient) > abs(LocalCurrentGradient) ? LocalPrevBlendedGradient : LocalCurrentGradient;
		#endif
			
		// Accumulate current frame variation.
		tsr_half LocalNewTotalVariation = LocalPrevTotalVariation + LocalTotalVariationContribution;
		tsr_half LocalNewTotalVariationCount = LocalPrevTotalVariationCount + LocalTotalVariationCountContribution;

		// Discard all moire history on parallax disocclusion.
		LocalNewGradient            = select(LocalIsDisoccluded, tsr_half(0.0), LocalNewGradient);
		LocalNewTotalVariation      = select(LocalIsDisoccluded, tsr_half(0.0), LocalNewTotalVariation);
		LocalNewTotalVariationCount = select(LocalIsDisoccluded, tsr_half(0.0), LocalNewTotalVariationCount);

		// Quantise total variation and count to history bit depth to variation drift in the history over time.
		tsr_half LocalQuantizedNewTotalVariationCount = floor(LocalNewTotalVariationCount * (tsr_half(255.0) / MaxPrevTotalVariationCount)) * (MaxPrevTotalVariationCount / tsr_half(255.0));
		LocalNewTotalVariation *= LocalQuantizedNewTotalVariationCount * SafeRcp(LocalNewTotalVariationCount);

		// Compute the final luminance 
		#if 1
			tsr_half LocalCountFadeIn = saturate(LocalNewTotalVariationCount / TotalVariationCountThreshold - tsr_half(0.5));
		#else
			tsr_half LocalCountFadeIn = saturate(LocalNewTotalVariationCount - TotalVariationCountThreshold);
		#endif
		tsr_half LocalMoireError = (abs(LocalNewTotalVariation * SafeRcp(LocalNewTotalVariationCount)) + LocalNewTotalVariationCount * MoireEncodingError) * LocalCountFadeIn;

		tsr_half4 PackedMoireHistory = tsr_half4(
			FinalFlickeringHistory.GetElement(SimdIndex),
			LocalNewGradient * tsr_half(127.0 / 255.0) + tsr_half(127.0 / 255.0),
			LocalNewTotalVariation,
			LocalQuantizedNewTotalVariationCount * rcp(MaxPrevTotalVariationCount));

		OutMoireHistory.SetElement(SimdIndex, PackedMoireHistory);

		OutMoireError.SetElement(SimdIndex, LocalMoireError);
	}
		
	// Moving object in the scene have very low chance of creating moire pattern with TAA jitter, so discard the moire error to still
	// have character animation ghost free evem as environement shadow project different things on character.
	OutMoireError = OutMoireError * bIsStatic;
} // ComputeMoireError()


//------------------------------------------------------- SHADING REJECTION

template<bool ApplyMoireError>
void MeasureRejection(
	tsr_simd_halfC InputC0,
	tsr_simd_halfC InputC2,
	tsr_simd_halfC HistoryC2,
	tsr_simd_half  MoireError,
	out tsr_simd_half OutRejectionBlendFinal,
	out tsr_simd_half OutRejectionClampBlend)
{
	tsr_simd_halfC BackbufferQuantizationErrorVector = tsr_simd_halfC::Const(MeasureBackbufferLDRQuantizationError());
		
	tsr_simd_halfC FilteredHistory = Blur3x3(HistoryC2);
	
	tsr_simd_halfC TotalVarInputDiffC0C2 = abs(TotalVariation3x3(abs(InputC0 - InputC2)));
	tsr_simd_halfC TotalVarInputC2 = abs(TotalVariation3x3(InputC2));

	tsr_simd_halfC ClampError = BackbufferQuantizationErrorVector;
	ClampError = max(ClampError, Blur3x3(min(TotalVarInputDiffC0C2, TotalVarInputC2)));
	
	tsr_simd_halfC InputC2BoxSize = MaxMinusMin3x3(InputC2);
	ClampError = max(ClampError, InputC2BoxSize * tsr_half(FilteringWeight * 0.25));
	ClampError = ClampError + BackbufferQuantizationErrorVector;

	tsr_simd_halfC FilteredInput   = Blur3x3(InputC2);

	// Build the clamping box of the filtered signal
	tsr_simd_halfC FilteredBoxMin;
	tsr_simd_halfC FilteredBoxMax;
	MinMax3x3(FilteredInput, /* out */ FilteredBoxMin, /* out */ FilteredBoxMax);
	FilteredBoxMin = FilteredBoxMin - ClampError;
	FilteredBoxMax = FilteredBoxMax + ClampError;
		
	// Clamp filtered signal
	tsr_simd_halfC ClampedFilteredHistory = fastClamp(FilteredHistory, FilteredBoxMin, FilteredBoxMax);
	if (ApplyMoireError)
	{
		tsr_simd_halfC MoireErrorSize;
			
		UNROLL_N(SIMD_SIZE)
		for (uint SimdIndex = 0; SimdIndex < SIMD_SIZE; SimdIndex++)
		#if 0
		{
			tsr_halfC ClampedEnergy = abs(FlickeringClampedFilteredHistory.GetElement(SimdIndex) - FilteredHistory.GetElement(SimdIndex));
			tsr_halfC ClampedEnergyAmount = ClampedEnergy * SafeRcp(ClampedEnergy[0] + ClampedEnergy[1] + ClampedEnergy[2]);

			// Apply the moire error on each individual channel based on how much they need to clamp.
			MoireErrorSize.SetElement(SimdIndex, ClampedEnergyAmount * (kMoireLumaToChannel * MoireError.GetElement(SimdIndex)));
		}
		#else
		{
			MoireErrorSize.SetElement(SimdIndex, kMoireLumaToChannel * MoireError.GetElement(SimdIndex));
		}
		#endif

		tsr_simd_halfC StableFilteredBoxMin = min(FilteredBoxMin, FilteredBoxMax - MoireErrorSize);
		tsr_simd_halfC StableFilteredBoxMax = max(FilteredBoxMax, FilteredBoxMin + MoireErrorSize);
			
		ClampedFilteredHistory = fastClamp(FilteredHistory, StableFilteredBoxMin, StableFilteredBoxMax);
	}
		
	// Compute the box size.
	tsr_simd_halfC BoxSize;
	{
		BoxSize = (
			InputC2BoxSize * tsr_simd_halfC::Const(FilteringWeight) +
			(BackbufferQuantizationErrorVector * tsr_half(2 * FilteringWeight)));

		if (ApplyMoireError)
		{
			tsr_simd_halfC MoireErrorSize;
			UNROLL_N(SIMD_SIZE)
			for (uint SimdIndex = 0; SimdIndex < SIMD_SIZE; SimdIndex++)
			{
				tsr_halfC ClampedEnergy = abs(ClampedFilteredHistory.GetElement(SimdIndex) - FilteredHistory.GetElement(SimdIndex));
				tsr_halfC ClampedEnergyAmount = ClampedEnergy * SafeRcp(ClampedEnergy[0] + ClampedEnergy[1] + ClampedEnergy[2]);

				// Apply the moire error on each individual channel based on how much they need to clamp.
				MoireErrorSize.SetElement(SimdIndex, ClampedEnergyAmount * ((FilteringWeight * tsr_half(3.0)) * MoireError.GetElement(SimdIndex)));
			}
			BoxSize = max(BoxSize, MoireErrorSize);
		}
	}

	tsr_simd_halfC Delta = max(abs(FilteredInput - FilteredHistory), BoxSize);

	tsr_simd_halfC RawClampedEnergy      = abs(ClampedFilteredHistory - FilteredHistory);

	tsr_simd_halfC RawFactor        = saturate(tsr_simd_halfC::Const(1.0) - RawClampedEnergy * rcp(Delta));
	tsr_simd_half RawRejection      = min3(RawFactor[0], RawFactor[1], RawFactor[2]);
	#if CONFIG_SCENE_COLOR_ALPHA
		RawRejection = min(RawRejection, RawFactor[3]);
	#endif

	#if CONFIG_SCENE_COLOR_ALPHA
		OutRejectionClampBlend = Min3x3(Median3x3(RawRejection));
		tsr_simd_halfC FilteredClampedEnergy = Max3x3(Median3x3(RawClampedEnergy));
	#else
		tsr_simd_halfC FilteredClampedEnergy;
		Deconcatenate(MaxRGBMinA3x3(Median3x3(Concatenate(RawClampedEnergy, RawRejection))), /* out */ FilteredClampedEnergy, /* out */ OutRejectionClampBlend);
	#endif

	tsr_simd_halfC FilteredFactor   = saturate(tsr_simd_halfC::Const(1.0) - FilteredClampedEnergy * rcp(Delta));
	tsr_simd_half FilteredRejection = min3(FilteredFactor[0], FilteredFactor[1], FilteredFactor[2]);
	#if CONFIG_SCENE_COLOR_ALPHA
		FilteredRejection = min(FilteredRejection, FilteredFactor[3]);
	#endif
	OutRejectionBlendFinal          = FilteredRejection;
} // MeasureRejection()


//------------------------------------------------------- RESURRECTION

#if CONFIG_HISTORY_RESURRECTION

// Returns whether resurrected frame is closer than previous frame on per pixel basis.
CALL_SITE_DEBUGLOC
tsr_simd_bool IsResurrectedFrameCloserThanPreviousFrame(tsr_simd_halfC ExposedInput, tsr_simd_halfC ExposedHistory, tsr_simd_halfC ExposedResurrectedHistory)
{
	tsr_simd_halfC PrevMatch         = abs(ExposedInput - ExposedHistory);
	tsr_simd_halfC ResurrectionMatch = abs(ExposedInput - ExposedResurrectedHistory);

	tsr_simd_halfC MatchDiff = PrevMatch - ResurrectionMatch;
	#if CONFIG_SCENE_COLOR_ALPHA
		tsr_simd_half TotalMatchDiff = Sum3x3(MatchDiff[0] + MatchDiff[1] + MatchDiff[2] + MatchDiff[3]);
	#else
		tsr_simd_half TotalMatchDiff = Sum3x3(MatchDiff[0] + MatchDiff[1] + MatchDiff[2]);
	#endif

	tsr_simd_half bResurrectedPixelIsCloser = saturate((TotalMatchDiff - tsr_simd_half::Const(tsr_half(0.05 * 3.0 * 9.0))) * tsr_simd_half::Const(tsr_half(POSITIVE_INFINITY)));

	tsr_simd_bool bResurrectionIsCloser = Sum3x3(bResurrectedPixelIsCloser) > tsr_simd_half::Const(4.0);

	//tsr_simd_bool bResurrectionIsCloser = MedianBool3x3((TotalMatchDiff - tsr_simd_half::Const(tsr_half(0.05 * 3.0 * 9.0))));

	return bResurrectionIsCloser;
}

// Whether it is worth for the entire tile to MeasureRejection() on the resurrected frame.
CALL_SITE_DEBUGLOC
bool IsWorthMeasuringRejectionOfResurrectedFrame(tsr_simd_half PrevRejectionBlendFinal, tsr_simd_bool bResurrectionIsCloser)
{
	tsr_simd_bool bPrevIsNotGoodEnough = PrevRejectionBlendFinal < tsr_simd_half::Const(0.5);
	tsr_simd_bool bIsValidTilePixel = IsValidTilePixel<LANE_STRIDE_X, LANE_STRIDE_Y>(TileOverscan);
	tsr_simd_bool bShouldComputeResurrection = and(and(bResurrectionIsCloser, bPrevIsNotGoodEnough), bIsValidTilePixel);

	bool bComputeResurrection = AnyThread(AnyComponent(bShouldComputeResurrection));

	return bComputeResurrection;
}

// Final logic whether the resurrection must actually happen on per pixel basis.
CALL_SITE_DEBUGLOC
tsr_simd_bool ShouldResurrectHistory(tsr_simd_half PrevRejectionBlendFinal, tsr_simd_half ResurrectionRejectionBlendFinal, tsr_simd_bool bResurrectionIsCloser)
{
	tsr_simd_bool bIsValidTilePixel = IsValidTilePixel<LANE_STRIDE_X, LANE_STRIDE_Y>(TileOverscan);
	tsr_simd_bool bResurrectionIsBetter = (ResurrectionRejectionBlendFinal - PrevRejectionBlendFinal) > tsr_simd_half::Const(0.1);
	tsr_simd_bool bResurrectHistory = and(and(bResurrectionIsCloser, bResurrectionIsBetter), bIsValidTilePixel);

	return bResurrectHistory;
}

// Load the depth for ComputeResurrectionVelocity()
CALL_SITE_DEBUGLOC
void FetchDeviceZ(
	tsr_simd_short2 PixelPos,
	out tsr_simd_float DeviceZ)
{
	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	{
		tsr_short2 ClampedFetchPixelPos = PixelPos.GetElement(ElementIndex);
		
		DeviceZ.SetElement(ElementIndex, ClosestDepthTexture[ClampedFetchPixelPos].g);
	}
} // FetchMoireInput()

// Compute the velocity used by the reprojection of the resurrection.
CALL_SITE_DEBUGLOC
tsr_simd_float2 ComputeResurrectionMotionVector(tsr_simd_float DeviceZ)
{
	tsr_simd_float2 ResurrectedEncodedScreenVelocity;
	
	UNROLL_N(SIMD_SIZE)
	for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
	{
		float2 ScreenPos = ApplyScreenTransform(float2(ComputeElementPixelPos(ElementIndex)), InputPixelPosToScreenPos);

		float4 ThisClip = float4(ScreenPos, DeviceZ.GetElement(ElementIndex), 1);
		float4 ResurrectionClip = mul(ThisClip, ClipToResurrectionClip); 
		float2 ResurrectionScreen = ResurrectionClip.xy / ResurrectionClip.w;
			
		ResurrectedEncodedScreenVelocity.SetElement(ElementIndex, EncodeVelocityToTexture(float3(ScreenPos - ResurrectionScreen, 0.0)).xy);
	}

	return ResurrectedEncodedScreenVelocity;
}

#endif // CONFIG_HISTORY_RESURRECTION


//------------------------------------------------------- UPDATE GUDIE

// Update the guide for next frame.
CALL_SITE_DEBUGLOC
tsr_simd_halfC UpdateGuide(tsr_simd_halfC ExposedInput, tsr_simd_halfC ExposedHistory, tsr_simd_bool bIsDisoccluded, tsr_simd_half RejectionBlendFinal)
{
	tsr_simd_bool bIsOffScreen = tsr_simd_bool::Const(false);

	tsr_simd_half TotalBlend = select(or(bIsOffScreen, bIsDisoccluded), tsr_simd_half::Const(1.0), saturate(tsr_simd_half::Const(1.0) - RejectionBlendFinal * tsr_simd_half::Const(4.0)));
	tsr_simd_half RejectedBlendFactor = max(tsr_simd_half::Const(tsr_half(TheoricBlendFactor)), tsr_simd_half::Const(1.0) - RejectionBlendFinal);

	tsr_simd_half BlendFinal = max(RejectedBlendFactor, TotalBlend);

	tsr_simd_halfC FinalGuide = ExposedInput * tsr_simd_halfC::Vectorize(BlendFinal) - ExposedHistory * tsr_simd_halfC::Vectorize(BlendFinal - 1.0);
	return FinalGuide;
}


//------------------------------------------------------- REGISTER PRESSURE HELPERS

#if CONFIG_LDS_DESPILL || CONFIG_CACHE_REFETCH

void RefetchInputAndHistoryFromLDSOrCache(
	out tsr_simd_halfC Input,
	out tsr_simd_half  InputUncertainty,
	out tsr_simd_halfC History,
	out tsr_simd_half  HistoryUncertainty)
#if CONFIG_LDS_DESPILL
{
	Deconcatenate(tsr_simd_half4::LoadLDSSpill(kDespillInput), /* out */ Input, /* out */ InputUncertainty);
	Deconcatenate(tsr_simd_half4::LoadLDSSpill(kDespillHistory), /* out */ History, /* out */ HistoryUncertainty);
}
#else
{
	tsr_simd_short2 PixelPos = ComputePixelPos();

	tsr_simd_halfC OriginalOpaqueInput;
	tsr_simd_half4 OriginalTranslucencyInput;
	tsr_simd_halfC OriginalHistory;
	tsr_simd_half  OriginalHistoryUncertainty;
	tsr_simd_half  VelocityEdge;
	tsr_simd_bool  bIsDisoccluded;

	FetchDecimateMask(PixelPos, /* out */ VelocityEdge, /* out */ bIsDisoccluded);
	FetchSceneColorAndTranslucency(PixelPos, /* out */ OriginalOpaqueInput, /* out */ OriginalTranslucencyInput);
	FetchHistoryGuide(
		ReprojectedHistoryGuideTexture,
		ReprojectedHistoryGuideMetadataTexture,
		PixelPos,
		/* out */ OriginalHistory,
		/* out */ OriginalHistoryUncertainty);

	tsr_simd_halfC OriginalInput = ComposeTranslucency(OriginalOpaqueInput, Blur3x3(OriginalTranslucencyInput));

	Input            = OriginalInput;
	InputUncertainty = VelocityEdge;
	History            = OriginalHistory;
	HistoryUncertainty = OriginalHistoryUncertainty;
}
#endif

#endif // CONFIG_LDS_DESPILL || CONFIG_CACHE_REFETCH


//------------------------------------------------------- ENTRY POINT

#if COMPILER_SUPPORTS_WAVE_SIZE && DIM_WAVE_SIZE > 0
WAVESIZE(DIM_WAVE_SIZE)
#endif
[numthreads(LANE_COUNT * WAVE_COUNT, 1, 1)]
void MainCS(
	uint2 GroupId : SV_GroupID,
	uint GroupThreadIndex : SV_GroupIndex)
{
	GGroupId = GroupId;
	GGroupThreadIndex = GroupThreadIndex;

	UNROLL_N(DEBUG_ARRAY_SIZE)
	for (uint DebugId = 0; DebugId < DEBUG_ARRAY_SIZE; DebugId++)
	{
		Debug[DebugId].SetAllElements(0.0);
	}
		
	// Analyses the moire pattern overtime.
	tsr_simd_halfC OriginalOpaqueInput;
	tsr_simd_half4 OriginalTranslucencyInput;
	tsr_simd_half  VelocityEdge;
	tsr_simd_bool  bIsDisoccluded;
	tsr_simd_half  MoireError = tsr_simd_half::Const(0.0);
	#if CONFIG_MOIRE_DETECTION
	PLATFORM_SPECIFIC_ISOLATE
	{
		// Load its own data
		#if CONFIG_MOIRE_DETECTION
			tsr_simd_half  MoireInput;
			tsr_simd_half4 PrevMoireHistory;
			tsr_simd_half  bIsStatic;
		#endif
		PLATFORM_SPECIFIC_ISOLATE
		{
			tsr_simd_short2 PixelPos = ComputePixelPos();
		
			FetchDecimateMask(PixelPos, /* out */ VelocityEdge, /* out */ bIsDisoccluded);
			FetchSceneColorAndTranslucency(PixelPos, /* out */ OriginalOpaqueInput, /* out */ OriginalTranslucencyInput);
			FetchMoireInput(
				PixelPos,
				/* out */ MoireInput,
				/* out */ PrevMoireHistory,
				/* out */ bIsStatic);
		}
	
		tsr_simd_half4 MoireHistory;
		ComputeMoireError(
			bIsDisoccluded,
			bIsStatic,
			MoireInput,
			OriginalOpaqueInput,
			PrevMoireHistory,
			/* out */ MoireHistory,
			/* out */ MoireError);

		// Stores moire output to save VGPR for what is next.
		UNROLL_N(SIMD_SIZE)
		for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
		{
			const tsr_short2 OutputPixelPos = ComputeElementOutputPixelPos(ElementIndex);

			HistoryMoireOutput[tsr_short3(OutputPixelPos, 0)] = MoireHistory.GetElement(ElementIndex);
		}
	}
	#endif // CONFIG_MOIRE_DETECTION
	
	// Load all the history data.
	tsr_simd_halfC OriginalHistory;
	tsr_simd_half  OriginalHistoryUncertainty;
	#if CONFIG_HISTORY_RESURRECTION
		tsr_simd_halfC OriginalResurrectedHistory;
		tsr_simd_half  OriginalResurrectedHistoryUncertainty;
	#endif
	PLATFORM_SPECIFIC_ISOLATE
	{
		tsr_simd_short2 PixelPos = ComputePixelPos();

		#if !CONFIG_MOIRE_DETECTION || 1
			FetchDecimateMask(PixelPos, /* out */ VelocityEdge, /* out */ bIsDisoccluded);
			FetchSceneColorAndTranslucency(PixelPos, /* out */ OriginalOpaqueInput, /* out */ OriginalTranslucencyInput);
		#endif
		FetchHistoryGuide(
			ReprojectedHistoryGuideTexture,
			ReprojectedHistoryGuideMetadataTexture,
			PixelPos,
			/* out */ OriginalHistory,
			/* out */ OriginalHistoryUncertainty);
			
		#if CONFIG_HISTORY_RESURRECTION
			FetchHistoryGuide(
				ResurrectedHistoryGuideTexture,
				ReprojectedHistoryGuideMetadataTexture,
				PixelPos,
				/* out */ OriginalResurrectedHistory,
				/* out */ OriginalResurrectedHistoryUncertainty);
		#endif
	}
	
	// Compute AA Luma and compose separate translucency into scene color for optimised HistoryUpdate.
	{
		tsr_simd_halfC CenterFinalSceneColor = ComposeTranslucency(OriginalOpaqueInput, OriginalTranslucencyInput);
		CenterFinalSceneColor = min(CenterFinalSceneColor, tsr_simd_halfC::Const(tsr_half(Max10BitsFloat)));
		
		tsr_simd_half CenterLumaLDR = ComputeSpatialAntiAliaserLumaLDR(CenterFinalSceneColor);

		PLATFORM_SPECIFIC_ISOLATE
		{
			UNROLL_N(SIMD_SIZE)
			for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
			{
				const tsr_short2 OutputPixelPos = ComputeElementOutputPixelPos(ElementIndex);
		
				InputSceneColorOutput[OutputPixelPos] = CenterFinalSceneColor.GetElement(ElementIndex);
				InputSceneColorLdrLumaOutput[OutputPixelPos] = CenterLumaLDR.GetElement(ElementIndex);
			}
		}
	}
	
	tsr_simd_halfC OriginalInput = ComposeTranslucency(OriginalOpaqueInput, Blur3x3(OriginalTranslucencyInput));

	// Despill to LDS to make room in VGPRs for the convolutions of ComputeMoireError()
	#if CONFIG_LDS_DESPILL
	PLATFORM_SPECIFIC_ISOLATE
	{
		Concatenate(OriginalInput, VelocityEdge).StoreLDSSpill(kDespillInput);
		Concatenate(OriginalHistory, OriginalHistoryUncertainty).StoreLDSSpill(kDespillHistory);
	}
	#endif // CONFIG_LDS_DESPILL

	// Measure rejection
	tsr_simd_half RejectionBlendFinal = tsr_simd_half::Const(1.0);
	tsr_simd_half RejectionClampBlend = tsr_simd_half::Const(1.0);
	tsr_simd_bool bAliasingIsVisible = tsr_simd_bool::Const(false);
	#if CONFIG_HISTORY_RESURRECTION
		tsr_simd_bool bResurrectionIsCloser = tsr_simd_bool::Const(false);
	#endif
	PLATFORM_SPECIFIC_ISOLATE
	{
		// Reload all the data from LDS or cache with moire to avoid register pressure
		tsr_simd_halfC Input   = OriginalInput;
		tsr_simd_halfC History = OriginalHistory;

		// Convert input to shading LDR
		tsr_simd_halfC ExposedInput = AddPerceptionAdd(Input, /* DestPerceptionAdd = */ PerceptionAdd);
		tsr_simd_halfC ExposedHistory = ChangePerceptionAdd(
			History,
			/* SourcePerceptionAdd = */ kHistoryGuidePreceptionAdd,
			/* DestPerceptionAdd   = */ PerceptionAdd);
			
		// Check whether the history resurrection is closer to input, to discard and no pay the register pressure of OriginalResurrectedHistory
		#if CONFIG_HISTORY_RESURRECTION
			tsr_simd_halfC ExposedResurrectedHistory = ChangePerceptionAdd(
				OriginalResurrectedHistory,
				/* SourcePerceptionAdd = */ kHistoryGuidePreceptionAdd,
				/* DestPerceptionAdd   = */ PerceptionAdd);
				
			bResurrectionIsCloser = IsResurrectedFrameCloserThanPreviousFrame(ExposedInput, ExposedHistory, ExposedResurrectedHistory);
		#endif
		
		// Mutual Annihilation
		tsr_simd_halfC ExposedInputMin;
		tsr_simd_halfC ExposedInputMax;
		MinMax3x3(ExposedInput, /* out */ ExposedInputMin, /* out */ ExposedInputMax);

		bAliasingIsVisible = IsAliasingVisible(ExposedInputMax - ExposedInputMin);

		tsr_simd_halfC ClampedInput = Clamp3x3(ExposedInput, fastClamp(ExposedHistory, ExposedInputMin, ExposedInputMax));
		tsr_simd_halfC ClampedHistory = AnnihilateToGuide3x3(ExposedHistory, /* Guide = */ ExposedInput);

		MeasureRejection</* ApplyMoireError = */ CONFIG_MOIRE_DETECTION != 0>(
			/* InputC0 = */    ExposedInput,
			/* InputC2 = */    ClampedInput,
			/* HistoryC2 = */  ClampedHistory,
			/* MoireError = */ MoireError,
			/* out */ RejectionBlendFinal,
			/* out */ RejectionClampBlend);
	}
	
	// Try resurrecting the history if necessary
	tsr_simd_bool bResurrectHistory = tsr_simd_bool::Const(false);
	#if CONFIG_HISTORY_RESURRECTION
	bool bComputeResurrection = IsWorthMeasuringRejectionOfResurrectedFrame(RejectionBlendFinal, bResurrectionIsCloser);
	BRANCH
	if (bComputeResurrection)
	PLATFORM_SPECIFIC_ISOLATE
	{
		// Reload the resurrected history from cache.
		tsr_simd_halfC Input;
		tsr_simd_halfC ResurrectedHistory;
		tsr_simd_half  ResurrectedHistoryUncertainty;
		#if CONFIG_CACHE_REFETCH || CONFIG_LDS_DESPILL
		{
			tsr_simd_short2 PixelPos = ComputePixelPos();
		
			FetchHistoryGuide(
				ResurrectedHistoryGuideTexture,
				ReprojectedHistoryGuideMetadataTexture,
				PixelPos,
				/* out */ ResurrectedHistory,
				/* out */ ResurrectedHistoryUncertainty);
				
			#if CONFIG_LDS_DESPILL
				Input = ResizeChannels<3>(tsr_simd_half4::LoadLDSSpill(kDespillInput));
			#else
				tsr_simd_halfC OriginalOpaqueInput;
				tsr_simd_half4 OriginalTranslucencyInput;
				FetchSceneColorAndTranslucency(PixelPos, /* out */ OriginalOpaqueInput, /* out */ OriginalTranslucencyInput);

				Input = ComposeTranslucency(OriginalOpaqueInput, Blur3x3(OriginalTranslucencyInput));
			#endif
		}
		#else
		ResurrectedHistory = OriginalResurrectedHistory;
		Input = OriginalInput;
		#endif
		
		// Convert input to shading LDR
		tsr_simd_halfC ExposedInput = AddPerceptionAdd(Input, /* DestPerceptionAdd = */ PerceptionAdd);
		tsr_simd_halfC ExposedResurrectedHistory = ChangePerceptionAdd(
			ResurrectedHistory,
			/* SourcePerceptionAdd = */ kHistoryGuidePreceptionAdd,
			/* DestPerceptionAdd   = */ PerceptionAdd);
			
		// Mutual Annihilation
		tsr_simd_halfC ClampedResurrectedInput, ClampedResurrectedHistory;
		AnnihilateMutually3x3(ExposedInput, ExposedResurrectedHistory, /* out */ ClampedResurrectedInput, /* out */ ClampedResurrectedHistory);

		tsr_simd_half ResurrectionRejectionBlendFinal = tsr_simd_half::Const(1.0);
		tsr_simd_half ResurrectionRejectionClampBlend = tsr_simd_half::Const(1.0);
		MeasureRejection</* ApplyMoireError = */ false>(
			/* InputC0 = */    ExposedInput,
			/* InputC2 = */    ClampedResurrectedInput,
			/* HistoryC2 = */  ClampedResurrectedHistory,
			/* MoireError = */ tsr_simd_half::Const(0.0),
			/* out */ ResurrectionRejectionBlendFinal,
			/* out */ ResurrectionRejectionClampBlend);
			
		bResurrectHistory = ShouldResurrectHistory(RejectionBlendFinal, ResurrectionRejectionBlendFinal, bResurrectionIsCloser);

		RejectionBlendFinal = select(bResurrectHistory, ResurrectionRejectionBlendFinal, RejectionBlendFinal);
		RejectionClampBlend = select(bResurrectHistory, ResurrectionRejectionClampBlend, RejectionClampBlend);
	} // if (bComputeResurrection)
	#endif // CONFIG_HISTORY_RESURRECTION
	
	// Update the guide for next frame.
	tsr_simd_halfC FinalGuide;
	tsr_simd_half  InputUncertainty;
	tsr_simd_half  HistoryUncertainty;
	PLATFORM_SPECIFIC_ISOLATE
	{
		// Reload all the data from LDS or cache
		tsr_simd_halfC Input;
		tsr_simd_halfC History;
		#if CONFIG_LDS_DESPILL || CONFIG_CACHE_REFETCH
			RefetchInputAndHistoryFromLDSOrCache(
				/* out */ Input,
				/* out */ InputUncertainty,
				/* out */ History,
				/* out */ HistoryUncertainty);
		#else
			Input            = OriginalInput;
			InputUncertainty = VelocityEdge;
			History            = OriginalHistory;
			HistoryUncertainty = OriginalHistoryUncertainty;
		#endif
	
		// Apply resurrection
		#if CONFIG_HISTORY_RESURRECTION
		BRANCH
		if (AnyComponent(bResurrectHistory))
		PLATFORM_SPECIFIC_ISOLATE
		{
			// Reload the resurrected history from cache.
			tsr_simd_halfC ResurrectedHistory;
			tsr_simd_half  ResurrectedHistoryUncertainty;
			tsr_simd_float DeviceZ;
			PLATFORM_SPECIFIC_ISOLATE
			{
				tsr_simd_short2 PixePos = ComputePixelPos();
				
				#if CONFIG_CACHE_REFETCH
					FetchHistoryGuide(
						ResurrectedHistoryGuideTexture,
						ReprojectedHistoryGuideMetadataTexture,
						PixePos,
						/* out */ ResurrectedHistory,
						/* out */ ResurrectedHistoryUncertainty);
				#else
					ResurrectedHistory            = OriginalResurrectedHistory;
					ResurrectedHistoryUncertainty = OriginalResurrectedHistoryUncertainty;
				#endif
					
				FetchDeviceZ(PixePos, /* out */ DeviceZ);
			}

			// Apply the resurrection on the guide immediatly to free up registers.
			History = select(tsr_simd_boolC::Vectorize(bResurrectHistory), ResurrectedHistory, History);
			HistoryUncertainty = select(bResurrectHistory, ResurrectedHistoryUncertainty, HistoryUncertainty);
			
			// Compute the motion vector for the resurrection
			tsr_simd_float2 ResurrectionMotionVector = ComputeResurrectionMotionVector(DeviceZ);
			
			// Amends the motion vector for resurrection areas.
			UNROLL_N(SIMD_SIZE)
			for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
			{
				tsr_short2 OutputPixelPos = ComputeElementOutputPixelPos(ElementIndex);
				OutputPixelPos.x = select(bResurrectHistory.GetElement(ElementIndex), OutputPixelPos.x, tsr_short(-1));

				DilatedVelocityOutput[OutputPixelPos] = ResurrectionMotionVector.GetElement(ElementIndex);
			}
		}
		#endif // CONFIG_HISTORY_RESURRECTION

		// Convert input to LDR
		tsr_simd_halfC ExposedInput = AddPerceptionAdd(Input, /* DestPerceptionAdd = */ kHistoryGuidePreceptionAdd);
	
		FinalGuide = UpdateGuide(ExposedInput, History, bIsDisoccluded, RejectionBlendFinal);
	}

	// Controls how the history and its validity is clamped.
	tsr_simd_half  DisableHistoryClamp;
	tsr_simd_half  IncreaseValidityMultiplier;
	PLATFORM_SPECIFIC_ISOLATE
	{
		DisableHistoryClamp        = select(and(bIsDisoccluded, not(bResurrectHistory)), tsr_simd_half::Const(0.0), min(RejectionClampBlend, min(InputUncertainty, Min3x3(HistoryUncertainty))));
		IncreaseValidityMultiplier = select(and(bIsDisoccluded, not(bResurrectHistory)), tsr_simd_half::Const(0.0), RejectionClampBlend);
	}
	
	// Whether to run spatial anti-aliaser on the frame. Must match SpatialAntiAliasingLerp.
	tsr_simd_bool bSpatialAntiAlias = ShouldSpatialAntiAlias(bIsDisoccluded, bResurrectHistory, bAliasingIsVisible, RejectionBlendFinal);

	// Output data.
	PLATFORM_SPECIFIC_ISOLATE
	{
		const uint LaneIndex = GGroupThreadIndex;

		UNROLL_N(SIMD_SIZE)
		for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
		{
			const tsr_short2 LaneSimdPixelOffset = GetElementPixelOffsetInTile(LANE_STRIDE_X, LANE_STRIDE_Y, GGroupThreadIndex, ElementIndex);
			const tsr_short2 OutputPixelPos = ComputeElementOutputPixelPos(ElementIndex);

			tsr_halfC FinalGuideColor = FinalGuide.GetElement(ElementIndex);
			
			tsr_half BitMask = (
				select(bIsDisoccluded.GetElement(ElementIndex),    tsr_half(0x0), tsr_half(0x1) * rcp(tsr_half(255.0))) + 
				select(bResurrectHistory.GetElement(ElementIndex), tsr_half(0x2) * rcp(tsr_half(255.0)), tsr_half(0x0)));

			#if CONFIG_ENABLE_STOCASTIC_QUANTIZATION
			{
				uint2 Random = Rand3DPCG16(int3(LaneSimdPixelOffset, View.StateFrameIndexMod8)).xy;
				tsr_half E = tsr_half(Hammersley16(0, 1, Random).x);
		
				FinalGuideColor.rgb = QuantizeForUNormRenderTarget(FinalGuideColor.rgb, E.x, HistoryGuideQuantizationError);
			}
			#endif

			#if CONFIG_SCENE_COLOR_ALPHA
				HistoryGuideOutput[tsr_short3(OutputPixelPos, 0)] = FinalGuideColor;
				HistoryGuideOutput[tsr_short3(OutputPixelPos, 1)] = tsr_half4(InputUncertainty.GetElement(ElementIndex), 0, 0, 0);
			#else
				HistoryGuideOutput[tsr_short3(OutputPixelPos, 0)] = tsr_half4(FinalGuideColor.xyz, InputUncertainty.GetElement(ElementIndex));
			#endif
			HistoryRejectionOutput[OutputPixelPos] = tsr_half4(
				RejectionBlendFinal.GetElement(ElementIndex) - tsr_half(0.5 * rcp(256.0)),
				DisableHistoryClamp.GetElement(ElementIndex) - tsr_half(0.5 * rcp(256.0)),
				tsr_half(255.5 * rcp(256.0)) - IncreaseValidityMultiplier.GetElement(ElementIndex),
				BitMask);
			AntiAliasMaskOutput[OutputPixelPos] = select(bSpatialAntiAlias.GetElement(ElementIndex), tsr_ushort(1), tsr_ushort(0));
		}
	}
	
	#if DEBUG_OUTPUT
	{
		// Mark the top left corner of the tile for debugging purposes.
		#if DEBUG_DISABLE_PADDING == 2
		if (GGroupThreadIndex == 0)
		{
			UNROLL_N(DEBUG_ARRAY_SIZE)
			for (uint DebugId = 0; DebugId < DEBUG_ARRAY_SIZE; DebugId++)
			{
				Debug[DebugId].SetElement(/* ElementIndex = */ 0, 1.0);
			}
		}
		#endif // DEBUG_DISABLE_PADDING == 2
	
		UNROLL_N(SIMD_SIZE)
		for (uint ElementIndex = 0; ElementIndex < SIMD_SIZE; ElementIndex++)
		{
			const tsr_short2 OutputPixelPos = ComputeElementOutputPixelPos(
				/* LaneStride = */ uint2(LANE_STRIDE_X, LANE_STRIDE_Y),
				TileOverscan,
				InputInfo_ViewportMin,
				InputInfo_ViewportMax,
				GGroupId,
				GGroupThreadIndex,
				ElementIndex,
				/* OutputDataOffset = */ int2(0, 0),
				/* OutputResDivisor = */ 1,
				/* bDebugDisablePadding = */ DEBUG_DISABLE_PADDING != 0);

			UNROLL_N(DEBUG_ARRAY_SIZE)
			for (uint DebugId = 0; DebugId < DEBUG_ARRAY_SIZE; DebugId++)
			{
				DebugOutput[tsr_short3(OutputPixelPos, DebugId)] = float4(ResizeChannels<4>(Debug[DebugId]).GetElement(ElementIndex));
			}
		}
	}
	#endif // DEBUG_OUTPUT
}
