// Copyright Epic Games, Inc. All Rights Reserved.

#include "TSRCommon.ush"


//------------------------------------------------------- CONFIG

#define TILE_SIZE 8


//------------------------------------------------------- CONSTS

static tsr_half3 kWhite  = tsr_half3(0.33, 0.33, 0.33);
static tsr_half3 kRed    = tsr_half3(1.00, 0.10, 0.10);
static tsr_half3 kOrange = tsr_half3(1.00, 0.75, 0.10);
static tsr_half3 kGreen  = tsr_half3(0.10, 1.00, 0.10);
static tsr_half3 kBlue   = tsr_half3(0.10, 0.10, 1.00);


//------------------------------------------------------- PARAMETERS

FScreenTransform OutputPixelPosToScreenPos;
FScreenTransform ScreenPosToHistoryUV;
FScreenTransform ScreenPosToInputPixelPos;
float4x4 ClipToResurrectionClip;
uint2 OutputViewRectMin;
uint2 OutputViewRectMax;
uint VisualizeId;
uint bCanResurrectHistory;
float MaxHistorySampleCount;
float OutputToHistoryResolutionFractionSquare;

Texture2D<tsr_half3> SceneColorTexture;
Texture2D<float>     ClosestDepthTexture;
Texture2D<float2>    DilatedVelocityTexture;
Texture2D<tsr_half>  ParallaxRejectionMaskTexture;
Texture2D<tsr_half2> HistoryRejectionTexture;
Texture2D<tsr_half>  HistoryResurrectionMaskTexture;
Texture2D<tsr_half4> HistoryMetadataTexture;
Texture2D<tsr_half3> ResurrectedHistoryColorTexture;

RWTexture2D<tsr_half4> Output;


//------------------------------------------------------- ENTRY POINT

tsr_half3 GrayScaleColor(tsr_half3 SceneColor)
{
	tsr_half3 C = SceneColor;
	C.rgb = dot(tsr_half(0.3333).xxx, SceneColor.rgb);
	return C;
}

struct FContext
{
	tsr_short2 OutputPixelPos;
	float2 ScreenPos;
	float2 InputUV;
};

tsr_half3 SampleTSROutputColor(FContext Ctx)
{
	return SceneColorTexture[Ctx.OutputPixelPos];
}

tsr_half3 SampleTSROutputGray(FContext Ctx)
{
	return GrayScaleColor(SceneColorTexture[Ctx.OutputPixelPos]);
}

tsr_half3 DisplayHistorySampleCount(FContext Ctx)
{
	float2 HistoryUV =  ApplyScreenTransform(Ctx.ScreenPos, ScreenPosToHistoryUV);
	HistoryUV = fastClamp(HistoryUV, HistoryInfo_UVViewportBilinearMin, HistoryInfo_UVViewportBilinearMax);

	tsr_half Validity = HistoryMetadataTexture.SampleLevel(GlobalBilinearClampedSampler, HistoryUV, 0).x;

#if 0
	tsr_half SampleCount = Validity * MaxHistorySampleCount;

	const tsr_half Threshold = tsr_half(1.0) + OutputToHistoryResolutionFractionSquare;

	if (SampleCount > Threshold)
	{
		return SampleTSROutputGray(Ctx) * lerp(kOrange, kGreen, saturate((SampleCount - Threshold) / (MaxHistorySampleCount - Threshold)));
	}

	return SampleTSROutputGray(Ctx) * lerp(kRed, kOrange, saturate((SampleCount - 1.0) / (Threshold - 1.0)));
#else
	return SampleTSROutputGray(Ctx) * lerp(kRed, kGreen, saturate(Validity));
#endif
}

tsr_half3 DisplayHistoryRejection(FContext Ctx)
{
	tsr_half2 RawRejection = HistoryRejectionTexture.SampleLevel(GlobalPointClampedSampler, Ctx.InputUV, 0);
	return SampleTSROutputGray(Ctx) * lerp(kRed, kWhite, saturate(RawRejection.x));
}

tsr_half3 DisplayHistoryClamp(FContext Ctx)
{
	tsr_half2 RawRejection = HistoryRejectionTexture.SampleLevel(GlobalPointClampedSampler, Ctx.InputUV, 0);
	return SampleTSROutputGray(Ctx) * lerp(kRed, kWhite, saturate(RawRejection.y));
}

tsr_half3 DisplayParallaxDisocclusionMask(FContext Ctx)
{
	tsr_half ParallaxDisocclusionMask = ParallaxRejectionMaskTexture.SampleLevel(GlobalPointClampedSampler, Ctx.InputUV, 0);

	return SampleTSROutputGray(Ctx) * lerp(kRed, kWhite, saturate(ParallaxDisocclusionMask));
}

tsr_half3 DisplayResurrectionMask(FContext Ctx)
{
	tsr_half ResurrectionMask = HistoryResurrectionMaskTexture.SampleLevel(GlobalPointClampedSampler, Ctx.InputUV, 0);
	if (!bCanResurrectHistory)
	{
		return SampleTSROutputGray(Ctx) * kRed;
	}
	return SampleTSROutputGray(Ctx) * lerp(kWhite, kGreen, saturate(ResurrectionMask));
}

tsr_half3 DisplayResurrectedColor(FContext Ctx)
{
	float ClosestDeviceZ = ClosestDepthTexture.SampleLevel(GlobalPointClampedSampler, Ctx.InputUV, 0);
	tsr_half ResurrectionMask = HistoryResurrectionMaskTexture.SampleLevel(GlobalPointClampedSampler, Ctx.InputUV, 0);

	float4 ThisClip = float4(Ctx.ScreenPos, ClosestDeviceZ, 1);
	float4 ResurrectionClip = mul(ThisClip, ClipToResurrectionClip); 
	float2 ResurrectionScreen = ResurrectionClip.xy / ResurrectionClip.w;
	
	float2 KernelHistoryBufferUV = ApplyScreenTransform(ResurrectionScreen, ScreenPosToPrevHistoryBufferUV);
	KernelHistoryBufferUV = fastClamp(KernelHistoryBufferUV, PrevHistoryInfo_UVViewportBilinearMin, PrevHistoryInfo_UVViewportBilinearMax);

	tsr_half3 ResurrectedColor = ResurrectedHistoryColorTexture.SampleLevel(GlobalBilinearClampedSampler, KernelHistoryBufferUV, 0) * tsr_half(ResurrectionPreExposureCorrection);

	return GrayScaleColor(ResurrectedColor) * lerp(kWhite, kGreen, saturate(ResurrectionMask));
}


//------------------------------------------------------- ENTRY POINT

[numthreads(TILE_SIZE * TILE_SIZE, 1, 1)]
void MainCS(
	uint2 GroupId : SV_GroupID,
	uint GroupThreadIndex : SV_GroupIndex)
{
	uint GroupWaveIndex = GetGroupWaveIndex(GroupThreadIndex, /* GroupSize = */ TILE_SIZE * TILE_SIZE);

	float4 Debug = 0.0;
	
	FContext Ctx;
	Ctx.OutputPixelPos = (
		tsr_short2(OutputViewRectMin) +
		tsr_short2(GroupId) * tsr_short2(TILE_SIZE, TILE_SIZE) +
		Map8x8Tile2x2Lane(GroupThreadIndex));
	Ctx.ScreenPos = ApplyScreenTransform(float2(Ctx.OutputPixelPos), OutputPixelPosToScreenPos);
	Ctx.InputUV = ApplyScreenTransform(Ctx.ScreenPos, ScreenPosToInputPixelPos);
	Ctx.InputUV = fastClamp(Ctx.InputUV, InputInfo_UVViewportBilinearMin, InputInfo_UVViewportBilinearMax);

	tsr_half3 OutputColor = tsr_half(0.0);

	BRANCH
	if (VisualizeId == 0)
	{
		OutputColor = DisplayHistorySampleCount(Ctx);
	}
	else if (VisualizeId == 1)
	{
		OutputColor = DisplayParallaxDisocclusionMask(Ctx);
	}
	else if (VisualizeId == 2)
	{
		OutputColor = DisplayHistoryRejection(Ctx);
	}
	else if (VisualizeId == 3)
	{
		OutputColor = DisplayHistoryClamp(Ctx);
	}
	else if (VisualizeId == 4)
	{
		OutputColor = DisplayResurrectionMask(Ctx);
	}
	else if (VisualizeId == 5)
	{
		OutputColor = DisplayResurrectedColor(Ctx);
	}

	{
		tsr_short2 OutputPixelPos = InvalidateOutputPixelPos(Ctx.OutputPixelPos, OutputViewRectMax);
		
		Output[OutputPixelPos] = tsr_half4(OutputColor, 0.0);
		
		#if DEBUG_OUTPUT
		{
			DebugOutput[tsr_short3(OutputPixelPos, 0)] = Debug;
		}
		#endif
	}
}
