// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "StochasticShadows.ush"

#define DEBUG_SHADOW_MASK 0	

Texture2D<UNORM float> ShadingTileAtlas;
Texture2D<uint> ShadingTileGridAllocator;
StructuredBuffer<uint> ShadingTileGrid;
StructuredBuffer<uint> ShadowMaskTileAllocator;
StructuredBuffer<uint> ShadingTileAllocator;
uint MaxShadowMaskTiles;
uint MaxShadingTiles;

StructuredBuffer<uint> TileAllocator;
StructuredBuffer<uint> TileData;
uint TileDataStride;

RWTexture2D<float4> RWSceneColor;

/**
 * Apply all lights per pixel to affected tiles using shadow data from the shadow mask.
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void ShadeLightSamplesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint TileIndex = GroupId.x;
	if (TileIndex < TileAllocator[TILE_TYPE])
	{
		uint2 TileCoord = UnpackTile(TileData[TileIndex + TILE_TYPE * TileDataStride]);
		uint2 ScreenCoord = TileCoord * TILE_SIZE + GroupThreadId.xy;

		if (all(ScreenCoord < View.ViewRectMinAndSize.zw))
		{
	#if DEBUG_MODE
			int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
			bool bDebug = all(ScreenCoord == DebugScreenCoord);
			FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.55, 0.05));
	#endif

			float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
			FGBufferData GBuffer = GetGBufferData(ScreenUV);

			if (GBuffer.Depth > 0.0f)
			{
				uint2 ShadingTileCoord = TileCoord;
				uint2 CoordInShadingTile = GroupThreadId.xy;

				float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, GBuffer.Depth);		
				float3 CameraVector = normalize(TranslatedWorldPosition - View.TranslatedWorldCameraOrigin);

				float4 LightRadianceSum = 0.0f;
				uint NumShadingTilesInCell = ShadingTileGridAllocator.Load(int3(ShadingTileCoord, 0));

				#if DEBUG_MODE
				if (bDebug)
				{
					Print(Context, TEXT("ShadeSamplesCS"));
					Newline(Context);
					Print(Context, TEXT("ScreenCoord: "));
					Print(Context, ScreenCoord.x);
					Print(Context, ScreenCoord.y);
					Newline(Context);
					Print(Context, TEXT("NumShadingTilesInCell: "));
					Print(Context, NumShadingTilesInCell);
					Newline(Context);
					Print(Context, TEXT("ShadowMaskTiles: "));
					Print(Context, ShadowMaskTileAllocator[0]);
					Print(Context, MaxShadowMaskTiles);
					Print(Context, ShadowMaskTileAllocator[0] / float(MaxShadowMaskTiles));
					Print(Context, float(ShadowMaskTileAllocator[0] * 8 * 8) / (View.ViewSizeAndInvSize.x * View.ViewSizeAndInvSize.y));
					Newline(Context);
					Print(Context, TEXT("ShadingTiles:    "));
					Print(Context, ShadingTileAllocator[0]);
					Print(Context, MaxShadingTiles);
					Print(Context, ShadingTileAllocator[0] / float(MaxShadingTiles));
					Newline(Context);
					Print(Context, TEXT("LightId   | Shadow    | Irradiance"));
				}
				#endif

				for (uint IndexInCell = 0; IndexInCell < NumShadingTilesInCell; ++IndexInCell)
				{
					const uint PackedShadingTile = ShadingTileGrid[GetShadingTileGridOffset(ShadingTileCoord, IndexInCell)];
					const FShadingTile ShadingTile = UnpackShadingTile(PackedShadingTile);
					const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(ShadingTile.LocalLightIndex);
					const FLightSceneData LightSceneData = GetLightSceneData(LocalLightData.LightSceneId);
					FDeferredLightData LightData = ConvertToDeferredLight(LightSceneData);

					// Initialize as unshadowed as tiles with index >= MaxShadingTiles are treated as fully unshadowed.
					float ShadowFactor = 1.0f;

					if (ShadingTile.ShadingTileIndex < MaxShadingTiles)
					{
						uint2 ShadingTileAtlasCoord = GetShadingTileAtlasCoord(ShadingTile.ShadingTileIndex, CoordInShadingTile);
						ShadowFactor = ShadingTileAtlas[ShadingTileAtlasCoord];
					}

					#if DEBUG_MODE
					if (bDebug)
					{
						Newline(Context);
						Print(Context, LocalLightData.LightSceneId);
						Print(Context, ShadowFactor);
					}
					#endif

					#if DEBUG_SHADOW_MASK
					{
						LightRadianceSum += float4(normalize(LightData.Color) * ShadowFactor, 0.0f);
					}
					#endif

					if (ShadowFactor > 0.0f)
					{
						GBuffer.Roughness = max(GBuffer.Roughness, View.MinRoughness);

						float4 LightAttenuation = ShadowFactor;
						float Dither = 0.5f;
						float SurfaceShadow = 1;
						float AmbientOcclusion = 1.0f;

						// #ss_todo: Move more shading models to TILE_MODE_SIMPLE_SHADING
						#if TILE_TYPE == TILE_MODE_SIMPLE_SHADING
						{
							GBuffer.ShadingModelID = SHADINGMODELID_DEFAULT_LIT;
						}
						#endif
						LightData.ShadowedBits = 1;

						float4 LightRadiance = GetDynamicLighting(
							TranslatedWorldPosition,
							CameraVector,
							GBuffer, 
							AmbientOcclusion,
							GBuffer.ShadingModelID,
							LightData,
							LightAttenuation,
							Dither,
							ScreenCoord, 
							SurfaceShadow);

						#if DEBUG_MODE 
						if (bDebug)
						{
							Print(Context, LightRadiance);
						}
						#endif

						#if !DEBUG_SHADOW_MASK
						{
							LightRadianceSum += LightRadiance * View.PreExposure;
						}
						#endif
					}
				}

				// #ss_todo: replace with a pixel shader?
				RWSceneColor[ScreenCoord] = RWSceneColor[ScreenCoord] + LightRadianceSum;
			}
		}
	}
}