// Copyright Epic Games, Inc. All Rights Reserved.

#define STOCHASTIC_SHADOWS 1

#include "../Common.ush"
#include "../LightGridCommon.ush"
#include "../ShaderPrint.ush"
#include "StochasticShadows.ush"

Texture2D<uint> ShadowMaskTileAtlas;
Texture2D<uint> ShadowMaskPageTable;
StructuredBuffer<uint> ShadowMaskHashTable;
StructuredBuffer<uint2> ShadowMaskTileData;
Texture2D<float> DownsampledSceneDepth;
Texture2D<UNORM float3> DownsampledSceneWorldNormal;
uint MaxShadingTiles;

Texture2D<float4> ShadowMaskUpsampleWeights;
RWStructuredBuffer<uint> RWShadingTiles;
RWStructuredBuffer<uint> RWShadingTileAllocator;
RWTexture2D<uint> RWShadingTileGridAllocator;
RWStructuredBuffer<uint> RWShadingTileGrid;
RWTexture2D<UNORM float> RWShadingTileAtlas;

#define SHARED_TILE_BORDER 1
#define SHARED_TILE_SIZE (8 + 2 * SHARED_TILE_BORDER)
groupshared uint SharedShadowMask[SHARED_TILE_SIZE][SHARED_TILE_SIZE];
groupshared float SharedSceneDepth[SHARED_TILE_SIZE][SHARED_TILE_SIZE];

// 2x2 tile mask. 1 means that we need to spawn a shading tile for that region.
groupshared uint SharedShadingTileMask;
groupshared uint SharedShadingTileIndex[2][2];

void AccumulateShadowMask(uint2 SharedShadowMaskTileCoord, float UpsampleWeight, inout FShadowMaskAccumulator Accumulator)
{
	if (UpsampleWeight > 0.01f)
	{
		FShadowMask ShadowMask = UnpackShadowMask(SharedShadowMask[SharedShadowMaskTileCoord.x][SharedShadowMaskTileCoord.y]);
		if (ShadowMask.IsValid())
		{
			Accumulator.FactorSum += ShadowMask.Factor * UpsampleWeight;
			Accumulator.FactorSqSum += ShadowMask.FactorSq * UpsampleWeight;
			Accumulator.WeightSum += UpsampleWeight;
			Accumulator.MinAge = min(Accumulator.MinAge, ShadowMask.Age);
			Accumulator.MaxHistoryLength = max(Accumulator.MaxHistoryLength, ShadowMask.HistoryLength);
		}
	}
}

/**
 * Run spatial filtering on the shadow mask and generate upsampled shading tiles.
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void ShadowMaskSpatialPassCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint ShadowMaskTileIndex = GroupId.x;
	uint2 LocalShadowMaskTileCoord = GroupThreadId.xy;

	uint LightSceneId;
	uint LocalLightIndex;
	uint2 BaseShadowMaskScreenCoord;	
	UnpackShadowMaskTile(ShadowMaskTileData[ShadowMaskTileIndex], LightSceneId, LocalLightIndex, BaseShadowMaskScreenCoord);

	if (all(GroupThreadId == 0))
	{
		SharedShadingTileMask = 0;
	}

	if (all(GroupThreadId < 2))
	{
		SharedShadingTileIndex[GroupThreadId.x][GroupThreadId.y] = 0xFFFFFFFF;
	}

	GroupMemoryBarrierWithGroupSync();

	// Load SharedShadowMask
	for (uint SharedShadowMaskY = GroupThreadId.y; SharedShadowMaskY < SHARED_TILE_SIZE; SharedShadowMaskY += THREADGROUP_SIZE)
	{
		for (uint SharedShadowMaskX = GroupThreadId.x; SharedShadowMaskX < SHARED_TILE_SIZE; SharedShadowMaskX += THREADGROUP_SIZE)
		{
			uint2 SampleShadowMaskScreenCoord = clamp(int2(BaseShadowMaskScreenCoord) + int2(SharedShadowMaskX - SHARED_TILE_BORDER, SharedShadowMaskY - SHARED_TILE_BORDER), 0, ShadowMaskViewSize - 1);

			uint2 SampleShadowMaskPageTableCoord = GetShadowMaskPageTableCoord(LocalLightIndex, SampleShadowMaskScreenCoord);

			uint SampleShadowMaskTileIndex = INVALID_SHADOW_MASK_TILE_INDEX;
			#if HASH_TABLE
			{
				const uint PageTableKey = GetShadowMaskPageTableKey(LightSceneId, SampleShadowMaskPageTableCoord);
				const uint MaxLinearProbingSteps = 4;

				LOOP
				for (uint LinearProbingStep = 0; LinearProbingStep < MaxLinearProbingSteps; ++LinearProbingStep)
				{
					uint Index = (PageTableKey + LinearProbingStep) & ShadowMaskHashTableIndexWrapMask;
					uint PackedValue = ShadowMaskHashTable[Index];

					if (PackedValue != INVALID_SHADOW_MASK_TILE_INDEX)
					{
						FShadowMaskHashTableValue TableValue = UnpackShadowMaskHashTableValue(PackedValue);
						if (TableValue.Checksum == GetShadowMaskHashTableValueChecksum(PageTableKey))
						{
							SampleShadowMaskTileIndex = TableValue.ShadowMaskTileIndex;
							break;
						}
					}
				}
			}
			#else
			{
				SampleShadowMaskTileIndex = ShadowMaskPageTable[SampleShadowMaskPageTableCoord];
			}
			#endif			

			FShadowMask ShadowMask = InitShadowMask();

			if (SampleShadowMaskTileIndex != INVALID_SHADOW_MASK_TILE_INDEX)
			{
				uint2 SampleShadowMaskTileAtlasCoord = GetShadowMaskTileAtlasCoord(SampleShadowMaskTileIndex, SampleShadowMaskScreenCoord % SHADOW_MASK_TILE_SIZE);
				ShadowMask = UnpackShadowMask(ShadowMaskTileAtlas[SampleShadowMaskTileAtlasCoord]);
			}

			SharedShadowMask[SharedShadowMaskX][SharedShadowMaskY] = PackShadowMask(ShadowMask);
			SharedSceneDepth[SharedShadowMaskX][SharedShadowMaskY] = DownsampledSceneDepth[SampleShadowMaskScreenCoord];
		}
	}

	GroupMemoryBarrierWithGroupSync();

	uint2 ShadowMaskScreenCoord = BaseShadowMaskScreenCoord + GroupThreadId.xy;

#define DEBUG_MODE 0
#if DEBUG_MODE
	int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
	bool bDebug = all(ShadowMaskScreenCoord == DebugScreenCoord / SHADOW_MASK_DOWNSAMPLE_FACTOR);
	FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.5, 0.5));

	if (bDebug)
	{
		Print(Context, TEXT("ShadowMaskSpatialPassCS"));
	}
#endif

#if SPATIAL_PASS
	// Spatial pass
	if (all(ShadowMaskScreenCoord < ShadowMaskViewSize))
	{
		uint2 ShadowMaskTileAtlasCoord = GetShadowMaskTileAtlasCoord(ShadowMaskTileIndex, LocalShadowMaskTileCoord);
		FShadowMaskAccumulator ShadowMaskAccumulator = InitShadowMaskAccumulator();

		uint2 CenterSampleSharedTileCoord = LocalShadowMaskTileCoord + SHARED_TILE_BORDER;
		const float2 ScreenUV = (DownsampledScreenCoordToScreenCoord(ShadowMaskScreenCoord) + 0.5f) * View.BufferSizeAndInvSize.zw;
		float CenterSampleDepth = SharedSceneDepth[CenterSampleSharedTileCoord.x][CenterSampleSharedTileCoord.y];
		float3 CenterSampleNormal = normalize(DecodeNormal(DownsampledSceneWorldNormal[ShadowMaskScreenCoord]));
		float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, CenterSampleDepth);
		float4 ScenePlane = float4(CenterSampleNormal, dot(TranslatedWorldPosition, CenterSampleNormal));

		const int KernelSize = 1;
		const float KernelWeights[3] = { 1.0f, 1.0f / 2.0f, 1.0f / 3.0f };
		for (int SampleOffsetY = -KernelSize; SampleOffsetY <= KernelSize; ++SampleOffsetY)
		{
			for (int SampleOffsetX = -KernelSize; SampleOffsetX <= KernelSize; ++SampleOffsetX)
			{
				uint2 SharedShadowMaskTileCoord = (GroupThreadId.xy + SHARED_TILE_BORDER) - int2(SampleOffsetX, SampleOffsetY);
				FShadowMask SampleShadowMask = UnpackShadowMask(SharedShadowMask[SharedShadowMaskTileCoord.x][SharedShadowMaskTileCoord.y]);

				if (SampleShadowMask.IsValid())
				{
					float SampleWeight = KernelWeights[abs(SampleOffsetX)] * KernelWeights[abs(SampleOffsetY)];

					uint2 SampleShadowMaskScreenCoord = clamp((int2)BaseShadowMaskScreenCoord + (int2)SharedShadowMaskTileCoord - SHARED_TILE_BORDER, 0, ShadowMaskViewSize - 1);
					float SampleDepth = SharedSceneDepth[SharedShadowMaskTileCoord.x][SharedShadowMaskTileCoord.y];
					float3 SampleTranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(DownsampledScreenCoordToScreenUV(SampleShadowMaskScreenCoord), SampleDepth);

					float BilateralFilterDepthWeightScale = 10000.0f;
					float PlaneDistance = abs(dot(float4(SampleTranslatedWorldPosition, -1), ScenePlane));
					float RelativeDepthDifference = PlaneDistance / SampleDepth;
					SampleWeight *= exp2(-BilateralFilterDepthWeightScale * (RelativeDepthDifference * RelativeDepthDifference));

					ShadowMaskAccumulator.FactorSum += SampleShadowMask.Factor * SampleWeight;
					ShadowMaskAccumulator.FactorSqSum += Pow2(SampleShadowMask.Factor) * SampleWeight;
					ShadowMaskAccumulator.WeightSum += SampleWeight;

					if (SampleWeight > 0.0f)
					{
						ShadowMaskAccumulator.MinAge = min(ShadowMaskAccumulator.MinAge, SampleShadowMask.Age);
					}

					#if DEBUG_MODE
					if (bDebug)
					{
						Newline(Context);
						Print(Context, TEXT("SampleShadowMask: "));
						Print(Context, SampleShadowMask.Factor);
						Print(Context, GBuffer.Depth);
					}
					#endif
				}
			}
		}

		FShadowMask ShadowMask = InitShadowMask();
		if (ShadowMaskAccumulator.WeightSum > 0.0f)
		{
			ShadowMask = ShadowMaskAccumulator.ResolveShadowMask();
		}

		#if DEBUG_MODE
		if (bDebug)
		{
			if (ShadowMask.IsValid())
			{
				Newline(Context);
				Print(Context, TEXT("ShadowMask: "));
				Print(Context, ShadowMask.Factor);
				Print(Context, ShadowMask.Age);
			}
		}
		#endif

		GroupMemoryBarrierWithGroupSync();

		// Update shared shadow mask tile with filtered results
		SharedShadowMask[GroupThreadId.x + SHARED_TILE_BORDER][GroupThreadId.y + SHARED_TILE_BORDER] = PackShadowMask(ShadowMask);

		if (ShadowMask.IsValid() && ShadowMask.Factor > 0.0f)
		{
			uint2 BitCoord = LocalShadowMaskTileCoord / 4;
			uint BitMask = 1u << (BitCoord.x + BitCoord.y * 2);
			InterlockedOr(SharedShadingTileMask, BitMask);
		}
	}
#else
	// Only mark sub-tiles requiring shading tiles
	{
		FShadowMask ShadowMask = UnpackShadowMask(SharedShadowMask[GroupThreadId.x + SHARED_TILE_BORDER][GroupThreadId.y + SHARED_TILE_BORDER]);

		if (ShadowMask.IsValid() && ShadowMask.Factor > 0.0f)
		{
			uint2 BitCoord = LocalShadowMaskTileCoord / 4;
			uint BitMask = 1u << (BitCoord.x + BitCoord.y * 2);
			InterlockedOr(SharedShadingTileMask, BitMask);
		}
	}
#endif

	GroupMemoryBarrierWithGroupSync();

	uint2 ShadingTileOffset = GroupThreadId.xy;

	// Allocate shading tiles
	if (all(ShadingTileOffset < 2))
	{
		uint BitMask = 1u << (ShadingTileOffset.x + ShadingTileOffset.y * 2);
		if (BitMask & SharedShadingTileMask)
		{	
			const uint2 ShadingTileCoord = (BaseShadowMaskScreenCoord * SHADOW_MASK_DOWNSAMPLE_FACTOR) / SHADOW_MASK_TILE_SIZE + ShadingTileOffset;

			if (all(ShadingTileCoord < ShadingTileGridSize))
			{
				uint ShadingTileIndex = 0;
				InterlockedAdd(RWShadingTileAllocator[0], 1u, ShadingTileIndex);

				if (ShadingTileIndex < MaxShadingTiles)
				{
					uint ShadingTileIndexInCell = 0;
					InterlockedAdd(RWShadingTileGridAllocator[ShadingTileCoord], 1u, ShadingTileIndexInCell);

					if (ShadingTileIndexInCell < MaxShadingTilesPerGridCell)
					{
						RWShadingTileGrid[GetShadingTileGridOffset(ShadingTileCoord, ShadingTileIndexInCell)] = PackShadingTile(LightSceneId, ShadingTileIndex);
						SharedShadingTileIndex[ShadingTileOffset.x][ShadingTileOffset.y] = ShadingTileIndex;
					}
				}
			}
		}
	}

	GroupMemoryBarrierWithGroupSync();

	// Composite shading tiles
	for (uint ShadingTileOffsetY = 0; ShadingTileOffsetY < 2; ++ShadingTileOffsetY)
	{
		for (uint ShadingTileOffsetX = 0; ShadingTileOffsetX < 2; ++ShadingTileOffsetX)
		{
			uint ShadingTileIndex = SharedShadingTileIndex[ShadingTileOffsetX][ShadingTileOffsetY];

			if (ShadingTileIndex < MaxShadingTiles)
			{
				const uint2 CoordInShadingTile = GroupThreadId.xy;
				const uint2 ShadingTileCoord = (BaseShadowMaskScreenCoord * SHADOW_MASK_DOWNSAMPLE_FACTOR) / SHADOW_MASK_TILE_SIZE + uint2(ShadingTileOffsetX, ShadingTileOffsetY);
				uint2 ScreenCoord = ShadingTileCoord * SHADOW_MASK_TILE_SIZE + CoordInShadingTile;
				float4 DownsampledScreenWeights = ShadowMaskUpsampleWeights[ScreenCoord];

				const uint2 SharedShadowMaskTileCoord00 = (uint2(ShadingTileOffsetX, ShadingTileOffsetY) * SHADOW_MASK_TILE_SIZE + CoordInShadingTile + 1) / SHADOW_MASK_DOWNSAMPLE_FACTOR;

				FShadowMaskAccumulator Accumulator = InitShadowMaskAccumulator();
				AccumulateShadowMask(SharedShadowMaskTileCoord00 + uint2(0, 0), DownsampledScreenWeights.x, Accumulator);
				AccumulateShadowMask(SharedShadowMaskTileCoord00 + uint2(1, 0), DownsampledScreenWeights.y, Accumulator);
				AccumulateShadowMask(SharedShadowMaskTileCoord00 + uint2(0, 1), DownsampledScreenWeights.z, Accumulator);
				AccumulateShadowMask(SharedShadowMaskTileCoord00 + uint2(1, 1), DownsampledScreenWeights.w, Accumulator);

				float ShadowFactor = 0.0f;
				if (Accumulator.FactorSum > 0.0f && Accumulator.WeightSum > 0.0f)
				{
					ShadowFactor = Accumulator.FactorSum / Accumulator.WeightSum;
				}

				uint2 ShadingTileAtlasCoord = GetShadingTileAtlasCoord(ShadingTileIndex, CoordInShadingTile);
				RWShadingTileAtlas[ShadingTileAtlasCoord] = ShadowFactor;
			}
		}
	}
}