// Copyright Epic Games, Inc. All Rights Reserved.

#define STOCHASTIC_SHADOWS 1
#define NON_DIRECTIONAL_DIRECT_LIGHTING 1
#define SUPPORT_CONTACT_SHADOWS 0

#ifndef NUM_SAMPLES_PER_PIXEL_1D
	#error NUM_SAMPLES_PER_PIXEL_1D must be defined
#endif

#include "../Common.ush"
#include "../LightGridCommon.ush"
#include "../BlueNoise.ush"
#if DEBUG_MODE
	#include "../ShaderPrint.ush"
#endif
#include "StochasticShadows.ush"
#include "StochasticShadowsTracing.ush"

float GetLocalLightTargetPDF(FDeferredLightData LightData, float3 TranslatedWorldPosition, FGBufferData GBuffer, uint2 ScreenCoord)
{
	float SampleWeight = 0.0f;

	float3 L = LightData.Direction;
	float3 ToLight = L;

	float LightMask = GetLocalLightAttenuation(TranslatedWorldPosition, LightData, ToLight, L);

	if (LightMask > 0.0f)
	{
		float Attenuation = 0.0f;

		if (LightData.bRectLight)
		{
			FRect Rect = GetRect(ToLight, LightData);
			Attenuation = IntegrateLight(Rect);
		}
		else
		{
			FCapsuleLight Capsule = GetCapsule(ToLight, LightData);
			Attenuation = IntegrateLight(Capsule, LightData.bInverseSquared);
		}

		// #sdl_todo: figure out cheap sampling
		SampleWeight = Attenuation * LightMask * View.PreExposure * Luminance(LightData.Color);

		#define REFERENCE_SAMPLING 1
		#if REFERENCE_SAMPLING
		{
			float3 CameraVector = normalize(TranslatedWorldPosition - View.TranslatedWorldCameraOrigin);
			GBuffer.Roughness = max(GBuffer.Roughness, View.MinRoughness);

			float4 LightAttenuation = 1.0f;
			float Dither = 0.5f;
			float SurfaceShadow = 1.0f;
			float AmbientOcclusion = 1.0f;

			// #sdl_todo: Move more shading models to TILE_MODE_SIMPLE_SHADING
			#if TILE_TYPE == TILE_MODE_SIMPLE_SHADING
			{
				GBuffer.ShadingModelID = SHADINGMODELID_DEFAULT_LIT;
			}
			#endif
			LightData.ShadowedBits = 0;

			float4 LightRadiance = GetDynamicLighting(
				TranslatedWorldPosition,
				CameraVector,
				GBuffer, 
				AmbientOcclusion,
				GBuffer.ShadingModelID,
				LightData,
				LightAttenuation,
				Dither,
				ScreenCoord, 
				SurfaceShadow);

			SampleWeight = Luminance(LightRadiance.xyz * View.PreExposure);
		}
		#endif
	}

	return SampleWeight;
}

Texture2D<uint> ShadowMaskPageTable;
Texture2D<uint> ShadowMaskTileAtlas;
Texture2D<uint2> ShadowMaskHistoryScreenCoord00;
Texture2D<float4> ShadowMaskHistoryWeights;
uint2 DownsampledViewSize;
uint MaxShadowMaskTiles;
float SamplingMinWeight;
uint2 NumSamplesPerPixel;
int DebugMode;

RWTexture2D<uint2> RWShadowMaskHistoryScreenCoord00;
RWTexture2D<float4> RWShadowMaskHistoryWeights;
RWTexture2D<float> RWDownsampledSceneDepth;
RWTexture2D<UNORM float3> RWDownsampledSceneWorldNormal;
RWTexture2D<uint> RWShadowMaskPageTable;
RWStructuredBuffer<uint> RWShadowMaskTileAllocator;
RWStructuredBuffer<uint2> RWShadowMaskTileData;
RWTexture2D<uint> RWLightSamples;

float4 HistoryScreenPositionScaleBias;
float4 HistoryUVMinMax;
Texture2D<float> ShadowMaskSceneDepthHistory;

groupshared uint SharedLightMask[LIGHT_SCENE_ID_MASK_SIZE];

#if CANDIDATE_LIGHT_MASK
	groupshared uint SharedCandidateLightMask[LIGHT_SCENE_ID_MASK_SIZE];
#endif

/** 
 * Adds LightSceneId to the linear probing hash table in groupshared memory in order build a compacted list of unique light ids.
 */
void MarkLightSceneId(uint LightSceneId)
{
	// Re-distribute nearby ids to different bytes in order to balance gather workload
	uint DWORDIndex = LightSceneId % LIGHT_SCENE_ID_MASK_SIZE;
	uint BitMask = 1u << (LightSceneId / LIGHT_SCENE_ID_MASK_SIZE);
	InterlockedOr(SharedLightMask[DWORDIndex], BitMask);
}

void WriteShadowMaskTileToPageTable(uint LightSceneId, uint LocalLightIndex, uint2 ShadowMaskScreenCoord, uint ShadowMaskTileIndex)
{
	uint2 ShadowMaskPageTableCoord = GetShadowMaskPageTableCoord(LocalLightIndex, ShadowMaskScreenCoord);

	RWShadowMaskTileData[ShadowMaskTileIndex] = PackShadowMaskTile(LightSceneId, LocalLightIndex, ShadowMaskScreenCoord);

	RWShadowMaskPageTable[ShadowMaskPageTableCoord] = ShadowMaskTileIndex;
}

StructuredBuffer<uint> DownsampledTileAllocator;
StructuredBuffer<uint> DownsampledTileData;
uint DownsampledTileDataStride;
float2 DownsampledBufferInvSize;

/**
 * Run one thread per sample and generate new light samples for tracing
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void GenerateSamplesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint LinearThreadIndex = GroupThreadId.y * THREADGROUP_SIZE + GroupThreadId.x;

	if (LinearThreadIndex < LIGHT_SCENE_ID_MASK_SIZE)
	{
		SharedLightMask[LinearThreadIndex] = 0;
	}

#if CANDIDATE_LIGHT_MASK
	if (LinearThreadIndex < LIGHT_SCENE_ID_MASK_SIZE)
	{
		SharedCandidateLightMask[LinearThreadIndex] = 0;
	}
#endif

	GroupMemoryBarrierWithGroupSync();

	uint DownsampledTileIndex = GroupId.x;
	if (DownsampledTileIndex < DownsampledTileAllocator[TILE_TYPE])
	{
		uint2 DownsampledTileCoord = UnpackTile(DownsampledTileData[DownsampledTileIndex + TILE_TYPE * DownsampledTileDataStride]);
		uint2 DownsampledScreenCoord = DownsampledTileCoord * TILE_SIZE + GroupThreadId.xy;

		#if CANDIDATE_LIGHT_MASK
		if (all(DownsampledScreenCoord < DownsampledViewSize))
		{
			uint2 ScreenCoord = DownsampledScreenCoordToScreenCoord(DownsampledScreenCoord);	
			const float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
			const FGBufferData GBuffer = GetGBufferData(ScreenUV);
			const float SceneDepth = GBuffer.Depth;

			float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, SceneDepth);		

			const uint EyeIndex = 0;
			const uint GridIndex = ComputeLightGridCellIndex(ScreenCoord, SceneDepth, EyeIndex);
			const FCulledLightsGridData CulledLightGridData = GetCulledLightsGrid(GridIndex, EyeIndex);
			const uint NumLightsInGridCell = min(CulledLightGridData.NumLights, GetMaxLightsPerCell(EyeIndex));

			for (uint GridLightIndex = 0; GridLightIndex < NumLightsInGridCell; ++GridLightIndex)
			{
				const uint LocalLightIndex = GetCulledLightDataGrid(CulledLightGridData.DataStartIndex + GridLightIndex);
				const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);

				if (LocalLightData.bStochasticShadowsSupported && LocalLightIndex < MAX_LIGHT_SCENE_ID)
				{
					uint DWORDIndex = LocalLightIndex / 32;
					uint BitMask = 1u << (LocalLightIndex % 32);
					InterlockedOr(SharedCandidateLightMask[DWORDIndex], BitMask);
				}
			}
		}
		#endif
	
		GroupMemoryBarrierWithGroupSync();

		if (all(DownsampledScreenCoord < DownsampledViewSize))
		{
			uint2 ScreenCoord = DownsampledScreenCoordToScreenCoord(DownsampledScreenCoord);

	#if DEBUG_MODE
			int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
			bool bDebug = all(DownsampledScreenCoord == DebugScreenCoord / DOWNSAMPLE_FACTOR);
			FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.05, 0.05));
	#endif

			uint SelectedLights[NUM_SAMPLES_PER_PIXEL_1D];
			for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
			{
				SelectedLights[LightSampleIndex] = INVALID_LIGHT_SCENE_ID;
			}

			const uint2 LightSampleOffsets[4] = 
			{
				uint2(0, 0),
				uint2(1, 0),
				uint2(0, 1),
				uint2(1, 1),
			};

			uint2 ShadowMaskHistoryScreenCoord00 = 0;
			float4 ShadowMaskHistoryWeights = 0.0f;

			const float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
			const FGBufferData GBuffer = GetGBufferData(ScreenUV);
			const float SceneDepth = GBuffer.Depth;

			if (SceneDepth > 0)
			{
				// Prepare weights for history reprojection
				#if SHADOW_MASK_REPROJECTION_WEIGHTS
				{
					// Reproject center of downsampled texel
					float2 DownsampledScreenUV = (DownsampledScreenCoord + 0.5f) * DOWNSAMPLE_FACTOR * View.BufferSizeAndInvSize.zw;

					float DeviceZ = ConvertToDeviceZ(SceneDepth);
					float2 ScreenPosition = (DownsampledScreenUV - View.ScreenPositionScaleBias.wz) / View.ScreenPositionScaleBias.xy;
					float3 HistoryScreenPosition = GetHistoryScreenPosition(ScreenPosition, DownsampledScreenUV, DeviceZ);
					float2 HistoryScreenUV = HistoryScreenPosition.xy * HistoryScreenPositionScaleBias.xy + HistoryScreenPositionScaleBias.wz;

					bool bHistoryWasOnScreen = all(HistoryScreenUV >= HistoryUVMinMax.xy) && all (HistoryScreenUV <= HistoryUVMinMax.zw);
					if (bHistoryWasOnScreen)
					{
						uint2 HistoryScreenCoord = floor(HistoryScreenUV * View.BufferSizeAndInvSize.xy / DOWNSAMPLE_FACTOR - 0.5f);
						float2 HistoryBilinearWeights = frac(HistoryScreenUV * View.BufferSizeAndInvSize.xy / DOWNSAMPLE_FACTOR - 0.5f);
						float2 HistoryGatherUV = (HistoryScreenCoord + 1.0f) * DownsampledBufferInvSize;

						float4 HistorySampleSceneDepth4 = ShadowMaskSceneDepthHistory.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy;

						// #sdl_todo: plane weighting
						float ReprojectedSceneDepth = ConvertFromDeviceZ(HistoryScreenPosition.z);
						float DisocclusionDistanceThreshold = 0.03f;
						const float4 DistanceToHistoryValue = abs(HistorySampleSceneDepth4 - ReprojectedSceneDepth);
						float4 DepthWeights = select(DistanceToHistoryValue >= ReprojectedSceneDepth * DisocclusionDistanceThreshold, 0.0f, 1.0f);

						float4 HistoryWeights = float4(
							(1 - HistoryBilinearWeights.y) * (1 - HistoryBilinearWeights.x),
							(1 - HistoryBilinearWeights.y) * HistoryBilinearWeights.x,
							HistoryBilinearWeights.y * (1 - HistoryBilinearWeights.x),
							HistoryBilinearWeights.y * HistoryBilinearWeights.x);

						HistoryWeights *= DepthWeights;

						// Use history only if we found at least one valid sample
						if (any(HistoryWeights > 0.01f))
						{
							ShadowMaskHistoryScreenCoord00 = HistoryScreenCoord;
							ShadowMaskHistoryWeights = HistoryWeights;
						}
					}
				}
				#endif

				float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, SceneDepth);		

				const uint EyeIndex = 0;
				const uint GridIndex = ComputeLightGridCellIndex(ScreenCoord, SceneDepth, EyeIndex);
				const FCulledLightsGridData CulledLightGridData = GetCulledLightsGrid(GridIndex, EyeIndex);
				const uint NumLightsInGridCell = min(CulledLightGridData.NumLights, GetMaxLightsPerCell(EyeIndex));
				const uint NumLocalLights = GetNumLocalLights(EyeIndex);

				float LightIndexRandom[NUM_SAMPLES_PER_PIXEL_1D];
				for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
				{
					LightIndexRandom[LightSampleIndex] = BlueNoiseScalar(DownsampledScreenCoord * DOWNSAMPLE_FACTOR + LightSampleOffsets[LightSampleIndex], StochasticShadowsStateFrameIndex);
				}

				#if DEBUG_MODE
				if (bDebug)
				{
					Print(Context, TEXT("GenerateSamplesCS"));
					Newline(Context);
					Print(Context, TEXT("ScreenCoord: "));
					Print(Context, ScreenCoord.x);
					Print(Context, ScreenCoord.y);
					Newline(Context);
					Print(Context, TEXT("TileType: "));
					Print(Context, uint(TILE_TYPE));
					Print(Context, DownsampledTileAllocator[TILE_TYPE]);
					Newline(Context);
					Print(Context, TEXT("View.PreExposure: "));
					Print(Context, View.PreExposure);
					Newline(Context);
					Print(Context, TEXT("NumLightsInGridCell: "));
					Print(Context, NumLightsInGridCell);
					Print(Context, TEXT("NumLocalLights: "));
					if (NumLocalLights <= MAX_LIGHT_SCENE_ID)
					{
						Print(Context, NumLocalLights);
					}
					else
					{
						Print(Context, NumLocalLights, FontRed);
					}
					AddCrossTWS(Context, TranslatedWorldPosition, 5.0f, float4(1, 1, 0, 1));
					Newline(Context);
					Print(Context, TEXT("LightId  | SampleWeight | Weight   | Estimate | Shadow | ShadowValid | ShadowAge | HistoryLength"));
				}
				#endif

				float WeightSum = 0.0f;

				// Weighted blue noise sampling
				float Xi[NUM_SAMPLES_PER_PIXEL_1D] = LightIndexRandom;

	#if CANDIDATE_LIGHT_MASK
				for (uint MaskIndex = 0; MaskIndex < LIGHT_SCENE_ID_MASK_SIZE; ++MaskIndex)
				{
					uint CandidateLightMask = SharedCandidateLightMask[MaskIndex];
					while (CandidateLightMask != 0)
					{
						const uint NextBitIndex = firstbitlow(CandidateLightMask);
						const uint NextBitMask = 1u << NextBitIndex;
						CandidateLightMask ^= NextBitMask;

						const uint LocalLightIndex = MaskIndex * 32 + NextBitIndex;
						const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);
						const uint LightSceneId = LocalLightData.LightSceneId;
						FDeferredLightData LightData = ConvertToDeferredLight(LocalLightData);
					
						float SampleWeight = GetLocalLightTargetPDF(LightData, TranslatedWorldPosition, GBuffer, ScreenCoord);

						// Simulate tonemapping
						SampleWeight = log2(max(SampleWeight + 1.0f, 1.0f));

						// Get shadow factor from the last frame
						FShadowMask HistoryShadowMask = InitShadowMask();
						float ShadowFactorEstimate = 1.0f;

						#if SHADOW_FACTOR_ESTIMATE
						{
							if (any(ShadowMaskHistoryWeights > 0))
							{
								FShadowMaskAccumulator Accumulator = InitShadowMaskAccumulator();

								uint PrevLocalLightIndex = LocalLightData.PrevLocalLightIndex;

								AccumulateHistoryShadowMask(LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(0, 0), ShadowMaskHistoryWeights.x, Accumulator);
								AccumulateHistoryShadowMask(LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(1, 0), ShadowMaskHistoryWeights.y, Accumulator);
								AccumulateHistoryShadowMask(LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(0, 1), ShadowMaskHistoryWeights.z, Accumulator);
								AccumulateHistoryShadowMask(LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(1, 1), ShadowMaskHistoryWeights.w, Accumulator);

								if (Accumulator.WeightSum > 0.0f)
								{
									HistoryShadowMask = Accumulator.ResolveShadowMask();

									float AgeCertainty = (HistoryShadowMask.Age - 1) / float(MAX_SHADOW_MASK_AGE - 1.0f);
									ShadowFactorEstimate = lerp(HistoryShadowMask.Factor, 1.0f, saturate(AgeCertainty));
								}
							}
						}
						#endif

						#if DEBUG_MODE
						if (bDebug)
						{
							Newline(Context);
							Print(Context, LightSceneId);
							Print(Context, SampleWeight);
							Print(Context, SampleWeight * ShadowFactorEstimate);
							Print(Context, ShadowFactorEstimate);
							Print(Context, HistoryShadowMask.Factor);
							Print(Context, HistoryShadowMask.IsValid() ? 1u : 0u);
							Print(Context, HistoryShadowMask.Age);
							Print(Context, HistoryShadowMask.HistoryLength);
						}
						#endif

						if (SampleWeight > SamplingMinWeight)
						{
							// Allocate required shadow mask tiles for this frame
							MarkLightSceneId(LocalLightIndex);

							// Apply shadowing estimate from the last frame
							if (HistoryShadowMask.IsValid())
							{
								SampleWeight *= ShadowFactorEstimate;
							}

							if (SampleWeight > SamplingMinWeight)
							{
								float Tau = WeightSum / (WeightSum + SampleWeight);
								WeightSum += SampleWeight;

								for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
								{
									if (Xi[LightSampleIndex] < Tau)
									{
										Xi[LightSampleIndex] /= Tau;
									}
									else
									{
										// Select this sample
										Xi[LightSampleIndex] = (Xi[LightSampleIndex] - Tau) / (1.0f - Tau);
										SelectedLights[LightSampleIndex] = LightSceneId;
									}

									Xi[LightSampleIndex] = clamp(Xi[LightSampleIndex], 0, 0.9999f);
								}
							}
						}						
					}
				}

	#else
				for (uint GridLightIndex = 0; GridLightIndex < NumLightsInGridCell; ++GridLightIndex)
				{
					const uint LocalLightIndex = GetCulledLightDataGrid(CulledLightGridData.DataStartIndex + GridLightIndex);
					const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);

					if (LocalLightData.bStochasticShadowsSupported)
					{
						FDeferredLightData LightData = ConvertToDeferredLight(LocalLightData);
						float SampleWeight = GetLocalLightTargetPDF(LightData, TranslatedWorldPosition, GBuffer, ScreenCoord);

						// Simulate tonemapping
						SampleWeight = log2(max(SampleWeight + 1.0f, 1.0f));

						// Get shadow factor from the last frame
						FShadowMask HistoryShadowMask = InitShadowMask();
						float ShadowFactorEstimate = 1.0f;

						#if SHADOW_FACTOR_ESTIMATE
						{
							if (any(ShadowMaskHistoryWeights > 0))
							{
								FShadowMaskAccumulator Accumulator = InitShadowMaskAccumulator();

								uint PrevLocalLightIndex = LocalLightData.PrevLocalLightIndex;

								AccumulateHistoryShadowMask(LocalLightData.LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(0, 0), ShadowMaskHistoryWeights.x, Accumulator);
								AccumulateHistoryShadowMask(LocalLightData.LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(1, 0), ShadowMaskHistoryWeights.y, Accumulator);
								AccumulateHistoryShadowMask(LocalLightData.LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(0, 1), ShadowMaskHistoryWeights.z, Accumulator);
								AccumulateHistoryShadowMask(LocalLightData.LightSceneId, PrevLocalLightIndex, ShadowMaskHistoryScreenCoord00 + uint2(1, 1), ShadowMaskHistoryWeights.w, Accumulator);

								if (Accumulator.WeightSum > 0.0f)
								{
									HistoryShadowMask = Accumulator.ResolveShadowMask();

									float AgeCertainty = (HistoryShadowMask.Age - 1) / float(MAX_SHADOW_MASK_AGE - 1.0f);
									ShadowFactorEstimate = lerp(HistoryShadowMask.Factor, 1.0f, saturate(AgeCertainty));
								}
							}
						}
						#endif

						#if DEBUG_MODE
						if (bDebug)
						{
							Newline(Context);
							Print(Context, LocalLightData.LightSceneId);
							Print(Context, SampleWeight);
							Print(Context, SampleWeight * ShadowFactorEstimate);
							Print(Context, ShadowFactorEstimate);
							Print(Context, HistoryShadowMask.Factor);
							Print(Context, HistoryShadowMask.IsValid() ? 1u : 0u);
							Print(Context, HistoryShadowMask.Age);
							Print(Context, HistoryShadowMask.HistoryLength);
						}
						#endif

						if (SampleWeight > SamplingMinWeight)
						{
							// Allocate required shadow mask tiles for this frame
							MarkLightSceneId(LocalLightIndex);

							// Apply shadowing estimate from the last frame
							if (HistoryShadowMask.IsValid())
							{
								SampleWeight *= ShadowFactorEstimate;
							}

							if (SampleWeight > SamplingMinWeight)
							{
								float Tau = WeightSum / (WeightSum + SampleWeight);
								WeightSum += SampleWeight;

								for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
								{
									if (Xi[LightSampleIndex] < Tau)
									{
										Xi[LightSampleIndex] /= Tau;
									}
									else
									{
										// Select this sample
										Xi[LightSampleIndex] = (Xi[LightSampleIndex] - Tau) / (1.0f - Tau);
										SelectedLights[LightSampleIndex] = LocalLightData.LightSceneId;
									}

									Xi[LightSampleIndex] = clamp(Xi[LightSampleIndex], 0, 0.9999f);
								}
							}
						}
					}
				}
	#endif

				#if DEBUG_MODE
				if (bDebug)
				{
					Newline(Context);
					Print(Context, TEXT("Selected lights: "));

					for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
					{
						Print(Context, SelectedLights[LightSampleIndex]);

						if (DebugMode == DEBUG_MODE_VISUALIZE_SAMPLING)
						{
							const uint2 SampleCoord = DownsampledScreenCoord * DOWNSAMPLE_FACTOR + LightSampleOffsets[LightSampleIndex];
							FLightSceneData LightSceneData = GetLightSceneData(SelectedLights[LightSampleIndex]);
							FLightSampleTrace LightSampleTrace = GetLightSampleTrace(TranslatedWorldPosition, SelectedLights[LightSampleIndex], SampleCoord);
							AddLineTWS(Context, TranslatedWorldPosition, TranslatedWorldPosition + LightSampleTrace.Direction * LightSampleTrace.Distance, float4(LightSceneData.Color.xyz / Luminance(LightSceneData.Color.xyz), 1.0f));
						}
					}
				}
				#endif
			}

			// Cache common parts for later
			#if SHADOW_MASK_REPROJECTION_WEIGHTS
			{
				RWShadowMaskHistoryScreenCoord00[DownsampledScreenCoord] = ShadowMaskHistoryScreenCoord00;
				RWShadowMaskHistoryWeights[DownsampledScreenCoord] = ShadowMaskHistoryWeights;
			}
			#endif

			RWDownsampledSceneDepth[DownsampledScreenCoord] = SceneDepth;
			RWDownsampledSceneWorldNormal[DownsampledScreenCoord] = EncodeNormal(GBuffer.WorldNormal);

			for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
			{
				FLightSample LightSample;
				LightSample.LightSceneId = SelectedLights[LightSampleIndex];
				LightSample.bCompleted = LightSample.LightSceneId == INVALID_LIGHT_SCENE_ID ? true : false;
				LightSample.bVisible = true;
				RWLightSamples[DownsampledScreenCoord * NumSamplesPerPixel + LightSampleOffsets[LightSampleIndex]] = PackLightSample(LightSample);
			}
		}

		GroupMemoryBarrierWithGroupSync();

		// Write out allocated shadow mask tiles
		// #sdl_todo: process part of the list per tread
		if (LinearThreadIndex < LIGHT_SCENE_ID_MASK_SIZE)
		{
			const uint LightIndex = LinearThreadIndex;
			const uint BitMask = 1u << LightIndex;

			uint2 ShadowMaskScreenCoord = DownsampledTileCoord * SHADOW_MASK_TILE_SIZE;
	
			uint LightMask = SharedLightMask[LinearThreadIndex];
			while (LightMask != 0)
			{
				const uint NextBitIndex = firstbitlow(LightMask);
				const uint NextBitMask = 1u << NextBitIndex;
				LightMask ^= NextBitMask;

				const uint LocalLightIndex = LinearThreadIndex + NextBitIndex * LIGHT_SCENE_ID_MASK_SIZE;
				const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);
				const uint LightIndex = LocalLightData.LightSceneId;

				// #sdl_todo: merge allocations through groupshared and do only one atomic per group
				uint ShadowMaskTileIndex = 0;
				InterlockedAdd(RWShadowMaskTileAllocator[0], 1, ShadowMaskTileIndex);

				if (ShadowMaskTileIndex < MaxShadowMaskTiles)
				{
					WriteShadowMaskTileToPageTable(LightIndex, LocalLightIndex, ShadowMaskScreenCoord, ShadowMaskTileIndex);
				}
			}
		}
	}
}