// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../LightGridCommon.ush"
#include "../ShaderPrint.ush"
#include "StochasticShadows.ush"

RWBuffer<uint> RWIndirectArgs;
StructuredBuffer<uint> ShadowMaskTileAllocator;
uint MaxShadowMaskTiles;

[numthreads(THREADGROUP_SIZE, 1, 1)]
void InitShadowMaskUpdateIndirectArgsCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	if (all(DispatchThreadId == 0))
	{
		// Dispatch one group per shadow mask tile
		uint NumGroups = min(ShadowMaskTileAllocator[0], MaxShadowMaskTiles);
		WriteDispatchIndirectArgs(RWIndirectArgs, 0, NumGroups, 1, 1);
	}
}

RWTexture2D<float4> RWShadowMaskUpsampleWeights;

Texture2D<float> DownsampledSceneDepth;
float2 DownsampledBufferInvSize;

/**
 * Prepare weights for upsampling. This pulls out common per pixel shadow mask work into a separate dispatch.
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void InitShadowMaskUpsampleWeightsCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint2 ScreenCoord = DispatchThreadId.xy;

	if (all(ScreenCoord < View.ViewRectMinAndSize.zw))
	{
		float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
		FGBufferData GBuffer = GetGBufferData(ScreenUV);
		float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, GBuffer.Depth);		

		uint2 DownsampledScreenCoord = floor(ScreenUV * View.BufferSizeAndInvSize.xy / DOWNSAMPLE_FACTOR - 0.5f);
		float2 DownsampledBilinearWeights = frac(ScreenUV * View.BufferSizeAndInvSize.xy / DOWNSAMPLE_FACTOR - 0.5f);
		float2 DownsampledGatherUV = (DownsampledScreenCoord + 1.0f) * DownsampledBufferInvSize;

		float4 CornerDepths = DownsampledSceneDepth.GatherRed(GlobalPointClampedSampler, DownsampledGatherUV).wzxy;

		float4 InterpolationWeights = float4(
			(1 - DownsampledBilinearWeights.y) * (1 - DownsampledBilinearWeights.x),
			(1 - DownsampledBilinearWeights.y) * DownsampledBilinearWeights.x,
			DownsampledBilinearWeights.y * (1 - DownsampledBilinearWeights.x),
			DownsampledBilinearWeights.y * DownsampledBilinearWeights.x);

		float4 DepthWeights = 0.0f;	

		#define PLANE_WEIGHTING 1
		#if PLANE_WEIGHTING
		{
			float4 ScenePlane = float4(GBuffer.WorldNormal, dot(TranslatedWorldPosition, GBuffer.WorldNormal));

			float3 Position00 = GetTranslatedWorldPositionFromScreenUV(DownsampledScreenCoordToScreenUV(DownsampledScreenCoord + uint2(0, 0)), CornerDepths.x);
			float3 Position10 = GetTranslatedWorldPositionFromScreenUV(DownsampledScreenCoordToScreenUV(DownsampledScreenCoord + uint2(1, 0)), CornerDepths.y);
			float3 Position01 = GetTranslatedWorldPositionFromScreenUV(DownsampledScreenCoordToScreenUV(DownsampledScreenCoord + uint2(0, 1)), CornerDepths.z);
			float3 Position11 = GetTranslatedWorldPositionFromScreenUV(DownsampledScreenCoordToScreenUV(DownsampledScreenCoord + uint2(1, 1)), CornerDepths.w);

			float4 PlaneDistances;
			PlaneDistances.x = abs(dot(float4(Position00, -1), ScenePlane));
			PlaneDistances.y = abs(dot(float4(Position10, -1), ScenePlane));
			PlaneDistances.z = abs(dot(float4(Position01, -1), ScenePlane));
			PlaneDistances.w = abs(dot(float4(Position11, -1), ScenePlane));

			float4 RelativeDepthDifference = PlaneDistances / GBuffer.Depth;

			DepthWeights = select(CornerDepths > 0.0f, exp2(-10000.0f * (RelativeDepthDifference * RelativeDepthDifference)), 0.0f);
		}
		#else
		{
			float4 DepthDifference = abs(CornerDepths - GBuffer.Depth.xxxx);
			float4 RelativeDepthDifference = DepthDifference / GBuffer.Depth;	

			DepthWeights = select(CornerDepths > 0.0f, exp2(-100.0f * (RelativeDepthDifference * RelativeDepthDifference)), 0.0f);
		}
		#endif

		float Epsilon = 0.01f;
		InterpolationWeights *= DepthWeights;
		InterpolationWeights /= max(dot(InterpolationWeights, 1), Epsilon);

		RWShadowMaskUpsampleWeights[ScreenCoord] = InterpolationWeights;
	}
}

RWTexture2D<uint> RWShadowMaskTileAtlas;
StructuredBuffer<uint2> ShadowMaskTileHeader;
Texture2D<uint2> ShadowMaskHistoryScreenCoord00;
Texture2D<float4> ShadowMaskHistoryWeights;
Texture2D<uint> LightSamples;

/**
 * Run one thread per shadow mask pixel and composite current frame's traces.
 * Also output a compacted tile list for shading.
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void CompositeShadowMaskTracesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint ShadowMaskTileIndex = GroupId.x;
	uint2 LocalShadowMaskTileCoord = GroupThreadId.xy;

	uint LightSceneId = 0;
	uint2 ShadowMaskScreenCoord = 0;	
	UnpackShadowMaskTileHeader(ShadowMaskTileHeader[ShadowMaskTileIndex], LightSceneId, ShadowMaskScreenCoord);
	ShadowMaskScreenCoord += LocalShadowMaskTileCoord;

#define DEBUG_MODE 0
#if DEBUG_MODE
	int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
	bool bDebug = all(ShadowMaskScreenCoord == DebugScreenCoord / SHADOW_MASK_DOWNSAMPLE_FACTOR);
	FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.55, 0.2));

	if (bDebug)
	{
		Print(Context, TEXT("CompositeShadowMaskTracesCS"));
	}
#endif

	if (all(ShadowMaskScreenCoord < ShadowMaskViewSize))
	{
		FShadowMask ShadowMask = InitShadowMask();
		uint2 ShadowMaskTileAtlasCoord = GetShadowMaskTileAtlasCoord(ShadowMaskTileIndex, LocalShadowMaskTileCoord);

		#if TEMPORAL_ACCUMULATION
		{
			int2 ScreenCoord00 = ShadowMaskHistoryScreenCoord00[ShadowMaskScreenCoord];
			float4 Weights = ShadowMaskHistoryWeights[ShadowMaskScreenCoord];

			if (any(Weights > 0.0f))
			{
				FShadowMaskAccumulator Accumulator = InitShadowMaskAccumulator();

				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(0, 0), Weights.x, Accumulator);
				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(1, 0), Weights.y, Accumulator);
				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(0, 1), Weights.z, Accumulator);
				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(1, 1), Weights.w, Accumulator);

				if (Accumulator.WeightSum > 0.0f)
				{
					ShadowMask = Accumulator.ResolveShadowMask();
				}
			}
		}
		#endif

		// Upsample and composite current frame traces
		{
			// Accumulate traces
			FShadowMaskAccumulator Accumulator = InitShadowMaskAccumulator();
			for (uint LocalSampleY = 0; LocalSampleY < NUM_SAMPLES_PER_PIXEL_Y; ++LocalSampleY)
			{
				for (uint LocalSampleX = 0; LocalSampleX < NUM_SAMPLES_PER_PIXEL_X; ++LocalSampleX)
				{
					uint2 SampleCoord = ShadowMaskScreenCoord * uint2(NUM_SAMPLES_PER_PIXEL_X, NUM_SAMPLES_PER_PIXEL_Y) + uint2(LocalSampleX, LocalSampleY);
					FLightSample LightSample = UnpackLightSample(LightSamples[SampleCoord]);

					if (LightSample.LightSceneId == LightSceneId)
					{
						float Factor = LightSample.bVisible ? 1.0f : 0.0f;

						float Weight = 1.0f;
						Accumulator.FactorSum += Factor * Weight;
						Accumulator.FactorSqSum += Pow2(Factor) * Weight;
						Accumulator.WeightSum += Weight;
					}
				}
			}

			if (Accumulator.WeightSum > 0.0f)
			{
				// Merge with reprojected history data
				if (ShadowMask.IsValid())
				{
					float NewNumFramesAccumulated = max(Accumulator.MaxHistoryLength, 8.0f);
					float Alpha = 1.0f / (1.0f + NewNumFramesAccumulated);
					ShadowMask.Factor = lerp(ShadowMask.Factor, Accumulator.FactorSum / Accumulator.WeightSum, Alpha);
					ShadowMask.FactorSq = lerp(ShadowMask.FactorSq, Accumulator.FactorSqSum / Accumulator.WeightSum, Alpha);
					ShadowMask.Age = 0;
				}
				else
				{
					ShadowMask.Factor = Accumulator.FactorSum / Accumulator.WeightSum;
					ShadowMask.FactorSq = Accumulator.FactorSqSum / Accumulator.WeightSum;
					ShadowMask.Age = 0;
				}
			}
		}

		RWShadowMaskTileAtlas[ShadowMaskTileAtlasCoord] = PackShadowMask(ShadowMask);
	}
}