// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../LightGridCommon.ush"
#include "../ShaderPrint.ush"
#include "StochasticShadows.ush"

StructuredBuffer<uint2> ShadowMaskTileData;
Texture2D<uint2> ShadowMaskHistoryScreenCoord00;
Texture2D<float4> ShadowMaskHistoryWeights;
Texture2D<uint> LightSamples;
Texture2D<float> DownsampledSceneDepth;
Texture2D<UNORM float3> DownsampledSceneWorldNormal;
uint TemporalMaxFramesAccumulated;
float TemporalStdDevOffset;

RWTexture2D<uint> RWShadowMaskTileAtlas;

#define SHARED_TILE_BORDER 2
#define SHARED_TILE_SIZE (8 + 2 * SHARED_TILE_BORDER)
groupshared uint SharedSampleAccumulator[SHARED_TILE_SIZE][SHARED_TILE_SIZE];
groupshared float SharedSceneDepth[SHARED_TILE_SIZE][SHARED_TILE_SIZE];

struct FSampleAccumulator
{
	float SampleSum;
	float SampleWeightSum;
};

uint PackSampleAccumulator(FSampleAccumulator SampleAccumulator)
{
	return f32tof16(SampleAccumulator.SampleSum) | (f32tof16(SampleAccumulator.SampleWeightSum) << 16);
}

FSampleAccumulator UnpackSampleAccumulator(uint Packed)
{
	FSampleAccumulator SampleAccumulator;
	SampleAccumulator.SampleSum = f16tof32(Packed & 0xFFFF);
	SampleAccumulator.SampleWeightSum = f16tof32(Packed >> 16);
	return SampleAccumulator;
}

/**
 * Run one thread per shadow mask pixel and composite current frame's traces.
 * Also output a compacted tile list for shading.
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void CompositeShadowMaskTracesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint ShadowMaskTileIndex = GroupId.x;

	uint LightSceneId = 0;
	uint2 BaseShadowMaskScreenCoord = 0;	
	UnpackShadowMaskTile(ShadowMaskTileData[ShadowMaskTileIndex], LightSceneId, BaseShadowMaskScreenCoord);

	GroupMemoryBarrierWithGroupSync();
	
	// Composite traces into SharedShadowMask
	for (uint SharedShadowMaskY = GroupThreadId.y; SharedShadowMaskY < SHARED_TILE_SIZE; SharedShadowMaskY += THREADGROUP_SIZE)
	{
		for (uint SharedShadowMaskX = GroupThreadId.x; SharedShadowMaskX < SHARED_TILE_SIZE; SharedShadowMaskX += THREADGROUP_SIZE)
		{
			uint2 ShadowMaskScreenCoord = clamp(int2(BaseShadowMaskScreenCoord) + int2(SharedShadowMaskX - SHARED_TILE_BORDER, SharedShadowMaskY - SHARED_TILE_BORDER), 0, ShadowMaskViewSize - 1);
			
			FSampleAccumulator SampleAccumulator;
			SampleAccumulator.SampleSum = 0.0f;
			SampleAccumulator.SampleWeightSum = 0.0f;

			for (uint LocalSampleY = 0; LocalSampleY < NUM_SAMPLES_PER_PIXEL_Y; ++LocalSampleY)
			{
				for (uint LocalSampleX = 0; LocalSampleX < NUM_SAMPLES_PER_PIXEL_X; ++LocalSampleX)
				{
					uint2 SampleCoord = ShadowMaskScreenCoord * uint2(NUM_SAMPLES_PER_PIXEL_X, NUM_SAMPLES_PER_PIXEL_Y) + uint2(LocalSampleX, LocalSampleY);
					FLightSample LightSample = UnpackLightSample(LightSamples[SampleCoord]);

					if (LightSample.LightSceneId == LightSceneId)
					{
						SampleAccumulator.SampleSum += LightSample.bVisible ? 1 : 0;
						SampleAccumulator.SampleWeightSum += 1.0f;
					}
				}
			}

			SharedSampleAccumulator[SharedShadowMaskX][SharedShadowMaskY] = PackSampleAccumulator(SampleAccumulator);			
			SharedSceneDepth[SharedShadowMaskX][SharedShadowMaskY] = DownsampledSceneDepth[ShadowMaskScreenCoord];
		}
	}
	
	GroupMemoryBarrierWithGroupSync();

	uint2 LocalShadowMaskTileCoord = GroupThreadId.xy;
	uint2 ShadowMaskScreenCoord = BaseShadowMaskScreenCoord + LocalShadowMaskTileCoord;

#if DEBUG_MODE
	int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
	bool bDebug = all(ShadowMaskScreenCoord == DebugScreenCoord / SHADOW_MASK_DOWNSAMPLE_FACTOR) && LightSceneId == 0;
	FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.1, 0.3));

	if (bDebug)
	{
		Print(Context, TEXT("CompositeShadowMaskTraces"));
	}
#endif

	// Temporal reproject and write out new shadow masks
	if (all(ShadowMaskScreenCoord < ShadowMaskViewSize))
	{
		uint2 CenterSampleSharedTileCoord = LocalShadowMaskTileCoord + SHARED_TILE_BORDER;

		FSampleAccumulator CenterSampleAccumulator = UnpackSampleAccumulator(SharedSampleAccumulator[CenterSampleSharedTileCoord.x][CenterSampleSharedTileCoord.y]);

		FShadowMask ShadowMask = InitShadowMask();
		if (CenterSampleAccumulator.SampleWeightSum > 0.0f)
		{
			ShadowMask.Factor = CenterSampleAccumulator.SampleSum / CenterSampleAccumulator.SampleWeightSum;
			ShadowMask.FactorSq = CenterSampleAccumulator.SampleSum / CenterSampleAccumulator.SampleWeightSum;
			ShadowMask.Age = 0;
		}

		const float2 ScreenUV = (DownsampledScreenCoordToScreenCoord(ShadowMaskScreenCoord) + 0.5f) * View.BufferSizeAndInvSize.zw;
		float CenterSampleDepth = SharedSceneDepth[CenterSampleSharedTileCoord.x][CenterSampleSharedTileCoord.y];
		float3 CenterSampleNormal = normalize(DecodeNormal(DownsampledSceneWorldNormal[ShadowMaskScreenCoord]));
		float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, CenterSampleDepth);
		float4 ScenePlane = float4(CenterSampleNormal, dot(TranslatedWorldPosition, CenterSampleNormal));

		FSampleAccumulator SampleAccumulator = CenterSampleAccumulator;
		int KernelSize = 2;
		const float KernelWeights[3] = { 1.0f, 1.0f / 2.0f, 1.0f / 3.0f };
		for (int SampleOffsetY = -KernelSize; SampleOffsetY <= KernelSize; ++SampleOffsetY)
		{
			for (int SampleOffsetX = -KernelSize; SampleOffsetX <= KernelSize; ++SampleOffsetX)
			{
				if (!(SampleOffsetX == 0 && SampleOffsetY == 0))
				{
					uint2 SharedTileCoord = LocalShadowMaskTileCoord + SHARED_TILE_BORDER + int2(SampleOffsetX, SampleOffsetY);
					float SampleWeight = KernelWeights[abs(SampleOffsetX)] * KernelWeights[abs(SampleOffsetY)];

					uint2 SampleShadowMaskScreenCoord = clamp((int2)BaseShadowMaskScreenCoord + (int2)SharedTileCoord - SHARED_TILE_BORDER, 0, ShadowMaskViewSize - 1);
					float SampleDepth = SharedSceneDepth[SharedTileCoord.x][SharedTileCoord.y];
					float3 SampleTranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(DownsampledScreenCoordToScreenUV(SampleShadowMaskScreenCoord), SampleDepth);

					float BilateralFilterDepthWeightScale = 10000.0f;
					float PlaneDistance = abs(dot(float4(SampleTranslatedWorldPosition, -1), ScenePlane));
					float RelativeDepthDifference = PlaneDistance / SampleDepth;
					SampleWeight *= exp2(-BilateralFilterDepthWeightScale * (RelativeDepthDifference * RelativeDepthDifference));

					FSampleAccumulator NeighborSampleAccumulator = UnpackSampleAccumulator(SharedSampleAccumulator[SharedTileCoord.x][SharedTileCoord.y]);
					SampleAccumulator.SampleSum += SampleWeight * NeighborSampleAccumulator.SampleSum;
					SampleAccumulator.SampleWeightSum += SampleWeight * NeighborSampleAccumulator.SampleWeightSum;
				}
			}
		}

		#if DEBUG_MODE
		if (bDebug && ShadowMask.IsValid())
		{
			Newline(Context);
			Print(Context, TEXT("SampleSum: "));
			Print(Context, SampleAccumulator.SampleSum);
			Newline(Context);
			Print(Context, TEXT("SampleWeightSum: "));
			Print(Context, SampleAccumulator.SampleWeightSum);
			Newline(Context);
			Print(Context, TEXT("ShadowMask: "));
			Print(Context, ShadowMask.Factor);
		}
		#endif

		// Interpolate from the neighbourghood if we didn't trace this pixel
		if (SampleAccumulator.SampleWeightSum > 0 && CenterSampleAccumulator.SampleWeightSum == 0.0f)
		{
			ShadowMask.Factor = SampleAccumulator.SampleSum / SampleAccumulator.SampleWeightSum;
			ShadowMask.FactorSq = SampleAccumulator.SampleSum / SampleAccumulator.SampleWeightSum;
			ShadowMask.Age = 0;
		}

		#if TEMPORAL_ACCUMULATION
		{
			int2 ScreenCoord00 = ShadowMaskHistoryScreenCoord00[ShadowMaskScreenCoord];
			float4 Weights = ShadowMaskHistoryWeights[ShadowMaskScreenCoord];

			if (any(Weights > 0.0f))
			{
				FShadowMaskAccumulator Accumulator = InitShadowMaskAccumulator();

				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(0, 0), Weights.x, Accumulator);
				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(1, 0), Weights.y, Accumulator);
				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(0, 1), Weights.z, Accumulator);
				AccumulateHistoryShadowMask(LightSceneId, ScreenCoord00 + uint2(1, 1), Weights.w, Accumulator);

				if (Accumulator.WeightSum > 0.0f)
				{
					float HistoryShadowFactor = Accumulator.FactorSum / Accumulator.WeightSum;
					float HistoryShadowFactorSq = Accumulator.FactorSqSum / Accumulator.WeightSum;

					// #sdl_todo: with more samples clamp box should be smaller, instead of using a constant threshold
					// Neighborhood clamp
					if (SampleAccumulator.SampleWeightSum > 1.0f)
					{
						float Mean = SampleAccumulator.SampleSum / SampleAccumulator.SampleWeightSum;
						float Variance = max(Mean - Mean * Mean, 0.0f);
						float StdDev = sqrt(Variance) + TemporalStdDevOffset;
						float ClampMin = Mean - 0.5f * StdDev;
						float ClampMax = Mean + 0.5f * StdDev;
		
						#if DEBUG_MODE
						if (bDebug)
						{
							Newline(Context);
							Print(Context, TEXT("Clamp: "));
							Print(Context, ClampMin);
							Print(Context, ClampMax);
							Newline(Context);
							Print(Context, TEXT("HistoryShadowFactor: "));
							Newline(Context);
							Print(Context, HistoryShadowFactor);
							Newline(Context);
							Print(Context, clamp(HistoryShadowFactor, ClampMin, ClampMax));
						}
						#endif

						float ClampedHistoryShadowFactor = clamp(HistoryShadowFactor, ClampMin, ClampMax);
						float DistanceToClamped = abs(ClampedHistoryShadowFactor - HistoryShadowFactor);

						// Speedup accumulation if new samples don't fit history
						Accumulator.MaxHistoryLength *= saturate(1.0f - 2.0f * DistanceToClamped);
						HistoryShadowFactor = ClampedHistoryShadowFactor;
					}

					// Merge with reprojected history data
					if (ShadowMask.IsValid())
					{
						float NewNumFramesAccumulated = min(Accumulator.MaxHistoryLength, min(TemporalMaxFramesAccumulated, MAX_SHADOW_MASK_HISTORY_LENGTH));
						float Alpha = 1.0f / (1.0f + NewNumFramesAccumulated);
						ShadowMask.Factor = lerp(HistoryShadowFactor, ShadowMask.Factor, Alpha);
						ShadowMask.FactorSq = lerp(HistoryShadowFactorSq, ShadowMask.FactorSq, Alpha);
						ShadowMask.Age = 0;
						ShadowMask.HistoryLength = min(Accumulator.MaxHistoryLength + 1, MAX_SHADOW_MASK_HISTORY_LENGTH);
					}
					else
					{
						ShadowMask.Factor = HistoryShadowFactor;
						ShadowMask.FactorSq = HistoryShadowFactorSq;
						ShadowMask.Age = Accumulator.MinAge;
						ShadowMask.HistoryLength = Accumulator.MaxHistoryLength;
					}
				}
			}
		}
		#endif

		#if DEBUG_MODE
		if (bDebug && ShadowMask.IsValid())
		{
			Newline(Context);
			Print(Context, TEXT("Final: "));
			Print(Context, ShadowMask.Factor);
		}
		#endif

		uint2 ShadowMaskTileAtlasCoord = GetShadowMaskTileAtlasCoord(ShadowMaskTileIndex, LocalShadowMaskTileCoord);
		RWShadowMaskTileAtlas[ShadowMaskTileAtlasCoord] = PackShadowMask(ShadowMask);
	}
}