// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "../RayTracing/RayTracingCommon.ush"
#include "../SceneTexturesCommon.ush"
#include "StochasticShadows.ush"
#include "StochasticShadowsTracing.ush"
#if DEBUG_MODE
	#include "../ShaderPrint.ush"
#endif

uint StochasticShadowsStateFrameIndes;
uint2 SampleViewSize;
uint DebugMode;
RaytracingAccelerationStructure TLAS;

RWTexture2D<uint> RWLightSamples;
Texture2D<float> LightSampleRayDistance;
StructuredBuffer<uint> CompactedTraceTexelData;
StructuredBuffer<uint> CompactedTraceTexelAllocator;
Texture2D<float> DownsampledSceneDepth;

RAY_TRACING_ENTRY_RAYGEN_OR_INLINE(HardwareRayTraceLightSamples)
{
	uint ThreadIndex = DispatchThreadIndex.x;
	uint GroupIndex = DispatchThreadIndex.y;
	uint TraceTexelIndex = GroupIndex * 64 + ThreadIndex;

#if DEBUG_MODE
	FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.55, 0.3));
	if (TraceTexelIndex == 0)
	{
		Print(Context, TEXT("HardwareRayTraceLightSamples"));
		Newline(Context);
		Print(Context, TEXT("CompactedTraceTexelAllocator: "));
		Print(Context, CompactedTraceTexelAllocator[0]);
	}
#endif

	if (TraceTexelIndex < CompactedTraceTexelAllocator[0])
	{
		uint2 SampleCoord = UnpackTraceTexel(CompactedTraceTexelData[TraceTexelIndex]);
		uint2 ScreenCoord = SampleCoordToScreenCoord(SampleCoord);
		uint2 DownsampledScreenCoord = SampleCoordToDownsampledScreenCoord(SampleCoord);

		#if DEBUG_MODE
			int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
			bool bDebug = all(DebugScreenCoord / DOWNSAMPLE_FACTOR == DownsampledScreenCoord);
		#endif

		float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
		float SceneDepth = DownsampledSceneDepth[DownsampledScreenCoord];
		float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, SceneDepth);

		FLightSample LightSample = UnpackLightSample(RWLightSamples[SampleCoord]);
		FLightSampleTrace LightSampleTrace = GetLightSampleTrace(TranslatedWorldPosition, LightSample.LightSceneId, SampleCoord);
		const float LightSampleRayMinT = LightSampleRayDistance[SampleCoord];

		// #sdl_todo: proper bias
		FRayDesc Ray = (FRayDesc)0;
		Ray.Origin = TranslatedWorldPosition;
		Ray.Direction = LightSampleTrace.Direction;
		Ray.TMin = max(LightSampleRayMinT, 1.0f);
		Ray.TMax = LightSampleTrace.Distance;

		uint RayTracingFlags = RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH;
		uint RayTracingMask = RAY_TRACING_MASK_SHADOW;

		FMinimalPayload MinimalPayload = TraceVisibilityRay(
			TLAS,
			RayTracingFlags,
			RayTracingMask,
			Ray);

		if (MinimalPayload.IsHit())
		{
			LightSample.bVisible = false;
			RWLightSamples[SampleCoord] = PackLightSample(LightSample);
		}

		#if DEBUG_MODE
		if (bDebug && DebugMode == DEBUG_MODE_VISUALIZE_TRACING)
		{
			FLightSceneData LightSceneData = GetLightSceneData(LightSample.LightSceneId);
			AddLineTWS(Context, TranslatedWorldPosition + LightSampleTrace.Direction * Ray.TMin, TranslatedWorldPosition + LightSampleTrace.Direction * min(Ray.TMax, MinimalPayload.IsHit() ? MinimalPayload.HitT : 1e6), float4(LightSceneData.Color.xyz / Luminance(LightSceneData.Color.xyz), 1.0f));
		}
		#endif
	}
}