// Copyright Epic Games, Inc. All Rights Reserved.

#define STOCHASTIC_SHADOWS 1

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "../RayTracing/RayTracingCommon.ush"
#include "../SceneTexturesCommon.ush"
#include "StochasticShadows.ush"
#include "StochasticShadowsTracing.ush"
#include "../Lumen/LumenHardwareRayTracingPayloadCommon.ush"
#if DEBUG_MODE
	#include "../ShaderPrint.ush"
#endif

uint StochasticShadowsStateFrameIndes;
uint2 SampleViewSize;
uint DebugMode;
uint MaxTraversalIterations;
RaytracingAccelerationStructure TLAS;

#if LUMEN_HARDWARE_INLINE_RAYTRACING
	struct FHitGroupRootConstants
	{
		uint BaseInstanceIndex;
		uint UserData;
	};

	StructuredBuffer<FHitGroupRootConstants> HitGroupData;
	StructuredBuffer<FRayTracingSceneMetadataRecord> RayTracingSceneMetadata;
#endif

RWTexture2D<uint> RWLightSamples;
Texture2D<float> LightSampleRayDistance;
StructuredBuffer<uint> CompactedTraceTexelData;
StructuredBuffer<uint> CompactedTraceTexelAllocator;
Texture2D<float> DownsampledSceneDepth;

RAY_TRACING_ENTRY_RAYGEN_OR_INLINE(HardwareRayTraceLightSamples)
{
	uint ThreadIndex = DispatchThreadIndex.x;
	uint GroupIndex = DispatchThreadIndex.y;
	uint TraceTexelIndex = GroupIndex * 64 + ThreadIndex;

#if DEBUG_MODE
	FShaderPrintContext Context = InitShaderPrintContext(true, TraceTexelIndex == 0 ? float2(0.55, 0.4) : float2(0.55, 0.45));
	if (TraceTexelIndex == 0)
	{
		Print(Context, TEXT("HardwareRayTraceLightSamples"));
		Newline(Context);
		Print(Context, TEXT("CompactedTraceTexelAllocator: "));
		Print(Context, CompactedTraceTexelAllocator[0]);
	}
#endif

	if (TraceTexelIndex < CompactedTraceTexelAllocator[0])
	{
		uint2 SampleCoord = UnpackTraceTexel(CompactedTraceTexelData[TraceTexelIndex]);
		uint2 ScreenCoord = SampleCoordToScreenCoord(SampleCoord);
		uint2 DownsampledScreenCoord = SampleCoordToDownsampledScreenCoord(SampleCoord);

		#if DEBUG_MODE
			int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
			bool bDebug = all(DebugScreenCoord / DOWNSAMPLE_FACTOR == DownsampledScreenCoord);
		#endif

		float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
		float SceneDepth = DownsampledSceneDepth[DownsampledScreenCoord];
		float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, SceneDepth);

		FLightSample LightSample = UnpackLightSample(RWLightSamples[SampleCoord]);
		FLightSampleTrace LightSampleTrace = GetLightSampleTrace(TranslatedWorldPosition, LightSample.LightSceneId, SampleCoord);
		const float LightSampleRayMinT = LightSampleRayDistance[SampleCoord];

		// #sdl_todo: proper bias
		FRayDesc Ray = (FRayDesc)0;
		Ray.Origin = TranslatedWorldPosition;
		Ray.Direction = LightSampleTrace.Direction;
		Ray.TMin = max(LightSampleRayMinT, 1.0f);
		Ray.TMax = LightSampleTrace.Distance;

		uint RayFlags = RAY_FLAG_ACCEPT_FIRST_HIT_AND_END_SEARCH;
		uint RayMask = RAY_TRACING_MASK_OPAQUE;

		FLumenMinimalPayload Payload = (FLumenMinimalPayload)0;

		// #sdl_todo: Share it with LumenHardwareRayTracingCommon.ush
		#if LUMEN_HARDWARE_INLINE_RAYTRACING
		{
			FTraceRayInlineContext TraceRayInlineContext = CreateTraceRayInlineContext();
			TraceRayInlineContext.MaxIterations = MaxTraversalIterations;

			FTraceRayInlineResult TraceResult = TraceRayInline(TLAS, RayFlags, RayMask, Ray.GetNativeDesc(), TraceRayInlineContext);

			if (TraceResult.IsHit())
			{
				Payload.HitT = TraceResult.HitT;

				// Our SBTs always have 2 slots per material. Therefore InstanceContributionToHitGroupIndex has a RAY_TRACING_NUM_SHADER_SLOTS multiplier.
				// But because we only encode 1 material into LumenHardwareRayTracingHitDataBuffer we want to get actual material index.
				uint InstanceContributionIndex = TraceResult.InstanceContributionToHitGroupIndex / RAY_TRACING_NUM_SHADER_SLOTS;
				uint HitGroupIndex = TraceResult.GeometryIndex + InstanceContributionIndex;

				FHitGroupRootConstants HitData = HitGroupData[HitGroupIndex];

				const int Primitive = TraceResult.InstanceID;
				const int PrimitiveInstanceIndex = TraceResult.InstanceIndex - HitData.BaseInstanceIndex;
				const uint GPUSceneInstanceIndex = GetGPUSceneInstanceIndex(Primitive, PrimitiveInstanceIndex);
				Payload.SetGPUSceneInstanceIndex(GPUSceneInstanceIndex);

				uint MaterialShaderIndex = HitData.UserData & 0x3FFFFFFF;
				Payload.SetMaterialShaderIndex(MaterialShaderIndex);

				uint bIsTranslucent = (HitData.UserData >> 31) & 0x1;
				Payload.SetIsTranslucent(bIsTranslucent);

				uint bIsTwoSided = (HitData.UserData >> 30) & 0x1;
				Payload.SetIsTwoSided(bIsTwoSided);
			}
			else
			{
				Payload.SetMiss();
			}
		}
		#else
		{
			TraceRay(TLAS, RayFlags, RayMask, /*ShaderSlotIndex*/ 0, RAY_TRACING_NUM_SHADER_SLOTS, 0, Ray.GetNativeDesc(), Payload);
		}
		#endif

		if (Payload.IsHit())
		{
			LightSample.bVisible = false;
			RWLightSamples[SampleCoord] = PackLightSample(LightSample);
		}

		#if DEBUG_MODE
		if (bDebug && DebugMode == DEBUG_MODE_VISUALIZE_TRACING)
		{
			FLightSceneData LightSceneData = GetLightSceneData(LightSample.LightSceneId);
			AddLineTWS(Context, TranslatedWorldPosition + LightSampleTrace.Direction * Ray.TMin, TranslatedWorldPosition + LightSampleTrace.Direction * (Payload.IsHit() ? Payload.HitT : Ray.TMax), float4(LightSceneData.Color.xyz / Luminance(LightSceneData.Color.xyz), 1.0f));
		}
		#endif
	}
}