// Copyright Epic Games, Inc. All Rights Reserved.

#include "../NiagaraStatelessCommon.ush"

uint3 ScaleMeshSize_Distribution;
	
struct FStatelessModule_ScaleMeshSize
{
	FStatelessDistributionFloat3	MeshSizeDistribution;
};

void ScaleMeshSize_Initialize(inout FStatelessModule_ScaleMeshSize ModuleData, inout FStatelessParticle Particle)
{
	ModuleData.MeshSizeDistribution.Init(Particle, ScaleMeshSize_Distribution);
}
	
void ScaleMeshSize_Simulate(in FStatelessModule_ScaleMeshSize ModuleData, inout FStatelessParticle Particle)
{
	if (ModuleData.MeshSizeDistribution.IsValid())
	{
		Particle.Scale			*= ModuleData.MeshSizeDistribution.GetValue(Particle.NormalizedAge);
		Particle.PreviousScale	*= ModuleData.MeshSizeDistribution.GetValue(Particle.PreviousNormalizedAge);
	}
}
