// Copyright Epic Games, Inc. All Rights Reserved.

#include "../NiagaraStatelessCommon.ush"

uint3	ScaleColor_Distribution;

void ScaleColor_Simulate(inout FStatelessParticle Particle)
{
	FStatelessDistributionSamplerFloat4 ScaleDistribution;
	ScaleDistribution.Init(Particle, ScaleColor_Distribution);
	if (ScaleDistribution.IsValid())
	{
		Particle.Color *= ScaleDistribution.GetValue(Particle.NormalizedAge);
	}
}
