// Copyright Epic Games, Inc. All Rights Reserved.

#include "../NiagaraStatelessCommon.ush"

uint3 ScaleSpriteSize_Distribution;

struct FStatelessModule_ScaleSpriteSize
{
	FStatelessDistributionFloat2	ScaleDistribution;
};
	
void ScaleSpriteSize_Initialize(inout FStatelessModule_ScaleSpriteSize ModuleData, inout FStatelessParticle Particle)
{
	ModuleData.ScaleDistribution.Init(Particle, ScaleSpriteSize_Distribution);
}
	
void ScaleSpriteSize_Simulate(in FStatelessModule_ScaleSpriteSize ModuleData, inout FStatelessParticle Particle)
{
	if (ModuleData.ScaleDistribution.IsValid())
	{
		Particle.SpriteSize			*= ModuleData.ScaleDistribution.GetValue(Particle.NormalizedAge);
		Particle.PreviousSpriteSize	*= ModuleData.ScaleDistribution.GetValue(Particle.PreviousNormalizedAge);
	}
}
