// Copyright Epic Games, Inc. All Rights Reserved.

#include "../NiagaraStatelessCommon.ush"

uint3 CameraOffset_Distribution;

void CameraOffset_Simulate(inout FStatelessParticle Particle)
{
	FStatelessDistributionSamplerFloat OffsetSampler;
	OffsetSampler.Init(Particle, CameraOffset_Distribution);
	if (OffsetSampler.IsValid())
	{
		Particle.CameraOffset			= OffsetSampler.GetValue(Particle.NormalizedAge);
		Particle.PreviousCameraOffset	= OffsetSampler.GetValue(Particle.PreviousNormalizedAge);
	}
}
