// Copyright Epic Games, Inc. All Rights Reserved.

#include "/Engine/Public/Platform.ush"

#define WORK_TYPE float
#define BUFFER_TYPE float
#define READ(x) x
#define WRITE(x) x

Buffer<WORK_TYPE> Input;
RWBuffer<WORK_TYPE> Output;
int N;
int D;

groupshared WORK_TYPE SharedMemorySumExp[THREADGROUP_SIZE_X];

[numthreads(THREADGROUP_SIZE_X, 1, 1)]
void Softmax(in const uint3 DispatchThreadID : SV_DispatchThreadID, in const uint3 GroupThreadID : SV_GroupThreadID)
{
	const int StartIdx = DispatchThreadID.y * D;
	const int SharedMemoryOffsetY = GroupThreadID.y * THREADGROUP_SIZE_X;

	// Reduction using shared mem and THREADGROUP_SIZE_X thread
	// https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance
	if (DispatchThreadID.y < N)
	{
		WORK_TYPE SumExp = 0;
		int Count = 0;

		for (int CurrIdx = GroupThreadID.x; CurrIdx < D; CurrIdx += THREADGROUP_SIZE_X)
		{
			Count += 1;

			WORK_TYPE Value = READ(Input[StartIdx + CurrIdx]);

			SumExp += exp(Value);
		}

		SharedMemorySumExp[SharedMemoryOffsetY + GroupThreadID.x] = SumExp;
	}

	// Wait until all threads wrote result to shared memory
	GroupMemoryBarrierWithGroupSync();

	// Use one thread to calculate final result
	if (GroupThreadID.x == 0 && DispatchThreadID.y < N)
	{
		WORK_TYPE SumExp = 0;

		UNROLL
		for (int Idx = 0; Idx < THREADGROUP_SIZE_X; Idx++)
		{
			WORK_TYPE CurrSumExp = SharedMemorySumExp[SharedMemoryOffsetY + Idx];
			SumExp += CurrSumExp;
		}

		SharedMemorySumExp[SharedMemoryOffsetY] = SumExp;
	}

	// Wait until first thread wrote result to shared memory
	GroupMemoryBarrierWithGroupSync();

	if (DispatchThreadID.y < N)
	{
		WORK_TYPE SumExp = SharedMemorySumExp[SharedMemoryOffsetY];

		for (int CurrIdx = GroupThreadID.x; CurrIdx < D; CurrIdx += THREADGROUP_SIZE_X)
		{
			Output[StartIdx + CurrIdx] = WRITE(exp(READ(Input[StartIdx + CurrIdx])) / SumExp);
		}
	}
}