// Copyright Epic Games, Inc. All Rights Reserved.

#include "/Engine/Public/Platform.ush"

#define WORK_TYPE float
#define BUFFER_TYPE float
#define READ(x) x
#define WRITE(x) x

Buffer<WORK_TYPE> Input;
Buffer<WORK_TYPE> InputSumExp;
RWBuffer<WORK_TYPE> Output;
uint Num;
uint ThreadCountX;
uint AxisSize;

[numthreads(THREADGROUP_SIZE_X, 1, 1)]
void Softmax(in const uint3 DispatchThreadID : SV_DispatchThreadID)
{
	const uint Index = DispatchThreadID.y * ThreadCountX + DispatchThreadID.x;
	if (Index < Num)
	{
		uint SumExpIndex = Index/AxisSize;
		WORK_TYPE SumExp = READ(InputSumExp[SumExpIndex]);
		Output[Index] = WRITE(exp(READ(Input[Index])) / SumExp);
	}
}