// Copyright Epic Games, Inc. All Rights Reserved.

// Static mesh spawner kernel. Selects a primitive using a primitive cumulative distribution function (CDF) and packs attributes in custom floats.
// Passes through points to output.

#include "/Engine/Private/ComputeShaderUtils.ush"
#include "/Engine/Private/Quaternion.ush"
#include "/Plugin/PCG/Private/PCGShaderUtils.ush"

[numthreads(64, 1, 1)]
void Main(uint3 GroupId : SV_GroupID, uint GroupIndex : SV_GroupIndex)
{
	// Mark the kernel as having executed. Must run before we early out via thread index, because the kernel is still 'executed' even if the number of
	// threads to iterate on is zero. Even if GetNumThreads() returns 0, the kernel will still have been dispatched on a single thread to set this flag.
	if (all(GroupId == 0) && GroupIndex == 0)
	{
		Out_SetAsExecutedInternal();
	}

	const uint ThreadIndex = GetUnWrappedDispatchThreadId(GroupId, GroupIndex, 64);
	if (ThreadIndex >= InstanceData_GetNumInstancesAllPrimitives())
	{
		return;
	}

	// Break out thread index into DataIndex and ElementIndex
	uint DataIndex, ElementIndex;
	if (!In_GetThreadData(ThreadIndex, DataIndex, ElementIndex))
	{
		return;
	}

	const int NumPrimitives = InstanceData_GetNumPrimitives();

	uint PrimitiveIndex = 0;

	if (NumPrimitives > 1)
	{
		// Randomly select a primitive by inverting the cumulative distribution function.
		uint Seed = In_GetSeed(DataIndex, ElementIndex);
		const float RandomDraw = FRand(Seed);

		for (; PrimitiveIndex < uint(NumPrimitives) - 1; ++PrimitiveIndex)
		{
			if (RandomDraw < SMSpawner_GetPrimitiveSelectionCDF(PrimitiveIndex))
			{
				break;
			}
		}
	}

	const int InstanceIndexInt = InstanceData_GetIndexToWriteTo(PrimitiveIndex);
	if (InstanceIndexInt < 0)
	{
		// Saturated instances for this primitive. No-op.
		return;
	}

	uint Out_DataIndex, Out_ElementIndex;
	if (!Out_GetThreadData(ThreadIndex, Out_DataIndex, Out_ElementIndex))
	{
		// Should never happen.
		return;
	}

	const uint InstanceIndex = InstanceIndexInt;

	if (In_IsPointRemoved(DataIndex, ElementIndex))
	{
		// Cull the instance by setting the transform to 0.
		InstanceData_WriteInstanceLocalToWorld(InstanceIndex, (float4x4)0);
		
		// Propagate the 'Removed' status to the output point if either source or target point is removed. Otherwise, this point will not be culled.
		Out_RemovePoint(Out_DataIndex, Out_ElementIndex);

		return;
	}

	// Write instance transform.
	const float4x4 Transform = In_GetPointTransform(DataIndex, ElementIndex);
	InstanceData_WriteInstanceLocalToWorld(InstanceIndex, transpose(Transform));

	// Write instance custom float data.
	const uint DataAddress = In_GetDataAddress(DataIndex);
	const uint AttributeHeadersAddress = In_GetDataAttributeHeadersAddress(DataAddress);
	const uint NumAttributes = SMSpawner_GetNumAttributes();
	for (uint AttributeIndex = 0; AttributeIndex < NumAttributes; ++AttributeIndex)
	{
		const uint4 AttributeIdOffsetStride = SMSpawner_GetAttributeIdOffsetStride(AttributeIndex);
		const uint AttributeId = AttributeIdOffsetStride[0];
		const uint AttributeOffset = AttributeIdOffsetStride[1];
		const uint AttributeStride = AttributeIdOffsetStride[2];

		const uint AttributeHeaderAddress = In_GetAttributeHeaderAddress(AttributeHeadersAddress, AttributeId);
		const uint AttributeAddress = In_GetAttributeAddress(AttributeHeaderAddress);

		for (uint FloatIndex = 0; FloatIndex < AttributeStride; ++FloatIndex)
		{
			const uint AttributeValueAddress = AttributeAddress + ElementIndex * AttributeStride * 4;
			
			// Assumes floating point data. TODO add type information and deal with different types in different ways?
			InstanceData_WriteCustomFloatRaw(InstanceIndex, AttributeOffset + FloatIndex, In_LoadBufferInternal(AttributeValueAddress));
		}
	}

	// Write output point data (pass through).
	// TODO - support writing mesh bounds.
	Out_SetPosition(Out_DataIndex, Out_ElementIndex, In_GetPosition(DataIndex, ElementIndex));
	Out_SetRotation(Out_DataIndex, Out_ElementIndex, In_GetRotation(DataIndex, ElementIndex));
	Out_SetScale(Out_DataIndex, Out_ElementIndex, In_GetScale(DataIndex, ElementIndex));
	Out_SetBoundsMin(Out_DataIndex, Out_ElementIndex, In_GetBoundsMin(DataIndex, ElementIndex));
	Out_SetBoundsMax(Out_DataIndex, Out_ElementIndex, In_GetBoundsMax(DataIndex, ElementIndex));
	Out_SetColor(Out_DataIndex, Out_ElementIndex, In_GetColor(DataIndex, ElementIndex));
	Out_SetSeed(Out_DataIndex, Out_ElementIndex, In_GetSeed(DataIndex, ElementIndex));
	Out_SetDensity(Out_DataIndex, Out_ElementIndex, In_GetDensity(DataIndex, ElementIndex));
	Out_SetSteepness(Out_DataIndex, Out_ElementIndex, In_GetSteepness(DataIndex, ElementIndex));
}
