// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

// Change this to force recompilation of all Sampled Direct Lighting shaders
#pragma message("UESHADERMETADATA_VERSION 1A63AC4B-2335-2AD1-2CAB-82295C72CAFC")

#define SAMPLED_DIRECT_LIGHTING 1
#include "../LightGridCommon.ush"

#define SUPPORT_CONTACT_SHADOWS 0
#define NON_DIRECTIONAL_DIRECT_LIGHTING 0
#include "../DeferredLightingCommon.ush"
#include "../SceneData.ush"
#include "../Hash.ush"

#if DEBUG_MODE
	#include "../ShaderPrint.ush"
#endif

#define DEBUG_MODE_VISUALIZE_SAMPLING 1
#define DEBUG_MODE_VISUALIZE_TRACING  2

// Limited by PackLightSample
#define LOCAL_LIGHT_INDEX_BITS		(14)
#define LOCAL_LIGHT_INDEX_MASK		((1 << LOCAL_LIGHT_INDEX_BITS) - 1)
#define INVALID_LOCAL_LIGHT_INDEX	(LOCAL_LIGHT_INDEX_MASK)

// Keep in sync with SampledDirectLighting.cpp
#define SHADING_ATLAS_SIZE_IN_TILES 512
#define DOWNSAMPLE_FACTOR			2
#define TILE_SIZE					8
#define MAX_LOCAL_LIGHT_INDEX_XY	16
#define MAX_LOCAL_LIGHT_INDEX		(MAX_LOCAL_LIGHT_INDEX_XY * MAX_LOCAL_LIGHT_INDEX_XY)

#define SHARED_LIGHT_MASK_SIZE		(MAX_LOCAL_LIGHT_INDEX / 32)

// Keep in sync with SampledDirectLighting::ETileType
#define TILE_MODE_SIMPLE_SHADING	0
#define TILE_MODE_COMPLEX_SHADING	1
#define TILE_MODE_EMPTY				2
#define TILE_MODE_MAX				3

uint PackTile(uint2 TileCoord)
{
	return TileCoord.x | (TileCoord.y << 16);
}

uint2 UnpackTile(uint PackedTile)
{
	return uint2(PackedTile & 0xFFFF, PackedTile >> 16);
}

float3 GetTranslatedWorldPositionFromScreenUV(float2 ScreenUV, float SceneDepth)
{
	float2 ScreenPosition = (ScreenUV - View.ScreenPositionScaleBias.wz) / View.ScreenPositionScaleBias.xy;
	float3 TranslatedWorldPosition = mul(float4(GetScreenPositionForProjectionType(ScreenPosition, SceneDepth), SceneDepth, 1), View.ScreenToTranslatedWorld).xyz;
	return TranslatedWorldPosition;
}	

float3 GetHistoryScreenPosition(float2 ScreenPosition, float2 ScreenUV, float DeviceZ)
{
	float3 HistoryScreenPosition = float3(ScreenPosition, DeviceZ);
	bool bIsDynamicPixel = false;

	{
		float4 ThisClip = float4(HistoryScreenPosition, 1);
		float4 PrevClip = mul(ThisClip, View.ClipToPrevClip); //<=== doesn't contain AA offsets

		float3 PrevScreen = PrevClip.xyz / PrevClip.w;
		float3 Velocity = HistoryScreenPosition - PrevScreen;
		float4 EncodedVelocity = GBufferVelocityTexture.SampleLevel(GlobalPointClampedSampler, ScreenUV, 0);
		bIsDynamicPixel = EncodedVelocity.x > 0.0;

		if (bIsDynamicPixel)
		{
			// Note: overwriting velocity, this only works if DeviceZ matches what's in the depth buffer
			Velocity = DecodeVelocityFromTexture(EncodedVelocity);
		}

		HistoryScreenPosition -= Velocity;
	}

	return HistoryScreenPosition;
}

uint2 GetShadingTileAtlasCoord(uint ShadingTileIndex, uint2 CoordInTile)
{
	uint2 AtlasCoord;
	AtlasCoord.x = (ShadingTileIndex % SHADING_ATLAS_SIZE_IN_TILES) * TILE_SIZE + CoordInTile.x;
	AtlasCoord.y = (ShadingTileIndex / SHADING_ATLAS_SIZE_IN_TILES) * TILE_SIZE + CoordInTile.y;
	return AtlasCoord;
}

struct FLightSample
{
	uint LocalLightIndex;
	float Weight;
	bool bVisible;
	bool bCompleted; // Whether tracing was completed
};

FLightSample InitLightSample()
{
	FLightSample LightSample;
	LightSample.LocalLightIndex = INVALID_LOCAL_LIGHT_INDEX;
	LightSample.Weight = 0.0f;
	LightSample.bVisible = false;
	LightSample.bCompleted = true;
	return LightSample;
}

uint PackLightSample(FLightSample LightSample)
{
	uint PackedLightSample = LightSample.LocalLightIndex & LOCAL_LIGHT_INDEX_MASK;
	PackedLightSample |= LightSample.bVisible ? 0x8000 : 0;
	PackedLightSample |= LightSample.bCompleted ? 0x4000 : 0;
	PackedLightSample |= f32tof16(LightSample.Weight) << 16;
	return PackedLightSample;
}

FLightSample UnpackLightSample(uint PackedLightSample)
{
	FLightSample LightSample;
	LightSample.LocalLightIndex = PackedLightSample & 0x3FFF;
	LightSample.bVisible = PackedLightSample & 0x8000 ? true : false;
	LightSample.bCompleted = PackedLightSample & 0x4000 ? true : false;
	LightSample.Weight = f16tof32(PackedLightSample >> 16);
	return LightSample;
}

uint SampledDirectLightingStateFrameIndex;

/** 
 * Returns sample jitter offset in the range [0, DOWNSAMPLE_FACTOR - 1]
 */
uint2 GetSampleScreenCoordJitter()
{
	return Hammersley16(SampledDirectLightingStateFrameIndex, 8, 0) * DOWNSAMPLE_FACTOR;
}

/** 
 * Returns sample jitter offset in the range [0, DOWNSAMPLE_FACTOR - 1] from the last frame
 */
uint2 GetHistorySampleScreenCoordJitter()
{
	return Hammersley16(SampledDirectLightingStateFrameIndex + 7, 8, 0) * DOWNSAMPLE_FACTOR;
}

uint2 DownsampledScreenCoordToScreenCoord(uint2 DownsampledScreenCoord)
{
	return DownsampledScreenCoord * DOWNSAMPLE_FACTOR + GetSampleScreenCoordJitter();
}

float2 DownsampledScreenCoordToScreenUV(uint2 DownsampledScreenCoord)
{
	uint2 ScreenCoord = DownsampledScreenCoordToScreenCoord(DownsampledScreenCoord);
	float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
	return ScreenUV;
}

uint2 PackCompositeTile(uint LocalLightIndex, uint2 DownsampledScreenCoord)
{
	DownsampledScreenCoord /= TILE_SIZE;

	uint2 PackedTile;
	PackedTile.x = LocalLightIndex;
	PackedTile.y = (DownsampledScreenCoord.x & 0xFFFF) | ((DownsampledScreenCoord.y & 0xFFFF) << 16);
	return PackedTile;
}

void UnpackCompositeTile(uint2 PackedTile, out uint LocalLightIndex, out uint2 DownsampledScreenCoord)
{
	LocalLightIndex = PackedTile.x;
	DownsampledScreenCoord.x = PackedTile.y & 0xFFFF;
	DownsampledScreenCoord.y = PackedTile.y >> 16;

	DownsampledScreenCoord *= TILE_SIZE;
}

struct FShadingTile
{
	uint LocalLightIndex;
	uint ShadingTileIndex;
};

uint PackShadingTile(uint LocalLightIndex, uint ShadingTileIndex)
{
	uint PackedShadingTile = LocalLightIndex & 0xFFF;
	PackedShadingTile |= ShadingTileIndex << 12;
	return PackedShadingTile;
}

FShadingTile UnpackShadingTile(uint PackedShadingTile)
{
	FShadingTile ShadingTile;
	ShadingTile.LocalLightIndex = PackedShadingTile & 0xFFF;
	ShadingTile.ShadingTileIndex = PackedShadingTile >> 12;
	return ShadingTile;
}

uint2 ShadingTileGridSize;
uint MaxShadingTilesPerGridCell;

uint GetShadingTileGridOffset(uint2 ShadingTileCoord, uint IndexInCell)
{
	return (ShadingTileCoord.x + ShadingTileCoord.y * ShadingTileGridSize.x) * MaxShadingTilesPerGridCell + IndexInCell;
}

// Remove texture detail before denoising
float3 SafeDemodulate(float3 Lighting, float3 Texture)
{
	return Lighting / max(Texture, 0.001f);
}

// Restore texture detail after denoising
float3 SafeModulate(float3 Lighting, float3 Texture)
{
	return Lighting * max(Texture, 0.001f);
}