// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "SampledDirectLighting.ush"

RWTexture2D<float3> RWDiffuseLighting;
RWTexture2D<float3> RWSpecularLighting;
RWTexture2D<float4> RWLuminanceMoments;

Texture2D<float> ShadingTileAtlas;
Texture2D<uint> ShadingTileGridAllocator;
StructuredBuffer<uint> ShadingTileGrid;
StructuredBuffer<uint> CompositeTileAllocator;
StructuredBuffer<uint> ShadingTileAllocator;
uint MaxCompositeTiles;
uint MaxShadingTiles;

StructuredBuffer<uint> TileAllocator;
StructuredBuffer<uint> TileData;
uint TileDataStride;

float3 SafeDemodulate(float3 L, float3 C)
{
	L.x = C.x >= 0.01f ? L.x / C.x : L.x;
	L.y = C.y >= 0.01f ? L.y / C.y : L.y;
	L.z = C.z >= 0.01f ? L.z / C.z : L.z;
	return L;
}

/**
 * Apply all lights per pixel to affected tiles using sampled weights from upscaled shading tiles
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void ShadeLightSamplesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint TileIndex = GroupId.x;
	if (TileIndex < TileAllocator[TILE_TYPE])
	{
		uint2 TileCoord = UnpackTile(TileData[TileIndex + TILE_TYPE * TileDataStride]);
		uint2 ScreenCoord = TileCoord * TILE_SIZE + GroupThreadId.xy;

		if (all(ScreenCoord < View.ViewRectMinAndSize.zw))
		{
	#if DEBUG_MODE
			int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
			bool bDebug = all(ScreenCoord == DebugScreenCoord);
			FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.55, 0.05));
	#endif

			float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
			FGBufferData GBuffer = GetGBufferData(ScreenUV);

			if (GBuffer.Depth > 0.0f)
			{
				uint2 ShadingTileCoord = TileCoord;
				uint2 CoordInShadingTile = GroupThreadId.xy;

				float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, GBuffer.Depth);		
				float3 CameraVector = normalize(TranslatedWorldPosition - View.TranslatedWorldCameraOrigin);

				uint NumShadingTilesInCell = ShadingTileGridAllocator.Load(int3(ShadingTileCoord, 0));

				#if DEBUG_MODE
				if (bDebug)
				{
					Print(Context, TEXT("ShadeSamplesCS"));
					Newline(Context);
					Print(Context, TEXT("ScreenCoord: "));
					Print(Context, ScreenCoord.x);
					Print(Context, ScreenCoord.y);
					Newline(Context);
					Print(Context, TEXT("NumShadingTilesInCell: "));
					Print(Context, NumShadingTilesInCell);
					Newline(Context);
					Print(Context, TEXT("ShadingTiles:    "));
					Print(Context, ShadingTileAllocator[0]);
					Print(Context, MaxShadingTiles);
					Print(Context, ShadingTileAllocator[0] / float(MaxShadingTiles));
					Newline(Context);
					Print(Context, TEXT("LightId   | Weight    | Diffuse   | Specular"));
				}
				#endif

				const float3 N = GBuffer.WorldNormal;
				const float3 V = normalize(View.TranslatedWorldCameraOrigin - TranslatedWorldPosition);
				const float NoV = saturate(dot(N, V));
				const float3 SpecularEnv = EnvBRDF(GBuffer.SpecularColor, GBuffer.Roughness, NoV);

				float3 DiffuseLighting = 0.0f;
				float3 SpecularLighting = 0.0f;
				float2 DiffuseLuminanceMoments = 0.0f;
				float2 SpecularLuminanceMoments = 0.0f;

				for (uint IndexInCell = 0; IndexInCell < NumShadingTilesInCell; ++IndexInCell)
				{
					const uint PackedShadingTile = ShadingTileGrid[GetShadingTileGridOffset(ShadingTileCoord, IndexInCell)];
					const FShadingTile ShadingTile = UnpackShadingTile(PackedShadingTile);
					const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(ShadingTile.LocalLightIndex);
					const FLightSceneData LightSceneData = GetLightSceneData(LocalLightData.LightSceneId);
					FDeferredLightData LightData = ConvertToDeferredLight(LightSceneData);

					float SampleWeight = 0.0f;

					if (ShadingTile.ShadingTileIndex < MaxShadingTiles)
					{
						uint2 ShadingTileAtlasCoord = GetShadingTileAtlasCoord(ShadingTile.ShadingTileIndex, CoordInShadingTile);
						SampleWeight = ShadingTileAtlas[ShadingTileAtlasCoord];
					}

					#if DEBUG_MODE
					if (bDebug)
					{
						Newline(Context);
						Print(Context, LocalLightData.LightSceneId);
						Print(Context, SampleWeight);
					}
					#endif

					if (SampleWeight > 0.0f)
					{
						GBuffer.Roughness = max(GBuffer.Roughness, View.MinRoughness);

						float4 LightAttenuation = 1.0f;
						float Dither = 0.5f;
						float SurfaceShadow = 1;
						float AmbientOcclusion = 1.0f;

						// #sdl_todo: Move more shading models to TILE_MODE_SIMPLE_SHADING
						#if TILE_TYPE == TILE_MODE_SIMPLE_SHADING
						{
							GBuffer.ShadingModelID = SHADINGMODELID_DEFAULT_LIT;
						}
						#endif
						GBuffer.ShadingModelID = SHADINGMODELID_DEFAULT_LIT;
						LightData.ShadowedBits = 0;

						FDeferredLightingSplit SplitLighting = GetDynamicLightingSplit(
							TranslatedWorldPosition, CameraVector, GBuffer, AmbientOcclusion, GBuffer.ShadingModelID, 
							LightData, LightAttenuation, Dither, ScreenCoord, 
							SurfaceShadow);
		
						// Apply pre-exposure
						SplitLighting.DiffuseLighting.xyz *= View.PreExposure;
						SplitLighting.SpecularLighting.xyz *= View.PreExposure;

						// #sdl_todo: demodulate earlier during BRDF evaluation
						SplitLighting.DiffuseLighting.xyz = SafeDemodulate(SplitLighting.DiffuseLighting.xyz, GBuffer.DiffuseColor);
						SplitLighting.SpecularLighting.xyz = SafeDemodulate(SplitLighting.SpecularLighting.xyz, SpecularEnv);

						DiffuseLighting += SplitLighting.DiffuseLighting.xyz * SampleWeight;
						SpecularLighting += SplitLighting.SpecularLighting.xyz * SampleWeight;

						DiffuseLuminanceMoments.x += Luminance(SplitLighting.DiffuseLighting.xyz) * SampleWeight;
						DiffuseLuminanceMoments.y += Pow2(Luminance(SplitLighting.DiffuseLighting.xyz)) * SampleWeight;

						SpecularLuminanceMoments.x += Luminance(SplitLighting.SpecularLighting.xyz) * SampleWeight;
						SpecularLuminanceMoments.y += Pow2(Luminance(SplitLighting.SpecularLighting.xyz)) * SampleWeight;

						#if DEBUG_MODE 
						if (bDebug)
						{
							Print(Context, SplitLighting.DiffuseLighting.xyz);
							Print(Context, SplitLighting.SpecularLighting.xyz);
						}
						#endif
					}
				}

				#if DEBUG_MODE
				if (bDebug)
				{
					Newline(Context);
					Print(Context, TEXT("Diffuse: ")); 
					Print(Context, DiffuseLighting);
					Newline(Context);
					Print(Context, TEXT("Specular: ")); 
					Print(Context, SpecularLighting);
				}
				#endif

				// #sdl_todo: can first moment be derived from Diffuse/Specular Lighting?
				RWDiffuseLighting[ScreenCoord] = DiffuseLighting;
				RWSpecularLighting[ScreenCoord] = SpecularLighting;
				RWLuminanceMoments[ScreenCoord] = float4(DiffuseLuminanceMoments, SpecularLuminanceMoments);
			}
		}
	}
}