// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "SampledDirectLighting.ush"

Texture2D ResolvedDiffuseLighting;
Texture2D ResolvedSpecularLighting;
Texture2D ResolvedLuminanceMoments;
Texture2D SampledDirectLightingDepthHistory;
Texture2D DiffuseLightingHistoryTexture;
Texture2D SpecularLightingHistoryTexture;
Texture2D LuminanceMomentsHistoryTexture;
Texture2D<UNORM float> NumFramesAccumulatedHistoryTexture;

float4 HistoryScreenPositionScaleBias;
float4 HistoryUVMinMax;
float PrevSceneColorPreExposureCorrection;
float TemporalMaxFramesAccumulated;
float TemporalNeighborhoodClampScale;

RWTexture2D<float4> RWDiffuseLighting;
RWTexture2D<float4> RWSpecularLighting;
RWTexture2D<float4> RWLuminanceMoments;
RWTexture2D<UNORM float> RWNumFramesAccumulated;
RWTexture2D<float> RWSceneDepth;
RWTexture2D<float4> RWSceneColor;

struct FNeighborhoodClamp
{
	float3 Min;
	float3 Max;
};

FNeighborhoodClamp GetNeighborhoodClamp(
	uint2 ScreenCoord, 
	Texture2D SampleTexture,
	float3 CenterSample)
{
	float3 SampleSum = CenterSample;
	float3 SampleSqSum = Pow2(CenterSample);

	// #sdl_todo: optimize using groupshared and cross-lane ops
	const int KernelSize = 1;
	for (int SampleOffsetY = -KernelSize; SampleOffsetY <= KernelSize; ++SampleOffsetY)
	{
		for (int SampleOffsetX = -KernelSize; SampleOffsetX <= KernelSize; ++SampleOffsetX)
		{
			if (!(SampleOffsetX == 0 && SampleOffsetY == 0))
			{
				uint2 SampleScreenCoord = clamp(ScreenCoord + int2(SampleOffsetX, SampleOffsetY), 0u, View.ViewRectMinAndSize.zw - 1);
				float3 Sample = SampleTexture[SampleScreenCoord].xyz;
				
				SampleSum += Sample;
				SampleSqSum += Pow2(Sample);
			}
		}
	}

	float NumSamples = Pow2(2.0f * KernelSize + 1.0f);
	float3 M1 = SampleSum / NumSamples;
	float3 M2 = SampleSqSum / NumSamples;
	float3 Variance = max(M2 - Pow2(M1), 0.0f);
	float3 StdDev = sqrt(Variance);

	FNeighborhoodClamp NeighborhoodClamp = (FNeighborhoodClamp)0;
	NeighborhoodClamp.Min = M1 - TemporalNeighborhoodClampScale * StdDev;
	NeighborhoodClamp.Max = M1 + TemporalNeighborhoodClampScale * StdDev;
	return NeighborhoodClamp;
}

[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void SampledDirectLightingTemporalAccumulationCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint2 ScreenCoord = DispatchThreadId.xy;

#if DEBUG_MODE
	int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
	bool bDebug = all(ScreenCoord == DebugScreenCoord);
	FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.55, 0.3));
#endif

	if (all(ScreenCoord < View.ViewRectMinAndSize.zw))
	{
		float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
		FGBufferData GBuffer = GetGBufferData(ScreenUV);

		const float DeviceZ = SceneDepthTexture[ScreenCoord].x;
		GBuffer.Depth = ConvertFromDeviceZ(DeviceZ);

		if (GBuffer.Depth > 0.0f && GBuffer.ShadingModelID != SHADINGMODELID_UNLIT)
		{
			float3 DiffuseLighting = ResolvedDiffuseLighting[ScreenCoord].xyz;
			float3 SpecularLighting = ResolvedSpecularLighting[ScreenCoord].xyz;
			float4 LuminanceMoments = ResolvedLuminanceMoments[ScreenCoord].xyzw;
			float2 DiffuseLumimanceMoments = LuminanceMoments.xy;
			float2 SpecularLumimanceMoments = LuminanceMoments.zw;
			float NumFramesAccumulated = 0.0f;

			#if VALID_HISTORY
			{
				float2 ScreenPosition = (ScreenUV - View.ScreenPositionScaleBias.wz) / View.ScreenPositionScaleBias.xy;
				float3 HistoryScreenPosition = GetHistoryScreenPosition(ScreenPosition, ScreenUV, DeviceZ);
				float2 HistoryScreenUV = HistoryScreenPosition.xy * HistoryScreenPositionScaleBias.xy + HistoryScreenPositionScaleBias.wz;

				bool bHistoryWasOnScreen = all(HistoryScreenUV >= HistoryUVMinMax.xy) && all (HistoryScreenUV <= HistoryUVMinMax.zw);
				if (bHistoryWasOnScreen)
				{
					uint2 HistoryScreenCoord = floor(HistoryScreenUV * View.BufferSizeAndInvSize.xy - 0.5f);
					float2 HistoryBilinearWeights = frac(HistoryScreenUV * View.BufferSizeAndInvSize.xy - 0.5f);
					float2 HistoryGatherUV = (HistoryScreenCoord + 1.0f) * View.BufferSizeAndInvSize.zw;

					float4 HistorySampleSceneDepth4 = SampledDirectLightingDepthHistory.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy;

					// #sdl_todo: plane weighting
					float ReprojectedSceneDepth = ConvertFromDeviceZ(HistoryScreenPosition.z);
					float DisocclusionDistanceThreshold = 0.03f;
					const float4 DistanceToHistoryValue = abs(HistorySampleSceneDepth4 - ReprojectedSceneDepth);
					float4 DepthWeights = select(DistanceToHistoryValue >= ReprojectedSceneDepth * DisocclusionDistanceThreshold, 0.0f, 1.0f);

					float4 HistoryWeights = float4(
						(1 - HistoryBilinearWeights.y) * (1 - HistoryBilinearWeights.x),
						(1 - HistoryBilinearWeights.y) * HistoryBilinearWeights.x,
						HistoryBilinearWeights.y * (1 - HistoryBilinearWeights.x),
						HistoryBilinearWeights.y * HistoryBilinearWeights.x);

					HistoryWeights *= DepthWeights;

					#if DEBUG_MODE	
					if (bDebug)
					{
						Print(Context, TEXT("TemporalAccumulation"));
						Newline(Context);
						Print(Context, TEXT("ScreenCoord: "));
						Print(Context, ScreenCoord.x);
						Print(Context, ScreenCoord.y);
						Newline(Context);
						Print(Context, TEXT("DepthWeights: "));
						Print(Context, DepthWeights);
						Newline(Context);
						Print(Context, TEXT("HistoryWeights: "));
						Print(Context, HistoryWeights);
					}
					#endif

					// Use history only if we found at least one valid sample
					if (any(HistoryWeights > 0.01f))
					{
						float3 DiffuseLightingHistory = 0.0f;
						DiffuseLightingHistory.x = dot(DiffuseLightingHistoryTexture.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						DiffuseLightingHistory.y = dot(DiffuseLightingHistoryTexture.GatherGreen(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						DiffuseLightingHistory.z = dot(DiffuseLightingHistoryTexture.GatherBlue(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						DiffuseLightingHistory = DiffuseLightingHistory / dot(HistoryWeights, 1.0f);

						float3 SpecularLightingHistory = 0.0f;
						SpecularLightingHistory.x = dot(SpecularLightingHistoryTexture.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						SpecularLightingHistory.y = dot(SpecularLightingHistoryTexture.GatherGreen(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						SpecularLightingHistory.z = dot(SpecularLightingHistoryTexture.GatherBlue(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						SpecularLightingHistory = SpecularLightingHistory / dot(HistoryWeights, 1.0f);

						float4 LuminanceMomentsHistory = 0.0f;
						LuminanceMomentsHistory.x = dot(LuminanceMomentsHistoryTexture.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						LuminanceMomentsHistory.y = dot(LuminanceMomentsHistoryTexture.GatherGreen(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						LuminanceMomentsHistory.z = dot(LuminanceMomentsHistoryTexture.GatherBlue(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);						
						LuminanceMomentsHistory.w = dot(LuminanceMomentsHistoryTexture.GatherAlpha(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						LuminanceMomentsHistory = LuminanceMomentsHistory / dot(HistoryWeights, 1.0f);

						// Reproject and rescale normalized NumFramesAccumulated
						float NumFramesAccumulatedHistory = 0.0f;
						NumFramesAccumulatedHistory = dot(NumFramesAccumulatedHistoryTexture.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights) * TemporalMaxFramesAccumulated;
						NumFramesAccumulatedHistory = NumFramesAccumulatedHistory / dot(HistoryWeights, 1.0f);
						NumFramesAccumulated = min(NumFramesAccumulatedHistory + 1.0f, TemporalMaxFramesAccumulated);

						float Alpha = 1.0f / (1.0f + NumFramesAccumulated);
						DiffuseLighting = lerp(DiffuseLightingHistory, DiffuseLighting, Alpha);
						SpecularLighting = lerp(SpecularLightingHistory, SpecularLighting, Alpha);
						LuminanceMoments = lerp(LuminanceMomentsHistory, LuminanceMoments, Alpha);

						FNeighborhoodClamp DiffuseNeighborhoodClamp = GetNeighborhoodClamp(ScreenCoord, ResolvedDiffuseLighting, DiffuseLighting);
						DiffuseLighting = clamp(DiffuseLighting, DiffuseNeighborhoodClamp.Min, DiffuseNeighborhoodClamp.Max);

						FNeighborhoodClamp SpecularNeighborhoodClamp = GetNeighborhoodClamp(ScreenCoord, ResolvedSpecularLighting, SpecularLighting);
						SpecularLighting = clamp(SpecularLighting, SpecularNeighborhoodClamp.Min, SpecularNeighborhoodClamp.Max);
					}
				}
			}
			#endif

			DiffuseLighting = MakeFinite(DiffuseLighting);
			SpecularLighting = MakeFinite(SpecularLighting);

			RWDiffuseLighting[ScreenCoord] = float4(DiffuseLighting, 0.0f);
			RWSpecularLighting[ScreenCoord] = float4(SpecularLighting, 0.0f);
			RWLuminanceMoments[ScreenCoord] = float4(DiffuseLumimanceMoments, SpecularLumimanceMoments);
			RWNumFramesAccumulated[ScreenCoord] = (NumFramesAccumulated + 0.5f) / TemporalMaxFramesAccumulated;

			float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, GBuffer.Depth);
			const float3 N = GBuffer.WorldNormal;
			const float3 V = normalize(View.TranslatedWorldCameraOrigin - TranslatedWorldPosition);
			const float NoV = saturate(dot(N, V));

			// #sdl_todo: handle alpha channel
			// Add to scene color and output separately to history
			float3 Irradiance = GBuffer.DiffuseColor * DiffuseLighting + SpecularLighting * EnvBRDF(GBuffer.SpecularColor, GBuffer.Roughness, NoV);

			float DiffuseVariance = max(DiffuseLumimanceMoments.y - Pow2(DiffuseLumimanceMoments.x), 0.0f);
			float SpecularVariance = max(SpecularLumimanceMoments.y - Pow2(SpecularLumimanceMoments.x), 0.0f);

			#if DEBUG_MODE
			if (bDebug)
			{
				Newline(Context);
				Print(Context, TEXT("Irradiance: "));
				Print(Context, Irradiance);
				Newline(Context);
				Print(Context, TEXT("Variance: "));
				Newline(Context);
				Print(Context, DiffuseVariance);
				Print(Context, SpecularVariance);
			}
			#endif

			RWSceneColor[ScreenCoord] = RWSceneColor[ScreenCoord] + float4(Irradiance, 0.0f);
		}

		RWSceneDepth[ScreenCoord] = GBuffer.Depth;
	}
}