// Copyright Epic Games, Inc. All Rights Reserved.

#include "../Common.ush"
#include "SampledDirectLighting.ush"

struct FNeighborStatistics
{
	float3 Mean;
	float3 Variance;
	float3 StdDev;
	float3 Min;
	float3 Max;
	float3 HistoryClampMin;
	float3 HistoryClampMax;
};

// Note: corners need to be first for GetNeighborStatistics
static const int2 kOffsets3x3[8] =
{
	int2(-1, -1),
	int2( 1, -1),
	int2(-1,  1),
	int2( 1,  1),
	int2( 0, -1),
	int2(-1,  0),
	int2( 1,  0),
	int2( 0,  1),
};

FNeighborStatistics GetNeighborStatistics(
	uint2 ScreenCoord, 
	Texture2D LightingTexture,
	float3 NewLighting)
{
	FNeighborStatistics Result = (FNeighborStatistics)0;

	int Count = 1;
	float3 M1 = NewLighting;
	float3 M2 = (float3)0;

	Result.Min = NewLighting;
	Result.Max = NewLighting;

	UNROLL
	for(uint NeighborId = 0; NeighborId < 8; NeighborId++)
	{
		int2 SampleOffset = kOffsets3x3[NeighborId];

		uint2 NeighborScreenCoord = clamp(ScreenCoord + SampleOffset, 0u, View.ViewRectMinAndSize.zw - 1);

		float3 Sample = LightingTexture[NeighborScreenCoord].xyz;

		Result.Min = min(Result.Min, Sample);
		Result.Max = max(Result.Max, Sample);

		// Welford's online algorithm for variance.
		// More numerically stable than accumulating squares.
		// https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance
		Count += 1;
		float3 Delta1 = Sample - M1;
		M1 += Delta1 / Count;
		float3 Delta2 = Sample - M1;
		M2 += Delta1 * Delta2;
	}

	Result.Mean = M1;
	Result.Variance = M2 / (Count - 1);
	Result.StdDev = sqrt(Result.Variance);
	Result.HistoryClampMin = Result.Mean - Result.StdDev;
	Result.HistoryClampMax = Result.Mean + Result.StdDev;

	return Result;
}

Texture2D DiffuseLightingTexture;
Texture2D SpecularLightingTexture;
Texture2D SampledDirectLightingDepthHistory;
Texture2D DiffuseLightingHistoryTexture;
Texture2D SpecularLightingHistoryTexture;

float4 HistoryScreenPositionScaleBias;
float4 HistoryUVMinMax;
float PrevSceneColorPreExposureCorrection;
int TemporalMaxFramesAccumulated;
float TemporalStdDevOffset;

RWTexture2D<float4> RWDiffuseLightingTexture;
RWTexture2D<float4> RWSpecularLightingTexture;
RWTexture2D<float> RWSceneDepth;
RWTexture2D<float4> RWSceneColor;

[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void SampledDirectLightingTemporalAccumulationCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint2 ScreenCoord = DispatchThreadId.xy;

#if DEBUG_MODE
	int2 DebugScreenCoord = View.CursorPosition.x >= 0 ? View.CursorPosition * View.ViewResolutionFraction : -1;
	bool bDebug = all(ScreenCoord == DebugScreenCoord);
	FShaderPrintContext Context = InitShaderPrintContext(true, float2(0.55, 0.3));
#endif

	if (all(ScreenCoord < View.ViewRectMinAndSize.zw))
	{
		float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
		FGBufferData GBuffer = GetGBufferData(ScreenUV);

		const float DeviceZ = SceneDepthTexture[ScreenCoord].x;
		GBuffer.Depth = ConvertFromDeviceZ(DeviceZ);

		if (GBuffer.Depth > 0.0f)
		{
			float3 DiffuseLighting = DiffuseLightingTexture[ScreenCoord].xyz;
			float3 SpecularLighting = SpecularLightingTexture[ScreenCoord].xyz;

			#if VALID_HISTORY
			{
				float2 ScreenPosition = (ScreenUV - View.ScreenPositionScaleBias.wz) / View.ScreenPositionScaleBias.xy;
				float3 HistoryScreenPosition = GetHistoryScreenPosition(ScreenPosition, ScreenUV, DeviceZ);
				float2 HistoryScreenUV = HistoryScreenPosition.xy * HistoryScreenPositionScaleBias.xy + HistoryScreenPositionScaleBias.wz;

				bool bHistoryWasOnScreen = all(HistoryScreenUV >= HistoryUVMinMax.xy) && all (HistoryScreenUV <= HistoryUVMinMax.zw);
				if (bHistoryWasOnScreen)
				{
					uint2 HistoryScreenCoord = floor(HistoryScreenUV * View.BufferSizeAndInvSize.xy - 0.5f);
					float2 HistoryBilinearWeights = frac(HistoryScreenUV * View.BufferSizeAndInvSize.xy - 0.5f);
					float2 HistoryGatherUV = (HistoryScreenCoord + 1.0f) * View.BufferSizeAndInvSize.zw;

					float4 HistorySampleSceneDepth4 = SampledDirectLightingDepthHistory.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy;

					// #sdl_todo: plane weighting
					float ReprojectedSceneDepth = ConvertFromDeviceZ(HistoryScreenPosition.z);
					float DisocclusionDistanceThreshold = 0.03f;
					const float4 DistanceToHistoryValue = abs(HistorySampleSceneDepth4 - ReprojectedSceneDepth);
					float4 DepthWeights = select(DistanceToHistoryValue >= ReprojectedSceneDepth * DisocclusionDistanceThreshold, 0.0f, 1.0f);

					float4 HistoryWeights = float4(
						(1 - HistoryBilinearWeights.y) * (1 - HistoryBilinearWeights.x),
						(1 - HistoryBilinearWeights.y) * HistoryBilinearWeights.x,
						HistoryBilinearWeights.y * (1 - HistoryBilinearWeights.x),
						HistoryBilinearWeights.y * HistoryBilinearWeights.x);

					HistoryWeights *= DepthWeights;

					#if DEBUG_MODE	
					if (bDebug)
					{
						Print(Context, TEXT("TemporalAccumulation"));
						Newline(Context);
						Print(Context, TEXT("ScreenCoord: "));
						Print(Context, ScreenCoord.x);
						Print(Context, ScreenCoord.y);
						Newline(Context);
						Print(Context, TEXT("DepthWeights: "));
						Print(Context, DepthWeights);
						Newline(Context);
						Print(Context, TEXT("HistoryWeights: "));
						Print(Context, HistoryWeights);
					}
					#endif

					// Use history only if we found at least one valid sample
					if (any(HistoryWeights > 0.01f))
					{
						float3 DiffuseLightingHistory = 0.0f;
						DiffuseLightingHistory.x = dot(DiffuseLightingHistoryTexture.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						DiffuseLightingHistory.y = dot(DiffuseLightingHistoryTexture.GatherGreen(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						DiffuseLightingHistory.z = dot(DiffuseLightingHistoryTexture.GatherBlue(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						DiffuseLightingHistory = DiffuseLightingHistory / dot(HistoryWeights, 1.0f);

						float3 SpecularLightingHistory = 0.0f;
						SpecularLightingHistory.x = dot(SpecularLightingHistoryTexture.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						SpecularLightingHistory.y = dot(SpecularLightingHistoryTexture.GatherGreen(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						SpecularLightingHistory.z = dot(SpecularLightingHistoryTexture.GatherBlue(GlobalPointClampedSampler, HistoryGatherUV).wzxy, HistoryWeights);
						SpecularLightingHistory = SpecularLightingHistory / dot(HistoryWeights, 1.0f);

						float Alpha = 1.0f / (1.0f + TemporalMaxFramesAccumulated);
						DiffuseLighting = lerp(DiffuseLightingHistory, DiffuseLighting, Alpha);
						SpecularLighting = lerp(SpecularLightingHistory, SpecularLighting, Alpha);

						FNeighborStatistics SpecularNeighborStatistics = GetNeighborStatistics(ScreenCoord, SpecularLightingTexture, SpecularLighting);
						SpecularLighting = clamp(SpecularLighting, SpecularNeighborStatistics.HistoryClampMin, SpecularNeighborStatistics.HistoryClampMax);
					}
				}
			}
			#endif

			DiffuseLighting = MakeFinite(DiffuseLighting);
			SpecularLighting = MakeFinite(SpecularLighting);

			RWDiffuseLightingTexture[ScreenCoord] = float4(DiffuseLighting, 0.0f);
			RWSpecularLightingTexture[ScreenCoord] = float4(SpecularLighting, 0.0f);

			float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, GBuffer.Depth);
			const float3 N = GBuffer.WorldNormal;
			const float3 V = normalize(View.TranslatedWorldCameraOrigin - TranslatedWorldPosition);
			const float NoV = saturate(dot(N, V));

			// #sdl_todo: handle alpha channel
			// Add to scene color and output separately to history
			float3 Irradiance = GBuffer.DiffuseColor * DiffuseLighting + SpecularLighting * EnvBRDF(GBuffer.SpecularColor, GBuffer.Roughness, NoV);

			#if DEBUG_MODE 
			if (bDebug)
			{
				Newline(Context);
				Print(Context, TEXT("Irradiance: "));
				Print(Context, Irradiance);
			}
			#endif

			RWSceneColor[ScreenCoord] = RWSceneColor[ScreenCoord] + float4(Irradiance, 0.0f);
		}

		RWSceneDepth[ScreenCoord] = GBuffer.Depth;
	}
}