// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#ifndef SUBSTRATE_ENABLED
#error "This header should only be included when Substrate is enabled."
#endif

#include "../PathTracingCommon.ush"
#include "../../BRDF.ush"

#define SUBSTRATE_FRESNEL_F82  0

#define SUBSTRATE_PATH_TRACING_GLINTS (SUBSTRATE_COMPLEXSPECIALPATH && PLATFORM_ENABLES_SUBSTRATE_GLINTS)

#if SUBSTRATE_PATH_TRACING_GLINTS
#include "/Engine/Private/Substrate/Glint/GlintThirdParty.ush"
#endif

#ifndef SUBSTRATE_SHEEN_QUALITY
#define SUBSTRATE_SHEEN_QUALITY 0
#endif

float3 SubstrateLobeWeight(FPathTracingPayload Payload, float SatNoL)
{
	// See reference in LuminanceWeight
	const float DistanceL = rcp(max(SatNoL, 0.001f));
	const float3 TransmittanceAboveAlongL = select(Payload.TransmittanceN < 1.f, pow(max(Payload.TransmittanceN, 0.0001f), DistanceL), Payload.TransmittanceN);
	return Payload.BSDFOpacity * Payload.WeightV * lerp(1.0f, TransmittanceAboveAlongL, Payload.CoverageAboveAlongN);
}

float3 SubstrateSpecularTint(FPathTracingPayload Payload, float NoV, float NoL, float VoH, float NoH)
{
	float3 Out = 1.f;
	BRANCH
	if (Payload.SpecularProfileId != 0)
	{
		Out = EvaluateSpecularProfile(Payload.SpecularProfileId, NoV, NoL, VoH, NoH);
	}
	return Out;
}

void SubstrateGlint(FPathTracingPayload Payload, float3 InTangentV, float3 InTangentL, float2 InAlphaXY, in float InPdf, inout float OutWeight)
{
	// For now use the GGX lobe sampling. This will be changed with glint importance sampling later on.
#if SUBSTRATE_PATH_TRACING_GLINTS
	BRANCH
	if (Payload.GlintValue > 0)
	{
		const float2 GGXRoughnessXY = float2(sqrtFast(InAlphaXY.x), sqrtFast(InAlphaXY.y));
		FBeckmannDesc Beckmann = GGXToBeckmann(GGXRoughnessXY);
		const float Fs = f_P(InTangentV, InTangentL, float3(Beckmann.Sigma, Beckmann.Rho), Payload.GlintValue, Payload.GlintUV, Payload.GlintUVdx, Payload.GlintUVdy, true /*bIncludeGeometryTerm*/);
		OutWeight = Fs / max(0.0001f, InPdf);
	}
#endif
}

FBxDFEnergyTermsA ComputeSheenEnergyTerms(float NoV, float SheenRoughness)
{
#if SUBSTRATE_SHEEN_QUALITY == 1
	FBxDFEnergyTermsA Result;
	Result.E = SheenLTC_DirectionalAlbedo(NoV, SheenRoughness, View.SheenLTCTexture, View.SheenLTCSampler);
	Result.W = Result.E; // overall weight is the directional albedo
	return Result;
#else
	return ComputeClothEnergyTermsA(SheenRoughness, NoV);
#endif
}

#define USE_SHEEN_LTC_SAMPLER 1 // 0: fallback to uniform sampling (for reference)
								// 1: use the LTC coefficients for importance sampling

float ComputeSheenPdf(float3 V, float3 L, float3 N, float NoV, float SheenRoughness)
{
#if USE_SHEEN_LTC_SAMPLER != 0 && SUBSTRATE_SHEEN_QUALITY == 1
	// Disney's Cloth Lobe
	float FuzzDirectionalAlbedo = 1;
	float FuzzSpecularPathValueNoL = SheenLTC_Eval(V, L, N, NoV, SheenRoughness, View.SheenLTCTexture, View.SheenLTCSampler, FuzzDirectionalAlbedo);
	return FuzzSpecularPathValueNoL;
#else
	// uniform sampling (for legacy cloth lobe, or naive sampling of the LTC lobe)
	const float Pdf = 1 / (2 * PI);
	return Pdf;
#endif

}

float3 ComputeSheenWeight(float3 V, float3 L, float3 N, float NoV, float NoL, float NoH, float VoH, float SheenRoughness, float3 SheenColor)
{
#if SUBSTRATE_SHEEN_QUALITY == 1
	// Disney's Cloth Lobe
	float FuzzDirectionalAlbedo = 1; // NOTE: Path Tracer includes this term in the weight applied outside
	float FuzzSpecularPathValueNoL = SheenLTC_Eval(V, L, N, NoV, SheenRoughness, View.SheenLTCTexture, View.SheenLTCSampler, FuzzDirectionalAlbedo);
#if USE_SHEEN_LTC_SAMPLER == 0
	// using naive sampling, weight will include Brdf evaluation
	// uniform sampling, pdf is just 1/2pi
	return SheenColor * (FuzzSpecularPathValueNoL * 2 * PI);
#else
	// LTC sampling - pdf is equal to the brdf, so sample weight is just the color
	return SheenColor;
#endif

#else
	// Charlie's Cloth Lobe
	const float DCloth = D_Charlie(SheenRoughness, NoH);
	const float3 FCloth = F_Schlick(SheenColor, VoH);
	return (2 * PI * NoL * DCloth * Vis_Ashikhmin(NoV, NoL)) * FCloth;
#endif
}

float3 SampleSheenDirection(float3 V, float SheenRoughness, float2 Rand)
{
#if USE_SHEEN_LTC_SAMPLER != 0 && SUBSTRATE_SHEEN_QUALITY == 1
	return SheenLTC_Sample(CosineSampleHemisphere(Rand).xyz, V, float3(0, 0, 1), V.z, SheenRoughness, View.SheenLTCTexture, View.SheenLTCSampler);
#else
	return UniformSampleHemisphere(Rand).xyz;
#endif
}
