

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/ScreenPass.ush"

#define SOURCE_TYPE_TEXTURE		0
#define SOURCE_TYPE_BUFFER		1

Texture2D Input0_Texture;
SCREEN_PASS_TEXTURE_VIEWPORT(Input0)

float2 ConvertGridPos2UV(uint2 GridPosition)
{
	float2 GripPositionF = float2(GridPosition);
	return Input0_ExtentInverse * (GripPositionF + 0.5f);
}

Buffer<uint> SourceType;
RWBuffer<uint> RWIndirectDispatchArgsBuffer;
int2 NetworkTextureSize;

[numthreads(8, 1, 1)]
void BuildIndirectDispatchArgsCS(uint2 DispatchThreadId : SV_DispatchThreadID)
{
	if (DispatchThreadId.y == 0 && DispatchThreadId.x == 0)
	{
		if (SourceType[0] == SOURCE_TYPE_TEXTURE)
		{
			uint IndirectDispatchX = (NetworkTextureSize.x + THREAD_GROUP_SIZE - 1) / THREAD_GROUP_SIZE;
			uint IndirectDispatchY = (NetworkTextureSize.y + THREAD_GROUP_SIZE - 1) / THREAD_GROUP_SIZE;

			WriteDispatchIndirectArgs(RWIndirectDispatchArgsBuffer, 0, IndirectDispatchX, IndirectDispatchY, 1);
		}
		else
		{
			WriteDispatchIndirectArgs(RWIndirectDispatchArgsBuffer, 0, 0, 0, 1);
		}
	}
}

SamplerState InputTextureSampler;
int InputBufferWidth;
int InputBufferHeight;
RWBuffer<float> InputBuffer;
float ColorScale;

// from buffer to neural input
[numthreads(THREAD_GROUP_SIZE, THREAD_GROUP_SIZE, 1)]
void PrepareInput(in const uint3 DispatchThreadID : SV_DispatchThreadID)
{
	if (DispatchThreadID.x >= InputBufferWidth || DispatchThreadID.y >= InputBufferHeight)
	{
		return;
	}

	// calculate the grid size mapping from the rendered output to the input of the neuralnetwork
	const float2 BufferSize = float2(InputBufferWidth, InputBufferHeight) - 0.5f;
	const float2 WidthFactors = Input0_ViewportSize.xy / BufferSize;
	const int2 LoXY = Input0_ViewportMin.xy + (int2)(WidthFactors * (float2)DispatchThreadID.xy);
	const int2 HiXY = Input0_ViewportMin.xy + (int2)ceil(WidthFactors * (float2)(DispatchThreadID.xy + 1));
	int LoX = LoXY.x;
	int LoY = LoXY.y;
	int HiX = HiXY.x;
	int HiY = HiXY.y;

	// averaging each grid
	float4 Result = float4(0.0, 0.0, 0.0, 0.0);
	float Div = 0.0;
	for (int x = LoX; x <= HiX; x++)
	{
		if (x < Input0_Extent.x)
		{
			for (int y = LoY; y <= HiY; y++)
			{
				if (y < Input0_Extent.y)
				{
					float2 BufferUV = ConvertGridPos2UV(uint2(x,y));
					float2 ClampedBufferUV = clamp(BufferUV, Input0_UVViewportBilinearMin, Input0_UVViewportBilinearMax);
					Result += Input0_Texture.SampleLevel(InputTextureSampler, ClampedBufferUV, 0);
					Div += 1.0;
				}
			}
		}
	}
	Result /= Div;

	// write to the input buffer of the neural network
	int Idx = DispatchThreadID.y * InputBufferWidth + DispatchThreadID.x;
	int Offset1 = InputBufferWidth * InputBufferHeight;
	int Offset2 = Offset1 + Offset1;

	InputBuffer[Idx] = Result.r;
	InputBuffer[Idx + Offset1] = Result.g;
	InputBuffer[Idx + Offset2] = Result.b;
}

int OutputBufferWidth;
int OutputBufferHeight;
RWBuffer<float> OutputBuffer;

// from neural output to buffer, full screenpass pixel shader
float4 ProcessOutput(float4 Position : SV_POSITION) : SV_Target0
{
	float X = Position.x * float(OutputBufferWidth - 1) / (float)Input0_ViewportSize.x;
	float Y = Position.y * float(OutputBufferHeight - 1) / (float)Input0_ViewportSize.y;

	int LoX =  (int)clamp(floor(X), 0.0, float(OutputBufferWidth - 1));
	int HiX = (int)clamp(floor(X + 1.0), 0.0, float(OutputBufferWidth - 1));

	int LoY = (int)clamp(floor(Y), 0.0, float(OutputBufferHeight - 1));
	int HiY = (int)clamp(floor(Y + 1.0), 0.0, float(OutputBufferHeight - 1));

	int Offset1 = OutputBufferWidth * OutputBufferHeight;
	int Offset2 = Offset1 + Offset1;

	// bilinear filtering
	int Idx;

	Idx = LoY * OutputBufferWidth + LoX;
	float3 A = float3(OutputBuffer[Idx], OutputBuffer[Idx + Offset1], OutputBuffer[Idx + Offset2]);

	Idx = LoY * OutputBufferWidth + HiX;
	float3 B = float3(OutputBuffer[Idx], OutputBuffer[Idx + Offset1], OutputBuffer[Idx + Offset2]);

	Idx = HiY * OutputBufferWidth + LoX;
	float3 C = float3(OutputBuffer[Idx], OutputBuffer[Idx + Offset1], OutputBuffer[Idx + Offset2]);

	Idx = HiY * OutputBufferWidth + HiX;
	float3 D = float3(OutputBuffer[Idx], OutputBuffer[Idx + Offset1], OutputBuffer[Idx + Offset2]);

	float Alpha = clamp(X - (float)LoX, 0.0, 1.0);
	float Beta = clamp(Y - (float)LoY, 0.0, 1.0);

	float3 Result = (1.0 - Beta) * ((1.0 - Alpha) * A + Alpha * B) + Beta * ((1.0 - Alpha) * C + Alpha * D);

	Result = Result.rgb;

	return float4(Result, 1.0);
}