// Copyright Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	LightFunctionAtlasCommon.usf
=============================================================================*/

#pragma once

#include "../Common.ush"
#include "/Engine/Shared/LightDefinitions.h"

// In order to use function from that file, one must use FLightFunctionAtlasGlobalParameters

// Trick so that we can sample from LightFunctionAtlas when it is a global UB or when it is a Struct part of another UB.
#ifdef LightFunctionAtlasStruct
#undef  LightFunctionAtlas
#define LightFunctionAtlas LightFunctionAtlasStruct
#endif

#if COLORED_LIGHT_FUNCTION_ATLAS
#define FLightFunctionColor float3
#else
#define FLightFunctionColor float
#endif

FLightFunctionColor GetLocalLightFunctionCommon(float3 TranslatedWorldPosition, uint LightFunctionAtlasLightIndex)
{
	if (LightFunctionAtlasLightIndex == 0)
	{
		// No valid light function assigned to the light.
		return 1.0f;
	}

	const uint BaseBufferIndex = LightFunctionAtlasLightIndex * 5; // See FAtlasLightInfoData

	float4 LightFunctionLightDataParameters = LightFunctionAtlas.LightInfoDataBuffer[BaseBufferIndex + 0];
	const float  FadeDistance				= LightFunctionLightDataParameters.x;
	const uint   PackedLightInfoDataParams	= asuint(LightFunctionLightDataParameters.y);
	const float2 Slot_MinUV					= LightFunctionLightDataParameters.zw;

	const uint   LightType					= PackedLightInfoDataParams & 0xFF;
	const float  DisabledBrightness			= f16tof32((PackedLightInfoDataParams >> 8) & 0xFFFF);

	float4x4 ActualLightFunctionMatrix = float4x4(
		LightFunctionAtlas.LightInfoDataBuffer[BaseBufferIndex + 1],
		LightFunctionAtlas.LightInfoDataBuffer[BaseBufferIndex + 2],
		LightFunctionAtlas.LightInfoDataBuffer[BaseBufferIndex + 3],
		LightFunctionAtlas.LightInfoDataBuffer[BaseBufferIndex + 4]);
	float4 HomogeneousShadowPosition = mul(float4(TranslatedWorldPosition, 1), ActualLightFunctionMatrix);

	float2 LightFunctionUV;
	switch (LightType)
	{

	case LIGHT_TYPE_SPOT:
	{
		HomogeneousShadowPosition.xyz /= HomogeneousShadowPosition.www;
		LightFunctionUV = HomogeneousShadowPosition.xy;
		LightFunctionUV = 1 - LightFunctionUV;
		break;
	}

	case LIGHT_TYPE_POINT:
	{
		float3 LightVec = normalize(HomogeneousShadowPosition).zyx;
		LightFunctionUV = float2((atan2Fast(LightVec.y, LightVec.x) + PI) / (2 * PI), acosFast(LightVec.z) / PI);
		break;
	}

	//case LIGHT_TYPE_RECT:
	//case LIGHT_TYPE_DIRECTIONAL:
	default:
	{
		LightFunctionUV = frac(HomogeneousShadowPosition.zy);
		break;
	}

	}

	// Slot min uv and size already account for half texel offsets
	float2 AtlasUV = Slot_MinUV + saturate(LightFunctionUV) * LightFunctionAtlas.Slot_UVSize.xx;

#if COLORED_LIGHT_FUNCTION_ATLAS
	FLightFunctionColor LightFunctionColor = Texture2DSampleLevel(LightFunctionAtlas.LightFunctionAtlasTexture, LightFunctionAtlas.LightFunctionAtlasSampler, AtlasUV, 0).rgb;
#else
	FLightFunctionColor LightFunctionColor = Texture2DSampleLevel(LightFunctionAtlas.LightFunctionAtlasTexture, LightFunctionAtlas.LightFunctionAtlasSampler, AtlasUV, 0).x;
#endif
	LightFunctionColor = LightFunctionColor * LightFunctionColor; // Simple Gamma decompression

	// Calculate radial view distance for stable fading
	float ViewDistance = length(PrimaryView.TranslatedWorldCameraOrigin - TranslatedWorldPosition);
	float DistanceFadeAlpha = saturate((FadeDistance - ViewDistance) / (FadeDistance * .2f));
	// Fade to disabled based on FadeDistance
	LightFunctionColor = lerp(DisabledBrightness, LightFunctionColor, DistanceFadeAlpha);
	// Fade to disabled based on ShadowFadeFraction
	const float ShadowFadeFraction = 1.0f; // Not setup
	LightFunctionColor = LightFunctionColor; // lerp(DisabledBrightness, LightFunctionColor, ShadowFadeFraction);

	return LightFunctionColor;
}