// Copyright Epic Games, Inc. All Rights Reserved.
#include "/Engine/Public/Platform.ush"

#ifndef MAX_flt
#define MAX_flt			(3.402823466e+38F)
#endif

Texture2D SourceTiles;

RWTexture2D<float4> Result;
RWStructuredBuffer<uint4> Histogram : register(u0);

#ifndef THREADGROUPSIZE_X
#define THREADGROUPSIZE_X 1
#define THREADGROUPSIZE_Y 1
#define THREADGROUPSIZE_Z 1
#endif

[numthreads(THREADGROUPSIZE_X, THREADGROUPSIZE_Y, THREADGROUPSIZE_Z)]
void CSH_Histogram(
	uint3 GroupId : SV_GroupID,
	uint3 ThreadId : SV_DispatchThreadID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint GroupIndex: SV_GroupIndex
	)
{
	float4 Col = SourceTiles.Load(uint3(ThreadId.xy, 0));
	uint RBin = uint(Col.r * float(255));
	uint GBin = Col.g * 255;
	uint BBin = Col.b * 255;
	int Luma = (int)((0.2126 * RBin) + (0.7152 * GBin) + (0.0722 * BBin));

	InterlockedAdd(Histogram[RBin].r, 1);
	InterlockedAdd(Histogram[GBin].g, 1);
	InterlockedAdd(Histogram[BBin].b, 1);
	InterlockedAdd(Histogram[Luma].a, 1);

	GroupMemoryBarrierWithGroupSync();

	if(GroupIndex == 0)
	{
		float4 MinValue = float4(MAX_flt,MAX_flt,MAX_flt,MAX_flt);
		float4 MaxValue = float4(0,0,0,0);
		LOOP for(uint y = 0; y < 256 ; y++)
		{
			MinValue = min(Histogram[y],MinValue);
			MaxValue = max(Histogram[y],MaxValue);
			Result[uint2(y,0)] = float4(Histogram[y].r,Histogram[y].g,Histogram[y].b,Histogram[y].a);
		}
		Result[uint2(0,1)] = MinValue;//2nd row first pixel is the min value
		Result[uint2(1,1)] = MaxValue;//2nd row second pixel is the max value
	}
}
