// Copyright Epic Games, Inc. All Rights Reserved.

#include "/Engine/Public/Platform.ush"

Texture2D SourceTexture;
SamplerState SourceSampler;
float2 SourceDimensions;
RWTexture2D<float4> OutputTexture;

[numthreads(THREADGROUPSIZE_X, THREADGROUPSIZE_Y, THREADGROUPSIZE_Z)]
void PCGTextureReadback_CS(uint3 DispatchThreadId : SV_DispatchThreadID, uint GroupIndex : SV_GroupIndex)
{
	float2 TexCoord = DispatchThreadId.xy + 0.5;
	OutputTexture[TexCoord] = SourceTexture.SampleLevel(SourceSampler, TexCoord / SourceDimensions, /*lod=*/0);
}
