// Copyright Epic Games, Inc. All Rights Reserved.
#pragma once

#define StatelessDistributionFlag_Random	0x00000001
#define StatelessDistributionFlag_Uniform	0x00000002
#define StatelessDistributionFlag_Binding	0x00000004

#define DefineStatelessDistributionSampler(HLSLTYPE, NAMETYPE) \
	struct FStatelessDistributionSampler##NAMETYPE \
	{ \
		void Init(uint RandomSeedOffset, uint3 InParameters) \
		{ \
			Parameters = InParameters; \
			RandomOffset = 0.0f; \
			if ( (Parameters.x & StatelessDistributionFlag_Random) != 0) \
			{ \
				RandomOffset = Random##NAMETYPE##(RandomSeedOffset); \
			} \
		} \
		\
		bool IsValid() { return Parameters.z > 0; } \
		\
		HLSLTYPE GetValue(float NormalizedAge) \
		{ \
			if ((Parameters.x & StatelessDistributionFlag_Binding) != 0) \
			{ \
				return GetParameterBuffer##NAMETYPE##(Parameters.y, 0); \
			} \
			else if ((Parameters.x & StatelessDistributionFlag_Random) != 0) \
			{ \
				const HLSLTYPE Value0 = GetStatic##NAMETYPE##(Parameters.y, 0); \
				const HLSLTYPE Value1 = GetStatic##NAMETYPE##(Parameters.y, 1); \
				return StatelessLerp(Value0, Value1, RandomOffset, (Parameters.x & StatelessDistributionFlag_Uniform) != 0); \
			} \
			else \
			{ \
				const float Offset = NormalizedAge * float(Parameters.z); \
				const HLSLTYPE Value0 = GetStatic##NAMETYPE##(Parameters.y, floor(Offset)); \
				const HLSLTYPE Value1 = GetStatic##NAMETYPE##(Parameters.y, ceil(Offset)); \
				return lerp(Value0, Value1, frac(Offset)); \
			} \
		} \
		\
		uint3		Parameters; \
		HLSLTYPE	RandomOffset; \
	}

DefineStatelessDistributionSampler(float,  Float);
DefineStatelessDistributionSampler(float2, Float2);
DefineStatelessDistributionSampler(float3, Float3);
DefineStatelessDistributionSampler(float4, Float4);

#undef DefineStatelessDistributionSampler
