// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Dataflow/DataflowNode.h"
#include "GeometryCollection/ManagedArrayCollection.h"
#include "ChaosClothAsset/WeightedValue.h"
#include "ProxyDeformerNode.generated.h"

/** Add the proxy deformer information to this cloth collection's render data. */
USTRUCT(Meta = (DataflowCloth))
struct FChaosClothAssetProxyDeformerNode : public FDataflowNode
{
	GENERATED_USTRUCT_BODY()
	DATAFLOW_NODE_DEFINE_INTERNAL(FChaosClothAssetProxyDeformerNode, "ProxyDeformer", "Cloth", "Cloth Simulation Proxy Deformer")

public:

	UPROPERTY(Meta = (Dataflowinput, DataflowOutput, DataflowPassthrough = "Collection"))
	FManagedArrayCollection Collection;

	/** Whether using multiple simulation mesh triangles to influence the position of the deformed render vertex. */
	UPROPERTY(EditAnywhere, Category = "ProxyDeformer")
	bool bUseMultipleInfluences = false;

	/** The radius around the render vertices to look for all simulation mesh triangles influencing it (AKA SkinningKernelRadius). */
	UPROPERTY(EditAnywhere, Category = "ProxyDeformer", Meta = (EditCondition = "bUseMultipleInfluences"))
	float InfluenceRadius = 5.f;

	/**
	 * Whether to create a smoothed _SkinningBlendWeight render weight map to ease the transition between the deformed part and the skinned part of the render mesh.
	 * When no transition is created there will be a visible step in the rendered triangles around the edge of the kinematic/dynamic transition of the proxy simulation mesh.
	 * The _SkinningBlendWeight render weight map is created regardless of the transition being created smooth or not, and can be later adjusted using the weight map tool.
	 */
	UPROPERTY(EditAnywhere, Category = "ProxyDeformer")
	bool bUseSmoothTransition = true;

	/** The name of the simulation mesh MaxDistance weight map used to determine the kinematic/dynamic points. */
	UPROPERTY(EditAnywhere, Category = "ProxyDeformer")
	FChaosClothAssetWeightedValueNonAnimatableNoLowHighRange MaxDistance;

	/**
	 * The name of the render mesh weight map generated by this node detailing the contribution of the proxy deformer.
	 * Value ranges between 0 (fully deformed) and 1 (fully skinned).
	 * The name of this render mesh weight map cannot be changed and is only provided for further tweaking.
	 */
	UPROPERTY(VisibleAnywhere, Category = "ProxyDeformer", Meta = (DataflowOutput))
	FString SkinningBlendName;

	FChaosClothAssetProxyDeformerNode(const Dataflow::FNodeParameters& InParam, FGuid InGuid = FGuid::NewGuid());

private:
	virtual void Evaluate(Dataflow::FContext& Context, const FDataflowOutput* Out) const override;
};
