// Copyright Epic Games, Inc. All Rights Reserved.
#include "/Engine/Public/Platform.ush"
#include "/Plugin/TextureGraph/SamplerStates.ush"

Texture2D SourceTexture;
float MaxValue;

float4 FSH_Invert(float2 uv : TEXCOORD0) : SV_Target0
{
	float4 Color = SourceTexture.Sample(SamplerStates_NoBorder, uv);

	// TODO: Support HDR values
	return saturate(float4(MaxValue, MaxValue, MaxValue, MaxValue) - Color);
}
