// Copyright Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	GLCommon.ush: Common GL shader code
=============================================================================*/

#pragma once

// Update this GUID to invalidate shader recompilation for only GL shaders
#pragma message("UESHADERMETADATA_VERSION D7CA27C0-CEC3-4972-A5FC-8774AF3B4083")


