// Copyright Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	GLCommon.ush: Common GL shader code
=============================================================================*/

#pragma once

// Update this GUID to invalidate shader recompilation for only GL shaders
#pragma message("UESHADERMETADATA_VERSION 05706E20-1BE5-45C7-868F-CEB8BCE25DB8")


