
/*=============================================================================
	UWPTargetSettings.h: Declares the UUWPTargetSettings class.
=============================================================================*/

#pragma once

#include "WindowsTargetSettings.h"
#include "UWPTargetSettings.generated.h"

/**
 * Implements the settings for the UWP target platform.
 */
UCLASS(config = Engine, defaultconfig)
class UWPTARGETPLATFORM_API UUWPTargetSettings
	: public UObject
{
public:

	GENERATED_UCLASS_BODY()

	/**
	* Service Configuration GUID. Must match Dev Center configuration.
	*/
	UPROPERTY(EditAnywhere, config, Category = XboxLive)
	FString ServiceConfigId;

	/**
	* Title ID. Must match Dev Center configuration.
	*/
	UPROPERTY(EditAnywhere, config, Category = XboxLive)
	FString TitleId;

	/**
	* Whether this title's Xbox Live access is via the Xbox Live Creators Program.
	*/
	UPROPERTY(EditAnywhere, config, Category = XboxLive)
	uint32 bIsCreatorsProgramTitle : 1;

	/*
	* UWP includes SM4 support (D3D Feature level 10) by default.  This setting excludes this
	* support, possibly reducing package size, but limiting the range of devices the package
	* will run on.  Currently you must leave this DISABLED if you wish to run as UWP on Xbox One.
	*/
	UPROPERTY(EditAnywhere, config, Category = Rendering)
	uint32 bExcludeShaderModel4Support : 1;

	/*
	* Selects between the D3D12 RHI and the D3D11 RHI
	*/
	UPROPERTY(EditAnywhere, config, Category = Rendering)
	uint32 bUseD3D12RHI : 1;

	/**
	* Whether cooked content should be copied into the loose package image generated by deploy from Visual Studio.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Toolchain")
	uint32 bCopyCookedContentForF5Deployment : 1;

	UPROPERTY(EditAnywhere, config, Category=Packaging)
	FString SigningCertificate;

	UPROPERTY(EditAnywhere, config, Category=Packaging)
	FString Logo;

	UPROPERTY(EditAnywhere, config, Category=Packaging)
	FString SmallLogo;

	UPROPERTY(EditAnywhere, config, Category=Packaging)
	FString WideLogo;

	UPROPERTY(EditAnywhere, config, Category=Packaging)
	FString SplashScreen;

	UPROPERTY(EditAnywhere, config, Category = Packaging)
	FString StoreLogo;

	UPROPERTY(EditAnywhere, config, Category = Packaging)
	FString TileBackgroundColorHex;

	UPROPERTY(EditAnywhere, config, Category = Packaging)
	FString SplashScreenBackgroundColorHex;

	UPROPERTY(EditAnywhere, Category = Packaging, meta=(HideAlphaChannel))
	FColor TileBackgroundColor;

	UPROPERTY(EditAnywhere, Category = Packaging, meta=(HideAlphaChannel))
	FColor SplashScreenBackgroundColor;

	/**
	* Minimum version of the universal platform required to run this title.
	* It will not be possible to deploy the build on earlier versions.
	*/
	UPROPERTY(EditAnywhere, config, Category = "OS Info", Meta = (DisplayName = "Minimum supported platform version"))
	FString MinimumPlatformVersion;

	/**
	* Specifies the maximum version of the universal platform on which the
	* title is known to work as expected.  When deployed to later versions
	* the title will experience the runtime behavior of the version given here.
	*/
	UPROPERTY(EditAnywhere, config, Category = "OS Info", Meta = (DisplayName = "Maximum tested platform version"))
	FString MaximumPlatformVersionTested;

	/** The compiler version to use for this project. May be different to the chosen IDE. */
	UPROPERTY(EditAnywhere, config, Category = "Toolchain", Meta = (DisplayName = "Compiler Version"))
	ECompilerVersion CompilerVersion;
};
