name: live_link_vcam
description: A rebuild of the Live Link VCAM app for Flutter, enabling cross-platform deployment.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: "^3.7.0"

dependencies:
  flutter:
    sdk: flutter

  epic_common:
    path: ../../FlutterCommon

  logging: ^1.2.0
  package_info_plus: ^4.1.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pigeon: ^11.0.1
  share_plus: ^7.2.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Generate localization files
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: packages/epic_common/assets/fonts/Inter-VariableFont_slnt,wght.ttf

    - family: Droid Sans Mono
      fonts:
        - asset: packages/epic_common/assets/fonts/DroidSansMono.ttf

# Automatically generate arb localization files from a CSV
arb_generator:
  input_filepath: "lib/l10n/l10n.csv"
  output_directory: "lib/l10n"
  filename_prepend: "app_"
  csv_settings:
    description_index: 1
    base_index: 2
