
/*=============================================================================
	UWPTargetSettings.h: Declares the UUWPTargetSettings class.
=============================================================================*/

#pragma once

#include "WindowsTargetSettings.h"
#include "UWPTargetSettings.generated.h"

/**
 * Implements the settings for the UWP target platform.
 */
UCLASS(config = Engine, defaultconfig)
class UUWPTargetSettings
	: public UObject
{
public:

	GENERATED_UCLASS_BODY()

	virtual const TCHAR* GetConfigOverridePlatform() const override
	{
		return TEXT("UWP");
	}

	virtual void PostInitProperties() override;

	/**
	* Service Configuration GUID. Must match Dev Center configuration.
	*/
	UPROPERTY(EditAnywhere, config, Category = XboxLive)
	FString ServiceConfigId;

	/**
	* Title ID. Must match Dev Center configuration.
	*/
	UPROPERTY(EditAnywhere, config, Category = XboxLive)
	FString TitleId;

	/**
	* Whether this title's Xbox Live access is via the Xbox Live Creators Program.
	*/
	UPROPERTY(EditAnywhere, config, Category = XboxLive)
	uint32 bIsCreatorsProgramTitle : 1;

	/**
	* UWP includes SM4 support (D3D Feature level 10) by default.  This setting excludes this
	* support, possibly reducing package size, but limiting the range of devices the package
	* will run on.  Currently you must leave this DISABLED if you wish to run as UWP on Xbox One.
	*/
	UPROPERTY(EditAnywhere, config, Category = Rendering, Meta=(DisplayName="Exclude Shader Model 4 Support"))
	uint32 bExcludeShaderModel4Support : 1;

	/*
	* Selects between the D3D12 RHI and the D3D11 RHI
	*/
	UPROPERTY(EditAnywhere, config, Category = Rendering, Meta=(DisplayName = "Use D3D12 RHI"))
	uint32 bUseD3D12RHI : 1;

	/**
	* Whether cooked content should be copied into the loose package image generated by deploy from Visual Studio.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Toolchain", Meta = (DisplayName = "Copy Cooked Content for F5 Deployment"))
	uint32 bCopyCookedContentForF5Deployment : 1;

	/**
	* Controls whether to use the retail Windows Store environment for license checks.  This must be turned on
	* when building for submission to the Windows Store, or when sideloading outside of Developer Mode.  Note,
	* however, that testing a build with this flag enables requires that the product is listed in the retail
	* catalog for the Windows Store.
	*/
	UPROPERTY(EditAnywhere, config, Category = "Packaging", AdvancedDisplay, Meta = (DisplayName = "Use Retail Windows Store Environment"))
	uint32 bBuildForRetailWindowsStore : 1;

	UPROPERTY(EditAnywhere, config, Category = "Rendering", meta = (DisplayName = "Enable PIX Profiling"))
	uint32 bEnablePIXProfiling : 1;

	UPROPERTY(EditAnywhere, config, Category = Packaging, meta=(HideAlphaChannel))
	FColor TileBackgroundColor = FColor::FromHex(FString("#000040"));

	UPROPERTY(EditAnywhere, config, Category = Packaging, meta=(HideAlphaChannel))
	FColor SplashScreenBackgroundColor = FColor::FromHex(FString("#000040"));

	/**
	* The value for Package/Identity/Name in the generated AppX Manifest.  If empty, the ProjectName
	* from General Project Settings will be used.  When building for the Windows Store or using Xbox Live this value
	* must match the identity assigned in Dev Center
	*/
	UPROPERTY(EditAnywhere, config, Category = Packaging, AdvancedDisplay, Meta = (DisplayName = "Package/Identity/Name override"))
	FString PackageName;

	/**
	* The value for Package/Identity/Publisher in the generated AppX Manifest.  If empty, the CompanyDistinguishedName 
	* from General Project Settings will be used.  When building for the Windows Store or using Xbox Live this value 
	* must match the identity assigned in Dev Center
	*/
	UPROPERTY(EditAnywhere, config, Category = Packaging, AdvancedDisplay, Meta = (DisplayName = "Package/Identity/Publisher override"))
	FString PublisherName;

	/**
	* Identifies the device family that your package will target.
	*/
	UPROPERTY(EditAnywhere, config, Category = "OS Info")
	FString TargetDeviceFamily;

	/**
	* Minimum version of the universal platform required to run this title.
	* It will not be possible to deploy the build on earlier versions.
	*/
	UPROPERTY(EditAnywhere, config, Category = "OS Info", Meta = (DisplayName = "Minimum supported platform version"))
	FString MinimumPlatformVersion;

	/**
	* Specifies the maximum version of the universal platform on which the
	* title is known to work as expected.  When deployed to later versions
	* the title will experience the runtime behavior of the version given here.
	*/
	UPROPERTY(EditAnywhere, config, Category = "OS Info", Meta = (DisplayName = "Maximum tested platform version"))
	FString MaximumPlatformVersionTested;

	/** The compiler version to use for this project. May be different to the chosen IDE. */
	UPROPERTY(EditAnywhere, config, Category = "Toolchain", Meta = (DisplayName = "Compiler Version"))
	ECompilerVersion CompilerVersion;

	/**
	* List of supported <Capability><Capability> elements for the application.
	*/
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> CapabilityList;

	/**
	* List of supported <Capability><DeviceCapability> elements for the application.
	*/
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> DeviceCapabilityList;

	/**
	* List of supported <Capability><uap:Capability> elements for the application.
	*/
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> UapCapabilityList;

	/**
	* List of supported <Capability><uap2:Capability> elements for the application.
	*/
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	TArray<FString> Uap2CapabilityList;

	/**
	* Set default capabilities (InternetClientServer and PrivateNetworkClientServer) for the application.
	*/
	UPROPERTY(EditAnywhere, config, Category = Capabilities)
	bool bSetDefaultCapabilities = true;
};
