// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Editor/View/PredefinedReplicationColumns.h"
#include "ReplicationWidgetDelegates.h"

#include "Delegates/Delegate.h"
#include "Editor/View/ReplicationColumnsUtils.h"
#include "Misc/Attribute.h"
#include "Templates/SharedPointer.h"

class UObject;
class SWidget;

struct FConcertStreamObjectAutoBindingRules;
struct FObjectReplicationMap;

namespace UE::ConcertClientSharedSlate
{
	class IEditableMultiReplicationStreamModel;
	class IEditableReplicationStreamModel;
	class IMultiReplicationStreamEditor;
	
	class IReplicationStreamModel;
	class IObjectSelectionSourceModel;
	class IReplicationStreamEditor;
	class IReplicationStreamViewer;
	class IReplicationSubobjectView;
	class IStreamExtender;
	class ISubobjectModel;
	class IPropertySelectionSourceModel;
	
	/**
	 * Creates a model that can be passed to CreateEditor.
	 * 
	 * This model edits a FObjectReplicationMap that is assumed to be within the transactional OwnerObject.
	 * The model will respond to undo & redo by triggering the model's update callbacks.
	 * 
	 * @param OwnerObject The object containing the FObjectReplicationMap - used for transactions.
	 * @param ReplicationMapAttribute Getter for extracting the FObjectReplicationMap to edit
	 * @param Extender Optional callbacks for adding additional properties and objects when an object is added to the model
	 * 
	 * @return A model that will edit the FObjectReplicationMap.
	 */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IEditableReplicationStreamModel> CreatePropertySelectionModel(
		UObject& OwnerObject,
		TAttribute<FObjectReplicationMap*> ReplicationMapAttribute,
		TSharedPtr<IStreamExtender> Extender = nullptr
		);

	/** Builds a similar tree hierarchy as SSubobjectEditor. Reports only components as subobjects. */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<ISubobjectModel> CreateDefaultComponentHierarchySubobjectModel();
	
	/** Params for creating a IReplicationStreamViewer. */
	struct FCreateViewerParams
	{
		/**
		 * Optional. Determines the objects displayed as children to the top-level objects in the top section.
		 * If left unspecified, the top will only display actors.
		 * @note The created view will keep a strong reference to this.
		 */
		TSharedPtr<ISubobjectModel> SubobjectModel;

		/** Called to generate the context menu for objects. This extends the options already generated by this widget and is called at the end. */
		FExtendObjectMenu OnExtendObjectsContextMenu;
		
		/** Additional columns to add to the object view */
		TArray<ReplicationColumns::FReplicationTopLevelObjectColumn> AdditionalObjectColumns;
		/** Optional initial primary sort mode for object rows */
		FColumnSortInfo PrimaryObjectSort;
		/** Optional initial secondary sort mode for object rows */
		FColumnSortInfo SecondaryObjectSort;
		
		/** Additional columns to add to the property view */
		TArray<ReplicationColumns::FReplicationPropertyColumn> AdditionalPropertyColumns;
		/** Optional initial primary sort mode for object rows */
		FColumnSortInfo PrimaryPropertySort;
		/** Optional initial secondary sort mode for object rows */
		FColumnSortInfo SecondaryPropertySort;
		
		/** Optional widget to add to the left of the object list search bar. */
		TAlwaysValidWidget LeftOfObjectSearchBar;
		/** Optional widget to add to the left of the property list search bar. */
		TAlwaysValidWidget LeftOfPropertySearchBar;
	};

	// TODO DP 5.5: Create factory function that uses FCreateViewerParams and creates an IReplicationStreamViewer

	/** Params for creating an IReplicationStreamEditor */
	struct FCreateEditorParams
	{
		/**
		 * The model that the editor is displaying.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IEditableReplicationStreamModel> DataModel;
		
		/**
		 * Determines the objects that can be added to the object list. 
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IObjectSelectionSourceModel> ObjectSource;
		/**
		 * Determines the properties that can be added to the property list.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IPropertySelectionSourceModel> PropertySource;
		
		/** Optional. Determines whether all UI for changing the model should be disabled. */
		TAttribute<bool> IsEditingEnabled;
		/** Optional. Whenever IsEditingEnabled returns true, this tooltip is displayed for relevant, disabled UI. */
		TAttribute<FText> EditingDisabledToolTipText;

		/** Base params for customizing the viewing part of the editor */
		FCreateViewerParams ViewerParams;
	};

	/**
	 * Creates a base replication stream editor.
	 * 
	 * This editor implements base functionality for adding objects but has NO logic for editing properties.
	 * You are expected to inject widgets or columns, which implement editing properties.
	 * @see CreateDefaultStreamEditor, which adds a checkbox to the start of every property row.
	 *
	 * The editor consists of two or three areas (depending whether on whether SubobjectView was specified), which share similar workflows the level editor:
	 * 1. Root objects, similar to world outliner:
	 *		- Similar to World Outliner: Displays top-level objects, i.e. actors, are added here.
	 *		- FCreateEditorParams::ObjectSource is used to build a combo button through which new objects can be added.
	 * 2. Subobjects (optional):
	 *		- Similar to component view (SSubobjectEditor)
	 *		- Shows subobjects of a root objects selected above; typically components.
	 * 3. Properties:
	 *		- Similar to details panel
	 *		- Shows properties of the selected root object and / or subobjects.
	 */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IReplicationStreamEditor> CreateBaseStreamEditor(FCreateEditorParams Params);

	/**
	 * Creates a default IReplicationStreamEditor.
	 *
	 * This editor adds a checkbox to the start of every property row.
	 * - Checking adds the property to the selected objects' property mappings.
	 * - Unchecking removes the property to the selected objects' property mappings
	 * 
	 * @see CreateViewer for a description of the UI layout.
	 */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IReplicationStreamEditor> CreateDefaultStreamEditor(FCreateEditorParams Params);

	enum class EMultiStreamEditorFlags
	{
		None = 0,
		
		/** The passed in stream models transact and so should the implementation of the underlying editor. */
		Transactional = 1 << 0
	};
	ENUM_CLASS_FLAGS(EMultiStreamEditorFlags)

	DECLARE_DELEGATE_RetVal_OneParam(TSharedPtr<IEditableReplicationStreamModel>, FGetAutoAssignTarget, TConstArrayView<UObject*>);
	/** Params for creating an IMultiReplicationStreamEditor */
	struct FCreateMultiStreamEditorParams
	{
		/**
		 * The source of underlying streams that should be edited.
		 * Must NOT contain ConsolidationDataModel (this is check()-ed).
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IEditableMultiReplicationStreamModel> MultiStreamModel;
		
		/**
		 * Determines the objects that can be added to the object list. 
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IObjectSelectionSourceModel> ObjectSource;
		/**
		 * Determines the properties that can be added to the property list.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IPropertySelectionSourceModel> PropertySource;

		/** These flags modify the behaviour */
		EMultiStreamEditorFlags Flags = EMultiStreamEditorFlags::Transactional;

		/** Optional. If set, the Add Actor button should automatically assign the added object to stream returned */
		FGetAutoAssignTarget GetAutoAssignToStreamDelegate;
		
		/** Base params for customizing the viewing part of the editor */
		FCreateViewerParams ViewerParams;
	};

	/**
	 * Creates an editor that displays multiple streams in a single widget.
	 * 
	 * This editor consolidates all replicated objects into a single UI and display all properties in the class.
	 * You are supposed to inject custom columns into the property section for assigning specific properties
	 * to the streams in the IEditableReplicationStreamModel.
	 *
	 * The add & remove functionality of this editor adds to a
	 *
	 * @note This editor does NOT create any UI for changing the assigned properties. You are supposed to inject column widgets to the property rows for this.
	 */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IMultiReplicationStreamEditor> CreateBaseMultiStreamEditor(FCreateMultiStreamEditorParams Params);
}
