// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Editor/View/PredefinedReplicationColumns.h"
#include "ReplicationWidgetDelegates.h"

#include "Misc/Attribute.h"
#include "Templates/SharedPointer.h"

class UObject;
class SWidget;

struct FConcertReplicationEditorSettings;
struct FObjectReplicationMap;

namespace UE::ConcertClientSharedSlate
{
	class IEditableReplicationStreamModel;
	class IReplicationStreamModel;
	class IObjectSelectionSourceModel;
	class IReplicationStreamEditor;
	class IReplicationStreamViewer;
	class IReplicationSubobjectView;
	class ISubobjectModel;
	class IPropertySelectionSourceModel;
	
	/**
	 * Creates a model that can be passed to CreateEditor.
	 * 
	 * This model edits a FObjectReplicationMap that is assumed to be within the transactional OwnerObject.
	 * The model will respond to undo & redo by triggering the model's update callbacks.
	 * 
	 * @param OwnerObject The object containing the FObjectReplicationMap.
	 * @param ReplicationMapAttribute Getter for extracting the FObjectReplicationMap to edit
	 * 
	 * @return A model that will edit the FObjectReplicationMap.
	 */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IEditableReplicationStreamModel> CreatePropertySelectionModel(
		UObject& OwnerObject,
		TAttribute<FObjectReplicationMap*> ReplicationMapAttribute
		);

	/** Builds a similar tree hierarchy as SSubobjectEditor. Reports only components as subobjects. */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<ISubobjectModel> CreateDefaultComponentHierarchySubobjectModel();
	
	struct FCreateSubobjectViewParams
	{
		/** Additional columns that should be displayed for the subobjects. */
		TArray<ReplicationColumns::FReplicationSubobjectObjectColumn> AdditionalColumns;

		/** Determines the subobjects displayed in the view. */
		TSharedRef<ISubobjectModel> SubobjectModel = CreateDefaultComponentHierarchySubobjectModel();
	};
	/** Creates a stream editor with a subobject view that looks like the SSubobjectEditor. */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IReplicationSubobjectView> CreateUnrealEditorSubobjectView(
		FCreateSubobjectViewParams Params
		);

	/** Params for creating an IReplicationStreamEditor */
	struct FCreateEditorParams
	{
		/**
		 * The model that the editor is displaying.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IEditableReplicationStreamModel> DataModel;
		/**
		 * Determines the objects that can be added to the object list. 
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IObjectSelectionSourceModel> ObjectSource;
		/**
		 * Determines the properties that can be added to the property list.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IPropertySelectionSourceModel> PropertySource;

		/**
		 * Optional. This is inserted between the root object outliner and property view.
		 * It e.g. displays the components of the actor selected in the root object view.
		 * 
		 * Exists so it can be customized differently depending on whether used in the editor or on the server.
		 * @note The created view will keep a strong reference to this.
		 */
		TSharedPtr<IReplicationSubobjectView> SubobjectView;

		/**
		 * Optional. Determines the objects displayed as children to the top-level objects in the top section.
		 * If left unspecified, the top will only display actors.
		 * @note The created view will keep a strong reference to this.
		 */
		TSharedPtr<ISubobjectModel> SubobjectModel;

		/** Called to generate the context menu for objects. This extends the options already generated by this widget and is called at the end. */
		FExtendMenu OnExtendObjectsContextMenu;
		/** Optional. Used for determining the order in which properties are displayed. */
		FSortPropertyPredicate SortPropertyRowPredicate;
		
		/** Additional columns to add to the object view */
		TArray<ReplicationColumns::FReplicationTopLevelObjectColumn> AdditionalObjectColumns;
		/** Additional columns to add to the property view */
		TArray<ReplicationColumns::FReplicationPropertyColumn> AdditionalPropertyColumns;
		
		/** Optional widget to add to the left of the object list search bar. */
		TAlwaysValidWidget LeftOfObjectSearchBar;
		/** Optional widget to add to the left of the property list search bar. */
		TAlwaysValidWidget LeftOfPropertySearchBar;

		/** Optional. Determines whether all UI for changing the model should be disabled. */
		TAttribute<bool> IsEditingEnabled;
		/** Optional. Whenever IsEditingEnabled returns true, this tooltip is displayed for relevant, disabled UI. */
		TAttribute<FText> EditingDisabledToolTipText;

		/** Optional settings for auto adding common properties and objects. */
		TAttribute<const FConcertReplicationEditorSettings*> ReplicationSettingsAttribute;
	};

	/**
	 * Creates a base replication stream editor.
	 * 
	 * This editor implements base functionality for adding objects but has NO logic for editing properties.
	 * You are expected to inject widgets or columns, which implement editing properties.
	 * @see CreateDefaultStreamEditor, which adds a checkbox to the start of every property row.
	 *
	 * The editor consists of two or three areas (depending whether on whether SubobjectView was specified), which share similar workflows the level editor:
	 * 1. Root objects, similar to world outliner:
	 *		- Similar to World Outliner: Displays top-level objects, i.e. actors, are added here.
	 *		- FCreateEditorParams::ObjectSource is used to build a combo button through which new objects can be added.
	 * 2. Subobjects (optional):
	 *		- Similar to component view (SSubobjectEditor)
	 *		- Shows subobjects of a root objects selected above; typically components.
	 * 3. Properties:
	 *		- Similar to details panel
	 *		- Shows properties of the selected root object and / or subobjects.
	 */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IReplicationStreamEditor> CreateEditor(FCreateEditorParams Params);

	/**
	 * Creates a default IReplicationStreamEditor.
	 *
	 * This editor adds a checkbox to the start of every property row.
	 * - Checking adds the property to the selected objects' property mappings.
	 * - Unchecking removes the property to the selected objects' property mappings
	 *
	 * This requires a subobject view. If you do not pass it in, the default view, which looks like the SSubobjectEditor,
	 * is created.
	 * 
	 * @see CreateViewer for a description of the UI layout.
	 */
	CONCERTCLIENTSHAREDSLATE_API TSharedRef<IReplicationStreamEditor> CreateDefaultStreamEditor(FCreateEditorParams Params);
}