// Copyright Epic Games, Inc. All Rights Reserved.

// When loading SSS checkerboard pixel, do not adjust DiffuseColor/SpecularColor to preserve specular and diffuse lighting values for each pixel
#define ALLOW_SSS_MATERIAL_OVERRIDE 0

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "MegaLights.ush"
#include "MegaLightsVolume.ush"
#include "MegaLightsRayTracing.ush"
#include "../LightFunctionAtlas/LightFunctionAtlasCommon.usf"

uint VolumeDebugMode;
int VolumeDebugSliceIndex;
float3 VolumeFrameJitterOffset;
uint3 NumSamplesPerVoxel;
float VolumeMinSampleWeight;
uint3 DownsampledVolumeViewSize;
float VolumeInverseSquaredLightDistanceBiasScale;
uint DebugLightId;

RWTexture3D<uint> RWVolumeLightSamples;

uint3 GetSampleCoord(uint3 DownsampledVolumeCoord, uint LightSampleIndex)
{
	return DownsampledVolumeCoord * NumSamplesPerVoxel + uint3(LightSampleIndex % NUM_SAMPLES_PER_VOXEL_3D_X, LightSampleIndex / NUM_SAMPLES_PER_VOXEL_3D_X, 0);
}

/**
 * Run one thread per sample and generate new light samples for tracing
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, THREADGROUP_SIZE)]
void VolumeGenerateLightSamplesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	const uint3 DownsampledVolumeCoord = DispatchThreadId.xyz;
	if (all(DownsampledVolumeCoord < DownsampledVolumeViewSize))
	{
		FDebug Debug;
		#if DEBUG_MODE
		{
			int2 DebugScreenCoord = GetDebugScreenCoord();
			Debug.bActive = all(DownsampledVolumeCoord == int3(DebugScreenCoord >> MegaLightsVolumePixelSizeShift, VolumeDebugSliceIndex) / DOWNSAMPLE_FACTOR);
			Debug.Context = InitShaderPrintContext(true, float2(0.05, 0.05));
		}
		#endif

		const uint3 VolumeCoord = DownsampledVolumeCoordToVolumeCoord(DownsampledVolumeCoord);
		if (IsFroxelVisible(VolumeCoord))
		{
			float SceneDepth;
			const float3 TranslatedWorldPosition = ComputeCellTranslatedWorldPosition(VolumeCoord, VolumeFrameJitterOffset, SceneDepth);
			const float3 CameraVector = normalize(TranslatedWorldPosition - View.TranslatedWorldCameraOrigin);

			float SceneDepth2 = 0.0f;
			float CellRadius = length(TranslatedWorldPosition - ComputeCellTranslatedWorldPosition(VolumeCoord + uint3(1, 1, 1), VolumeFrameJitterOffset, SceneDepth2));
			// Bias the inverse squared light falloff based on voxel size to prevent aliasing near the light source
			float DistanceBiasSqr = max(CellRadius * VolumeInverseSquaredLightDistanceBiasScale, 1);
			DistanceBiasSqr *= DistanceBiasSqr;

			uint GridIndex = ComputeLightGridCellIndex(VolumeCoord.xy * MegaLightsVolumePixelSize, SceneDepth, 0);
			const FCulledLightsGridHeader CulledLightsGridHeader = GetCulledLightsGridHeader(GridIndex, 0);

			#if DEBUG_MODE
			if (Debug.bActive)
			{
				Print(Debug.Context, TEXT("VolumeGenerateLightSamples"));
				Newline(Debug.Context);
				Print(Debug.Context, TEXT("Coord: "));
				Print(Debug.Context, DownsampledVolumeCoord);
				Newline(Debug.Context);
				Print(Debug.Context, TEXT("TWS: "));
				Print(Debug.Context, TranslatedWorldPosition);
				Newline(Debug.Context);
				Print(Debug.Context, TEXT("DebugLightId: "));
				Print(Debug.Context, DebugLightId);

				AddCrossTWS(Debug.Context, TranslatedWorldPosition, 5.0f, float4(1, 0, 0, 1));

				Newline(Debug.Context);
				Print(Debug.Context, TEXT("LightId  | SampleWeight"));
			}
			#endif

			FLightSample LightSamples[NUM_SAMPLES_PER_VOXEL_1D];
			for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_VOXEL_1D; ++LightSampleIndex)
			{
				LightSamples[LightSampleIndex] = InitLightSample();
			}

			// Initialize random variables using spatiotemporal Blue Noise
			float LightIndexRandom[NUM_SAMPLES_PER_VOXEL_1D];
			{
				float GoldenRatioConjugate = 0.6180339887f;
				float RandomScalar = BlueNoiseScalar(VolumeCoordToNoiseCoord(DownsampledVolumeCoord), MegaLightsStateFrameIndex);

				for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_VOXEL_1D; ++LightSampleIndex)
				{
					LightIndexRandom[LightSampleIndex] = frac(RandomScalar + GoldenRatioConjugate * LightSampleIndex);
				}
			}

			#if DEBUG_MODE
			if (Debug.bActive)
			{
				Newline(Debug.Context);
				Print(Debug.Context, TEXT("NoiseCoord: "));
				Newline(Debug.Context);
				Print(Debug.Context, DownsampledVolumeCoord);
				Newline(Debug.Context);
				Print(Debug.Context, VolumeCoordToNoiseCoord(DownsampledVolumeCoord));
				Newline(Debug.Context);
				Print(Debug.Context, TEXT("Random: "));
				Print(Debug.Context, LightIndexRandom[0]);
			}
			#endif

			float WeightSum = 0.0f;

			LOOP
			for (uint GridLightIndex = 0; GridLightIndex < CulledLightsGridHeader.NumMegaLights; ++GridLightIndex)
			{
				const uint LocalLightIndex = GetCulledLightDataGrid(CulledLightsGridHeader.MegaLightsDataStartIndex + GridLightIndex);
				const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);
				const FDeferredLightData LightData = ConvertToDeferredLight(LocalLightData);

				checkSlow(LocalLightData.bMegaLightsSupported);
		
				float3 LightScattering = GetMegaLightsVolumeLighting(TranslatedWorldPosition, CameraVector, DistanceBiasSqr, LocalLightData, LightData) * View.PreExposure;
				float SampleWeight = log2(Luminance(LightScattering) + 1.0f);
				
				#if DEBUG_MODE
				if (Debug.bActive)
				{
					Newline(Debug.Context);
					Print(Debug.Context, LocalLightIndex);
					Print(Debug.Context, SampleWeight);
				}
				#endif

				if (SampleWeight > VolumeMinSampleWeight)
				{
					float Tau = WeightSum / (WeightSum + SampleWeight);
					WeightSum += SampleWeight;

					for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_VOXEL_1D; ++LightSampleIndex)
					{
						if (LightIndexRandom[LightSampleIndex] < Tau)
						{
							LightIndexRandom[LightSampleIndex] /= Tau;
						}
						else
						{
							// Select this sample
							LightIndexRandom[LightSampleIndex] = (LightIndexRandom[LightSampleIndex] - Tau) / (1.0f - Tau);
							LightSamples[LightSampleIndex].LocalLightIndex = LocalLightIndex;
							LightSamples[LightSampleIndex].Weight = SampleWeight;
						}

						LightIndexRandom[LightSampleIndex] = clamp(LightIndexRandom[LightSampleIndex], 0, 0.9999f);
					}
				}
			}

			#if DEBUG_MODE
			if (Debug.bActive)
			{
				Newline(Debug.Context);
				Print(Debug.Context, TEXT("Weight sum: "));
				Print(Debug.Context, WeightSum);
				Newline(Debug.Context);
				Print(Debug.Context, TEXT("Selected lights: "));

				for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_VOXEL_1D; ++LightSampleIndex)
				{
					FLightSample LightSample = LightSamples[LightSampleIndex];
						
					Newline(Debug.Context);
					Print(Debug.Context, LightSample.LocalLightIndex); 
					Print(Debug.Context, LightSample.Weight);
					Print(Debug.Context, WeightSum /  LightSample.Weight);

					if (VolumeDebugMode == DEBUG_MODE_VISUALIZE_SAMPLING)
					{
						const uint3 SampleCoord = GetSampleCoord(DownsampledVolumeCoord, LightSampleIndex);

						const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LightSample.LocalLightIndex);
						const FLightSampleTrace LightSampleTrace = GetLightSampleTrace(TranslatedWorldPosition, LightSample.LocalLightIndex, VolumeCoordToNoiseCoord(SampleCoord));

						AddLineTWS(Debug.Context, TranslatedWorldPosition, TranslatedWorldPosition + LightSampleTrace.Direction * LightSampleTrace.Distance, float4(LocalLightData.LightColorAndIdAndFalloffExponent.xyz / Luminance(LocalLightData.LightColorAndIdAndFalloffExponent.xyz), 1.0f));
					}
				}
			}
			#endif

			for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_VOXEL_1D; ++LightSampleIndex)
			{
				FLightSample LightSample = LightSamples[LightSampleIndex];

				if (LightSample.LocalLightIndex != MAX_LOCAL_LIGHT_INDEX)
				{
					const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LightSample.LocalLightIndex);
					const bool bCastShadows = UnpackCastShadow(asuint(LocalLightData.LightDirectionAndShadowMask.w));

					LightSample.bVisible = true;
					LightSample.bCompleted = bCastShadows ? false : true;
					LightSample.Weight = WeightSum / (NUM_SAMPLES_PER_VOXEL_1D * LightSample.Weight);
				}

				RWVolumeLightSamples[GetSampleCoord(DownsampledVolumeCoord, LightSampleIndex)] = PackLightSample(LightSample);
			}
		}
		else
		{
			for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_VOXEL_1D; ++LightSampleIndex)
			{
				FLightSample LightSample = InitLightSample();
				RWVolumeLightSamples[GetSampleCoord(DownsampledVolumeCoord, LightSampleIndex)] = PackLightSample(LightSample);
			}
		}
	}
}