// Copyright Epic Games, Inc. All Rights Reserved.

// When loading SSS checkerboard pixel, do not adjust DiffuseColor/SpecularColor to preserve specular and diffuse lighting values for each pixel
#define ALLOW_SSS_MATERIAL_OVERRIDE 0

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "MegaLights.ush"
#include "MegaLightsVolume.ush"
#include "../Lumen/LumenReflectionDenoiserCommon.ush"

int VolumeDebugSliceIndex;
float3 VolumeFrameJitterOffset;
float VolumeInverseSquaredLightDistanceBiasScale;
uint3 VolumeSampleViewSize;
uint3 NumSamplesPerVoxel;
Texture3D<uint> VolumeLightSamples;

RWTexture3D<float3> RWVolumeResolvedLighting;

// 2x2x2 neighborhood with borders
#define SHARED_TILE_SIZE_X ((2 + 2) * NUM_SAMPLES_PER_VOXEL_3D_X)
#define SHARED_TILE_SIZE_Y ((2 + 2) * NUM_SAMPLES_PER_VOXEL_3D_Y)
#define SHARED_TILE_SIZE_Z ((2 + 2) * NUM_SAMPLES_PER_VOXEL_3D_Z)
groupshared uint SharedSamples[SHARED_TILE_SIZE_X][SHARED_TILE_SIZE_Y][SHARED_TILE_SIZE_Z];

// Light scalarization
groupshared uint SharedLightHiMask;
groupshared uint SharedLightMask[SHARED_LIGHT_MASK_SIZE];

void AccumulateLightSample(uint3 SharedSampleCoord, uint LocalLightIndex, float UpsampleWeight, inout float SampleWeightSum)
{
	for (uint SampleOffsetZ = 0; SampleOffsetZ < NUM_SAMPLES_PER_VOXEL_3D_Z; ++SampleOffsetZ)
	{
		for (uint SampleOffsetY = 0; SampleOffsetY < NUM_SAMPLES_PER_VOXEL_3D_Y; ++SampleOffsetY)
		{
			for (uint SampleOffsetX = 0; SampleOffsetX < NUM_SAMPLES_PER_VOXEL_3D_X; ++SampleOffsetX)
			{
				FLightSample LightSample = UnpackLightSample(SharedSamples[SharedSampleCoord.x * NUM_SAMPLES_PER_VOXEL_3D_X + SampleOffsetX][SharedSampleCoord.y * NUM_SAMPLES_PER_VOXEL_3D_Y + SampleOffsetY][SharedSampleCoord.z * NUM_SAMPLES_PER_VOXEL_3D_Z + SampleOffsetZ]);

				if (LightSample.LocalLightIndex == LocalLightIndex)
				{
					SampleWeightSum += LightSample.Weight * UpsampleWeight;
				}
			}
		}
	}
}

uint3 GetStochasticOffset(float RandomScalar, float4 InterpolationWeights0, float4 InterpolationWeights1)
{
	uint3 StochasticTrilinearOffset = 0;
	if (RandomScalar < InterpolationWeights0.x)
	{
		StochasticTrilinearOffset = uint3(0, 0, 0);
	}
	else if (RandomScalar < InterpolationWeights0.x + InterpolationWeights0.y)
	{
		StochasticTrilinearOffset = uint3(1, 0, 0);
	}
	else if (RandomScalar < InterpolationWeights0.x + InterpolationWeights0.y + InterpolationWeights0.z)
	{
		StochasticTrilinearOffset = uint3(0, 1, 0);
	}
	else if (RandomScalar < InterpolationWeights0.x + InterpolationWeights0.y + InterpolationWeights0.z + InterpolationWeights0.w)
	{
		StochasticTrilinearOffset = uint3(1, 1, 0);
	}
	else if (RandomScalar < InterpolationWeights0.x + InterpolationWeights0.y + InterpolationWeights0.z + InterpolationWeights0.w + InterpolationWeights1.x)
	{
		StochasticTrilinearOffset = uint3(0, 0, 1);
	}
	else if (RandomScalar < InterpolationWeights0.x + InterpolationWeights0.y + InterpolationWeights0.z + InterpolationWeights0.w + InterpolationWeights1.x + InterpolationWeights1.y)
	{
		StochasticTrilinearOffset = uint3(1, 0, 1);
	}
	else if (RandomScalar < InterpolationWeights0.x + InterpolationWeights0.y + InterpolationWeights0.z + InterpolationWeights0.w + InterpolationWeights1.x + InterpolationWeights1.y + InterpolationWeights1.z)
	{
		StochasticTrilinearOffset = uint3(0, 1, 1);
	}
	else
	{
		StochasticTrilinearOffset = uint3(1, 1, 1);
	}
	return StochasticTrilinearOffset;
}

/**
 * Upsample light samples and apply all lights per voxel
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, THREADGROUP_SIZE)]
void VolumeShadeLightSamplesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint3 VolumeCoord = DispatchThreadId.xyz;

	uint LinearThreadIndex = GroupThreadId.x + GroupThreadId.y * THREADGROUP_SIZE + GroupThreadId.z * THREADGROUP_SIZE * THREADGROUP_SIZE;
	if (LinearThreadIndex == 0)
	{
		SharedLightHiMask = 0;
	}

	if (LinearThreadIndex < SHARED_LIGHT_MASK_SIZE)
	{
		SharedLightMask[LinearThreadIndex] = 0;
	}

	GroupMemoryBarrierWithGroupSync();

	// First load all samples into shared memory
	{
		uint LocalLightHiMask = 0;

		for (uint SharedCoordZ = GroupThreadId.z; SharedCoordZ < SHARED_TILE_SIZE_Z; SharedCoordZ += THREADGROUP_SIZE)
		{
			for (uint SharedCoordY = GroupThreadId.y; SharedCoordY < SHARED_TILE_SIZE_Y; SharedCoordY += THREADGROUP_SIZE)
			{
				for (uint SharedCoordX = GroupThreadId.x; SharedCoordX < SHARED_TILE_SIZE_X; SharedCoordX += THREADGROUP_SIZE)
				{
					const uint3 NumSamplesPerVoxel = uint3(NUM_SAMPLES_PER_VOXEL_3D_X, NUM_SAMPLES_PER_VOXEL_3D_Y, NUM_SAMPLES_PER_VOXEL_3D_Z);
					uint3 SharedSampleCoord = uint3(SharedCoordX, SharedCoordY, SharedCoordZ);
					int3 DownsampledVolumeCoord = int3(GroupId.xyz * THREADGROUP_SIZE - 1) / DOWNSAMPLE_FACTOR + SharedSampleCoord / NumSamplesPerVoxel;
					int3 SampleCoord = DownsampledVolumeCoord * NumSamplesPerVoxel + SharedSampleCoord % NumSamplesPerVoxel;

					FLightSample LightSample = InitLightSample();

					if (and(all(SampleCoord >= 0), all(SampleCoord < VolumeSampleViewSize)))
					{
						LightSample = UnpackLightSample(VolumeLightSamples[SampleCoord]);

						if (LightSample.bVisible && LightSample.LocalLightIndex < MAX_LOCAL_LIGHT_INDEX)
						{
							uint DWORDIndex = LightSample.LocalLightIndex / 32;
							uint BitMask = 1u << (LightSample.LocalLightIndex % 32);
							InterlockedOr(SharedLightMask[DWORDIndex], BitMask);

							uint HiBitMask = 1u << DWORDIndex;
							LocalLightHiMask |= HiBitMask;
						}
						else
						{
							LightSample = InitLightSample();
						}
					}

					SharedSamples[SharedSampleCoord.x][SharedSampleCoord.y][SharedSampleCoord.z] = PackLightSample(LightSample);
				}
			}
		}

		uint WaveHiMask = WaveActiveBitOr(LocalLightHiMask);
		if (WaveIsFirstLane())
		{
			InterlockedOr(SharedLightHiMask, WaveHiMask);
		}

		GroupMemoryBarrierWithGroupSync();
	}

	if (all(VolumeCoord < VolumeViewSize))
	{
		FDebug Debug;
		#if DEBUG_MODE
		{
			int2 DebugScreenCoord = GetDebugScreenCoord();
			Debug.bActive = all(VolumeCoord == int3(DebugScreenCoord >> MegaLightsVolumePixelSizeShift, VolumeDebugSliceIndex));
			Debug.Context = InitShaderPrintContext(true, float2(0.5, 0.05));
		}
		#endif

		float SceneDepth = 0.0f;
		const float3 TranslatedWorldPosition = ComputeCellTranslatedWorldPosition(VolumeCoord, VolumeFrameJitterOffset, SceneDepth);
		const float3 CameraVector = normalize(TranslatedWorldPosition - View.TranslatedWorldCameraOrigin);

		#if DEBUG_MODE
		if (Debug.bActive)
		{
			Print(Debug.Context, TEXT("VolumeShadeLightSamples"));
			Newline(Debug.Context);
			Print(Debug.Context, TEXT("Coord: "));
			Print(Debug.Context, VolumeCoord);
			Newline(Debug.Context);
			Print(Debug.Context, TEXT("TileCoord: "));
			Print(Debug.Context, GroupId.xyz);
			Newline(Debug.Context);
			Print(Debug.Context, TEXT("TWS: "));
			Print(Debug.Context, TranslatedWorldPosition);
			AddCrossTWS(Debug.Context, TranslatedWorldPosition, 5.0f, float4(0, 0, 1, 1));

			Newline(Debug.Context);
			Print(Debug.Context, TEXT("LightId   | Weight    | Lighting"));
		}
		#endif

		float SceneDepth2 = 0.0f;
		float SceneDepth3 = 0.0f;
		float CellRadius = length(TranslatedWorldPosition - ComputeCellTranslatedWorldPosition(VolumeCoord + uint3(1, 1, 1), VolumeFrameJitterOffset, SceneDepth2));
		float Cell2DRadius = length(TranslatedWorldPosition - ComputeCellTranslatedWorldPosition(VolumeCoord + uint3(1, 1, 0), VolumeFrameJitterOffset, SceneDepth3));
		float LightVolumetricSoftFadeDistance = LightSoftFading * Cell2DRadius;
		// Bias the inverse squared light falloff based on voxel size to prevent aliasing near the light source
		float DistanceBiasSqr = max(CellRadius * VolumeInverseSquaredLightDistanceBiasScale, 1);
		DistanceBiasSqr *= DistanceBiasSqr;

		const uint3 SharedSampleCoord000 = (GroupThreadId.xyz + 1) / DOWNSAMPLE_FACTOR;

		int3 DownsampledVolumeCoord000 = int3(VolumeCoord - 1) / DOWNSAMPLE_FACTOR;
		int3 VolumeCoordOffset = VolumeCoord - DownsampledVolumeCoord000 * 2;
		int3 SampleOffset000 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(0, 0, 0)) + uint3(0, 0, 0) * 2 - VolumeCoordOffset;
		int3 SampleOffset100 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(1, 0, 0)) + uint3(1, 0, 0) * 2 - VolumeCoordOffset;
		int3 SampleOffset010 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(0, 1, 0)) + uint3(0, 1, 0) * 2 - VolumeCoordOffset;
		int3 SampleOffset110 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(1, 1, 0)) + uint3(1, 1, 0) * 2 - VolumeCoordOffset;
		int3 SampleOffset001 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(0, 0, 1)) + uint3(0, 0, 1) * 2 - VolumeCoordOffset;
		int3 SampleOffset101 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(1, 0, 1)) + uint3(1, 0, 1) * 2 - VolumeCoordOffset;
		int3 SampleOffset011 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(0, 1, 1)) + uint3(0, 1, 1) * 2 - VolumeCoordOffset;
		int3 SampleOffset111 = GetSampleVoxelCoordJitter(DownsampledVolumeCoord000 + uint3(1, 1, 1)) + uint3(1, 1, 1) * 2 - VolumeCoordOffset;

		// Triangle filter weight between the shaded voxel and 8 neighbors
		float4 InterpolationWeights0;
		InterpolationWeights0.x = (2.0f - abs(SampleOffset000.x)) * (2.0f - abs(SampleOffset000.y)) * (2.0f - abs(SampleOffset000.z));
		InterpolationWeights0.y = (2.0f - abs(SampleOffset100.x)) * (2.0f - abs(SampleOffset100.y)) * (2.0f - abs(SampleOffset100.z));
		InterpolationWeights0.z = (2.0f - abs(SampleOffset010.x)) * (2.0f - abs(SampleOffset010.y)) * (2.0f - abs(SampleOffset010.z));
		InterpolationWeights0.w = (2.0f - abs(SampleOffset110.x)) * (2.0f - abs(SampleOffset110.y)) * (2.0f - abs(SampleOffset110.z));
		float4 InterpolationWeights1;
		InterpolationWeights1.x = (2.0f - abs(SampleOffset001.x)) * (2.0f - abs(SampleOffset001.y)) * (2.0f - abs(SampleOffset001.z));
		InterpolationWeights1.y = (2.0f - abs(SampleOffset101.x)) * (2.0f - abs(SampleOffset101.y)) * (2.0f - abs(SampleOffset101.z));
		InterpolationWeights1.z = (2.0f - abs(SampleOffset011.x)) * (2.0f - abs(SampleOffset011.y)) * (2.0f - abs(SampleOffset011.z));
		InterpolationWeights1.w = (2.0f - abs(SampleOffset111.x)) * (2.0f - abs(SampleOffset111.y)) * (2.0f - abs(SampleOffset111.z));

		// Normalize weights
		InterpolationWeights0 /= 8.0f;
		InterpolationWeights1 /= 8.0f;

		float3 LightScattering = 0.0f;

		if (IsFroxelVisible(VolumeCoord))
		{
			uint3 StochasticTrilinearOffset0 = 0;
			uint3 StochasticTrilinearOffset1 = 0;
			#if STOCHASTIC_SAMPLE_INTERPOLATION
			{
				const float RandomScalar = BlueNoiseScalar(VolumeCoordToNoiseCoord(VolumeCoord), MegaLightsStateFrameIndex);
				StochasticTrilinearOffset0 = GetStochasticOffset((RandomScalar + 0.0f) / 2.0f, InterpolationWeights0, InterpolationWeights1);
				StochasticTrilinearOffset1 = GetStochasticOffset((RandomScalar + 1.0f) / 2.0f, InterpolationWeights0, InterpolationWeights1);
			}
			#endif

			uint LightHiMask = SharedLightHiMask;
			while (LightHiMask != 0)
			{
				const uint NextHiBitIndex = firstbitlow(LightHiMask);
				const uint NextHiBitMask = 1u << NextHiBitIndex;
				LightHiMask ^= NextHiBitMask;

				const uint MaskIndex = NextHiBitIndex;
				uint LightMask = SharedLightMask[MaskIndex];

				while (LightMask != 0)
				{
					const uint NextBitIndex = firstbitlow(LightMask);
					const uint NextBitMask = 1u << NextBitIndex;
					LightMask ^= NextBitMask;

					const uint LocalLightIndex = MaskIndex * 32 + NextBitIndex;
					const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);
					const FDeferredLightData LightData = ConvertToDeferredLight(LocalLightData);

					float SampleWeight = 0.0f;
					#if STOCHASTIC_SAMPLE_INTERPOLATION
					{
						AccumulateLightSample(SharedSampleCoord000 + StochasticTrilinearOffset0, LocalLightIndex, 0.5f, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + StochasticTrilinearOffset1, LocalLightIndex, 0.5f, SampleWeight);
					}
					#else
					{
						AccumulateLightSample(SharedSampleCoord000 + uint3(0, 0, 0), LocalLightIndex, InterpolationWeights0.x, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + uint3(1, 0, 0), LocalLightIndex, InterpolationWeights0.y, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + uint3(0, 1, 0), LocalLightIndex, InterpolationWeights0.z, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + uint3(1, 1, 0), LocalLightIndex, InterpolationWeights0.w, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + uint3(0, 0, 1), LocalLightIndex, InterpolationWeights1.x, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + uint3(1, 0, 1), LocalLightIndex, InterpolationWeights1.y, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + uint3(0, 1, 1), LocalLightIndex, InterpolationWeights1.z, SampleWeight);
						AccumulateLightSample(SharedSampleCoord000 + uint3(1, 1, 1), LocalLightIndex, InterpolationWeights1.w, SampleWeight);
					}
					#endif

					#if DEBUG_MODE
					if (Debug.bActive)
					{
						Newline(Debug.Context);
						Print(Debug.Context, LocalLightIndex);
						Print(Debug.Context, SampleWeight);
						Print(Debug.Context, LightScattering);
					}
					#endif

					if (SampleWeight > 0.01f)
					{
						LightScattering += GetMegaLightsVolumeLighting(TranslatedWorldPosition, CameraVector, DistanceBiasSqr, LightVolumetricSoftFadeDistance, LocalLightData, LightData) * SampleWeight;
					}
				}
			}
		}

		#if DEBUG_MODE
		if (Debug.bActive)
		{
			Newline(Debug.Context);
			Print(Debug.Context, TEXT("Lighting: "));
			Print(Debug.Context, LightScattering);
		}
		#endif

		RWVolumeResolvedLighting[VolumeCoord] = LightScattering * View.PreExposure;
	}
}