// Copyright Epic Games, Inc. All Rights Reserved.

#ifndef NUM_SAMPLES_PER_PIXEL_1D
	#define NUM_SAMPLES_PER_PIXEL_1D 1
	#define NUM_SAMPLES_PER_PIXEL_2D_X 1
	#define NUM_SAMPLES_PER_PIXEL_2D_Y 1
#endif

#ifndef TILE_TYPE
	#define TILE_TYPE TILE_MODE_EMPTY
#endif

// When loading SSS checkerboard pixel, do not adjust DiffuseColor/SpecularColor to preserve specular and diffuse lighting values for each pixel
#define ALLOW_SSS_MATERIAL_OVERRIDE 0

// Disable hair backlit during sample generation as Hair's TT term creates too much false positive: 
// the TT terms is very strong, and is in most case occluded by underlying geometry (head/body/...)
#define HAIR_BSDF_BACKLIT 0

#define USE_IES_PROFILE 1
#define USE_LIGHT_FUNCTION_ATLAS 1

#include "../Common.ush"
#include "../BlueNoise.ush"
#include "MegaLightsShading.ush"
#include "MegaLightsRayTracing.ush"
#include "../LightFunctionAtlas/LightFunctionAtlasCommon.usf"

ADAPTIVE_LICM

struct FLightTargetPDF
{
	float3 Diffuse;
	float3 Specular;
	float Weight;
};

FLightTargetPDF InitLightTargetPDF()
{
	FLightTargetPDF LightTargetPDF;
	LightTargetPDF.Diffuse = 0.0f;
	LightTargetPDF.Specular = 0.0f;
	LightTargetPDF.Weight = 0.0f;
	return LightTargetPDF;
}

FLightTargetPDF GetLocalLightTargetPDF(FDeferredLightData LightData, float3 TranslatedWorldPosition, FMegaLightsMaterial Material, uint2 ScreenCoord, inout FDebug Debug)
{
	FLightTargetPDF LightTargetPDF = InitLightTargetPDF();

	float3 CameraVector = normalize(TranslatedWorldPosition - View.TranslatedWorldCameraOrigin);

	float4 LightAttenuation = 1.0f;
	float Dither = 0.5f;
	float SurfaceShadow = 1.0f;
	float AmbientOcclusion = 1.0f;

	LightData.ShadowedBits = 0;

	FDeferredLightingSplit SplitLighting = GetMegaLightsSplitLighting(
		TranslatedWorldPosition, CameraVector, Material, AmbientOcclusion, 
		LightData, LightAttenuation, Dither, ScreenCoord, 
		SurfaceShadow);

	LightTargetPDF.Diffuse = SplitLighting.DiffuseLighting.xyz * View.PreExposure;
	LightTargetPDF.Specular = SplitLighting.SpecularLighting.xyz * View.PreExposure;

	// #ml_todo: move light profile to GetDynamicLightingSplit for better handling
	if (LightData.IESAtlasIndex >= 0 && Luminance(LightTargetPDF.Diffuse + LightTargetPDF.Specular) > 0.01f)
	{
		const float LightProfileMult = ComputeLightProfileMultiplier(TranslatedWorldPosition, LightData.TranslatedWorldPosition, -LightData.Direction, LightData.Tangent, LightData.IESAtlasIndex);
		LightTargetPDF.Diffuse *= LightProfileMult;
		LightTargetPDF.Specular *= LightProfileMult;
	}

	// Simulate tonemapping
	LightTargetPDF.Weight = log2(Luminance(LightTargetPDF.Diffuse + LightTargetPDF.Specular) + 1.0f);

	return LightTargetPDF;
}

uint2 DownsampledViewMin;
uint2 DownsampledViewSize;
float MinSampleWeight;
uint2 NumSamplesPerPixel;
int UseIESProfiles;
int UseLightFunctionAtlas;
int DebugMode;
uint DebugLightId;

RWTexture2D<float> RWDownsampledSceneDepth;
RWTexture2D<UNORM float3> RWDownsampledSceneWorldNormal;
RWTexture2D<uint> RWLightSamples;
RWTexture2D<uint> RWLightSampleUV;

Texture2D MegaLightsDepthHistory;
float4 HistoryScreenPositionScaleBias;
float4 HistoryUVMinMax;
float4 HistoryGatherUVMinMax;

groupshared uint SharedCandidateLightHiMask;
groupshared uint SharedCandidateLightMask[SHARED_LIGHT_MASK_SIZE];

StructuredBuffer<uint> DownsampledTileAllocator;
StructuredBuffer<uint> DownsampledTileData;

StructuredBuffer<uint> VisibleLightHashHistory;
uint2 LightMaskSizeInTiles;
uint GuideByHistoryMode;
float LightWasHiddenPDFWeightScale;

uint DownsampledTileDataStride;
float2 DownsampledBufferInvSize;

uint2 GetSampleCoord(uint2 DownsampledScreenCoord, uint LightSampleIndex)
{
	return DownsampledScreenCoord * NumSamplesPerPixel + uint2(LightSampleIndex % NUM_SAMPLES_PER_PIXEL_2D_X, LightSampleIndex / NUM_SAMPLES_PER_PIXEL_2D_X);
}

void AppendVisibleLightsHashMap(uint2 TileCoordinate, int2 TileOffset, inout uint VisibleLightsHashMap[VISIBLE_LIGHT_HASH_SIZE])
{
	int2 LightMaskHistoryTileCoord = TileCoordinate + TileOffset;
	uint VisibleInLastFrameMask = 0;

	if (all(LightMaskHistoryTileCoord >= 0) && all(LightMaskHistoryTileCoord < (int2)LightMaskSizeInTiles))
	{
		uint LightMaskHistoryBase = VISIBLE_LIGHT_HASH_SIZE * (LightMaskHistoryTileCoord.y * LightMaskSizeInTiles.x + LightMaskHistoryTileCoord.x);
		for (uint HashMapElementIndex = 0; HashMapElementIndex < VISIBLE_LIGHT_HASH_SIZE; ++HashMapElementIndex)
		{
			VisibleLightsHashMap[HashMapElementIndex] |= VisibleLightHashHistory[LightMaskHistoryBase + HashMapElementIndex];
		}
	}
}

uint GetLightVisibilityMask(uint VisibleLightsHashMap[VISIBLE_LIGHT_HASH_SIZE], uint PrevLocalLightIndex)
{
	uint VisibilityMask = (VisibleLightsHashMap[(PrevLocalLightIndex % 32) / 8] >> (4 * (PrevLocalLightIndex % 8))) & 0xF;
	return VisibilityMask;
}

/**
 * Run one thread per sample and generate new light samples for tracing
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void GenerateLightSamplesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint LinearThreadIndex = GroupThreadId.y * THREADGROUP_SIZE + GroupThreadId.x;

	if (LinearThreadIndex == 0)
	{
		SharedCandidateLightHiMask = 0;
	}

	if (LinearThreadIndex < SHARED_LIGHT_MASK_SIZE)
	{
		SharedCandidateLightMask[LinearThreadIndex] = 0;
	}

	GroupMemoryBarrierWithGroupSync();

	uint DownsampledTileIndex = GroupId.x;
	if (DownsampledTileIndex < DownsampledTileAllocator[TILE_TYPE])
	{
		uint LocalCandidateLightHiMask = 0;
		uint2 DownsampledTileCoord = UnpackTile(DownsampledTileData[DownsampledTileIndex + TILE_TYPE * DownsampledTileDataStride]);
		uint2 DownsampledScreenCoord = DownsampledTileCoord * TILE_SIZE + GroupThreadId.xy;

		const bool bForceSimpleShading = 
			TILE_TYPE == TILE_MODE_SIMPLE_SHADING 
			|| TILE_TYPE == TILE_MODE_SIMPLE_SHADING_RECT
			|| TILE_TYPE == TILE_MODE_SIMPLE_SHADING_RECT_TEXTURED;

		if (all(DownsampledScreenCoord < DownsampledViewMin + DownsampledViewSize))
		{
			uint2 ScreenCoord = DownsampledScreenCoordToScreenCoord(DownsampledScreenCoord);	
			const float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
			const FMegaLightsMaterial Material = LoadMaterial(ScreenUV, ScreenCoord, bForceSimpleShading);
			const float SceneDepth = Material.Depth;

			const uint EyeIndex = 0;
			const uint GridIndex = ComputeLightGridCellIndex(ScreenCoord - View.ViewRectMin.xy, SceneDepth, EyeIndex);
			const FCulledLightsGridHeader CulledLightGridHeader = GetCulledLightsGridHeader(GridIndex, EyeIndex);
			const uint NumLightsInGridCell = min(CulledLightGridHeader.NumMegaLights, GetMaxLightsPerCell(EyeIndex));

			for (uint GridLightIndex = 0; GridLightIndex < NumLightsInGridCell; ++GridLightIndex)
			{
				const uint LocalLightIndex = GetCulledLightDataGrid(CulledLightGridHeader.MegaLightsDataStartIndex + GridLightIndex);
				const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);
				checkSlow(LocalLightData.bMegaLightsSupported);

				if (LocalLightIndex < MAX_LOCAL_LIGHT_INDEX)
				{
					uint DWORDIndex = LocalLightIndex / 32;
					uint BitMask = 1u << (LocalLightIndex % 32);
					InterlockedOr(SharedCandidateLightMask[DWORDIndex], BitMask);

					uint HiBitMask = 1u << DWORDIndex;
					LocalCandidateLightHiMask |= HiBitMask;
				}
			}
		}

		uint WaveHiMask = WaveActiveBitOr(LocalCandidateLightHiMask);
		if (WaveIsFirstLane())
		{
			InterlockedOr(SharedCandidateLightHiMask, WaveHiMask);
		}
	
		GroupMemoryBarrierWithGroupSync();

		if (all(DownsampledScreenCoord < DownsampledViewMin + DownsampledViewSize))
		{
			uint2 ScreenCoord = DownsampledScreenCoordToScreenCoord(DownsampledScreenCoord);

			FDebug Debug;
			#if DEBUG_MODE
			{
				int2 DebugScreenCoord = GetDebugScreenCoord();
				Debug.bActive = all(DownsampledScreenCoord == DebugScreenCoord / DOWNSAMPLE_FACTOR);
				Debug.Context = InitShaderPrintContext(true, float2(0.05, 0.05));
			}
			#endif

			FLightSample LightSamples[NUM_SAMPLES_PER_PIXEL_1D];
			for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
			{
				LightSamples[LightSampleIndex] = InitLightSample();
			}

			const float2 ScreenUV = (ScreenCoord + 0.5f) * View.BufferSizeAndInvSize.zw;
			const FMegaLightsMaterial Material = LoadMaterial(ScreenUV, ScreenCoord, bForceSimpleShading);
			const float SceneDepth = Material.Depth;
			float WeightSum = 0.0f;

			if (SceneDepth > 0)
			{
				float3 TranslatedWorldPosition = GetTranslatedWorldPositionFromScreenUV(ScreenUV, SceneDepth);		

				const uint EyeIndex = 0;
				const uint GridIndex = ComputeLightGridCellIndex(ScreenCoord - View.ViewRectMin.xy, SceneDepth, EyeIndex);
				const FCulledLightsGridHeader CulledLightGridHeader = GetCulledLightsGridHeader(GridIndex, EyeIndex);
				const uint NumLightsInGridCell = min(CulledLightGridHeader.NumLights, GetMaxLightsPerCell(EyeIndex));
				const uint NumLocalLights = GetNumLocalLights(EyeIndex);

				// Initialize random variables using spatiotemporal Blue Noise
				float LightIndexRandom[NUM_SAMPLES_PER_PIXEL_1D];
				{
					float RandomScalar = BlueNoiseScalar(DownsampledScreenCoord, MegaLightsStateFrameIndex);

					for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
					{
						LightIndexRandom[LightSampleIndex] = (RandomScalar + LightSampleIndex) / NUM_SAMPLES_PER_PIXEL_1D;
					}
				}

				bool bHasValidHistory = true;
				uint2 PrevScreenCoord = ScreenCoord;

#define REPROJECT_HISTORY_FOR_GUIDING 1
#if GUIDE_BY_HISTORY && REPROJECT_HISTORY_FOR_GUIDING
				{
					bHasValidHistory = false;

					float2 ScreenPosition = (ScreenUV - View.ScreenPositionScaleBias.wz) / View.ScreenPositionScaleBias.xy;
					float3 HistoryScreenPosition = GetHistoryScreenPosition(ScreenPosition, ScreenUV, ConvertToDeviceZ(SceneDepth));
					float2 HistoryScreenUV = HistoryScreenPosition.xy * HistoryScreenPositionScaleBias.xy + HistoryScreenPositionScaleBias.wz;

					bool bHistoryWasOnScreen = all(HistoryScreenUV >= HistoryUVMinMax.xy) && all(HistoryScreenUV <= HistoryUVMinMax.zw);

					HistoryScreenUV = clamp(HistoryScreenUV, HistoryGatherUVMinMax.xy, HistoryGatherUVMinMax.zw);

					uint2 HistoryScreenCoord = floor(HistoryScreenUV * View.BufferSizeAndInvSize.xy - 0.5f);
					float2 HistoryBilinearWeights = frac(HistoryScreenUV * View.BufferSizeAndInvSize.xy - 0.5f);
					float2 HistoryGatherUV = (HistoryScreenCoord + 1.0f) * View.BufferSizeAndInvSize.zw;

					float4 HistorySampleSceneDepth4 = MegaLightsDepthHistory.GatherRed(GlobalPointClampedSampler, HistoryGatherUV).wzxy;
					HistorySampleSceneDepth4.x = ConvertFromDeviceZ(HistorySampleSceneDepth4.x);
					HistorySampleSceneDepth4.y = ConvertFromDeviceZ(HistorySampleSceneDepth4.y);
					HistorySampleSceneDepth4.z = ConvertFromDeviceZ(HistorySampleSceneDepth4.z);
					HistorySampleSceneDepth4.w = ConvertFromDeviceZ(HistorySampleSceneDepth4.w);

					float ReprojectedSceneDepth = ConvertFromDeviceZ(HistoryScreenPosition.z);
					float DisocclusionDistanceThreshold = 0.03f;
					const float4 DistanceToHistoryValue = abs(HistorySampleSceneDepth4 - ReprojectedSceneDepth);
					float4 DepthWeights = select(DistanceToHistoryValue >= ReprojectedSceneDepth * DisocclusionDistanceThreshold, 0.0f, 1.0f);

					// If we are in a disoccluded region, ignore history
					// If our history was off-screen, it's still better to use the history at the edge of the screen
					if (any(DepthWeights > 0.01f) || !bHistoryWasOnScreen)
					{
						bHasValidHistory = true;
						PrevScreenCoord = HistoryScreenCoord;
					}
				}
#endif

				#if DEBUG_MODE
				if (Debug.bActive)
				{
					Print(Debug.Context, TEXT("MegaLights"));
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("TileType  | Num      "));
					Newline(Debug.Context);
					PrintTileTypeString(Debug.Context, TILE_MODE_SIMPLE_SHADING);
					Print(Debug.Context, TEXT(": "));
					Print(Debug.Context, DownsampledTileAllocator[TILE_MODE_SIMPLE_SHADING]);
					Newline(Debug.Context);
					PrintTileTypeString(Debug.Context, TILE_MODE_SIMPLE_SHADING_RECT);
					Print(Debug.Context, TEXT(": "));
					Print(Debug.Context, DownsampledTileAllocator[TILE_MODE_SIMPLE_SHADING_RECT]);
					Newline(Debug.Context);
					PrintTileTypeString(Debug.Context, TILE_MODE_SIMPLE_SHADING_RECT_TEXTURED);
					Print(Debug.Context, TEXT(": "));
					Print(Debug.Context, DownsampledTileAllocator[TILE_MODE_SIMPLE_SHADING_RECT_TEXTURED]);
					Newline(Debug.Context);
					PrintTileTypeString(Debug.Context, TILE_MODE_COMPLEX_SHADING);
					Print(Debug.Context, TEXT(": "));
					Print(Debug.Context, DownsampledTileAllocator[TILE_MODE_COMPLEX_SHADING]);
					Newline(Debug.Context);
					PrintTileTypeString(Debug.Context, TILE_MODE_COMPLEX_SHADING_RECT);
					Print(Debug.Context, TEXT(": "));
					Print(Debug.Context, DownsampledTileAllocator[TILE_MODE_COMPLEX_SHADING_RECT]);
					Newline(Debug.Context);
					PrintTileTypeString(Debug.Context, TILE_MODE_COMPLEX_SHADING_RECT_TEXTURED);
					Print(Debug.Context, TEXT(": "));
					Print(Debug.Context, DownsampledTileAllocator[TILE_MODE_COMPLEX_SHADING_RECT_TEXTURED]);
					Newline(Debug.Context);
					PrintTileTypeString(Debug.Context, TILE_MODE_EMPTY);
					Print(Debug.Context, TEXT(": "));
					Print(Debug.Context, DownsampledTileAllocator[TILE_MODE_EMPTY]);
					Newline(Debug.Context);
					Newline(Debug.Context);

					Print(Debug.Context, TEXT("GenerateSamples"));
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("ScreenCoord: "));
					Print(Debug.Context, ScreenCoord.x);
					Print(Debug.Context, ScreenCoord.y);
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("Roughness: "));
					Print(Debug.Context, Material.Roughness);
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("TileType: "));
					PrintTileTypeString(Debug.Context, TILE_TYPE);
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("View.PreExposure: "));
					Print(Debug.Context, View.PreExposure);
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("NumLightsInGridCell: "));
					Print(Debug.Context, NumLightsInGridCell);
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("NumLocalLights: "));
					Print(Debug.Context, NumLocalLights, Select(NumLocalLights < MAX_LOCAL_LIGHT_INDEX, FontWhite, FontRed));
					AddCrossTWS(Debug.Context, TranslatedWorldPosition, 5.0f, float4(1, 1, 0, 1));
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("LightId | LocalLightId | Weight  | LFAtlas   | IESAtlas  | History"));
				}
				#endif

#if GUIDE_BY_HISTORY
				uint VisibleLightsHashMap[VISIBLE_LIGHT_HASH_SIZE];
				for (uint HashMapElementIndex = 0; HashMapElementIndex < VISIBLE_LIGHT_HASH_SIZE; ++HashMapElementIndex)
				{
					VisibleLightsHashMap[HashMapElementIndex] = 0;
				}

				uint2 PrevScreenTileCoord = PrevScreenCoord / TILE_SIZE;
				AppendVisibleLightsHashMap(PrevScreenTileCoord, int2(0, 0), VisibleLightsHashMap);
				AppendVisibleLightsHashMap(PrevScreenTileCoord, int2(+1, 0), VisibleLightsHashMap);
				AppendVisibleLightsHashMap(PrevScreenTileCoord, int2(-1, 0), VisibleLightsHashMap);
				AppendVisibleLightsHashMap(PrevScreenTileCoord, int2(0, +1), VisibleLightsHashMap);
				AppendVisibleLightsHashMap(PrevScreenTileCoord, int2(0, -1), VisibleLightsHashMap);
#endif

				uint CandidateLightHiMask = SharedCandidateLightHiMask;
				while (CandidateLightHiMask != 0)
				{
					const uint NextHiBitIndex = firstbitlow(CandidateLightHiMask);
					const uint NextHiBitMask = 1u << NextHiBitIndex;
					CandidateLightHiMask ^= NextHiBitMask;

					const uint MaskIndex = NextHiBitIndex;
					uint CandidateLightMask = SharedCandidateLightMask[MaskIndex];

					while (CandidateLightMask != 0)
					{
						const uint NextBitIndex = firstbitlow(CandidateLightMask);
						const uint NextBitMask = 1u << NextBitIndex;
						CandidateLightMask ^= NextBitMask;

						const uint LocalLightIndex = MaskIndex * 32 + NextBitIndex;
						const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LocalLightIndex);
						FDeferredLightData LightData = ConvertToDeferredLight(LocalLightData);

						if (UseLightFunctionAtlas == 0)
						{
							LightData.LightFunctionAtlasLightIndex = 0;
						}

						if (UseIESProfiles == 0)
						{
							LightData.IESAtlasIndex = -1;
						}
						
						const bool bTileHasRect = TILE_TYPE == TILE_MODE_SIMPLE_SHADING_RECT || TILE_TYPE == TILE_MODE_SIMPLE_SHADING_RECT_TEXTURED || TILE_TYPE == TILE_MODE_COMPLEX_SHADING_RECT || TILE_TYPE == TILE_MODE_COMPLEX_SHADING_RECT_TEXTURED;
						if (!bTileHasRect)
						{
							LightData.bRectLight = false;
						}

						const bool bTileHasTextured = TILE_TYPE == TILE_MODE_SIMPLE_SHADING_RECT_TEXTURED || TILE_TYPE == TILE_MODE_COMPLEX_SHADING_RECT_TEXTURED;
						if (!bTileHasTextured)
						{
							LightData.RectLightData.AtlasData.AtlasMaxLevel = MAX_RECT_ATLAS_MIP;
						}
					
						FLightTargetPDF LightTargetPDF = GetLocalLightTargetPDF(LightData, TranslatedWorldPosition, Material, ScreenCoord, Debug);

						uint VisibleInLastFrameMask = 0;

						#if GUIDE_BY_HISTORY
						if (bHasValidHistory && LightTargetPDF.Weight > MinSampleWeight && LocalLightData.PrevLocalLightIndex >= 0)
						{
							VisibleInLastFrameMask = GetLightVisibilityMask(VisibleLightsHashMap, LocalLightData.PrevLocalLightIndex);
							LightTargetPDF.Weight *= VisibleInLastFrameMask != 0 ? 1.0f : LightWasHiddenPDFWeightScale;
						}
						#endif

						#if DEBUG_MODE
						if (Debug.bActive)
						{
							Newline(Debug.Context);
							Print(Debug.Context, LocalLightData.LightSceneId, Select(LocalLightData.LightSceneId == DebugLightId, FontYellow, FontWhite));
							Print(Debug.Context, LocalLightIndex, Select(LocalLightData.LightSceneId == DebugLightId, FontYellow, FontWhite));
							Print(Debug.Context, LightTargetPDF.Weight);
							Print(Debug.Context, LightData.LightFunctionAtlasLightIndex, Select(LightData.LightFunctionAtlasLightIndex != 0, FontWhite, FontGrey));
							Print(Debug.Context, LightData.IESAtlasIndex, Select(LightData.IESAtlasIndex != -1, FontWhite, FontGrey));

							uint VisibleInLastFrameMaskDebug = 0;
							VisibleInLastFrameMaskDebug += VisibleInLastFrameMask & 0x1 ? 1 : 0;
							VisibleInLastFrameMaskDebug += VisibleInLastFrameMask & 0x2 ? 10 : 0;
							VisibleInLastFrameMaskDebug += VisibleInLastFrameMask & 0x4 ? 100 : 0;
							VisibleInLastFrameMaskDebug += VisibleInLastFrameMask & 0x8 ? 1000 : 0;
							Print(Debug.Context, VisibleInLastFrameMaskDebug, Select(VisibleInLastFrameMask != 0, FontWhite, FontGrey));
						}
						#endif

						if (LightTargetPDF.Weight > MinSampleWeight)
						{
							float Tau = WeightSum / (WeightSum + LightTargetPDF.Weight);
							WeightSum += LightTargetPDF.Weight;

							for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
							{
								if (LightIndexRandom[LightSampleIndex] < Tau)
								{
									LightIndexRandom[LightSampleIndex] /= Tau;
								}
								else
								{
									// Select this sample
									LightIndexRandom[LightSampleIndex] = (LightIndexRandom[LightSampleIndex] - Tau) / (1.0f - Tau);
									LightSamples[LightSampleIndex].LocalLightIndex = LocalLightIndex;
									LightSamples[LightSampleIndex].Weight = LightTargetPDF.Weight;
								}

								LightIndexRandom[LightSampleIndex] = clamp(LightIndexRandom[LightSampleIndex], 0, 0.9999f);
							}
						}
					}
				}

				#if DEBUG_MODE
				if (Debug.bActive)
				{
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("Weight sum: "));
					Print(Debug.Context, WeightSum);
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("Selected:"));
					Newline(Debug.Context);
					Print(Debug.Context, TEXT("LightId | Weight  | PartiallyVis | UV"));
				}
				#endif

				// Finalize samples
				for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
				{
					FLightSample LightSample = LightSamples[LightSampleIndex];
					const FLocalLightData LocalLightData = GetLocalLightDataNonStereo(LightSample.LocalLightIndex);
					FDeferredLightData LightData = ConvertToDeferredLight(LocalLightData);

					uint2 SampleCoord = GetSampleCoord(DownsampledScreenCoord, LightSampleIndex);
					float2 LightSampleUV = BlueNoiseVec2(SampleCoord, MegaLightsStateFrameIndex);

					#if GUIDE_BY_HISTORY
					if (GuideByHistoryMode == 2)
					{
						uint VisibleInLastFrameMask = GetLightVisibilityMask(VisibleLightsHashMap, LocalLightData.PrevLocalLightIndex);

						// If entire light is fully visible or invisible then no need to guide samples towards the visible parts
						const bool bAreaLight = LightData.SourceRadius > 0.0f || LightData.SourceLength > 0.0f;
						if (VisibleInLastFrameMask != 0 && VisibleInLastFrameMask != 0xF && bAreaLight)
						{
							// Probabilities of hitting of 2x2 light UV regions based on the visibility from the previous frame
							const float Weight00 = VisibleInLastFrameMask & 0x1 ? 1.0f : LightWasHiddenPDFWeightScale;
							const float Weight10 = VisibleInLastFrameMask & 0x2 ? 1.0f : LightWasHiddenPDFWeightScale;
							const float Weight01 = VisibleInLastFrameMask & 0x4 ? 1.0f : LightWasHiddenPDFWeightScale;
							const float Weight11 = VisibleInLastFrameMask & 0x8 ? 1.0f : LightWasHiddenPDFWeightScale;

							// Warp samples across Y to fit desired distribution
							float SplitY = (Weight00 + Weight01) / (Weight00 + Weight10 + Weight01 + Weight11);

							if (LightSampleUV.x < SplitY)
							{
								LightSampleUV.x = LightSampleUV.x / SplitY;
								LightSampleUV.x *= 0.5f;
							}
							else
							{
								LightSampleUV.x = (LightSampleUV.x - SplitY) / (1.0f - SplitY);
								LightSampleUV.x = LightSampleUV.x * 0.5f + 0.5f;
							}

							// Warp samples across X to fit desired distribution
							float SplitX = LightSampleUV.x < 0.5f ? (Weight00 / (Weight00 + Weight01)) : (Weight10 / (Weight10 + Weight11));
							if (LightSampleUV.y < SplitX)
							{
								LightSampleUV.y = LightSampleUV.y / SplitX;
								LightSampleUV.y *= 0.5f;
							}
							else
							{
								LightSampleUV.y = (LightSampleUV.y - SplitX) / (1.0f - SplitX);
								LightSampleUV.y = LightSampleUV.y * 0.5f + 0.5f;
							}

							float SelectedWeight;
							if (LightSampleUV.x < 0.5f)
							{
								SelectedWeight = LightSampleUV.y < 0.5f ? Weight00 : Weight01;
							}
							else
							{
								SelectedWeight = LightSampleUV.y < 0.5f ? Weight10 : Weight11;
							}

							// Fixup weights to match new sample distribution
							float PerLightWeightSum = Weight00 + Weight10 + Weight01 + Weight11;
							float Normalization = LightSample.Weight / PerLightWeightSum;
							LightSample.Weight = SelectedWeight * Normalization * 4.0f;
							LightSample.bPartiallyVisibleLight = true;
						}
					}
					#endif

					RWLightSampleUV[SampleCoord] = PackLightSampleUV(LightSampleUV);

					#if DEBUG_MODE
					if (Debug.bActive)
					{						
						Newline(Debug.Context);
						Print(Debug.Context, LocalLightData.LightSceneId, Select(LocalLightData.LightSceneId == DebugLightId, FontYellow, FontWhite));
						Print(Debug.Context, LightSample.Weight);
						Print(Debug.Context, LightSample.bPartiallyVisibleLight ? 1u : 0u);
						Print(Debug.Context, LightSampleUV);
						if (DebugMode == DEBUG_MODE_VISUALIZE_SAMPLING)
						{
							const uint2 SampleCoord = GetSampleCoord(DownsampledScreenCoord, LightSampleIndex);
							const FLightSampleTrace LightSampleTrace = GetLightSampleTrace(TranslatedWorldPosition, LightSample.LocalLightIndex, LightSampleUV);
							AddLineTWS(Debug.Context, TranslatedWorldPosition, TranslatedWorldPosition + LightSampleTrace.Direction * LightSampleTrace.Distance, float4(LocalLightData.LightColorAndIdAndFalloffExponent.xyz / Luminance(LocalLightData.LightColorAndIdAndFalloffExponent.xyz), 1.0f));
						}
					}
					#endif

					if (LightSample.LocalLightIndex != MAX_LOCAL_LIGHT_INDEX)
					{
						const bool bCastShadows = UnpackCastShadow(asuint(LocalLightData.LightDirectionAndShadowMask.w));

						LightSample.bVisible = true;
						LightSample.bCompleted = bCastShadows ? false : true;
						LightSample.Weight = WeightSum / (NUM_SAMPLES_PER_PIXEL_1D * LightSample.Weight);
					}

					RWLightSamples[GetSampleCoord(DownsampledScreenCoord, LightSampleIndex)] = PackLightSample(LightSample);
				}
			}
			else
			{
				for (uint LightSampleIndex = 0; LightSampleIndex < NUM_SAMPLES_PER_PIXEL_1D; ++LightSampleIndex)
				{
					RWLightSamples[GetSampleCoord(DownsampledScreenCoord, LightSampleIndex)] = PackLightSample(InitLightSample());
				}
			}

			RWDownsampledSceneDepth[DownsampledScreenCoord] = SceneDepth;
			RWDownsampledSceneWorldNormal[DownsampledScreenCoord] = EncodeNormal(Material.WorldNormalForPositionBias);
		}
	}
}

/**
 * Clear data for empty tiles, which won't be processed by GenerateLightSamplesCS
 */
[numthreads(THREADGROUP_SIZE, THREADGROUP_SIZE, 1)]
void ClearLightSamplesCS(
	uint3 GroupId : SV_GroupID,
	uint3 GroupThreadId : SV_GroupThreadID,
	uint3 DispatchThreadId : SV_DispatchThreadID)
{
	uint DownsampledTileIndex = GroupId.x;
	if (DownsampledTileIndex < DownsampledTileAllocator[TILE_MODE_EMPTY])
	{
		uint2 DownsampledTileCoord = UnpackTile(DownsampledTileData[DownsampledTileIndex + TILE_MODE_EMPTY * DownsampledTileDataStride]);
		uint2 DownsampledScreenCoord = DownsampledTileCoord * TILE_SIZE + GroupThreadId.xy;

		if (all(DownsampledScreenCoord < DownsampledViewMin + DownsampledViewSize))
		{
			for (uint LightSampleY = 0; LightSampleY < NumSamplesPerPixel.y; ++LightSampleY)
			{
				for (uint LightSampleX = 0; LightSampleX < NumSamplesPerPixel.x; ++LightSampleX)
				{
					FLightSample LightSample = InitLightSample();
					RWLightSamples[DownsampledScreenCoord * NumSamplesPerPixel + uint2(LightSampleX, LightSampleY)] = PackLightSample(LightSample);
				}
			}
		}
	}
}