// Copyright Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	FullscreenVertexShader.usf: Most basic multi platform full screen vertex shader
=============================================================================*/

#include "../Common.ush"

#ifndef SCREEN_VS_FOR_INSTANCED_VIEWS
	#define SCREEN_VS_FOR_INSTANCED_VIEWS 0
#endif

void MainVS(
	float2 ViewportUV : ATTRIBUTE0,
	float2 UV         : ATTRIBUTE1, // TODO: kill
#if !SCREEN_VS_FOR_INSTANCED_VIEWS
	out float4 OutPosition : SV_POSITION
#else
	uint InstanceId	  : SV_InstanceID,
	out float4 OutPosition : SV_POSITION,
	out uint OutViewportId	: SV_ViewportArrayIndex,
	out nointerpolation uint OutViewId : VIEW_ID
#endif
	)
{
	OutPosition = float4(ViewportUVToScreenPos(ViewportUV), 0, 1);

#if SCREEN_VS_FOR_INSTANCED_VIEWS
	OutViewportId = InstanceId;
	OutViewId = InstanceId;
#endif
}

float4 PreTransform;
void MainForPreTransform(in uint VertexId : SV_VertexID, out FScreenVertexOutput Output)
{
	Output.UV = float2(((VertexId + 1) / 3) & 1, VertexId & 1);
	Output.Position.xy = float2(Output.UV.x, 1.f - Output.UV.y) * 2.f - 1.f;
	Output.Position.zw = float2(0, 1);
	Output.Position.xy = float2(Output.Position.x * PreTransform.x + Output.Position.y * PreTransform.z, Output.Position.x * PreTransform.y + Output.Position.y * PreTransform.w);
}