// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Editor/View/PredefinedReplicationColumns.h"
#include "ReplicationWidgetDelegates.h"

#include "Delegates/Delegate.h"
#include "Editor/View/ReplicationColumnsUtils.h"
#include "Misc/Attribute.h"
#include "Templates/SharedPointer.h"

class UObject;
class SWidget;

struct FConcertStreamObjectAutoBindingRules;
struct FConcertObjectReplicationMap;

namespace UE::ConcertSharedSlate
{
	class IEditableMultiReplicationStreamModel;
	class IEditableReplicationStreamModel;
	class IMultiReplicationStreamEditor;
	
	class IReplicationStreamModel;
	class IObjectSelectionSourceModel;
	class IReplicationStreamEditor;
	class IReplicationStreamViewer;
	class IReplicationSubobjectView;
	class IStreamExtender;
	class ISubobjectModel;
	class IPropertySelectionSourceModel;
	
	/**
	 * Creates a model that can be passed to CreateEditor.
	 * 
	 * @param ReplicationMapAttribute Getter for extracting the FConcertObjectReplicationMap to edit
	 * @param Extender Optional callbacks for adding additional properties and objects when an object is added to the model
	 * 
	 * @return A model that will edit the FConcertObjectReplicationMap.
	 */
	CONCERTSHAREDSLATE_API TSharedRef<IEditableReplicationStreamModel> CreateBaseStreamModel(
		TAttribute<FConcertObjectReplicationMap*> ReplicationMapAttribute,
		TSharedPtr<IStreamExtender> Extender = nullptr
		);
	
	/** Params for creating a IReplicationStreamViewer. */
	struct FCreateViewerParams
	{
		/**
		 * Optional. Determines the objects displayed as children to the top-level objects in the top section.
		 * If left unspecified, the top will only display actors.
		 * @note The created view will keep a strong reference to this.
		 */
		TSharedPtr<ISubobjectModel> SubobjectModel;

		/** Called to generate the context menu for objects. This extends the options already generated by this widget and is called at the end. */
		FExtendObjectMenu OnExtendObjectsContextMenu;
		
		/** Additional columns to add to the object view */
		TArray<ReplicationColumns::FReplicationTopLevelObjectColumn> AdditionalObjectColumns;
		/** Optional initial primary sort mode for object rows */
		FColumnSortInfo PrimaryObjectSort;
		/** Optional initial secondary sort mode for object rows */
		FColumnSortInfo SecondaryObjectSort;
		
		/** Additional columns to add to the property view */
		TArray<ReplicationColumns::FReplicationPropertyColumn> AdditionalPropertyColumns;
		/** Optional initial primary sort mode for object rows */
		FColumnSortInfo PrimaryPropertySort;
		/** Optional initial secondary sort mode for object rows */
		FColumnSortInfo SecondaryPropertySort;
		
		/** Optional widget to add to the left of the object list search bar. */
		TAlwaysValidWidget LeftOfObjectSearchBar;
		/** Optional widget to add to the left of the property list search bar. */
		TAlwaysValidWidget LeftOfPropertySearchBar;
	};

	// TODO DP 5.5: Create factory function that uses FCreateViewerParams and creates an IReplicationStreamViewer

	/** Params for creating an IReplicationStreamEditor */
	struct FCreateEditorParams
	{
		/**
		 * The model that the editor is displaying.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IEditableReplicationStreamModel> DataModel;
		
		/**
		 * Determines the objects that can be added to the object list. 
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IObjectSelectionSourceModel> ObjectSource;
		/**
		 * Determines the objects that are displayed in the property list. 
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IPropertySelectionSourceModel> PropertySource;
		
		/** Optional. Determines whether all UI for changing the model should be disabled. */
		TAttribute<bool> IsEditingEnabled;
		/** Optional. Whenever IsEditingEnabled returns true, this tooltip is displayed for relevant, disabled UI. */
		TAttribute<FText> EditingDisabledToolTipText;

		/** Base params for customizing the viewing part of the editor */
		FCreateViewerParams ViewerParams;
	};

	/**
	 * Creates a base replication stream editor.
	 * 
	 * This editor implements base functionality for adding objects but has NO logic for editing properties.
	 * You are expected to inject widgets or columns, which implement editing properties.
	 * @see ConcertClientSharedSlate::CreateDefaultStreamEditor, which adds a checkbox to the start of every property row.
	 *
	 * The editor consists of two or three areas (depending whether on whether SubobjectView was specified), which share similar workflows the level editor:
	 * 1. Root objects, similar to world outliner:
	 *		- Similar to World Outliner: Displays top-level objects, i.e. actors, are added here.
	 *		- FCreateEditorParams::ObjectSource is used to build a combo button through which new objects can be added.
	 * 2. Subobjects (optional):
	 *		- Similar to component view (SSubobjectEditor)
	 *		- Shows subobjects of a root objects selected above; typically components.
	 * 3. Properties:
	 *		- Similar to details panel
	 *		- Shows properties of the selected root object and / or subobjects.
	 */
	CONCERTSHAREDSLATE_API TSharedRef<IReplicationStreamEditor> CreateBaseStreamEditor(FCreateEditorParams Params);

	DECLARE_DELEGATE_RetVal_OneParam(TSharedPtr<IEditableReplicationStreamModel>, FGetAutoAssignTarget, TConstArrayView<UObject*>);
	/** Params for creating an IMultiReplicationStreamEditor */
	struct FCreateMultiStreamEditorParams
	{
		/**
		 * The source of underlying streams that should be edited.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IEditableMultiReplicationStreamModel> MultiStreamModel;

		/**
		 * This model consolidates all objects in all streams.
		 * 
		 * When an object is added
		 * - to one of the streams,
		 * - via the "add" button,
		 * it is added here, too. 
		 * This is needed for the internal operation of the multi view.
		 *
		 * You can make this model internally transact (@see ConcertClientSharedSlate::CreateTransactionalStreamModel).
		 * Doing so causes the objects added via "add" button to be transacted meaning the user can undo adding objects.
		 * 
		 * @note The view will keep a strong reference to this
		 */
		TSharedRef<IEditableReplicationStreamModel> ConsolidatedObjectModel;
		
		/**
		 * Determines the objects that are displayed in the property list. 
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IObjectSelectionSourceModel> ObjectSource;
		/**
		 * Determines the properties that can be added to the property list.
		 * @note The view will keep a strong reference to this.
		 */
		TSharedRef<IPropertySelectionSourceModel> PropertySource;

		/** Optional. If set, the Add Actor button should automatically assign the added object to stream returned */
		FGetAutoAssignTarget GetAutoAssignToStreamDelegate;
		
		/** Base params for customizing the viewing part of the editor */
		FCreateViewerParams ViewerParams;
	};

	/**
	 * Creates an editor that displays multiple streams in a single widget.
	 * 
	 * This editor consolidates all replicated objects into a single UI and display all properties in the class.
	 * You are supposed to inject custom columns into the property section for assigning specific properties
	 * to the streams in the IEditableReplicationStreamModel.
	 *
	 * @note This editor does NOT create any UI for changing the assigned properties. You are supposed to inject column widgets to the property rows for this.
	 */
	CONCERTSHAREDSLATE_API TSharedRef<IMultiReplicationStreamEditor> CreateBaseMultiStreamEditor(FCreateMultiStreamEditorParams Params);
}
