// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

// Sanity guard. 
#ifndef SUBSTRATE_ENABLED
	#define SUBSTRATE_ENABLED 1
	#error SUBSTRATE_ENABLED needs to be defined
#endif

#if SUBSTRATE_ENABLED

#define USE_SUBSTRATE_ENV_LIGHTING_COMMON 1
#include "SubstrateLightingCommon.ush"

// Env. lighting evaluation for Substrate material.
// Unpack BSDF on-the-fly
FSubstrateDeferredLighting SubstrateEnvironmentLighting(
	float4 SvPosition,
	float2 BufferUV,
	float SceneDepth,
	float3 WorldPosition,
	float3 TranslatedWorldPosition,
	float3 CameraToPixel,
	float3 V,
	float ScreenAmbientOcclusion,
	float TopLayerSpecularContributionFactor,
	bool bEnableSpecular,
	FSubstrateIntegrationSettings Settings,
	FSubstrateMaterialContainer MaterialBuffer,
	FSubstrateAddressing SubstrateAddressing,
	FSubstratePixelHeader SubstratePixelHeader,
	float CloudVolumetricAOShadow,
	inout float SSRReductionFactor,
	inout float3 SSRTopLayerEnvBRDF)
{
	FSubstrateDeferredLighting SubstrateLighting = GetInitialisedSubstrateDeferredLighting();

	SSRReductionFactor = 1.0f;

#if APPLY_SKY_SHADOWING
	// Sample DFAO only once
	FUpsampleDFAOOutput UpsampleDFAOOutput = UpsampleDFAO(BufferUV, SceneDepth);
#endif

	float CombinedScreenAndMaterialAO = SubstrateGetAO(SubstratePixelHeader) * ScreenAmbientOcclusion;

	
#if USE_DEFAULT_ENV_LIGHTING_INPUT && FEATURE_LEVEL >= FEATURE_LEVEL_SM5
	float2 LocalPosition = SvPosition.xy - View.ViewRectMin.xy;

	uint GridIndex = ComputeLightGridCellIndex(uint2(LocalPosition.x, LocalPosition.y), SceneDepth);
	uint NumCulledEntryIndex = (ForwardLightData.NumGridCells + GridIndex) * NUM_CULLED_LIGHTS_GRID_STRIDE;
	uint NumCulledReflectionCaptures = min(ForwardLightData.NumCulledLightsGrid[NumCulledEntryIndex + 0], ForwardLightData.NumReflectionCaptures);
	uint CaptureDataStartIndex = ForwardLightData.NumCulledLightsGrid[NumCulledEntryIndex + 1];
#else
	uint CaptureDataStartIndex = 0;
	uint NumCulledReflectionCaptures = 0;
#endif

	Substrate_for (uint ClosureIndex = 0, ClosureIndex < SubstratePixelHeader.ClosureCount, ++ClosureIndex)
	{
		FSubstrateBSDF BSDF = UnpackSubstrateBSDF(MaterialBuffer, SubstrateAddressing, SubstratePixelHeader);

		// Create the BSDF context
		FSubstrateBSDFContext SubstrateBSDFContext = SubstrateCreateBSDFContext(SubstratePixelHeader, BSDF, SubstrateAddressing, V);

		const float3 BSDFThroughput = LuminanceWeight(SubstrateBSDFContext, BSDF); // Use the reflected direction

		// Evaluate environment lighting
		FSubstrateEnvLightResult SubstrateEnvLight = SubstrateEvaluateForEnvLight(SubstrateBSDFContext, bEnableSpecular, Settings);

		float3 BentNormal = SubstrateEnvLight.DiffuseNormal;
	#if APPLY_SKY_SHADOWING
		// Set DiffuseNormal as the bent normal for all diffuse computations.
		BentNormal = ApplyDFAO(UpsampleDFAOOutput, SubstrateEnvLight.DiffuseNormal);
	#endif

		float3 DiffuseLighting = 0;
		float3 SpecularLighting = 0;
		SubstrateEnvLightingCommon(
			SubstrateEnvLight,
			SubstratePixelHeader,
			SubstrateBSDFContext,
			BSDF,
			BentNormal,
			BSDFThroughput,
			CaptureDataStartIndex,
			NumCulledReflectionCaptures,
			ScreenAmbientOcclusion,
			CloudVolumetricAOShadow,
			TopLayerSpecularContributionFactor,
			TranslatedWorldPosition,
			CombinedScreenAndMaterialAO,
			SSRReductionFactor,
			DiffuseLighting,
			SpecularLighting);

		const bool bIsTopLayer = BSDF_GETISTOPLAYER(BSDF);
		if (bIsTopLayer)
		{
			// The specular path weight applied on SSR. It must account for throughput even for top surface because it also contains coverage.
			SSRTopLayerEnvBRDF += BSDFThroughput * SubstrateEnvLight.SSRSpecularWeight;
		}

		// SUBSTRATE_TODO ReflectionEnvironment(...) for static reflection volumes.

		FLightAccumulator Out = (FLightAccumulator)0;
		LightAccumulator_AddSplit(Out, DiffuseLighting, SpecularLighting, DiffuseLighting, View.PreExposure, SubstrateEnvLight.bPostProcessSubsurface);
		AccumulateSubstrateDeferredLighting(SubstrateLighting, Out, SubstrateEnvLight.bPostProcessSubsurface, BSDF_GETISTOPLAYER(BSDF));
	}

	SSRReductionFactor = saturate(SSRReductionFactor);

	return SubstrateLighting;
}

#endif // SUBSTRATE_ENABLED