// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "/Engine/Private/Common.ush"
#include "/Engine/Shared/SubstrateDefinitions.h"   
#include "Substrate.ush"

#if SUBSTRATE_ENABLED

#ifndef USE_8BIT_TILE_COORD
#error USE_8BIT_TILE_COORD needs to be defined
#define USE_8BIT_TILE_COORD 0
#endif
////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Substrate material type tile

uint2 SubstrateUnpackTile(uint In)
{
#if USE_8BIT_TILE_COORD
	return uint2(In & 0xFF, In >> 8);
#else
	return uint2(In & 0xFFFF, In >> 16);
#endif
}

uint SubstratePackTile(uint2 TileCoord)
{
#if USE_8BIT_TILE_COORD
	return TileCoord.x | (TileCoord.y << 8);
#else
  #if COMPILER_SUPPORTS_PACK_INTRINSICS
	return PackUInt2ToUInt(TileCoord.x, TileCoord.y);
  #else
	return TileCoord.x | (TileCoord.y << 16); // assumes 16bit is enough to represent a tiled resolution up to 65,535 :)
  #endif
#endif
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Substrate BSDF tile

struct FSubstrateBSDFTile
{
	uint2 TileCoord;
	uint  BSDFIndex;
	uint  BSDFCount;
};

uint PackBSDFTile(FSubstrateBSDFTile In)
{
	// Tile coord are encoded onto 10bits. Max resolution 8k x 8k. Max 8 tiles per pixel.
	return 
		PackTileCoord10bits(In.TileCoord)|
		((In.BSDFIndex    & 0xF  ) << 20)| 
		((In.BSDFCount    & 0xF  ) << 24);
}

FSubstrateBSDFTile UnpackBSDFTile(uint In)
{
	FSubstrateBSDFTile Out;
	Out.TileCoord   = UnpackTileCoord10bits(In);
	Out.BSDFIndex   = (In >> 20u) & 0xF;
	Out.BSDFCount   = (In >> 24u) & 0xF;
	return Out;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Substrate BSDF offset

// Store the material slice index offset for each BSDF, for pixels containing several BSDFs
struct FSubstrateBSDFOffset
{
	uint BSDFOffsets[SUBSTRATE_MAX_BSDF_COUNT_FOR_BDSFOFFSET];
	uint BSDFCount;
};

bool HasMultipleBSDFs(uint InPackedBSDFOffset)
{
	// If a tile has:
	// * No BSDF its value will be 0 (no offset)
	// * 1 BSDF it will have a single offset (value=1, 1uint header)
	// * Several BSDFs, it will have several offset (value > 1)
	return InPackedBSDFOffset > 1;
}

uint PackBSDFOffset(FSubstrateBSDFOffset In)
{
	// Packed as relative cumulative offsets of N bits, stored into 32 bits
	// | N bits | N bits | N bits | N bits | ... | N bits |
	//   BSDF 0   BSDF 1   BSDF 2   BSDF 3  ...   BSDF (2^N - 1)

	uint Out = 0;
	const uint BSDFCount = min(In.BSDFCount, SUBSTRATE_MAX_BSDF_COUNT_FOR_BDSFOFFSET);
	if (BSDFCount > 0)
	{
		Out = In.BSDFOffsets[0] & SUBSTRATE_BSDF_OFFSET_BIT_MASK;
		UNROLL_N(SUBSTRATE_MAX_BSDF_COUNT_FOR_BDSFOFFSET-1)
		for (uint i = 1; i < BSDFCount; i++)
		{
			const uint Curr = In.BSDFOffsets[i];
			const uint Prev = In.BSDFOffsets[i-1];
			Out = Out | (((Curr - Prev) & SUBSTRATE_BSDF_OFFSET_BIT_MASK) << (SUBSTRATE_BSDF_OFFSET_BIT_COUNT * i));
		}
	}
	return Out;
}

FSubstrateBSDFOffset UnpackBSDFOffset(uint In, uint InBSDFCount)
{
	FSubstrateBSDFOffset Out = (FSubstrateBSDFOffset)0;
	if (InBSDFCount > 0)
	{
		Out.BSDFCount = min(InBSDFCount, SUBSTRATE_MAX_BSDF_COUNT_FOR_BDSFOFFSET);
		Out.BSDFOffsets[0] = (In & SUBSTRATE_BSDF_OFFSET_BIT_MASK);

		UNROLL_N(SUBSTRATE_MAX_BSDF_COUNT_FOR_BDSFOFFSET-1)
		for (uint i = 1; i < Out.BSDFCount; i++)
		{
			Out.BSDFOffsets[i] = Out.BSDFOffsets[i-1] + ((In>>(SUBSTRATE_BSDF_OFFSET_BIT_COUNT * i)) & SUBSTRATE_BSDF_OFFSET_BIT_MASK);
		}
	}
	return Out;
}

uint UnpackBSDFOffsetAtIndex(uint In, uint InIndex, uint InBSDFCount)
{
	uint Out = 0;
	if (InBSDFCount > 0)
	{
		const uint OffsetCount = min3(InIndex+1, InBSDFCount, SUBSTRATE_MAX_BSDF_COUNT_FOR_BDSFOFFSET);
		UNROLL_N(SUBSTRATE_MAX_BSDF_COUNT_FOR_BDSFOFFSET)
		for (uint i = 0; i < OffsetCount; i++)
		{
			Out += ((In >> (SUBSTRATE_BSDF_OFFSET_BIT_COUNT * i)) & SUBSTRATE_BSDF_OFFSET_BIT_MASK);
		}
	}
	return Out;
}

void SubstrateSeekBSDF(inout FSubstrateAddressing Addressing, uint AddressOffset)
{
	Addressing.CurrentIndex = AddressOffset;
	Addressing.ReadBytes = Addressing.CurrentIndex * 4;
}

void SubstrateSeekBSDF(inout FSubstrateAddressing Addressing, FSubstrateBSDFOffset Offsets, uint BSDFIndex)
{
	if (BSDFIndex < Offsets.BSDFCount)
	{
		Addressing.CurrentIndex = Offsets.BSDFOffsets[BSDFIndex];
		Addressing.ReadBytes = Addressing.CurrentIndex * 4;
	}
}

#endif // SUBSTRATE_ENABLED
