// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "Common.ush"
#include "Quaternion.ush"

struct FBoneTransform
{
	FQuat  Rotation;
	float3 Location;
};

struct FBoneTransformWithScale
{
	FQuat  Rotation;
	float3 Location;
	float3 Scale;
};

////

FBoneTransform MakeBoneTransform(FQuat Rotation, float3 Location)
{
	FBoneTransform Transform;
	Transform.Rotation = Rotation;
	Transform.Location = Location;
	return Transform;
}

FBoneTransform MakeBoneTransformIdentity()
{
	return MakeBoneTransform(
		QuatIdentity(),
		float3(0.0f, 0.0f, 0.0f)
	);
}

FBoneTransform MultiplyBoneTransform(FBoneTransform LHS, FBoneTransform RHS)
{
	FQuat Rotation	= QuatMultiply(RHS.Rotation, LHS.Rotation);
	float3 Location	= QuatRotateVector(RHS.Rotation, LHS.Location) + RHS.Location;
	return MakeBoneTransform(Rotation, Location);
}

FBoneTransform InvertBoneTransform(FBoneTransform Transform)
{
	FQuat Rotation	=  QuatConjugate(Transform.Rotation);
	float3 Location	= -QuatRotateVector(Rotation, Transform.Location);
	return MakeBoneTransform(Rotation, Location);
}

FBoneTransform RemoveBoneTransformScale(FBoneTransformWithScale Transform)
{
	FBoneTransform Result;
	Result.Location = Transform.Location;
	Result.Rotation = QuatNormalize(Transform.Rotation);
	return Result;
}

float4x4 MatrixFromBoneTransform(FBoneTransform Transform)
{
	float3x3 RotationMatrix = QuatToMatrix(Transform.Rotation);

	float4x4 OutMatrix;
	OutMatrix[0] = float4(RotationMatrix[0], 0.0);
	OutMatrix[1] = float4(RotationMatrix[1], 0.0);
	OutMatrix[2] = float4(RotationMatrix[2], 0.0);
	OutMatrix[3] = float4(Transform.Location, 1.0);
	return OutMatrix;
}

////

FBoneTransformWithScale MakeBoneTransformWithScale(FQuat Rotation, float3 Location, float3 Scale)
{
	FBoneTransformWithScale Transform;
	Transform.Rotation = Rotation;
	Transform.Location = Location;
	Transform.Scale = Scale;
	return Transform;
}

FBoneTransformWithScale MakeBoneTransformWithScaleIdentity()
{
	return MakeBoneTransformWithScale(QuatIdentity(), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f));
}

FBoneTransformWithScale MultiplyBoneTransformWithScale(FBoneTransformWithScale LHS, FBoneTransformWithScale RHS)
{
	// NOTE: Assumes no negative scale! Otherwise should multiply using matrices
	FQuat Rotation	= QuatMultiply(RHS.Rotation, LHS.Rotation);
	float3 Location	= QuatRotateVector(RHS.Rotation, RHS.Scale * LHS.Location) + RHS.Location;
	float3 Scale = LHS.Scale * RHS.Scale;
	return MakeBoneTransformWithScale(Rotation, Location, Scale);
}

float4x4 MatrixFromBoneTransformWithScale(FBoneTransformWithScale Transform)
{
	float3x3 RotationMatrix = QuatToMatrix(Transform.Rotation);

	RotationMatrix[0] *= Transform.Scale.xxx;
	RotationMatrix[1] *= Transform.Scale.yyy;
	RotationMatrix[2] *= Transform.Scale.zzz;

	float4x4 OutMatrix;
	OutMatrix[0] = float4(RotationMatrix[0], 0.0);
	OutMatrix[1] = float4(RotationMatrix[1], 0.0);
	OutMatrix[2] = float4(RotationMatrix[2], 0.0);
	OutMatrix[3] = float4(Transform.Location, 1.0);
	return OutMatrix;
}