// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "/Engine/Shared/SplineMeshShaderParams.h"
#include "ShaderPrint.ush"
#include "SceneData.ush"

#ifndef USE_SPLINE_MESH_SCENE_RESOURCES
	#define USE_SPLINE_MESH_SCENE_RESOURCES 0
#endif

// Methods for calculating deformed spline mesh bounds
#define SPLINE_MESH_DEFORM_BOUNDS_METHOD_SPHERES	0
#define SPLINE_MESH_DEFORM_BOUNDS_METHOD_QUADS		1

#ifndef SPLINE_MESH_DEFORM_BOUNDS_METHOD
	#define SPLINE_MESH_DEFORM_BOUNDS_METHOD SPLINE_MESH_DEFORM_BOUNDS_METHOD_SPHERES
#endif

FSplineMeshShaderParams SplineMeshLoadParamsFromInstancePayload(uint PayloadOffset)
{
	const float4 SplineParams[SPLINE_MESH_PARAMS_FLOAT4_SIZE] =
	{
		LoadInstancePayloadDataElement(PayloadOffset + 0),
		LoadInstancePayloadDataElement(PayloadOffset + 1),
		LoadInstancePayloadDataElement(PayloadOffset + 2),
		LoadInstancePayloadDataElement(PayloadOffset + 3),
		LoadInstancePayloadDataElement(PayloadOffset + 4),
		LoadInstancePayloadDataElement(PayloadOffset + 5),
		LoadInstancePayloadDataElement(PayloadOffset + 6),
	};

	return UnpackSplineMeshParams(SplineParams);
}

FSplineMeshShaderParams SplineMeshLoadParamsFromInstancePayload(FInstanceSceneData InstanceData)
{
	checkSlow(InstanceData.PayloadExtensionOffset != INVALID_INSTANCE_PAYLOAD_OFFSET);
	return SplineMeshLoadParamsFromInstancePayload(InstanceData.PayloadExtensionOffset);
}

/** Calculate normalized distance along the spline based on local mesh position */
float SplineMeshCalcSplineDistance(FSplineMeshShaderParams Params, float3 LocalPos)
{
	float ZPos = dot(LocalPos, Params.MeshDir);
	return saturate(ZPos * Params.MeshScaleZ - Params.MeshMinZ);
}

#if USE_SPLINE_MESH_SCENE_RESOURCES

/** Evaluates both position and tangent direction of the spline at the specified normalized distance along the spline */
void SplineMeshEvalPosAndDir(FSplineMeshShaderParams Params, float SplineDist, inout float3 OutPos, inout float3 OutDir)
{
	const float SplineDistU = SplineDist * Scene.SplineMesh.SplineWidthU;
	const float2 TexelSizeUV = Scene.SplineMesh.SplineTextureInvExtent;
	const float2 UVOffset = (Params.TextureCoord + (float2)0.5f) * TexelSizeUV;
	const float2 UV0 = UVOffset + float2(SplineDistU, 0);
	const float3 Pos0 = Scene.SplineMesh.SplineTexture.SampleLevel(Scene.SplineMesh.SplineSampler, UV0, 0).xyz;

	// decide where to take a second sample to calculate the tangent direction
	const float Sample1Dir = (SplineDistU + TexelSizeUV.x < Scene.SplineMesh.SplineWidthU) ? 1.0f : -1.0f;
	const float2 UV1 = UVOffset + float2(SplineDistU + TexelSizeUV.x * Sample1Dir, 0);
	const float3 Pos1 = Scene.SplineMesh.SplineTexture.SampleLevel(Scene.SplineMesh.SplineSampler, UV1, 0).xyz;

	OutPos = Pos0;
	OutDir = normalize(Pos1 - Pos0) * Sample1Dir;
}

/** Evaluates the position on the spline based on normalized distance along the spline */
float3 SplineMeshEvalPos(FSplineMeshShaderParams Params, float SplineDist)
{
	float3 Pos, Dir;
	SplineMeshEvalPosAndDir(Params, SplineDist, Pos, Dir);
	return Pos;
}

/** Evaluates the normalized tangent direction of the spline at a specified normalized distance along the spline */
float3 SplineMeshEvalDir(FSplineMeshShaderParams Params, float SplineDist)
{
	float3 Pos, Dir;
	SplineMeshEvalPosAndDir(Params, SplineDist, Pos, Dir);
	return Dir;
}

#else // !USE_SPLINE_MESH_SCENE_RESOURCES

/** Evaluates the position on the spline based on normalized distance along the spline */
float3 SplineMeshEvalPos(FSplineMeshShaderParams Params, float SplineDist)
{
	float A = SplineDist;
	float A2 = A  * A;
	float A3 = A2 * A;

	return (((2*A3)-(3*A2)+1) * Params.StartPos) +
		   ((A3-(2*A2)+A) * Params.StartTangent) +
		   ((A3-A2) * Params.EndTangent) +
		   (((-2*A3)+(3*A2)) * Params.EndPos);
}

/** Evaluates the normalized tangent direction of the spline at a specified normalized distance along the spline */
float3 SplineMeshEvalDir(FSplineMeshShaderParams Params, float SplineDist)
{
	float3 C = (6*Params.StartPos) + (3*Params.StartTangent) + (3*Params.EndTangent) - (6*Params.EndPos);
	float3 D = (-6*Params.StartPos) - (4*Params.StartTangent) - (2*Params.EndTangent) + (6*Params.EndPos);
	float3 E = Params.StartTangent;

	float A = SplineDist;
	float A2 = A * A;

	return normalize((C * A2) + (D * A) + E);
}

/** Evaluates both position and tangent direction of the spline at the specified normalized distance along the spline */
void SplineMeshEvalPosAndDir(FSplineMeshShaderParams Params, float SplineDist, inout float3 OutPos, inout float3 OutDir)
{
	OutPos = SplineMeshEvalPos(Params, SplineDist);
	OutDir = SplineMeshEvalDir(Params, SplineDist);
}

#endif // USE_SPLINE_MESH_SCENE_RESOURCES

/** Evaluates the scale, roll, and offset of a slice of the spline at the specified normalized distance */
void SplineMeshEvalScaleRollOffset(FSplineMeshShaderParams Params, float SplineDist, inout float2 Scale, inout float Roll, inout float2 Offset)
{
	// Apply hermite interp to SplineDist if desired
	float HermiteAlpha = Params.bSmoothInterpRollScale ? smoothstep(0.0, 1.0, SplineDist) : SplineDist;

	Scale = lerp(Params.StartScale, Params.EndScale, HermiteAlpha);
	Roll = lerp(Params.StartRoll, Params.EndRoll, HermiteAlpha);
	Offset = lerp(Params.StartOffset, Params.EndOffset, HermiteAlpha);
}

/** Calculate full transform that defines frame along spline, given the normalized distance along the spline. */
float4x3 SplineMeshCalcSliceTransform(FSplineMeshShaderParams Params, float SplineDist)
{
	// Find the point and direction of the spline at this point along it
	float3 SplinePos, SplineDir;
	SplineMeshEvalPosAndDir(Params, SplineDist, SplinePos, SplineDir);

	// Find base frenet frame
	float3 BaseXVec = normalize( cross(Params.SplineUpDir, SplineDir) );
	float3 BaseYVec = cross(SplineDir, BaseXVec);

	float2 Scale, Offset;
	float Roll;
	SplineMeshEvalScaleRollOffset(Params, SplineDist, Scale, Roll, Offset);

	// Apply roll to frame around spline
	float SinAng, CosAng;
	sincos(Roll, SinAng, CosAng);
	float3 XVec = (CosAng * BaseXVec) - (SinAng * BaseYVec);
	float3 YVec = (CosAng * BaseYVec) + (SinAng * BaseXVec);

	// Apply scale at this point along spline
	XVec *= Scale.x;
	YVec *= Scale.y;

	// Offset from the spline, using the frenet frame
	SplinePos += Offset.x * BaseXVec;
	SplinePos += Offset.y * BaseYVec;

	// Build overall transform
	float3x3 SliceTransform3 = mul(transpose(float3x3(Params.MeshDir, Params.MeshX, Params.MeshY)), float3x3(float3(0,0,0), XVec, YVec));
	float4x3 SliceTransform = float4x3(SliceTransform3[0], SliceTransform3[1], SliceTransform3[2], SplinePos);

	return SliceTransform;
}

/** Calculate full transform that defines frame along spline, given the local position of a vertex. */
float4x3 SplineMeshCalcSliceTransformFromLocalPos(FSplineMeshShaderParams Params, float3 LocalPos)
{
	return SplineMeshCalcSliceTransform(Params, SplineMeshCalcSplineDistance(Params, LocalPos));
}

/** Calculate full transform that defines frame along spline, given the local position of a vertex. */
float3 SplineMeshDeformLocalPos(FSplineMeshShaderParams Params, float4 LocalPos)
{
	return mul(LocalPos, SplineMeshCalcSliceTransformFromLocalPos(Params, LocalPos.xyz));
}

/** Calculate rotation matrix that defines frame along spline, given the normalized distance along the spline. */
half3x3 SplineMeshCalcSliceRot(FSplineMeshShaderParams Params, float SplineDist)
{
	// Find the point and direction of the spline at this point along it
	half3 SplineDir = SplineMeshEvalDir( Params, SplineDist );

	// Find base frenet frame
	half3 BaseXVec = normalize( cross(Params.SplineUpDir, (half3)SplineDir) );
	half3 BaseYVec = cross((half3)SplineDir, BaseXVec);

	float2 Scale, Offset;
	float Roll;
	SplineMeshEvalScaleRollOffset(Params, SplineDist, Scale, Roll, Offset);

	// Apply roll to frame around spline
	half SinAng, CosAng;
	sincos(Roll, SinAng, CosAng);
	half3 XVec = (CosAng * BaseXVec) - (SinAng * BaseYVec);
	half3 YVec = (CosAng * BaseYVec) + (SinAng * BaseXVec);

	// Flip X or Y direction when negative scale
	XVec *= Scale.x >= 0.0f ? 1.0f : -1.0f;
	YVec *= Scale.y >= 0.0f ? 1.0f : -1.0f;

	// Build rotation transform
	half3x3 SliceTransform = mul(transpose(half3x3(Params.MeshDir, Params.MeshX, Params.MeshY)), half3x3(SplineDir, XVec, YVec));

	return SliceTransform;
}

/** Calculate rotation matrix that defines frame along spline, given the local position of a vertex. */
half3x3 SplineMeshCalcSliceRotFromLocalPos(FSplineMeshShaderParams Params, float3 LocalPos)
{
	return SplineMeshCalcSliceRot(Params, SplineMeshCalcSplineDistance(Params, LocalPos));
}

struct FSplineMeshDeformBoundsContext
{
	FSplineMeshShaderParams Params;
	float3 MeshBoundsCenter;
	float3 MeshBoundsExtent;
	float3 MeshMinBounds;
	float3 MeshMaxBounds;
	float3 DeformedMinBounds;
	float3 DeformedMaxBounds;
	float3 LastSplinePos;
	float CurSplineLength;
	float MaxScaleXY;
	FShaderPrintContext ShaderPrint;
	float4x4 LocalToTWS;
};

struct FSplineMeshDeformedLocalBounds
{
	float3 BoundsCenter;
	float3 BoundsExtent;
	float MaxDeformScale;
};

FSplineMeshDeformBoundsContext SplineMeshInitializeDeformBoundsContext(
	FSplineMeshShaderParams Params,
	float3 MeshBoundsCenter,
	float3 MeshBoundsExtent,
	FShaderPrintContext ShaderPrint,
	float4x4 LocalToTWS
)
{
	FSplineMeshDeformBoundsContext Result;
	Result.Params				= Params;
	Result.MeshBoundsCenter		= MeshBoundsCenter;
	Result.MeshBoundsExtent		= MeshBoundsExtent;
	Result.MeshMinBounds		= MeshBoundsCenter - MeshBoundsExtent;
	Result.MeshMaxBounds		= MeshBoundsCenter + MeshBoundsExtent;
	Result.DeformedMinBounds	= (float3)POSITIVE_INFINITY;
	Result.DeformedMaxBounds	= (float3)NEGATIVE_INFINITY;
	Result.CurSplineLength		= -1.0f; // Negative to mark as not started
	Result.MaxScaleXY			= 0.0f;
	Result.ShaderPrint			= ShaderPrint;
	Result.LocalToTWS			= LocalToTWS;

	return Result;
}

FSplineMeshDeformBoundsContext SplineMeshInitializeDeformBoundsContext(
	FSplineMeshShaderParams Params,
	float3 MeshBoundsCenter,
	float3 MeshBoundsExtent
)
{
	FSplineMeshDeformBoundsContext Result;
	Result.Params				= Params;
	Result.MeshBoundsCenter		= MeshBoundsCenter;
	Result.MeshBoundsExtent		= MeshBoundsExtent;
	Result.MeshMinBounds		= MeshBoundsCenter - MeshBoundsExtent;
	Result.MeshMaxBounds		= MeshBoundsCenter + MeshBoundsExtent;
	Result.DeformedMinBounds	= (float3)POSITIVE_INFINITY;
	Result.DeformedMaxBounds	= (float3)NEGATIVE_INFINITY;
	Result.CurSplineLength		= -1.0f; // Negative to mark as not started
	Result.MaxScaleXY			= 0.0f;

	Result.ShaderPrint.bIsActive	= false;
	Result.LocalToTWS				= (float4x4)0;

	return Result;
}

/** Solves post-deformed bounds of a slice of a spline mesh given the mesh-local bounds (iterative step) */
void SplineMeshDeformLocalBoundsStep(inout FSplineMeshDeformBoundsContext Context, float SplineDist)
{
	// Find the point and direction of the spline at this point along it
	float3 SplinePos, SplineDir;
	SplineMeshEvalPosAndDir(Context.Params, SplineDist, SplinePos, SplineDir);

	// Find base frenet frame
	const float3 BaseXVec = normalize( cross(Context.Params.SplineUpDir, SplineDir) );
	const float3 BaseYVec = cross(SplineDir, BaseXVec);

	float2 Scale, Offset;
	float Roll;
	SplineMeshEvalScaleRollOffset(Context.Params, SplineDist, Scale, Roll, Offset);

	// Calculate the offset from the spline
	SplinePos += Offset.x * BaseXVec + Offset.y * BaseYVec;

	// Get the rotated X/Y directions
	float SinAng, CosAng;
	sincos(Roll, SinAng, CosAng);
	const float3 XVec = (CosAng * BaseXVec) - (SinAng * BaseYVec);
	const float3 YVec = (CosAng * BaseYVec) + (SinAng * BaseXVec);

	// Get Max absolute scale in either X or Y
	const float AbsMaxScaleXY = max(abs(Scale.x), abs(Scale.y));

	float3 SliceMin, SliceMax;
#if SPLINE_MESH_DEFORM_BOUNDS_METHOD == SPLINE_MESH_DEFORM_BOUNDS_METHOD_QUADS
	// Calculate the mesh bounds along the X/Y of the slice
	const float2 MeshMinXY = Scale * float2(dot(Context.Params.MeshX, Context.MeshMinBounds),
											dot(Context.Params.MeshY, Context.MeshMinBounds));
	const float2 MeshMaxXY = Scale * float2(dot(Context.Params.MeshX, Context.MeshMaxBounds),
											dot(Context.Params.MeshY, Context.MeshMaxBounds));

	// Determine local-space AABB for a slice of the spline by transforming rect cross-section of bounds and take min/max
	const float3 RectPoints[4] =
	{
		SplinePos + XVec * MeshMinXY.x + YVec * MeshMinXY.y,
		SplinePos + XVec * MeshMinXY.x + YVec * MeshMaxXY.y,
		SplinePos + XVec * MeshMaxXY.x + YVec * MeshMaxXY.y,
		SplinePos + XVec * MeshMaxXY.x + YVec * MeshMinXY.y
	};

	SliceMin = min(min(RectPoints[0], RectPoints[1]), min(RectPoints[2], RectPoints[3]));
	SliceMax = max(max(RectPoints[0], RectPoints[1]), max(RectPoints[2], RectPoints[3]));
#elif SPLINE_MESH_DEFORM_BOUNDS_METHOD == SPLINE_MESH_DEFORM_BOUNDS_METHOD_SPHERES
	const float2 SphereCenterXY = Scale * float2(dot(Context.Params.MeshX, Context.MeshBoundsCenter),
												 dot(Context.Params.MeshY, Context.MeshBoundsCenter));
	const float3 SphereCenterOffset = XVec * SphereCenterXY.x + YVec * SphereCenterXY.y;
	const float RadiusXY = AbsMaxScaleXY * abs(dot(Context.Params.MeshX + Context.Params.MeshY, Context.MeshBoundsExtent));

	SliceMin = SplinePos + SphereCenterOffset - RadiusXY.xxx;
	SliceMax = SplinePos + SphereCenterOffset + RadiusXY.xxx;
#else
	#error Invalid SPLINE_MESH_DEFORM_BOUNDS_METHOD
#endif

	// Extend current AABB and approximate spline length
	Context.DeformedMinBounds = min(Context.DeformedMinBounds, SliceMin);
	Context.DeformedMaxBounds = max(Context.DeformedMaxBounds, SliceMax);
	if (Context.CurSplineLength < 0.0f)
	{
		Context.CurSplineLength = 0.0f;
	}
	else
	{
		Context.CurSplineLength += length(SplinePos - Context.LastSplinePos);
	}
	Context.MaxScaleXY = max(Context.MaxScaleXY, AbsMaxScaleXY);
	Context.LastSplinePos = SplinePos;

	// Debug draw
	if (Context.ShaderPrint.bIsActive)
	{
#if SPLINE_MESH_DEFORM_BOUNDS_METHOD == SPLINE_MESH_DEFORM_BOUNDS_METHOD_QUADS
		float3 RectPointsTWS[4];
		UNROLL_N(4)
		for(int i = 0; i < 4; ++i)
		{
			RectPointsTWS[i] = mul(float4(RectPoints[i], 1.0f), Context.LocalToTWS).xyz;
		}

		const float4 MinColor = { 1.0f, 0.0f, 0.0f, 1.0f };
		const float4 MaxColor = { 0.0f, 1.0f, 0.0f, 1.0f };
		AddLineTWS(Context.ShaderPrint, RectPointsTWS[0], RectPointsTWS[1], MinColor);
		AddLineTWS(Context.ShaderPrint, RectPointsTWS[1], RectPointsTWS[2], MaxColor);
		AddLineTWS(Context.ShaderPrint, RectPointsTWS[2], RectPointsTWS[3], MaxColor);
		AddLineTWS(Context.ShaderPrint, RectPointsTWS[3], RectPointsTWS[0], MinColor);
#elif SPLINE_MESH_DEFORM_BOUNDS_METHOD == SPLINE_MESH_DEFORM_BOUNDS_METHOD_SPHERES
		const float3 SphereCenter = mul(float4(SplinePos + SphereCenterOffset, 1.0f), Context.LocalToTWS).xyz;
		const float4 SphereColor = { 0.0f, 1.0f, 0.0f, 1.0f };
		AddSphereTWS(Context.ShaderPrint, SphereCenter, RadiusXY, SphereColor);
#endif
	}
}

/** Solves for approximate post-deformed bounds of a region of spline mesh given the mesh-local bounds */
FSplineMeshDeformedLocalBounds SplineMeshDeformLocalBounds(FSplineMeshDeformBoundsContext Context)
{
	// Find the min and max distance along the spline
	const float SplineDistMin = SplineMeshCalcSplineDistance(Context.Params, Context.MeshMinBounds);
	const float SplineDistMax = SplineMeshCalcSplineDistance(Context.Params, Context.MeshMaxBounds);

	const uint NUM_SLICE_SAMPLES = 8; // How many slices to sample along the length of the bounds
	float CurSplineDist = SplineDistMin;
	const float SplineDistStep = (SplineDistMax - SplineDistMin) / float(NUM_SLICE_SAMPLES - 1);

	// Sample at evenly-spaced intervals from min->max, accumulating the convex combination of slice bounds
	LOOP
	for (int i = 0; i < NUM_SLICE_SAMPLES; ++i)
	{
		SplineMeshDeformLocalBoundsStep(Context, CurSplineDist);
		CurSplineDist += SplineDistStep;
	}

	FSplineMeshDeformedLocalBounds Result;
	Result.BoundsCenter = (Context.DeformedMinBounds + Context.DeformedMaxBounds) * 0.5f;
	Result.BoundsExtent = (Context.DeformedMaxBounds - Context.DeformedMinBounds) * 0.5f;

	// Allow cluster bounds extent to be scaled by a parameter as a kludge to fix any issues that might
	// occur with clusters dropping out due to inaccurate bounds calculated under extreme deformation.
	Result.BoundsExtent *= Context.Params.NaniteClusterBoundsScale;

	// Calculate an estimate for the largest scale in any one dimension caused by spline deformation and scaling.
	// This value is used to fudge the threshold at which to render Nanite clusters in HW to prevent issues.
	const float PreDeformLen = 2.0f * abs(dot(Context.Params.MeshDir, Context.MeshBoundsExtent));
	const float DeformLenScale = PreDeformLen == 0.0f ? 1.0f : Context.CurSplineLength * rcp(PreDeformLen);
	Result.MaxDeformScale = max(DeformLenScale, Context.MaxScaleXY);

	return Result;
}

FSplineMeshDeformedLocalBounds SplineMeshDeformLocalBounds(FSplineMeshShaderParams Params, float3 BoundsCenter, float3 BoundsExtent)
{
	return SplineMeshDeformLocalBounds(
		SplineMeshInitializeDeformBoundsContext(
			Params,
			BoundsCenter,
			BoundsExtent
		)
	);
}

FSplineMeshDeformedLocalBounds SplineMeshDeformLocalBoundsDebug(
	FSplineMeshShaderParams Params,
	FShaderPrintContext ShaderPrint,
	float4x4 LocalToTWS,
	float3 BoundsCenter,
	float3 BoundsExtent
)
{
	return SplineMeshDeformLocalBounds(
		SplineMeshInitializeDeformBoundsContext(
			Params,
			BoundsCenter,
			BoundsExtent,
			ShaderPrint,
			LocalToTWS
		)
	);
}

/**
 * Deforms a local-space mesh bounding sphere to *approximately* match its post-deformation equivalent along the spline.
 *
 * NOTE: This is currently only needed for Nanite LOD spheres, which are pretty tolerant to being very approximate
 * without having huge repercussions to the LOD quality. This is not a good solution if you need an accurate
 * transformation of local bounds (e.g. for use with culling). Also, this solution is not a monotonic transformation,
 * which is known to potentially create issues with Nanite's LOD selection.
 */
float4 SplineMeshDeformLODSphereBounds(FSplineMeshShaderParams Params, float4 LODSphere)
{
	const float SplineDist = SplineMeshCalcSplineDistance(Params, LODSphere.xyz);
	float3 SplinePos, SplineDir;
	SplineMeshEvalPosAndDir(Params, SplineDist, SplinePos, SplineDir);

	float2 Scale, Offset;
	float Roll;
	SplineMeshEvalScaleRollOffset(Params, SplineDist, Scale, Roll, Offset);

	const float3 BaseXVec = normalize( cross(Params.SplineUpDir, SplineDir) );
	const float3 BaseYVec = cross(SplineDir, BaseXVec);

	float SinAng, CosAng;
	sincos(Roll, SinAng, CosAng);
	const float3 XVec = (CosAng * BaseXVec) - (SinAng * BaseYVec);
	const float3 YVec = (CosAng * BaseYVec) + (SinAng * BaseXVec);

	const float2 LocalCenterXY = { dot(Params.MeshX, LODSphere.xyz), dot(Params.MeshY, LODSphere.xyz) };
	const float3 SliceCenter = SplinePos +
		XVec * LocalCenterXY.x * Scale.x +
		YVec * LocalCenterXY.y * Scale.y +
		BaseXVec * Offset.x +
		BaseYVec * Offset.y;

	return float4(SliceCenter, LODSphere.w * Params.MeshDeformScaleMinMax.y);
}

