// Copyright Epic Games, Inc. All Rights Reserved.

#include "Common.ush"
#include "SplineMeshCommon.ush"
#include "ComputeShaderUtils.ush"


RWTexture2D<float4> SplineTextureOut;
StructuredBuffer<uint> InstanceIdLookup;
StructuredBuffer<uint> UpdateRequests;
uint NumUpdateRequests;
uint InstanceDataSOAStride;
float TextureHeight;
float TextureHeightInv;

[numthreads(SPLINE_MESH_TEXEL_WIDTH, 1, 1)]
void FillTexture(uint3 GroupId : SV_GroupID, uint GroupThreadId : SV_GroupThreadID)
{
	GroupId = GetUnWrappedDispatchGroupId(GroupId);

	// 0 requests means we're filling the whole texture
	const uint SplineMeshIndex = NumUpdateRequests > 0 ? UpdateRequests[GroupId.x] : GroupId.x;
	const uint InstanceId = InstanceIdLookup[SplineMeshIndex];

	if (InstanceId == (uint)-1)
	{
		// Skip gaps in the lookup
		return;
	}

	FInstanceSceneData InstanceData = GetInstanceSceneData(InstanceId, InstanceDataSOAStride, false);
	FPrimitiveSceneData PrimitiveData = GetPrimitiveData(InstanceData.PrimitiveId);

	if ((PrimitiveData.Flags & PRIMITIVE_SCENE_DATA_FLAG_SPLINE_MESH) == 0 ||
		(InstanceData.Flags & INSTANCE_SCENE_DATA_FLAG_HAS_PAYLOAD_EXTENSION) == 0)
	{
		// Not a spline mesh instance?
		return;
	}

	FSplineMeshShaderParams SplineMeshParams = SplineMeshLoadParamsFromInstancePayload(InstanceData);

	// determine the coord of the first texel of the spline and fill the row of texels with the spline positions
	const uint2 PixelPos = SplineMeshParams.TextureCoord + uint2(GroupThreadId.x, 0);
	const float SplineDist = float(GroupThreadId.x) * rcp(SPLINE_MESH_TEXEL_WIDTH - 1);
	SplineTextureOut[PixelPos] = float4(SplineMeshEvalPos(SplineMeshParams, SplineDist), 1);
}