name: UnrealEngine Build and Archive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    # Step 1: Checkout repository with submodules and depth 1
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 1

    # Step 2: Install Visual Studio 2017 with required workloads and components
    - name: Install Visual Studio 2017
      shell: cmd
      run: |
        choco install visualstudio2017community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Workload.NativeGame --addComponent Microsoft.Net.Component.4.6.2.TargetingPack --includeRecommended --includeOptional --passive --norestart"
        choco install windows-sdk-10.0 --version 10.0.17763.0
        choco install windows-sdk-10.0 --version 10.0.17134.0
        choco install windows-sdk-10.0 --version 10.0.16299.0
        choco install windows-sdk-8.1 --version 8.100.26936

    # Step 3: Run Unreal Build
    - name: Run Unreal Build
      shell: cmd
      run: Engine\Build\BatchFiles\RunUAT.bat BuildGraph -script=Engine/Build/InstalledEngineBuild.xml -target="Make Installed Build Win64" -nosign -set:HostPlatformCompiler=VisualStudio2017 -set:Game

    # Step 4: Install 7-Zip
    - name: Install 7-Zip
      run: choco install 7zip -y
      shell: powershell

    # Step 5: Compress the installed engine into a .7z file
    - name: Compress Installed Engine
      shell: cmd
      run: 7z a InstalledEngine.7z LocalBuilds\Engine

    # Step 6: Upload the .7z file as an artifact
    - name: Upload Installed Engine Archive
      uses: actions/upload-artifact@v3
      with:
        name: InstalledEngine
        path: InstalledEngine.7z
