name: UnrealEngine Build and Archive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - name: Cache repository
        id: cache-repo
        uses: actions/cache@v4
        with:
          path: |
            .git
            **/submodules
          key: windows-repo-cache

      - name: Checkout repository
        if: steps.cache-repo.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Cache Setup
        id: cache-setup
        uses: actions/cache@v4
        with:
          path: ./.setup_cache
          key: windows-setup-cache

      - name: Run Setup.bat
        if: steps.cache-setup.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cmd /c ".\Setup.bat"
        timeout-minutes: 20
        continue-on-error: true

      - name: Run GenerateProjectFiles.bat
        shell: cmd
        run: |
          cd ${{ github.workspace }}
          .\GenerateProjectFiles.bat -2017

      - name: Build Unreal Engine Editor
        shell: powershell
        run: |
          $SolutionPath = "${{ github.workspace }}\UE4.sln"
          $Configuration = "Development Editor"
          $Platform = "Win64"
          $vswherePath = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" `
            -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          & $vswherePath $SolutionPath /p:Configuration="$Configuration" /p:Platform="$Platform" /m
        timeout-minutes: 240

      - name: Compress Installed Engine
        shell: cmd
        run: 7z a InstalledEngine.7z LocalBuilds\Engine

      - name: Upload Installed Engine Archive
        uses: actions/upload-artifact@v3
        with:
          name: InstalledEngine
          path: InstalledEngine.7z
