// Copyright Epic Games, Inc.All Rights Reserved.
#pragma once

#include "Chaos/Core.h"
#include "Chaos/Collision/ContactPoint.h"
#include "Chaos/Collision/ContactTriangles.h"
#include "Chaos/CollisionResolutionTypes.h"
#include "Chaos/Framework/HashMappedArray.h"
#include "Chaos/Triangle.h"

namespace Chaos::Private
{
	// Adapter for FContactEdgeID use in THashMappedArray
	template<> struct THashMappedArrayIDTraits<FContactEdgeID>
	{
		using FIDType = FContactEdgeID;

		static uint32 HashID(const FIDType& ID)
		{
			return uint32(MurmurFinalize64(ID.EdgeID));
		}
	};

	/**
	* Generate contacts between a collision shape and the triangles from a mesh.
	*/
	class FMeshContactGenerator
	{
	public:
		FMeshContactGenerator(const int32 InHashSize);

		// Clear and initialize buffers
		void BeginCollect(const int32 InNumTriangles)
		{
			const int32 ExpectedNumContacts = FMath::Min(InNumTriangles * 4, 1000);
			Reset(InNumTriangles, ExpectedNumContacts);
		}

		// Add a triangle that we might be overlapping
		void AddTriangle(const FTriangle& MeshTriangle, const int32 MeshTriangleIndex, const int32 VertexIndex0, const int32 VertexIndex1, const int32 VertexIndex2)
		{
			Triangles.Emplace(MeshTriangle, MeshTriangleIndex, VertexIndex0, VertexIndex1, VertexIndex2);
		}

		void EndCollect()
		{
			for (int32 LocalTriangleIndex = 0; LocalTriangleIndex < GetNumTriangles(); ++LocalTriangleIndex)
			{
				const FTriangleExt& Triangle = Triangles[LocalTriangleIndex];
				AddTriangleEdge(LocalTriangleIndex, Triangle.VertexIndices[0], Triangle.VertexIndices[1]);
				AddTriangleEdge(LocalTriangleIndex, Triangle.VertexIndices[1], Triangle.VertexIndices[2]);
				AddTriangleEdge(LocalTriangleIndex, Triangle.VertexIndices[2], Triangle.VertexIndices[0]);
			}
		}

		// Loop over (the required subset of) all triangles and call the TriangleContactGenerator to create a manifold for each.
		// TriangleContactGeneratorType: void(const FTriangle& Triangle, FContactPointManifold& OutContactPoints)
		template<typename TriangleContactGeneratorType>
		void GenerateMeshContacts(const TriangleContactGeneratorType& TriangleContactGenerator)
		{
			FContactPointManifold TriangleContactPoints;

			// First loop: Visit triangles that do not have any collisions on any of their vertices or edges.
			// This will skip all triangles whose neighbours have already been processed and generated a contact
			// on a shared edge/vertex.
			for (int32 LocalTriangleIndex = 0; LocalTriangleIndex < GetNumTriangles(); ++LocalTriangleIndex)
			{
				if (GetNumTriangleFaceCollisions(LocalTriangleIndex) == 0)
				{
					TriangleContactPoints.Reset();
					TriangleContactGenerator(Triangles[LocalTriangleIndex].Triangle, TriangleContactPoints);

					AddTriangleContacts(TriangleContactPoints, LocalTriangleIndex);

					SetTriangleVisited(LocalTriangleIndex, 0);
				}
			}

			// Second loop: Visit remaining triangles that have less than 3 contacts on them. This will skip all triangles
			// that have a full manifold as a result of collisions on shared edges/vertices from adjacent triangles.
			for (int32 LocalTriangleIndex = 0; LocalTriangleIndex < GetNumTriangles(); ++LocalTriangleIndex)
			{
				if (!IsTriangleVisited(LocalTriangleIndex) && (GetNumTriangleFaceCollisions(LocalTriangleIndex) < 3))
				{
					TriangleContactPoints.Reset();
					TriangleContactGenerator(Triangles[LocalTriangleIndex].Triangle, TriangleContactPoints);

					AddTriangleContacts(TriangleContactPoints, LocalTriangleIndex);

					SetTriangleVisited(LocalTriangleIndex, 1);
				}
			}
		}

		// Process all the contact points generated by GenerateMeshContacts. This prunes duplicates, fixes normals, and
		// transforms the contact data back into shape-local space.
		void ProcessGeneratedContacts(const FRigidTransform3& ConvexTransform, const FRigidTransform3& MeshToConvexTransform);

		// The results of contact generation (must call ProcessGeneratedContacts prior to GetContactPoints)
		TArrayView<const FContactPoint> GetContactPoints() const
		{
			return MakeArrayView(Contacts);
		}

	private:
		// A triangle plus some extended data and state
		class FTriangleExt
		{
		public:
			FTriangleExt(const FTriangle& InTriangle, const int32 InTriangleIndex, const int32 InVertexIndex0, const int32 InVertexIndex1, const int32 InVertexIndex2)
				: Triangle(InTriangle)
				, Normal(InTriangle.GetNormal())
				, TriangleIndex(InTriangleIndex)
				, VertexIndices{ InVertexIndex0, InVertexIndex1, InVertexIndex2 }
				, NumFaceEdgeCollisions(0)
				, VisitIndex(INDEX_NONE)
				, bEnabled(true)
			{
			}

			// Does this triangle contains the specified vertex? (VertexIndex is an index into the owning mesh's vertices)
			inline bool HasVertexIndex(const int32 VertexIndex) const
			{
				return (VertexIndices[0] == VertexIndex) || (VertexIndices[1] == VertexIndex) || (VertexIndices[2] == VertexIndex);
			}

			inline bool GetVertexPosition(const int32 VertexIndex, FVec3& OutVertex) const
			{
				if (VertexIndex == VertexIndices[0])
				{
					OutVertex = Triangle.GetVertex(0);
					return true;
				}
				else if (VertexIndex == VertexIndices[1])
				{
					OutVertex = Triangle.GetVertex(1);
					return true;
				}
				else if (VertexIndex == VertexIndices[2])
				{
					OutVertex = Triangle.GetVertex(2);
					return true;
				}
				return false;
			}

			// Get the positions of the other two vertices in the triangle. (VertexIndex is an index into the owning mesh's vertices)
			inline bool GetOtherVertexPositions(const int32 VertexIndex, FVec3& OutVertex0, FVec3& OutVertex1) const
			{
				if (VertexIndex == VertexIndices[0])
				{
					OutVertex0 = Triangle.GetVertex(1);
					OutVertex1 = Triangle.GetVertex(2);
					return true;
				}
				else if (VertexIndex == VertexIndices[1])
				{
					OutVertex0 = Triangle.GetVertex(2);
					OutVertex1 = Triangle.GetVertex(0);
					return true;
				}
				else if (VertexIndex == VertexIndices[2])
				{
					OutVertex0 = Triangle.GetVertex(0);
					OutVertex1 = Triangle.GetVertex(1);
					return true;
				}
				return false;
			}

			FTriangle Triangle;
			FVec3 Normal;
			int32 TriangleIndex;
			int32 VertexIndices[3];
			int8 NumFaceEdgeCollisions;
			int8 VisitIndex;
			bool bEnabled;
		};

		// A contact index combined with a flag to indicate if the normal is roughly along the triangle face
		struct FVertexContactIndex
		{
			FContactVertexID ID;
			int32 ContactIndex;
			bool bIsFaceContact;
		};

		// The triangle indices that share an edge (assumes only 2)
		struct FEdgeTriangleIndices
		{
			FEdgeTriangleIndices(const FContactEdgeID& InEdgeID, const int32 InIndex0, const int32 InIndex1)
				: ID(InEdgeID)
				, LocalTriangleIndices{ InIndex0, InIndex1 }
			{
			}

			FContactEdgeID ID;
			int32 LocalTriangleIndices[2];
		};

		void Reset(const int32 InMaxTriangles, const int32 InMaxContacts);

		void AddTriangleEdge(const int32 LocalTriangleIndex, const int32 VertexIndex0, const int32 VertexIndex1)
		{
			const FContactEdgeID EdgeID = FContactEdgeID(VertexIndex0, VertexIndex1);
			FEdgeTriangleIndices* EdgeTriangleIndices = EdgeTriangleIndicesMap.Find(EdgeID);
			if (EdgeTriangleIndices == nullptr)
			{
				EdgeTriangleIndicesMap.Emplace(EdgeID, EdgeID, LocalTriangleIndex, INDEX_NONE);
			}
			else
			{
				EdgeTriangleIndices->LocalTriangleIndices[1] = LocalTriangleIndex;
			}
		}

		int32 GetOtherTriangleIndexForEdge(const int32 LocalTriangleIndex, const FContactEdgeID EdgeID)
		{
			FEdgeTriangleIndices* EdgeTriangleIndices = EdgeTriangleIndicesMap.Find(EdgeID);
			if (EdgeTriangleIndices != nullptr)
			{
				return (EdgeTriangleIndices->LocalTriangleIndices[0] == LocalTriangleIndex) ? EdgeTriangleIndices->LocalTriangleIndices[1] : EdgeTriangleIndices->LocalTriangleIndices[0];
			}
			return INDEX_NONE;
		}

		bool HasFaceVertexCollision(const FContactVertexID VertexID) const
		{
			if (const FVertexContactIndex* ContactIndex = VertexContactIndicesMap.Find(VertexID))
			{
				return ContactIndex->bIsFaceContact;
			}
			return false;
		}

		int32 GetNumTriangleFaceCollisions(const int32 LocalTriangleIndex) const
		{
			const int32 MeshVertexIndex0 = Triangles[LocalTriangleIndex].VertexIndices[0];
			const int32 MeshVertexIndex1 = Triangles[LocalTriangleIndex].VertexIndices[1];
			const int32 MeshVertexIndex2 = Triangles[LocalTriangleIndex].VertexIndices[2];
			int32 NumCollisions = Triangles[LocalTriangleIndex].NumFaceEdgeCollisions;
			NumCollisions += HasFaceVertexCollision(MeshVertexIndex0) ? 1 : 0;
			NumCollisions += HasFaceVertexCollision(MeshVertexIndex1) ? 1 : 0;
			NumCollisions += HasFaceVertexCollision(MeshVertexIndex2) ? 1 : 0;
			return NumCollisions;
		}

		bool IsTriangleVisited(const int32 LocalTriangleIndex) const
		{
			return Triangles[LocalTriangleIndex].VisitIndex != INDEX_NONE;
		}

		void SetTriangleVisited(const int32 LocalTriangleIndex, const int8 VisitIndex)
		{
			Triangles[LocalTriangleIndex].VisitIndex = VisitIndex;
		}

		int32 GetNumTriangles() const
		{
			return Triangles.Num();
		}

		void AddTriangleContacts(const FContactPointManifold& TriangleContactPoints, const int32 LocalTriangleIndex);
		void PruneAndCorrectContacts();
		void FixContactNormal(const int32 ContactIndex);
		void RemoveDisabledContacts();
		void FinalizeContacts(const FRigidTransform3& MeshToConvexTransform);

		void DebugDrawContacts(const FRigidTransform3& ConvexTransform, const FColor& Color, const FReal LineScale);
		void DebugDrawTriangles(const FRigidTransform3& ConvexTransform, const FColor& VisitedColor, const FColor& IgnoredColor);
		void DebugDrawTriangle(const FRigidTransform3& ConvexTransform, const FTriangleExt& TriangleData, const FColor& Color);

	private:
		// All the triangles we might collide with
		TArray<FTriangleExt> Triangles;

		// The contact data. This is split into the output data (FContactPoint) and the extra
		// per-contact metadata required during processing (FTriangleContactPointData).
		TArray<FContactPoint> Contacts;
		TArray<FTriangleContactPointData> ContactDatas;

		// A map of EdgeID to the two triangles (indices) that use the Edge
		THashMappedArray<FContactEdgeID, FEdgeTriangleIndices> EdgeTriangleIndicesMap;

		// A map of VertexID to contact index on that vertex - we only ever keep one contact per vertex
		THashMappedArray<FContactVertexID, FVertexContactIndex> VertexContactIndicesMap;
	};

}